'use strict';function aa(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}function e(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):{next:aa(a)}}function g(a){if(!(a instanceof Array)){a=e(a);for(var c,b=[];!(c=a.next()).done;)b.push(c.value);a=b}return a};/*
 lui.js web frame work 1.1.2
 inspired by react and mithril
 L3P3.de 2021
*/
(function(){var h=null,n=!h,r=h,t=0,v=0,z=0,A=n,B=[],C=[],D={},E={},F={},G=[],I=[],J=h,K=n,L=!n,ba=Array,ca=Object,da=ca.assign,M=ca.keys,ea=document,fa=window.performance||Date;function ha(a){return new Function("a","b","return a!==b&&("+a.join("||")+")")}function N(a){var c=(a=M(a)).join(",");return F[c]||(F[c]=ha(a.map(function(b){return"a."+b+"!==b."+b})))}function ia(a,c){return a===c?I:M(a).filter(function(b){return a[b]!==c[b]})}
function O(a){return a?G[a.length]||(G[a.length]=ha(a.map(function(c,b){return"a["+b+"]!==b["+b+"]"}))):J}
function Q(a,c){var b=h,d=c,k=b.v+1;r=b.s;t=1;b.B=L;if(b.u.G!==N){var f=J;try{f=b.u.G(b.u.o)}catch(wa){}var p=b.i;if(f){p&&(a=p,c=J);var m=f.length,l,u=b.m||(b.m=(new ba(m)).fill(J));do{var q=u[--m];(l=f[m])&&l!==K?((n=!q)?((u[m]=h=q={u:l,M:l.o&&N(l.o),H:b,v:k,O:m,s:[],m:J,i:J,j:J,B:L}).s[0]={l:0,T:q},Q(a,c),q.i&&a.insertBefore(q.j=q.i,c)):l.o&&q.M(q.u.o,l.o)&&((h=q).u=l,Q(a,c)),q.j&&(c=q.j)):q&&(R(q,a),u[m]=J)}while(0<m)}else if(b.m){k=e(b.m);for(f=k.next();!f.done;f=k.next())(f=f.value)&&R(f,a);
b.m=J}p||(b.j=c!==d?c:J)}else{f=b.u.o;p=f.G;var w=f.L;f=f.o;m=w.length;q=K;if(!(0>=S(m,m)+m)){l=T();u={};var H=[];w=0<m&&ja(w,u,H);if(l.J){q=f!==J&&l.M(f,l.ca);for(var P=e(l.ba),x=P.next();!x.done;x=P.next())x=x.value,x in u||(R(l.J[x],a),delete l.J[x]);l.ca=f;l.ba=H}else l.J={},l.V=w?N(u[H[0]]):J,l.ba=H,l.M=(l.ca=f)&&N(f);for(P=b.m=new ba(m);0<m;){x=H[--m];var y=l.J[x];if(n=!y)(l.J[x]=h=y={u:{G:p,o:da({I:u[x]},f)},M:J,H:b,v:k,O:m,s:[],m:J,i:J,j:J,B:L}).s[0]={l:0,T:y},Q(a,c),y.i&&a.insertBefore(y.j=
y.i,c);else if(ka(y,a,c),q||w&&l.V(u[x],y.u.o.I))(h=y).u.o=da({I:u[x]},f),Q(a,c);(P[y.O=m]=y).j&&(c=y.j)}b.j=c!==d?c:J}}}function R(a,c){c&&a.i&&(c.removeChild(a.i),c=J);if(a.m)for(var b=e(a.m),d=b.next();!d.done;d=b.next())(d=d.value)&&R(d,c);U(a.s);if(a.B){var k,f;(!(f=B[k=a.v])||0>(k=f.indexOf(a)))&&(!(f=C[k])||0>(k=f.indexOf(a)))||f.splice(k,1)}}
function U(a){for(var c,b=a.length;1<b;)switch((c=a[--b]).l){case 1:c.N&&c.N.apply(c,g(c.h));break;case 2:c.h=I;break;case 3:la(c);break;case 4:U(c.s)}}function ja(a,c,b){var d,k="object"===typeof a[0];a=e(a);for(d=a.next();!d.done;d=a.next()){d=d.value;var f=k?d.id:d;c[f]=d;b.push(f)}return k}function ka(a,c,b){if(a.i)return c.insertBefore(a.i,b),a.i;if(a.j){var d=a.m.length;do a.m[--d]&&(b=ka(a.m[d],c,b));while(0<d)}return b}
function ma(a){for(;0!==a[0].l;){if(!a[0].U.D)return J;a[0].U.D=L;a=a[0].aa}return a[0].T}function V(a){return(a=ma(a))&&!a.B&&(a.B=K,B[a.v]?B[a.v].push(a):B[a.v]=[a],A||W())}function na(){var a=ma(r);a&&(a.B=K,C[a.v]?C[a.v].push(a):C[a.v]=[a])}function oa(a,c){if(t>=r.length)r[t]={l:1,A:O(c),h:c=c||I,N:a.apply(null,g(c))||J};else if(c){var b=r[t];b.A(b.h,c)&&(b.N&&b.N.apply(b,g(b.h)),b.N=a.apply(null,g(b.h=c))||J)}++t}
function pa(a){if(t<r.length)return r[t++].g;var c=r,b=[a,function(d){b[0]!==d&&(b[0]=d,V(c))},function(){return b[0]}];r[t++]={l:0,g:b};return b}function T(a){return(t<r.length?r[t++]:r[t++]={l:0,g:void 0===a?{}:a}).g}function qa(a,c){return t>=r.length?(r[t++]={l:0,A:O(c),h:c=c||I,g:a.apply(null,g(c))}).g:c&&r[t].A(r[t].h,c)?r[t].g=a.apply(null,g(r[t++].h=c)):r[t++].g}function S(a,c){return t<r.length?(c=r[t].g,r[t++].g=a):r[t++]={l:0,g:a},c}
function ra(a,c){return a=setTimeout(function(){return c(K)},a),function(){return clearTimeout(a)}}function la(a){for(var c=e(a.X),b=c.next();!b.done;b=c.next())U(a.K[b.value])}function sa(a,c,b){return{Z:b.$,ea:a,Y:v,da:n?v:v+c}}function X(a){var c=S(a,J);return c?ia(c,a):M(a)}
function Y(a){var c=h.i;if(a){for(var b=e(X(a)),d=b.next();!d.done;d=b.next())switch(d=d.value,d.charCodeAt(0)){case 70:c.className=M(a.F).filter(function(k){return a.F[k]}).join(" ");continue;case 82:a.R(c);case 67:case 83:continue;default:c[d]=a[d]}if(a.S)for(b=e(X(a.S)),d=b.next();!d.done;d=b.next())d=d.value,c.style[d]=a.S[d]}return c}function Z(a,c,b){return{G:a,o:c?b?(c.C=b,c):c:b?{C:b}:J}}
function W(){n=0>=v;v=fa.now();A=K;z=0;for(var a;(a=B).length;){B=[];a=e(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value){c=e(c);for(var b=c.next();!b.done;b=c.next())if(h=b.value,h.B){if(h.i)Q(J,J);else{var d,k=J;b=h.j;for(var f=h,p=h;!(d=(f=f.H).i););do for(var m=p.O,l=(p=p.H).m,u=l.length;++m<u&&l[m]&&!(k=l[m].j););while(!k&&p!==f);p=h;Q(d,k);if(p.j!==b)for(;!(p=p.H).i;){b=J;d=e(p.m);for(k=d.next();!(k.done||(k=k.value)&&(b=k.j));k=d.next());if(b===p.j)break;p.j=b}}n=L}}}A=L;C.length&&(B=
C,C=a,ta())}function ta(){return z||(z=requestAnimationFrame(W))}function ua(a){var c=D[a];if(!c){var b=a.indexOf("[");D[a]=c=ea.createElement(0>b?a.substr(0):a.substr(0,b));if(0<b)for(a=e(a.substring(b+1,a.length-1).split("][")),b=a.next();!b.done;b=a.next()){b=b.value;var d=b.indexOf("=");0<d?c[b.substr(0,d)]=b.substr(d+1):c[b]=K}}return c}function va(a){var c=E[a];if(!c){var b=ua(a);E[a]=c=function(d){return n&&(h.i=b.cloneNode(K)),Y(d),d&&d.C||J}}return c};define({defer:function(){return A=K,ta()},defer_end:function(){return cancelAnimationFrame(z),W()},hook_assert:function(a){if(!a)throw D;},hook_async:function(a,c,b){var d;if((t<r.length?(d=r[t++],L):d=r[t++]={l:2,A:O(c),h:c||I,g:J})||c&&d.A(d.h,c)&&(d.h=c)){void 0!==b&&(d.g=b);var k=r;a.apply(null,g(d.h)).then(function(f){return d.g!==f&&d.h===c&&(d.g=f,V(k))})}return d.g},hook_callback:function(a,c){var b=T();b.h=c;return b.fa||(b.fa=function(d){for(var k=[],f=0;f<arguments.length;++f)k[f]=arguments[f];
return a.apply(null,[].concat(g(b.h),g(k)))})},hook_delay:function(a){var c=e(pa(L)),b=c.next().value;c=c.next().value;oa(ra,[a,c]);return b},hook_dom:function(a,c){return n&&(h.i=ua(a).cloneNode(K)),Y(c||J)},hook_effect:oa,hook_first:function(){return n},hook_map:function(a,c,b){var d=J,k=K;if(t<r.length)if((d=r[t]).P!==a)la(d),d=J;else if(!d.D||b&&d.A(d.h,b))d.h=b||I,d.D=K;else{if(c===d.L)return++t,d.g;k=L}var f=n,p=r,m=++t,l={},u=[],q=0<c.length&&ja(c,l,u);if(d){if(d.g=[],d.L!==c)for(d.L=c,c=e(d.X),
b=c.next();!b.done;b=c.next())b=b.value,b in l||(U(d.K[b]),delete d.K[b])}else r[m-1]=d={l:3,A:O(b),h:b||I,g:[],D:K,P:a,V:q?N(c[0]):J,X:[],K:{},L:c};c=e(u);for(b=c.next();!b.done;b=c.next()){b=b.value;var w=d.K[b];if(n=!w)d.K[b]=w=[{l:1,aa:p,U:d,W:J,g:J}];if(k||n||(q?d.V(l[b],w[0].W):l[b]!==w[0].W)){r=w;t=1;try{w[0].g=a.apply(null,[w[0].W=l[b]].concat(g(d.h)))}catch(H){}}d.g.push(w[0].g)}n=f;r=p;t=m;d.X=u;return d.g},hook_memo:qa,hook_object_changes:X,hook_prev:S,hook_reducer:function(a){if(t<r.length)return r[t++].g;
var c=r,b=[a[0](J),function(d,k){d=a[d](b[0],k);b[0]!==d&&(b[0]=d,V(c))}];r[t++]={l:0,g:b};return b},hook_reducer_f:function(a,c){if(t<r.length)return r[t++].g;var b=r,d=[c?c():J,function(k){k=a(d[0],k);d[0]!==k&&(d[0]=k,V(b))}];r[t++]={l:0,g:d};return d},hook_rerender:na,hook_state:pa,hook_static:T,hook_sub:function(a,c){var b=J;if(t<r.length)if((b=r[t]).P!==a)U(b.s),b=J;else if(!b.D||c&&b.A(b.h,c))c&&(b.h=c),b.D=K;else return++t,b.g;var d=n,k=r,f=t;if(n=!b)(r[t]=b={l:4,A:O(c),h:c||I,g:J,P:a,D:K,
s:[]}).s[0]={l:2,aa:r,U:b};r=b.s;t=1;try{b.g=a.apply(null,g(b.h))}catch(p){}n=d;r=k;t=f+1;return b.g},hook_transition:function(a,c){var b=T({$:a});a=qa(sa,[a,c,b]);return b.$=a.da<=v?a.ea:(na(),a.Y===v?a.Z:a.Z+(a.ea-a.Z)*(v-a.Y)/(a.da-a.Y))},init:function(a,c){var b;c.innerHTML="";(h={u:{G:function(){return Y((b=a())[0]),b[1]},o:J},M:J,H:J,v:0,O:0,s:[],m:J,i:c,j:c,B:K}).s[0]={l:0,T:h};B[0]=[h];W()},node:Z,node_dom:function(a,c,b){return Z(va(a),c,b)},node_map:function(a,c,b){return Z(N,{G:a,L:c,o:b||
J})},now:function(){return v}})})()