"use strict";/*
 lui.js web framework 2.2.2
 inspired by react and mithril
 l3p3.de 2025
*/
{let e=null,g=!e,h=e,l=0,v=0,w=0,x=!g,y=[],z=[];
const A={},C={},D={},aa=[e,(a,b)=>a!==b&&a[0]!==b[0],(a,b)=>a!==b&&(a[0]!==b[0]||a[1]!==b[1]),(a,b)=>a!==b&&(a[0]!==b[0]||a[1]!==b[1]||a[2]!==b[2])],E=[],ba={},F=e,G=g,I=x,J=Array,K=Object,L=K.assign,M=K.keys,N=document,ca=window,ea=ca.performance||Date,O=a=>{const b=(a=M(a)).join(",");return D[b]||(D[b]=a)},Q=(a,b,c)=>{if(a===b)return!1;for(const d of c)if(a[d]!==b[d])return!0;return!1},fa=(a,b)=>a===b?E:M(a).filter(c=>a[c]!==b[c]),R=a=>a?a.length<5?aa[a.length]:ha:F,ha=(a,b)=>{if(a===b)return!1;
for(let c=0,d=a.length;c<d;++c)if(a[c]!==b[c])return!0;return!1},S=(a,b)=>{const c=e,d=b,n=c.u+1;h=c.N;l=0;c.v=I;if(c.o.B!==S){var f=F;try{f=(0,c.o.B)(c.o.l||ba)}catch(P){}var q=c.g;if(f){q&&(a=q,b=F);var r=f.length,k,t=c.j||(c.j=(new J(r)).fill(F));do{var m=t[--r];(k=f[r])&&k!==G?((g=!m)?(t[r]=e=m={o:k,K:k.l&&O(k.l),H:c,u:n,M:r,N:[],j:F,g:F,h:F,v:I},S(a,b),m.g&&a.insertBefore(m.h=m.g,b)):k.l&&Q(m.o.l,k.l,m.K)&&((e=m).o=k,S(a,b)),m.h&&(b=m.h)):m&&(T(m,a),t[r]=F)}while(r>0)}else if(c.j){for(r of c.j)r&&
T(r,a);c.j=F}q||(c.h=b!==d?b:F)}else{r=c.o.l.B;var u=c.o.l.U;m=c.o.l.l;t=u.length;let P=G;if(!(U(t,t)+t<=0)){k=ia();f={};q=[];var p;if(p=t>0){p=typeof u[0]==="object";for(var B of u)u=p?B.id:B,f[u]=B,q.push(u)}B=p;if(k.J){P=m&&Q(m,k.P,k.K);for(var H of k.O)H in f||(T(k.J[H],a),delete k.J[H]);k.P=m;k.O=q}else k.J={},k.T=B?O(f[q[0]]):F,k.O=q,k.K=(k.P=m)&&O(m);for(H=c.j=new J(t);t>0;){u=q[--t];p=k.J[u];if(g=!p)k.J[u]=e=p={o:{B:r,l:L({I:f[u]},m)},K:F,H:c,u:n,M:t,N:[],j:F,g:F,h:F,v:I},S(a,b),p.g&&a.insertBefore(p.h=
p.g,b);else{const da=ja(p);da&&da.nextSibling!==b&&ka(p,a,b);if(P||B&&Q(f[u],p.o.l.I,k.T))(e=p).o.l=L({I:f[u]},m),S(a,b)}(H[p.M=t]=p).h&&(b=p.h)}c.h=b!==d?b:F}}},T=(a,b)=>{b&&a.g&&(a.g.remove(),b=F);if(a.j)for(var c of a.j)c&&T(c,b);b=a.N;let d=b.length;for(;d>1;)switch((c=b[--d]).A){case 1:c.L&&c.L(...c.m);break;case 2:c.m=E}if(a.v){let n,f;(!(f=y[n=a.u])||(n=f.indexOf(a))<0)&&(!(f=z[n])||(n=f.indexOf(a))<0)||f.splice(n,1)}},ja=a=>{if(a.g)return a.g;let b;a=(b=a.j)?b.length:0;let c,d;for(;a>0;)if((d=
b[--a])&&(c=ja(d)))return c;return F},ka=(a,b,c)=>{if(a.g)return b.insertBefore(a.g,c);if(a.h){let d=a.j.length;do a.j[--d]&&(c=ka(a.j[d],b,c));while(d>0)}return c},W=a=>!a.v&&(a.v=G,y[a.u]?y[a.u].push(a):y[a.u]=[a],x||V()),ia=a=>(l<h.length?h[l++]:h[l++]={A:0,i:a===void 0?{}:a}).i,U=(a,b)=>(l<h.length?(b=h[l].i,h[l++].i=a):h[l++]={A:0,i:a},b),X=a=>{const b=U(a,F);return b?fa(b,a):M(a)},la=a=>{const b=e.g;if(a){for(const c of X(a)){switch(c.charCodeAt(0)){case 70:b.className=M(a.F).filter(d=>a.F[d]).join(" ");
continue;case 82:a.R(b);case 67:case 68:case 83:continue}b[c]=a[c]}if(a.D)for(const c of X(a.D))b.dataset[c]=a.D[c];if(a.S)for(const c of X(a.S))b.style[c]=a.S[c]}return b},Y=(a,b,c)=>({B:a,l:b?c?(b.C=c,b):b:c?{C:c}:F}),V=()=>{g=v<=0;v=ea.now();w&&cancelAnimationFrame(w);x=G;w=0;for(var a;(a=y).length;){y=[];for(const b of a)if(b)for(e of b)if(e.v){if(e.g)S(F,F);else{let c=F,d=e.h,n=e,f=e;for(;!(a=(n=n.H).g););do{let q=f.M;const {j:r}=f=f.H,k=r.length;for(;++q<k&&r[q]&&!(c=r[q].h););}while(!c&&f!==
n);f=e;S(a,c);if(f.h!==d)for(;!(f=f.H).g;){d=F;for(const q of f.j)if(q&&(d=q.h))break;if(d===f.h)break;f.h=d}}g=I}}x=I;z.length&&(y=z,z=a,ma())},ma=()=>w||(w=requestAnimationFrame(V)),Z=a=>{let b=A[a];if(!b){const c=a.indexOf("[");A[a]=b=N.createElement(c<0?a:a.substr(0,c));if(c>0)for(const d of a.substring(c+1,a.length-1).split("]["))a=d.indexOf("="),a>0?b[d.substr(0,a)]=d.substr(a+1):b[d]=G}return b},na=a=>{let b=C[a];if(!b){const c=Z(a);C[a]=b=d=>(g&&(e.g=c.cloneNode(G)),la(d),d&&d.C||F)}return b};ca.lui={defer:()=>(x=G,ma()),defer_end:V,dom_define:(a,b,c)=>{b=Z(b);c&&(b=b.cloneNode(G),c.D&&(L(b.dataset,c.D),delete c.D),c.S&&(L(b.style,c.S),delete c.S),L(b,c));A["#"+a]=b},hook_assert:a=>{if(!a)throw A;},hook_async:(a,b,c)=>{let d;if((l<h.length?(d=h[l++],I):d=h[l++]={A:2,G:R(b),m:b||E,i:F})||b&&d.G(d.m,b)&&(d.m=b)){c!==void 0&&(d.i=c);const n=e;a(...d.m).then(f=>d.i!==f&&d.m===b&&(d.i=f,W(n)))}return d.i},hook_dom:(a,b)=>(e.g===F&&(e.g=Z(a).cloneNode(G)),la(b||F)),hook_effect:(a,b)=>{if(l>=
h.length)h[l]={A:1,G:R(b),m:b=b||E,L:a(...b)||F};else if(b){const c=h[l];c.G(c.m,b)&&(c.L&&c.L(...c.m),c.L=a(...(c.m=b))||F)}++l},hook_memo:(a,b)=>l>=h.length?(h[l++]={A:0,G:R(b),m:b=b||E,i:a(...b)}).i:b&&h[l].G(h[l].m,b)?h[l].i=a(...(h[l++].m=b)):h[l++].i,hook_model:a=>{if(l<h.length)return h[l++].i;const b=e,c=[(0,a.init)(F),{}];for(const d of M(a))c[1][d]=(...n)=>{n=(0,a[d])(c[0],...n);c[0]!==n&&(c[0]=n,W(b))};h[l++]={A:0,i:c};return c},hook_prev:U,hook_rerender:()=>{const a=e;a.v=G;z[a.u]?z[a.u].push(a):
z[a.u]=[a]},hook_state:a=>{if(l<h.length)return h[l++].i;const b=e,c=[a,d=>{c[0]!==d&&(c[0]=d,W(b))},()=>c[0]];h[l++]={A:0,i:c};return c},hook_static:ia,init:(a,b=N.body,c=F)=>{b.innerHTML="";W({o:{B:a,l:c},K:F,H:F,u:0,M:0,N:[],j:F,g:b,h:b,v:I})},node:Y,node_dom:(a,b,c)=>Y(na(a),b,c),node_map:(a,b,c)=>Y(S,{B:a,U:b,l:c||F}),now:()=>v}}
