'use strict';/*
 lui.js web frame work 1.1.3
 inspired by react and mithril
 L3P3.de 2021
*/
{let e=null,f=!e,g=e,h=0,p=0,t=0,u=f,x=[],y=[];
const A={},aa={},ba={},ca=[],B=[],C=e,D=f,E=!f,G=Array,da=Object,ea=da.assign,H=da.keys,fa=document,I=window,ha=I.performance||Date,ia=({s:{A:a}})=>a===J?"list":a.name_||a.name||"?",K=a=>{throw Error("lui: "+a);},L=(a,b)=>{a===b||a&&b&&JSON.stringify(H(a))===JSON.stringify(H(b))||K("object keys mismatch")},M=(a,b,c)=>{g||K("hook called outside of hook context");c&&(c.constructor!==G&&K("deps must be in an array"),0===c.length&&K("deps must not be empty"));b&&0!==g[0].i&&K("hook called outside of component rendering");
a!==C&&h<g.length&&(g[h].i!==a&&K("inconsistent hook order"),g[h].h&&ja(g[h].h,c))},O=(a,b)=>{M(C,E,C);a!==N(a,a)&&K(b+" changed between renderings")},ja=(a,b)=>{b?a.length!==b.length&&K("deps length changed"):0<a.length&&K("deps presence changed")},ka=a=>new Function("a","b",`return a!==b&&(${a.join("||")})`),J=a=>{const b=(a=H(a)).join(",");return ba[b]||(0===a.length&&K("object empty"),a.some(c=>(c.includes("-")||"0123456789".includes(c.charAt(0)))&&K("invalid key: "+c)),ba[b]=ka(a.map(c=>`a.${c}!==b.`+
c)))},la=(a,b)=>(L(a,b),a===b?B:H(a).filter(c=>a[c]!==b[c])),R=a=>a?ca[a.length]||(0===a.length&&K("deps must not be empty"),ca[a.length]=ka(a.map((b,c)=>`a[${c}]!==b[${c}]`))):C,S=(a,b)=>{const c=e,d=b,l=c.v+1;g=c.u;h=1;c.D=E;if(c.s.A!==J){var m=C;try{m=c.s.A(c.s.o)}catch(P){if(P!==A)throw P;}var q=c.j;"object"!==typeof m&&K("components need to return child list or null");if(m){q&&(a=q,b=C);var r=m.length,k;"number"!==typeof r&&K("childs must be returned in a list");0===r&&K("returned childs list empty");
c.l&&r!==c.l.length&&K("returned childs count changed");var v=c.l||(c.l=(new G(r)).fill(C));do{var n=v[--r];if((k=m[r])&&k!==D){n&&n.s.A!==k.A&&K("child component changed at "+r);if(f=!n)(v[r]=e=n={s:k,P:k.o&&J(k.o),J:c,v:l,O:r,u:[],l:C,j:C,m:C,D:E}).u[0]={i:0,T:n},S(a,b),n.j&&a.insertBefore(n.m=n.j,b);else if(L(n.s.o,k.o),k.o&&n.P(n.s.o,k.o))(e=n).s=k,S(a,b);n.m&&(b=n.m)}else n&&(T(n,a),v[r]=C)}while(0<r)}else if(c.l){for(r of c.l)r&&T(r,a);c.l=C}q||(c.m=b!==d?b:C)}else{r=c.s.o.A;var w=c.s.o.N;n=
c.s.o.o;"object"===typeof w&&w&&w.constructor===G||K("list_data must be an array");"object"!==typeof n&&K("props must be an object");O(r,"item component");O(n&&H(n).join(","),"common props");v=w.length;let P=D;if(!(0>=N(v,v)+v)){k=U();m={};q=[];w=0<v&&ma(w,m,q);v||U();if(k.L){P=n!==C&&k.P(n,k.ca);for(var F of k.ba)F in m||(T(k.L[F],a),delete k.L[F]);k.ca=n;k.ba=q}else k.L={},k.X=w?J(m[q[0]]):C,k.ba=q,k.P=(k.ca=n)&&J(n);for(F=c.l=new G(v);0<v;){const Q=q[--v];let z=k.L[Q];if(f=!z)(k.L[Q]=e=z={s:{A:r,
o:ea({I:m[Q]},n)},P:C,J:c,v:l,O:v,u:[],l:C,j:C,m:C,D:E}).u[0]={i:0,T:z},S(a,b),z.j&&a.insertBefore(z.m=z.j,b);else if(na(z,a,b),P||w&&k.X(m[Q],z.s.o.I))(e=z).s.o=ea({I:m[Q]},n),S(a,b);(F[z.O=v]=z).m&&(b=z.m)}c.m=b!==d?b:C}}},T=(a,b)=>{b&&a.j&&(b.removeChild(a.j),b=C);if(a.l)for(const c of a.l)c&&T(c,b);V(a.u);if(a.D){let c,d;(!(d=x[c=a.v])||0>(c=d.indexOf(a)))&&(!(d=y[c])||0>(c=d.indexOf(a)))||d.splice(c,1)}},V=a=>{let b,c=a.length;for(;1<c;)switch((b=a[--c]).i){case 3:b.H&&b.H(...b.h);break;case 4:b.h=
B;break;case 7:oa(b);break;case 12:V(b.u)}},ma=(a,b,c)=>{const d="object"===typeof a[0],l=U();l.ea||(a[0]!==C&&["object","string","number"].includes(l.ea=typeof a[0])||K("item type invalid"),d&&(!["string","number"].includes(l.ha=typeof a[0].id)&&K("item id type invalid"),l.keys=H(a[0]).join(",")));for(const m of a)m===C&&K("item is null"),typeof m!==l.ea&&K("item type changed"),d&&(typeof m.id!==l.ha&&K("item id type changed"),H(m).join(",")!==l.keys&&K("item keys differ of "+m.id));for(const m of a)a=
d?m.id:m,a in b&&K("item key not unique: "+a),b[a]=m,c.push(a);return d},na=(a,b,c)=>{if(a.j)return b.insertBefore(a.j,c),a.j;if(a.m){let d=a.l.length;do a.l[--d]&&(c=na(a.l[d],b,c));while(0<d)}return c},pa=a=>{for(;0!==a[0].i;){if(!a[0].W.G)return C;a[0].W.G=E;a=a[0].V}return a[0].T},X=a=>(a=pa(a))&&!a.D&&(a.D=D,x[a.v]?x[a.v].push(a):x[a.v]=[a],u||W()),qa=()=>{M(C,E,C);const a=pa(g);a&&(a.D=D,y[a.v]?y[a.v].push(a):y[a.v]=[a])},ra=(a,b)=>{M(3,E,b);if(h>=g.length)g[h]={i:3,B:R(b),h:b=b||B,H:a(...b)||
C};else if(b){const c=g[h];c.B(c.h,b)&&(c.H&&c.H(...c.h),c.H=a(...(c.h=b))||C)}g[h].H&&g[h].H.then&&K("effect function must be synchronous");++h},sa=a=>{M(5,E,C);if(h<g.length)return g[h++].g;const b=g,c=[a,d=>{c[0]!==d&&(c[0]=d,X(b))},()=>c[0]];g[h++]={i:5,g:c};return c},U=a=>(M(6,E,C),(h<g.length?g[h++]:g[h++]={i:6,g:void 0===a?{}:a}).g),ta=(a,b)=>(M(8,E,b),h>=g.length?(g[h++]={i:8,B:R(b),h:b=b||B,g:a(...b)}).g:b&&g[h].B(g[h].h,b)?g[h].g=a(...(g[h++].h=b)):g[h++].g),N=(a,b)=>(M(9,E,C),h<g.length?
(b=g[h].g,g[h++].g=a):g[h++]={i:9,g:a},b),ua=(a,b)=>(a=setTimeout(()=>b(D),a),()=>clearTimeout(a)),oa=a=>{for(const b of a.Y)V(a.M[b])},va=(a,b,c)=>({$:c.aa,fa:a,Z:p,da:f?p:p+b}),Y=a=>{"object"===typeof a&&a||K("object required");const b=N(a,C);return b?la(b,a):H(a)},Z=a=>{O(!a,"attributes presence");const b=e.j;if(a){for(const c of Y(a))switch(1<c.length&&c.charAt(0).toLowerCase()!==c.charAt(0)&&K("capital prop: "+c),c.charCodeAt(0)){case 70:"object"===typeof a.F&&a.F||K("invalid css flags");b.className=
H(a.F).filter(d=>a.F[d]).join(" ");continue;case 82:"function"!==typeof a.R&&K("invalid ref"),a.R(b);case 67:case 83:continue;default:97>c.charCodeAt(0)&&K("invalid prop: "+c),b[c]=a[c]}O(!a.S,"style presence");if(a.S)for(const c of Y(a.S))b.style[c]=a.S[c]}return b},wa=(a,b,c)=>("string"===typeof a&&K("component expected, use node_dom instead"),c&&c.constructor!==G&&K("invalid childs type"),{A:a,o:b?c?(b.C=c,b):b:c?{C:c}:C}),W=()=>{f=0>=p;p=ha.now();u=D;t=0;var a;let b=0;for(;(a=x).length;){10<++b&&
K("rerender loop detected");x=[];for(const c of a)if(c)for(e of c)if(e.D){if(e.j)S(C,C);else{let d=C,l=e.m,m=e,q=e;for(;!(a=(m=m.J).j););do{let r=q.O;const {l:k}=q=q.J,v=k.length;for(;++r<v&&k[r]&&!(d=k[r].m););}while(!d&&q!==m);q=e;S(a,d);if(q.m!==l)for(;!(q=q.J).j;){l=C;for(const r of q.l)if(r&&(l=r.m))break;if(l===q.m)break;q.m=l}}f=E}}u=E;e=g=C;y.length&&(x=y,y=a,xa())},xa=()=>t||(t=requestAnimationFrame(W)),ya=a=>{var b=A[a];if(!b){const c=a.indexOf("[");b=0>c?a.substr(0):a.substr(0,c);(0===
b.length||b!==b.toLowerCase()||b.includes(" ")||b.includes("#")||b.includes("."))&&K("dom: invalid tag");A[a]=b=fa.createElement(b);if(0<c){!a.endsWith("]")&&K("dom: ] missing");for(const d of a.substring(c+1,a.length-1).split("]["))!d&&K("dom: empty attribute"),(d.includes("[")||d.includes("]"))&&K("dom: attributes screwed up"),a=d.indexOf("="),d.includes(" ")&&(0>a||d.indexOf(" ")<a)&&K("dom: space in attribute name"),0<a?b[d.substr(0,a)]=d.substr(a+1):b[d]=D}}return b},za=a=>{let b=aa[a];if(!b){const c=
ya(a);aa[a]=b=d=>(f&&(e.j=c.cloneNode(D)),Z(d),d&&d.C||C);b.name_="$"+a}return b};I.onerror=()=>{if(e){var a=console,b=a.log;const c=[];let d=g,l=C;if(d){for(c.unshift("$"+(h-1));0!==d[0].i;)c.unshift(1===d[0].i?`hook_map[${"object"===typeof d[0].K?d[0].K.id:d[0].K}]`:"hook_sub"),d=d[0].V;d=d[0].T}for(;d;)c.unshift(ia(d)+(l?":"+l:"")),l=d.O,d=d.J;b.call(a,"lui "+(c.join("/")||"-")+": error",...[])}return x=y=[]};I.lui={defer:()=>(e&&K("defer while rendering"),u=D,xa()),defer_end:()=>(e&&K("defer_end while rendering"),u||K("nothing was deferred"),cancelAnimationFrame(t),W()),hook_assert:a=>{M(C,E,C);if(!a)throw A;},hook_async:(a,b,c)=>{M(4,E,b);let d;if((h<g.length?(d=g[h++],E):d=g[h++]={i:4,B:R(b),h:b||B,g:C})||b&&d.B(d.h,b)&&(d.h=b)){void 0!==c&&(d.g=c);const l=g;a(...d.h).then(m=>d.g!==m&&d.h===b&&(d.g=m,X(l)))}return d.g},hook_callback:(a,b)=>{const c=U();c.h&&ja(c.h,b);c.h=b;return c.ga||(c.ga=(...d)=>
a(...c.h,...d))},hook_delay:a=>{const [b,c]=sa(E);ra(ua,[a,c]);return b},hook_dom:(a,b)=>(M(C,D,C),e.j?f&&K("hook_dom called twice"):f||K("hook_dom skipped before"),b&&(b.C&&K("hook_dom cannot have childs"),b.R&&K("hook_dom cannot have a ref")),f&&(e.j=ya(a).cloneNode(D)),Z(b||C)),hook_effect:ra,hook_first:()=>(M(C,E,C),f),hook_map:(a,b,c)=>{M(7,E,c);let d=C,l=D;if(h<g.length)if((d=g[h]).U!==a)oa(d),d=C;else if(!d.G||c&&d.B(d.h,c))d.h=c||B,d.G=D;else{if(b===d.N)return++h,d.g;l=E}const m=f,q=g,r=++h,
k={},v=[],n=0<b.length&&ma(b,k,v);0===b.length&&U();if(d){if(d.g=[],d.N!==b){d.N=b;for(const w of d.Y)w in k||(V(d.M[w]),delete d.M[w])}}else g[r-1]=d={i:7,B:R(c),h:c||B,g:[],G:D,U:a,X:n?J(b[0]):C,Y:[],M:{},N:b};for(const w of v){b=d.M[w];if(f=!b)d.M[w]=b=[{i:1,V:q,W:d,K:C,g:C}];if(l||f||(n?d.X(k[w],b[0].K):k[w]!==b[0].K)){g=b;h=1;try{b[0].g=a(b[0].K=k[w],...d.h)}catch(F){if(F!==A)throw F;}g=q}d.g.push(b[0].g)}f=m;g=q;h=r;d.Y=v;return d.g},hook_memo:ta,hook_object_changes:Y,hook_prev:N,hook_reducer:a=>
{M(10,E,C);a&&a.constructor!==G&&K("actions array required");"function"===typeof a&&K("array required, use hook_reducer_f instead");if(h<g.length)return g[h++].g;const b=g,c=[a[0](C),(d,l)=>{d=a[d](c[0],l);c[0]!==d&&(c[0]=d,X(b))}];g[h++]={i:10,g:c};return c},hook_reducer_f:(a,b)=>{M(11,E,C);"function"!==typeof a&&K("reducer function required");b&&"function"!==typeof b&&K("initializer must be a function");if(h<g.length)return g[h++].g;const c=g,d=[b?b():C,l=>{l=a(d[0],l);d[0]!==l&&(d[0]=l,X(c))}];
g[h++]={i:11,g:d};return d},hook_rerender:qa,hook_state:sa,hook_static:U,hook_sub:(a,b)=>{M(12,E,b);let c=C;if(h<g.length)if((c=g[h]).U!==a)V(c.u),c=C;else if(!c.G||b&&c.B(c.h,b))b&&(c.h=b),c.G=D;else return++h,c.g;const d=f,l=g,m=h;if(f=!c)(g[h]=c={i:12,B:R(b),h:b||B,g:C,U:a,G:D,u:[]}).u[0]={i:2,V:g,W:c};g=c.u;h=1;try{c.g=a(...c.h)}catch(q){if(q!==A)throw q;}f=d;g=l;h=m+1;return c.g},hook_transition:(a,b)=>{const c=U({aa:a});a=ta(va,[a,b,c]);return c.aa=a.da<=p?a.fa:(qa(),a.Z===p?a.$:a.$+(a.fa-a.$)*
(p-a.Z)/(a.da-a.Z))},init:a=>{(e||x.length||y.length)&&K("init called more than once");"function"!==typeof a&&K("no init function specified");let b;const c=fa.body;c.innerHTML="";const d=()=>((!(b=a())||2!==b.length)&&K("root component must return [props, childs]"),O(!b[0],"attributes presence"),b[0]!==C&&("object"!==typeof b[0]&&K("invalid props type"),L(N(b[0],b[0]),b[0]),b[0].C&&K("root childs must be in second return value")),Z(b[0]),b[1]);d.name_="$root";(e={s:{A:d,o:C},P:C,J:C,v:0,O:0,u:[],
l:C,j:c,m:c,D}).u[0]={i:0,T:e};x[0]=[e];e=g=C;W()},node:wa,node_dom:(a,b,c)=>wa(za(a),b,c),node_map:(a,b,c)=>wa(J,{A:a,N:b,o:c||C}),now:()=>p}}