function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function g(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function h(a){if(!(a instanceof Array)){a=g(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function ba(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};/*
 lui.js web frame work 1.1.5
 inspired by react and mithril
 L3P3.de 2021
*/
(function(){var k=null,p=!k,r=k,t=0,v=0,z=0,A=p,B=[],C=[],D={},ca={},da={},ea=[],E=[],F=k,G=p,H=!p,I=Array,K=Object,fa=K.assign||(K.assign=function(a){for(var b=arguments.length,c=0,d,e;++c<b;)if(d=arguments[c])for(e in d)a[e]=d[e];return a}),L=K.keys||(K.keys=function(a){var b=[],c;for(c in a)b.push(c);return b}),ha=setTimeout,ia=clearTimeout,ja=document,M=window,N=Date;function ka(a){return new Function("a","b","return a!==b&&("+a.join("||")+")")}
function O(a){var b=(a=L(a)).join(",");return da[b]||(da[b]=ka(a.map(function(c){return"a."+c+"!==b."+c})))}function la(a,b){return a===b?E:L(a).filter(function(c){return a[c]!==b[c]})}function P(a){return a?ea[a.length]||(ea[a.length]=ka(a.map(function(b,c){return"a["+c+"]!==b["+c+"]"}))):F}
function Q(a,b){var c=k,d=b,e=c.v+1;r=c.s;t=1;c.D=H;if(c.u.H!==O){var f=F;try{f=(0,c.u.H)(c.u.o)}catch(Da){}var m=c.i;if(f){m&&(a=m,b=F);var n=f.length,l,u=c.m||(c.m=(new I(n)).fill(F));do{var q=u[--n];(l=f[n])&&l!==G?((p=!q)?((u[n]=k=q={u:l,N:l.o&&O(l.o),J:c,v:e,P:n,s:[],m:F,i:F,j:F,D:H}).s[0]={l:0,U:q},Q(a,b),q.i&&a.insertBefore(q.j=q.i,b)):l.o&&q.N(q.u.o,l.o)&&((k=q).u=l,Q(a,b)),q.j&&(b=q.j)):q&&(R(q,a),u[n]=F)}while(0<n)}else if(c.m){e=g(c.m);for(f=e.next();!f.done;f=e.next())(f=f.value)&&R(f,
a);c.m=F}m||(c.j=b!==d?b:F)}else{f=c.u.o;m=f.H;var w=f.M;f=f.o;n=w.length;q=G;if(!(0>=S(n,n)+n)){l=T();u={};var J=[];w=0<n&&ma(w,u,J);if(l.K){q=f!==F&&l.N(f,l.da);for(var U=g(l.ca),x=U.next();!x.done;x=U.next())x=x.value,void 0===u[x]&&(R(l.K[x],a),delete l.K[x]);l.da=f;l.ca=J}else l.K={},l.W=w?O(u[J[0]]):F,l.ca=J,l.N=(l.da=f)&&O(f);for(U=c.m=new I(n);0<n;){x=J[--n];var y=l.K[x];if(p=!y)(l.K[x]=k=y={u:{H:m,o:fa({I:u[x]},f)},N:F,J:c,v:e,P:n,s:[],m:F,i:F,j:F,D:H}).s[0]={l:0,U:y},Q(a,b),y.i&&a.insertBefore(y.j=
y.i,b);else if(na(y,a,b),q||w&&l.W(u[x],y.u.o.I))(k=y).u.o=fa({I:u[x]},f),Q(a,b);(U[y.P=n]=y).j&&(b=y.j)}c.j=b!==d?b:F}}}function R(a,b){b&&a.i&&(b.removeChild(a.i),b=F);if(a.m)for(var c=g(a.m),d=c.next();!d.done;d=c.next())(d=d.value)&&R(d,b);V(a.s);if(a.D){var e,f;(!(f=B[e=a.v])||0>(e=f.indexOf(a)))&&(!(f=C[e])||0>(e=f.indexOf(a)))||f.splice(e,1)}}
function V(a){for(var b,c=a.length;1<c;)switch((b=a[--c]).l){case 1:b.O&&b.O.apply(b,h(b.h));break;case 2:b.h=E;break;case 3:oa(b);break;case 4:V(b.s)}}function ma(a,b,c){var d,e="object"===typeof a[0];a=g(a);for(d=a.next();!d.done;d=a.next()){d=d.value;var f=e?d.id:d;b[f]=d;c.push(f)}return e}function na(a,b,c){if(a.i)return b.insertBefore(a.i,c),a.i;if(a.j){var d=a.m.length;do a.m[--d]&&(c=na(a.m[d],b,c));while(0<d)}return c}
function pa(a){for(;0!==a[0].l;){if(!a[0].V.G)return F;a[0].V.G=H;a=a[0].ba}return a[0].U}function W(a){return(a=pa(a))&&!a.D&&(a.D=G,B[a.v]?B[a.v].push(a):B[a.v]=[a],A||X())}function qa(){var a=pa(r);a&&(a.D=G,C[a.v]?C[a.v].push(a):C[a.v]=[a])}function ra(a,b){if(t>=r.length)r[t]={l:1,A:P(b),h:b=b||E,O:a.apply(null,h(b))||F};else if(b){var c=r[t];c.A(c.h,b)&&(c.O&&c.O.apply(c,h(c.h)),c.O=a.apply(null,h(c.h=b))||F)}++t}
function sa(a){if(t<r.length)return r[t++].g;var b=r,c=[a,function(d){c[0]!==d&&(c[0]=d,W(b))},function(){return c[0]}];r[t++]={l:0,g:c};return c}function T(a){return(t<r.length?r[t++]:r[t++]={l:0,g:void 0===a?{}:a}).g}function ta(a,b){return t>=r.length?(r[t++]={l:0,A:P(b),h:b=b||E,g:a.apply(null,h(b))}).g:b&&r[t].A(r[t].h,b)?r[t].g=a.apply(null,h(r[t++].h=b)):r[t++].g}function S(a,b){return t<r.length?(b=r[t].g,r[t++].g=a):r[t++]={l:0,g:a},b}
function ua(a,b){return a=ha(function(){return b(G)},a),function(){return ia(a)}}function oa(a){for(var b=g(a.Y),c=b.next();!c.done;c=b.next())V(a.L[c.value])}function va(a,b,c){return{$:c.aa,fa:a,Z:v,ea:p?v:v+b}}function wa(a){var b=S(a,F);return b?la(b,a):L(a)}
function xa(a){var b=k.i;if(a){for(var c=g(wa(a)),d=c.next();!d.done;d=c.next())switch(d=d.value,d){case "F":b.className=L(a.F).filter(function(e){return a.F[e]}).join(" ");continue;case "R":a.R(b);case "C":case "S":continue;default:b[d]=a[d]}if(a.S)for(c=g(wa(a.S)),d=c.next();!d.done;d=c.next())d=d.value,b.style[d]=a.S[d]}return b}function ya(a,b,c){return{H:a,o:b?c?(b.C=c,b):b:c?{C:c}:F}}
function X(){p=0>=v;v=N.now();z&&cancelAnimationFrame(z);A=G;z=0;for(var a;(a=B).length;){B=[];a=g(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value){b=g(b);for(var c=b.next();!c.done;c=b.next())if(k=c.value,k.D){if(k.i)Q(F,F);else{var d,e=F;c=k.j;for(var f=k,m=k;!(d=(f=f.J).i););do for(var n=m.P,l=(m=m.J).m,u=l.length;++n<u&&l[n]&&!(e=l[n].j););while(!e&&m!==f);m=k;Q(d,e);if(m.j!==c)for(;!(m=m.J).i;){c=F;d=g(m.m);for(e=d.next();!(e.done||(e=e.value)&&(c=e.j));e=d.next());if(c===m.j)break;m.j=
c}}p=H}}}A=H;C.length&&(B=C,C=a,za())}function za(){return z||(z=requestAnimationFrame(X))}var Aa=X;function Ba(a){var b=D[a];if(!b){var c=a.indexOf("[");D[a]=b=ja.createElement(0>c?a.substr(0):a.substr(0,c));if(0<c)for(a=g(a.substring(c+1,a.length-1).split("][")),c=a.next();!c.done;c=a.next()){c=c.value;var d=c.indexOf("=");0<d?b[c.substr(0,d)]=c.substr(d+1):b[c]=G}}return b}
function Ca(a){var b=ca[a];if(!b){var c=Ba(a);ca[a]=b=function(d){return p&&(k.i=c.cloneNode(G)),xa(d),d&&d.C||F}}return b}var Y=I.prototype,Z=String.prototype;
N.now||(N.now=function(){return(new N).getTime()},Y.map||(Y.map=function(a){for(var b=[],c=this.length,d=0;d<c;++d)b.push(a(this[d],d));return b},Y.filter=function(a){for(var b=[],c=this.length,d=0;d<c;++d)a(this[d],d)&&b.push(this[d]);return b},Y.indexOf=function(a,b){b=b||0;for(var c=this.length;b<c;++b)if(this[b]===a)return b;return-1},Y.fill=function(a){for(var b=this.length,c=0;c<b;++c)this[c]=a;return this},Y.push||(Y.push=function(a){this[this.length]=a},Y.concat=function(){for(var a=arguments,
b=this,c=[],d=a.length,e=b.length,f=0,m=0,n=-1;m<e;++m)c[++n]=b[m];for(;f<d;++f)for(e=(m=0,b=a[f]).length;m<e;++m)c[++n]=b[m];return c},Y.join=function(a){for(var b="",c=this.length-1,d=0;d<c;++d)b+=this[d]+a;d<c+1&&(b+=this[d]);return b},Z.split=function(a){for(var b=[],c=this.length,d=a.length,e=0,f;0<=(f=this.indexOf(a,e));e=f+d)b.push(this.substring(e,f));e<c&&b.push(this.substr(e));return b},Function.prototype.apply=function(a,b){a=null==a?(M.B=this,M):(K.prototype.B=this,a);switch(b?b.length:
0){case 0:return a.B();case 1:return a.B(b[0]);case 2:return a.B(b[0],b[1]);case 3:return a.B(b[0],b[1],b[2]);case 4:return a.B(b[0],b[1],b[2],b[3]);case 5:return a.B(b[0],b[1],b[2],b[3],b[4]);default:return a.B(b[0],b[1],b[2],b[3],b[4],b[5])}},Z.charAt||(Z.charAt=function(a){return this[a]},Z.substring=function(a,b){for(var c="";a<b;++a)c+=this[a];return c},Z.substr=function(a){return this.substring(a,this.length)},Z.indexOf=function(a,b){a=a[0];b=b||0;for(var c=this.length;b<c;++b)if(this[b]===
a)return b;return-1}))));M.requestAnimationFrame||(requestAnimationFrame=M.mozRequestAnimationFrame||M.webkitCancelAnimationFrame&&M.webkitRequestAnimationFrame||function(a){return ha(a,20)},cancelAnimationFrame=M.mozCancelAnimationFrame||M.webkitCancelAnimationFrame||ia);M.lui={defer:function(){return A=G,za()},defer_end:Aa,hook_assert:function(a){if(!a)throw D;},hook_async:function(a,b,c){var d;if((t<r.length?(d=r[t++],H):d=r[t++]={l:2,A:P(b),h:b||E,g:F})||b&&d.A(d.h,b)&&(d.h=b)){void 0!==c&&(d.g=c);var e=r;a.apply(null,h(d.h)).then(function(f){return d.g!==f&&d.h===b&&(d.g=f,W(e))})}return d.g},hook_callback:function(a,b){var c=T();c.h=b;return c.ga||(c.ga=function(){var d=ba.apply(0,arguments);return a.apply(null,[].concat(h(c.h),h(d)))})},hook_delay:function(a){var b=
g(sa(H)),c=b.next().value;b=b.next().value;ra(ua,[a,b]);return c},hook_dom:function(a,b){return p&&(k.i=Ba(a).cloneNode(G)),xa(b||F)},hook_effect:ra,hook_first:function(){return p},hook_map:function(a,b,c){var d=F,e=G;if(t<r.length)if((d=r[t]).T!==a)oa(d),d=F;else if(!d.G||c&&d.A(d.h,c))d.h=c||E,d.G=G;else{if(b===d.M)return++t,d.g;e=H}var f=p,m=r,n=++t,l={},u=[],q=0<b.length&&ma(b,l,u);if(d){if(d.g=[],d.M!==b)for(d.M=b,b=g(d.Y),c=b.next();!c.done;c=b.next())c=c.value,void 0===l[c]&&(V(d.L[c]),delete d.L[c])}else r[n-
1]=d={l:3,A:P(c),h:c||E,g:[],G:G,T:a,W:q?O(b[0]):F,Y:[],L:{},M:b};b=g(u);for(c=b.next();!c.done;c=b.next()){c=c.value;var w=d.L[c];if(p=!w)d.L[c]=w=[{l:1,ba:m,V:d,X:F,g:F}];if(e||p||(q?d.W(l[c],w[0].X):l[c]!==w[0].X)){r=w;t=1;try{w[0].g=a.apply(null,[w[0].X=l[c]].concat(h(d.h)))}catch(J){}}d.g.push(w[0].g)}p=f;r=m;t=n;d.Y=u;return d.g},hook_memo:ta,hook_object_changes:wa,hook_prev:S,hook_reducer:function(a){if(t<r.length)return r[t++].g;var b=r,c=[(0,a[0])(F),function(d,e){var f=(0,a[d])(c[0],e);
c[0]!==f&&(c[0]=f,W(b))}];r[t++]={l:0,g:c};return c},hook_reducer_f:function(a,b){if(t<r.length)return r[t++].g;var c=r,d=[b?b():F,function(e){e=a(d[0],e);d[0]!==e&&(d[0]=e,W(c))}];r[t++]={l:0,g:d};return d},hook_rerender:qa,hook_state:sa,hook_static:T,hook_sub:function(a,b){var c=F;if(t<r.length)if((c=r[t]).T!==a)V(c.s),c=F;else if(!c.G||b&&c.A(c.h,b))b&&(c.h=b),c.G=G;else return++t,c.g;var d=p,e=r,f=t;if(p=!c)(r[t]=c={l:4,A:P(b),h:b||E,g:F,T:a,G:G,s:[]}).s[0]={l:2,ba:r,V:c};r=c.s;t=1;try{c.g=a.apply(null,
h(c.h))}catch(m){}p=d;r=e;t=f+1;return c.g},hook_transition:function(a,b){var c=T({aa:a}),d=ta(va,[a,b,c]);return c.aa=d.ea<=v?d.fa:(qa(),d.Z===v?d.$:d.$+(d.fa-d.$)*(v-d.Z)/(d.ea-d.Z))},init:function(a){var b,c=ja.body;c.innerHTML="";(k={u:{H:function(){return xa((b=a())[0]),b[1]},o:F},N:F,J:F,v:0,P:0,s:[],m:F,i:c,j:c,D:G}).s[0]={l:0,U:k};B[0]=[k];X()},node:ya,node_dom:function(a,b,c){return ya(Ca(a),b,c)},node_map:function(a,b,c){return ya(O,{H:a,M:b,o:c||F})},now:function(){return v}}})()