function aa(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}function e(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):{next:aa(a)}}function f(a){if(!(a instanceof Array)){a=e(a);for(var c,b=[];!(c=a.next()).done;)b.push(c.value);a=b}return a}function ba(){for(var a=Number(this),c=[],b=a;b<arguments.length;b++)c[b-a]=arguments[b];return c};/*
 lui.js web frame work 1.2.0
 inspired by react and mithril
 L3P3.de 2021
*/
(function(){var g=null,n=!g,r=g,t=0,u=0,z=0,A=n,B=[],C=[],D={},E={},F={},ca=[],G=[],I=g,J=n,K=!n,da=/[A-Z]/g,L=Array,ea=Object,fa=ea.assign,M=ea.keys,ha=document,ia=window.performance||Date;function ja(a){return new Function("a","b","return a!==b&&("+a.join("||")+")")}function N(a){var c=(a=M(a)).join(",");return F[c]||(F[c]=ja(a.map(function(b){return"a."+b+"!==b."+b})))}function ka(a,c){return a===c?G:M(a).filter(function(b){return a[b]!==c[b]})}
function O(a){return a?ca[a.length]||(ca[a.length]=ja(a.map(function(c,b){return"a["+b+"]!==b["+b+"]"}))):I}
function Q(a,c){var b=g,d=c,k=b.v+1;r=b.s;t=1;b.B=K;if(b.u.H!==N){var h=I;try{h=(0,b.u.H)(b.u.o)}catch(Aa){}var p=b.i;if(h){p&&(a=p,c=I);var m=h.length,l,v=b.m||(b.m=(new L(m)).fill(I));do{var q=v[--m];(l=h[m])&&l!==J?((n=!q)?((v[m]=g=q={u:l,N:l.o&&N(l.o),J:b,v:k,P:m,s:[],m:I,i:I,j:I,B:K}).s[0]={l:0,U:q},Q(a,c),q.i&&a.insertBefore(q.j=q.i,c)):l.o&&q.N(q.u.o,l.o)&&((g=q).u=l,Q(a,c)),q.j&&(c=q.j)):q&&(R(q,a),v[m]=I)}while(0<m)}else if(b.m){k=e(b.m);for(h=k.next();!h.done;h=k.next())(h=h.value)&&R(h,
a);b.m=I}p||(b.j=c!==d?c:I)}else{h=b.u.o;p=h.H;var w=h.M;h=h.o;m=w.length;q=J;if(!(0>=S(m,m)+m)){l=T();v={};var H=[];w=0<m&&la(w,v,H);if(l.K){q=h!==I&&l.N(h,l.da);for(var P=e(l.ca),x=P.next();!x.done;x=P.next())x=x.value,x in v||(R(l.K[x],a),delete l.K[x]);l.da=h;l.ca=H}else l.K={},l.W=w?N(v[H[0]]):I,l.ca=H,l.N=(l.da=h)&&N(h);for(P=b.m=new L(m);0<m;){x=H[--m];var y=l.K[x];if(n=!y)(l.K[x]=g=y={u:{H:p,o:fa({I:v[x]},h)},N:I,J:b,v:k,P:m,s:[],m:I,i:I,j:I,B:K}).s[0]={l:0,U:y},Q(a,c),y.i&&a.insertBefore(y.j=
y.i,c);else if(ma(y,a,c),q||w&&l.W(v[x],y.u.o.I))(g=y).u.o=fa({I:v[x]},h),Q(a,c);(P[y.P=m]=y).j&&(c=y.j)}b.j=c!==d?c:I}}}function R(a,c){c&&a.i&&(c.removeChild(a.i),c=I);if(a.m)for(var b=e(a.m),d=b.next();!d.done;d=b.next())(d=d.value)&&R(d,c);U(a.s);if(a.B){var k,h;(!(h=B[k=a.v])||0>(k=h.indexOf(a)))&&(!(h=C[k])||0>(k=h.indexOf(a)))||h.splice(k,1)}}
function U(a){for(var c,b=a.length;1<b;)switch((c=a[--b]).l){case 1:c.O&&c.O.apply(c,f(c.h));break;case 2:c.h=G;break;case 3:na(c);break;case 4:U(c.s)}}function la(a,c,b){var d,k="object"===typeof a[0];a=e(a);for(d=a.next();!d.done;d=a.next()){d=d.value;var h=k?d.id:d;c[h]=d;b.push(h)}return k}function ma(a,c,b){if(a.i)return c.insertBefore(a.i,b),a.i;if(a.j){var d=a.m.length;do a.m[--d]&&(b=ma(a.m[d],c,b));while(0<d)}return b}
function oa(a){for(;0!==a[0].l;){if(!a[0].V.G)return I;a[0].V.G=K;a=a[0].ba}return a[0].U}function V(a){return(a=oa(a))&&!a.B&&(a.B=J,B[a.v]?B[a.v].push(a):B[a.v]=[a],A||W())}function pa(){var a=oa(r);a&&(a.B=J,C[a.v]?C[a.v].push(a):C[a.v]=[a])}function qa(a,c){if(t>=r.length)r[t]={l:1,A:O(c),h:c=c||G,O:a.apply(null,f(c))||I};else if(c){var b=r[t];b.A(b.h,c)&&(b.O&&b.O.apply(b,f(b.h)),b.O=a.apply(null,f(b.h=c))||I)}++t}
function ra(a){if(t<r.length)return r[t++].g;var c=r,b=[a,function(d){b[0]!==d&&(b[0]=d,V(c))},function(){return b[0]}];r[t++]={l:0,g:b};return b}function T(a){return(t<r.length?r[t++]:r[t++]={l:0,g:void 0===a?{}:a}).g}function sa(a,c){return t>=r.length?(r[t++]={l:0,A:O(c),h:c=c||G,g:a.apply(null,f(c))}).g:c&&r[t].A(r[t].h,c)?r[t].g=a.apply(null,f(r[t++].h=c)):r[t++].g}function S(a,c){return t<r.length?(c=r[t].g,r[t++].g=a):r[t++]={l:0,g:a},c}
function ta(a,c){return a=setTimeout(function(){return c(J)},a),function(){return clearTimeout(a)}}function na(a){for(var c=e(a.Y),b=c.next();!b.done;b=c.next())U(a.L[b.value])}function ua(a,c,b){return{$:b.aa,fa:a,Z:u,ea:n?u:u+c}}function X(a){var c=S(a,I);return c?ka(c,a):M(a)}
function Y(a){var c=g.i;if(a){for(var b=e(X(a)),d=b.next();!d.done;d=b.next())switch(d=d.value,d.charCodeAt(0)){case 70:c.className=M(a.F).filter(function(k){return a.F[k]}).join(" ");continue;case 82:a.R(c);case 67:case 68:case 83:continue;default:c[d]=a[d]}if(a.D)for(b=e(X(a.D)),d=b.next();!d.done;d=b.next())d=d.value,c.setAttribute("data-"+d.replace(da,"-$&").toLowerCase(),a.D[d]);if(a.S)for(b=e(X(a.S)),d=b.next();!d.done;d=b.next())d=d.value,c.style[d]=a.S[d]}return c}
function Z(a,c,b){return{H:a,o:c?b?(c.C=b,c):c:b?{C:b}:I}}
function W(){n=0>=u;u=ia.now();z&&cancelAnimationFrame(z);A=J;z=0;for(var a;(a=B).length;){B=[];a=e(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value){c=e(c);for(var b=c.next();!b.done;b=c.next())if(g=b.value,g.B){if(g.i)Q(I,I);else{var d,k=I;b=g.j;for(var h=g,p=g;!(d=(h=h.J).i););do for(var m=p.P,l=(p=p.J).m,v=l.length;++m<v&&l[m]&&!(k=l[m].j););while(!k&&p!==h);p=g;Q(d,k);if(p.j!==b)for(;!(p=p.J).i;){b=I;d=e(p.m);for(k=d.next();!(k.done||(k=k.value)&&(b=k.j));k=d.next());if(b===p.j)break;p.j=
b}}n=K}}}A=K;C.length&&(B=C,C=a,va())}function va(){return z||(z=requestAnimationFrame(W))}var wa=W;function xa(a){var c=D[a];if(!c){var b=a.indexOf("[");D[a]=c=ha.createElement(0>b?a.substr(0):a.substr(0,b));if(0<b)for(a=e(a.substring(b+1,a.length-1).split("][")),b=a.next();!b.done;b=a.next()){b=b.value;var d=b.indexOf("=");0<d?c[b.substr(0,d)]=b.substr(d+1):c[b]=J}}return c}function ya(a){var c=E[a];if(!c){var b=xa(a);E[a]=c=function(d){return n&&(g.i=b.cloneNode(J)),Y(d),d&&d.C||I}}return c}
var za=L.prototype;za.fill||(za.fill=function(a){for(var c=this.length,b=0;b<c;++b)this[b]=a;return this});define({defer:function(){return A=J,va()},defer_end:wa,hook_assert:function(a){if(!a)throw D;},hook_async:function(a,c,b){var d;if((t<r.length?(d=r[t++],K):d=r[t++]={l:2,A:O(c),h:c||G,g:I})||c&&d.A(d.h,c)&&(d.h=c)){void 0!==b&&(d.g=b);var k=r;a.apply(null,f(d.h)).then(function(h){return d.g!==h&&d.h===c&&(d.g=h,V(k))})}return d.g},hook_callback:function(a,c){var b=T();b.h=c;return b.ga||(b.ga=function(){var d=ba.apply(0,arguments);return a.apply(null,[].concat(f(b.h),f(d)))})},hook_delay:function(a){var c=
e(ra(K)),b=c.next().value;c=c.next().value;qa(ta,[a,c]);return b},hook_dom:function(a,c){return n&&(g.i=xa(a).cloneNode(J)),Y(c||I)},hook_effect:qa,hook_first:function(){return n},hook_map:function(a,c,b){var d=I,k=J;if(t<r.length)if((d=r[t]).T!==a)na(d),d=I;else if(!d.G||b&&d.A(d.h,b))d.h=b||G,d.G=J;else{if(c===d.M)return++t,d.g;k=K}var h=n,p=r,m=++t,l={},v=[],q=0<c.length&&la(c,l,v);if(d){if(d.g=[],d.M!==c)for(d.M=c,c=e(d.Y),b=c.next();!b.done;b=c.next())b=b.value,b in l||(U(d.L[b]),delete d.L[b])}else r[m-
1]=d={l:3,A:O(b),h:b||G,g:[],G:J,T:a,W:q?N(c[0]):I,Y:[],L:{},M:c};c=e(v);for(b=c.next();!b.done;b=c.next()){b=b.value;var w=d.L[b];if(n=!w)d.L[b]=w=[{l:1,ba:p,V:d,X:I,g:I}];if(k||n||(q?d.W(l[b],w[0].X):l[b]!==w[0].X)){r=w;t=1;try{w[0].g=a.apply(null,[w[0].X=l[b]].concat(f(d.h)))}catch(H){}}d.g.push(w[0].g)}n=h;r=p;t=m;d.Y=v;return d.g},hook_memo:sa,hook_object_changes:X,hook_prev:S,hook_reducer:function(a){if(t<r.length)return r[t++].g;var c=r,b=[(0,a[0])(I),function(d,k){d=(0,a[d])(b[0],k);b[0]!==
d&&(b[0]=d,V(c))}];r[t++]={l:0,g:b};return b},hook_reducer_f:function(a,c){if(t<r.length)return r[t++].g;var b=r,d=[c?c():I,function(k){k=a(d[0],k);d[0]!==k&&(d[0]=k,V(b))}];r[t++]={l:0,g:d};return d},hook_rerender:pa,hook_state:ra,hook_static:T,hook_sub:function(a,c){var b=I;if(t<r.length)if((b=r[t]).T!==a)U(b.s),b=I;else if(!b.G||c&&b.A(b.h,c))c&&(b.h=c),b.G=J;else return++t,b.g;var d=n,k=r,h=t;if(n=!b)(r[t]=b={l:4,A:O(c),h:c||G,g:I,T:a,G:J,s:[]}).s[0]={l:2,ba:r,V:b};r=b.s;t=1;try{b.g=a.apply(null,
f(b.h))}catch(p){}n=d;r=k;t=h+1;return b.g},hook_transition:function(a,c){var b=T({aa:a});a=sa(ua,[a,c,b]);return b.aa=a.ea<=u?a.fa:(pa(),a.Z===u?a.$:a.$+(a.fa-a.$)*(u-a.Z)/(a.ea-a.Z))},init:function(a,c){var b;c.innerHTML="";(g={u:{H:function(){return Y((b=a())[0]),b[1]},o:I},N:I,J:I,v:0,P:0,s:[],m:I,i:c,j:c,B:J}).s[0]={l:0,U:g};B[0]=[g];W()},node:Z,node_dom:function(a,c,b){return Z(ya(a),c,b)},node_map:function(a,c,b){return Z(N,{H:a,M:c,o:b||I})},now:function(){return u}})})()