"use strict";/*
 lui.js web framework 2.4.0
 inspired by react and mithril
 l3p3.de 2025
*/
{let e=null,k=!e,l=e,m=0,u=0,w=0,x=!k,y=[],z=[];
const A={},B={},E={},aa=[e,(a,b)=>a!==b&&a[0]!==b[0],(a,b)=>a!==b&&(a[0]!==b[0]||a[1]!==b[1]),(a,b)=>a!==b&&(a[0]!==b[0]||a[1]!==b[1]||a[2]!==b[2])],F=[],ba={},G=e,H=k,I=x,K=Array,L=Object,M=L.assign,N=L.keys,O=document,P=window,ca=P.performance||Date,Q=a=>{const b=(a=N(a)).join(",");return E[b]||(E[b]=a)},R=(a,b,c)=>{if(a===b)return!1;for(const d of c)if(a[d]!==b[d])return!0;return!1},da=(a,b)=>a===b?F:N(a).filter(c=>a[c]!==b[c]),S=a=>a?a.length<5?aa[a.length]:ea:G,ea=(a,b)=>{if(a===b)return!1;for(let c=
0,d=a.length;c<d;++c)if(a[c]!==b[c])return!0;return!1},T=(a,b)=>{const c=e,d=c.u+1;let h=b;l=c.M;m=0;c.v=I;if(c.o.G!==T){var f=G;try{f=(0,c.o.G)(c.o.i||ba)}catch(C){if(c.v)return}var n=c.g;if(f){n&&(a=n,h=G);var p=f.length,r,v=c.l||(c.l=(new K(p)).fill(G));do{var g=v[--p];(r=f[p])&&r!==H?((k=!g)?(v[p]=e=g={o:r,L:r.i&&Q(r.i),J:c,u:d,O:p,M:[],l:G,g:G,m:G,v:I},T(a,h),g.g&&a.insertBefore(g.m=g.g,h)):r.i&&R(g.o.i,r.i,g.L)&&((e=g).o=r,T(a,h)),g.m&&(h=g.m)):g&&(U(g,a),v[p]=G)}while(p>0)}else if(c.l){for(p of c.l)p&&
U(p,n||a);c.l=G}if(n)return}else{r=c.o.i.G;var t=c.o.i.U;f=c.o.i.i;n=t.length;p=H;g=fa();v={};const C=[];var q;if(q=n>0){q=typeof t[0]==="object";for(var D of t)t=q?D.id:D,v[t]=D,C.push(t)}D=q;if(g.K){if(!(g.N.length|n))return;p=f&&R(f,g.P,g.L);for(var J of g.N)J in v||(U(g.K[J],a),delete g.K[J]);g.P=f;g.N=C}else{if(n===0)return;g.K={};g.T=D?Q(v[C[0]]):G;g.N=C;g.L=(g.P=f)&&Q(f)}for(J=c.l=new K(n);n>0;){t=C[--n];q=g.K[t];if(k=!q)g.K[t]=e=q={o:{G:r,i:M({I:v[t]},f)},L:G,J:c,u:d,O:0,M:[],l:G,g:G,m:G,
v:I},T(G,G),a.insertBefore(q.g,h);else{if(p||D&&R(v[t],q.o.i.I,g.T))(e=q).o.i=M({I:v[t]},f),T(G,G);q.g.nextSibling!==h&&a.insertBefore(q.g,h)}h=(J[n]=q).g}}c.m=h!==b?h:G},U=(a,b)=>{b&&a.g&&(a.g.remove(),b=G);if(a.l)for(var c of a.l)c&&U(c,b);b=a.M;let d=b.length;for(;d>1;)switch((c=b[--d]).A){case 1:c.B&&c.B(...c.j);break;case 2:c.j=F}if(a.v){let h,f;(!(f=y[h=a.u])||(h=f.indexOf(a))<0)&&(!(f=z[h])||(h=f.indexOf(a))<0)||f.splice(h,1)}},W=a=>!a.v&&(a.v=H,y[a.u]?y[a.u].push(a):y[a.u]=[a],x||V()),fa=
a=>(m<l.length?l[m++]:l[m++]={A:0,h:a===void 0?{}:a}).h,ha=(a,b)=>(m<l.length?(b=l[m].h,l[m++].h=a):l[m++]={A:0,h:a},b),X=a=>{const b=ha(a,G);return b?da(b,a):N(a)},ia=a=>{const b=e.g;if(a){for(const c of X(a)){switch(c.charCodeAt(0)){case 70:b.className=N(a.F).filter(d=>a.F[d]).join(" ");continue;case 82:a.R(b);case 67:case 68:case 83:continue}b[c]=a[c]}if(a.D)for(const c of X(a.D))b.dataset[c]=a.D[c];if(a.S)for(const c of X(a.S))b.style[c]=a.S[c]}return b},Y=(a,b,c)=>({G:a,i:b?c?(b.C=c,b):b:c?{C:c}:
G}),V=()=>{k=u<=0;u=ca.now();w&&cancelAnimationFrame(w);x=H;w=0;for(var a;(a=y).length;){y=[];for(const b of a)if(b)for(e of b)if(e.v){if(e.g)T(G,G);else{let c=G,d=e.m,h=e,f=e;for(;!(a=(h=h.J).g););do{let n=f.O;const {l:p}=f=f.J,r=p.length;for(;++n<r&&p[n]&&!(c=p[n].m););}while(!c&&f!==h);f=e;T(a,c);if(f.m!==d)for(;!(f=f.J).g;){d=G;for(const n of f.l)if(n&&(d=n.m))break;if(d===f.m)break;f.m=d}}k=I}}x=I;z.length&&(y=z,z=a,ja())},ja=()=>w||(w=requestAnimationFrame(V)),Z=a=>{let b=A[a];if(!b){const c=
a.indexOf("[");A[a]=b=O.createElement(c<0?a:a.substr(0,c));if(c>0)for(const d of a.substring(c+1,a.length-1).split("]["))a=d.indexOf("="),a>0?b[d.substr(0,a)]=d.substr(a+1):b[d]=H}return b},ka=a=>{let b=B[a];if(!b){const c=Z(a);B[a]=b=d=>(k&&(e.g=c.cloneNode(H)),ia(d),d&&d.C||G)}return b};P.lui={defer:()=>(x=H,ja()),defer_end:V,dom_define:(a,b,c)=>{b=Z(b);c&&(b=b.cloneNode(H),c.D&&(M(b.dataset,c.D),delete c.D),c.S&&(M(b.style,c.S),delete c.S),M(b,c));A["#"+a]=b},hook_assert:a=>{if(!a)throw A;},hook_async:(a,b,c)=>{let d;if((m<l.length?(d=l[m++],I):d=l[m++]={A:2,H:S(b),j:b||F,h:G})||b&&d.H(d.j,b)&&(d.j=b)){c!==void 0&&(d.h=c);const h=e;a(...d.j).then(f=>d.h!==f&&d.j===b&&(d.h=f,W(h)))}return d.h},hook_dom:(a,b)=>(e.g===G&&(e.g=Z(a).cloneNode(H)),ia(b||G)),hook_effect:(a,b)=>{if(m>=
l.length)(l[m]={A:1,H:S(b),j:b=b||F,B:G}).B=a(...b)||G;else if(b){const c=l[m];c.H(c.j,b)&&(c.B&&c.B(...c.j),c.B=G,c.B=a(...(c.j=b))||G)}++m},hook_memo:(a,b)=>m>=l.length?(l[m++]={A:0,H:S(b),j:b=b||F,h:a(...b)}).h:b&&l[m].H(l[m].j,b)?l[m].h=a(...(l[m++].j=b)):l[m++].h,hook_model:a=>{if(m<l.length)return l[m++].h;const b=e,c=[(0,a.init)(G),{}];for(const d of N(a))c[1][d]=(...h)=>{h=(0,a[d])(c[0],...h);if(c[0]!==h&&(c[0]=h,W(b),e===b))throw A;return h};l[m++]={A:0,h:c};return c},hook_prev:ha,hook_rerender:()=>
{const a=e;a.v=H;z[a.u]?z[a.u].push(a):z[a.u]=[a]},hook_state:a=>{if(m<l.length)return l[m++].h;const b=e,c=[a,d=>{if(c[0]!==d&&(c[0]=d,W(b),e===b))throw A;return d},()=>c[0]];l[m++]={A:0,h:c};return c},hook_static:fa,init:(a,b=O.body,c=G)=>{b.innerHTML="";W({o:{G:a,i:c},L:G,J:G,u:0,O:0,M:[],l:G,g:b,m:b,v:I})},node:Y,node_dom:(a,b,c)=>Y(ka(a),b,c),node_map:(a,b,c)=>Y(T,{G:a,U:b,i:c||G}),now:()=>u}}
