"use strict";/*
 lui.js web framework 2.2.2
 inspired by react and mithril
 l3p3.de 2025
*/
(function(){function aa(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}function f(a){var c=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(c)return c.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function k(a){if(!(a instanceof Array)){a=f(a);for(var c,b=[];!(c=a.next()).done;)b.push(c.value);a=b}return a}
function ba(){for(var a=Number(this),c=[],b=a;b<arguments.length;b++)c[b-a]=arguments[b];return c};var l=null,n=!l,u=l,x=0,y=0,z=0,A=!n,B=[],C=[],D={},E={},F={},ca=[],G=[],da={},H=l,I=n,J=A,ea=/[A-Z]/g,M=Array,N=Object,O=N.assign,P=N.keys;N.values||(N.values=function(a){var c=[],b;for(b in a)c.push(a[b]);return c});var ha=document,ia=window.performance||Date;function ja(a){return new Function("a","b","return a!==b&&("+a.join("||")+")")}function Q(a){var c=(a=P(a)).join(",");return F[c]||(F[c]=ja(a.map(function(b){return"a."+b+"!==b."+b})))}
function ka(a,c){return a===c?G:P(a).filter(function(b){return a[b]!==c[b]})}function R(a){return a?ca[a.length]||(ca[a.length]=ja(a.map(function(c,b){return"a["+b+"]!==b["+b+"]"}))):H}
function S(a,c){var b=l,d=c,g=b.u+1;u=b.N;x=0;b.v=J;if(b.o.B!==S){var e=H;try{e=(0,b.o.B)(b.o.m||da)}catch(ta){}var q=b.g;if(e){q&&(a=q,c=H);var m=e.length,h,v=b.j||(b.j=(new M(m)).fill(H));do{var r=v[--m];(h=e[m])&&h!==I?((n=!r)?(v[m]=l=r={o:h,K:h.m&&Q(h.m),H:b,u:g,M:m,N:[],j:H,g:H,h:H,v:J},S(a,c),r.g&&a.insertBefore(r.h=r.g,c)):h.m&&r.K(r.o.m,h.m)&&((l=r).o=h,S(a,c)),r.h&&(c=r.h)):r&&(T(r,a),v[m]=H)}while(m>0)}else if(b.j){g=f(b.j);for(e=g.next();!e.done;e=g.next())(e=e.value)&&T(e,a);b.j=H}q||
(b.h=c!==d?c:H)}else{e=b.o.m;q=e.B;var w=e.V;e=e.m;m=w.length;r=I;if(!(U(m,m)+m<=0)){h=la();v={};var K=[],L;if(L=m>0){L=typeof w[0]==="object";w=f(w);for(var p=w.next();!p.done;p=w.next()){p=p.value;var t=L?p.id:p;v[t]=p;K.push(t)}}if(h.J){r=e&&h.K(e,h.T);w=f(h.P);for(p=w.next();!p.done;p=w.next())p=p.value,p in v||(T(h.J[p],a),delete h.J[p]);h.T=e;h.P=K}else h.J={},h.U=L?Q(v[K[0]]):H,h.P=K,h.K=(h.T=e)&&Q(e);for(w=b.j=new M(m);m>0;){p=K[--m];t=h.J[p];if(n=!t)h.J[p]=l=t={o:{B:q,m:O({I:v[p]},e)},K:H,
H:b,u:g,M:m,N:[],j:H,g:H,h:H,v:J},S(a,c),t.g&&a.insertBefore(t.h=t.g,c);else{var fa=ma(t);fa&&fa.nextSibling!==c&&na(t,a,c);if(r||L&&h.U(v[p],t.o.m.I))(l=t).o.m=O({I:v[p]},e),S(a,c)}(w[t.M=m]=t).h&&(c=t.h)}b.h=c!==d?c:H}}}
function T(a,c){c&&a.g&&(c.removeChild(a.g),c=H);if(a.j)for(var b=f(a.j),d=b.next();!d.done;d=b.next())(d=d.value)&&T(d,c);c=a.N;for(d=c.length;d>1;)switch((b=c[--d]).A){case 1:b.L&&b.L.apply(b,k(b.l));break;case 2:b.l=G}if(a.v){var g,e;(!(e=B[g=a.u])||(g=e.indexOf(a))<0)&&(!(e=C[g])||(g=e.indexOf(a))<0)||e.splice(g,1)}}function ma(a){if(a.g)return a.g;var c;a=(c=a.j)?c.length:0;for(var b,d;a>0;)if((d=c[--a])&&(b=ma(d)))return b;return H}
function na(a,c,b){if(a.g)return c.insertBefore(a.g,b);if(a.h){var d=a.j.length;do a.j[--d]&&(b=na(a.j[d],c,b));while(d>0)}return b}function V(a){return!a.v&&(a.v=I,B[a.u]?B[a.u].push(a):B[a.u]=[a],A||W())}function la(a){return(x<u.length?u[x++]:u[x++]={A:0,i:a===void 0?{}:a}).i}function U(a,c){return x<u.length?(c=u[x].i,u[x++].i=a):u[x++]={A:0,i:a},c}function X(a){var c=U(a,H);return c?ka(c,a):P(a)}
function oa(a){var c=l.g;if(a){for(var b=f(X(a)),d=b.next();!d.done;d=b.next()){d=d.value;switch(d.charCodeAt(0)){case 70:c.className=P(a.F).filter(function(g){return a.F[g]}).join(" ");continue;case 82:a.R(c);case 67:case 68:case 83:continue}c[d]=a[d]}if(a.D)for(b=f(X(a.D)),d=b.next();!d.done;d=b.next())d=d.value,c.setAttribute("data-"+d.replace(ea,"-$&").toLowerCase(),a.D[d]);if(a.S)for(b=f(X(a.S)),d=b.next();!d.done;d=b.next())d=d.value,c.style[d]=a.S[d]}return c}
function Y(a,c,b){return{B:a,m:c?b?(c.C=b,c):c:b?{C:b}:H}}
function W(){n=y<=0;y=ia.now();z&&cancelAnimationFrame(z);A=I;z=0;for(var a;(a=B).length;){B=[];a=f(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value){c=f(c);for(var b=c.next();!b.done;b=c.next())if(l=b.value,l.v){if(l.g)S(H,H);else{var d,g=H;b=l.h;for(var e=l,q=l;!(d=(e=e.H).g););do for(var m=q.M,h=(q=q.H).j,v=h.length;++m<v&&h[m]&&!(g=h[m].h););while(!g&&q!==e);q=l;S(d,g);if(q.h!==b)for(;!(q=q.H).g;){b=H;d=f(q.j);for(g=d.next();!(g.done||(g=g.value)&&(b=g.h));g=d.next());if(b===q.h)break;q.h=
b}}n=J}}}A=J;C.length&&(B=C,C=a,pa())}function pa(){return z||(z=requestAnimationFrame(W))}var qa=W;function Z(a){var c=D[a];if(!c){var b=a.indexOf("[");D[a]=c=ha.createElement(b<0?a:a.substr(0,b));if(b>0)for(a=f(a.substring(b+1,a.length-1).split("][")),b=a.next();!b.done;b=a.next()){b=b.value;var d=b.indexOf("=");d>0?c[b.substr(0,d)]=b.substr(d+1):c[b]=I}}return c}function ra(a){var c=E[a];if(!c){var b=Z(a);E[a]=c=function(d){return n&&(l.g=b.cloneNode(I)),oa(d),d&&d.C||H}}return c}var sa=M.prototype;
N.entries||(N.entries=function(a){var c=[],b;for(b in a)c.push([b,a[b]]);return c},sa.fill||(sa.fill=function(a){for(var c=this.length,b=0;b<c;++b)this[b]=a;return this}));define({defer:function(){return A=I,pa()},defer_end:qa,dom_define:function(a,c,b){c=Z(c);b&&(c=c.cloneNode(I),b.D&&(O(c.dataset,b.D),delete b.D),b.S&&(O(c.style,b.S),delete b.S),O(c,b));D["#"+a]=c},hook_assert:function(a){if(!a)throw D;},hook_async:function(a,c,b){var d;if((x<u.length?(d=u[x++],J):d=u[x++]={A:2,G:R(c),l:c||G,i:H})||c&&d.G(d.l,c)&&(d.l=c)){b!==void 0&&(d.i=b);var g=l;a.apply(null,k(d.l)).then(function(e){return d.i!==e&&d.l===c&&(d.i=e,V(g))})}return d.i},hook_dom:function(a,c){return l.g===
H&&(l.g=Z(a).cloneNode(I)),oa(c||H)},hook_effect:function(a,c){if(x>=u.length)u[x]={A:1,G:R(c),l:c=c||G,L:a.apply(null,k(c))||H};else if(c){var b=u[x];b.G(b.l,c)&&(b.L&&b.L.apply(b,k(b.l)),b.L=a.apply(null,k(b.l=c))||H)}++x},hook_memo:function(a,c){return x>=u.length?(u[x++]={A:0,G:R(c),l:c=c||G,i:a.apply(null,k(c))}).i:c&&u[x].G(u[x].l,c)?u[x].i=a.apply(null,k(u[x++].l=c)):u[x++].i},hook_model:function(a){if(x<u.length)return u[x++].i;for(var c=l,b=[(0,a.init)(H),{}],d=f(P(a)),g=d.next(),e={};!g.done;e=
{O:void 0},g=d.next())e.O=g.value,b[1][e.O]=function(q){return function(){var m=a[q.O].apply(null,[b[0]].concat(k(ba.apply(0,arguments))));b[0]!==m&&(b[0]=m,V(c))}}(e);u[x++]={A:0,i:b};return b},hook_prev:U,hook_rerender:function(){var a=l;a.v=I;C[a.u]?C[a.u].push(a):C[a.u]=[a]},hook_state:function(a){if(x<u.length)return u[x++].i;var c=l,b=[a,function(d){b[0]!==d&&(b[0]=d,V(c))},function(){return b[0]}];u[x++]={A:0,i:b};return b},hook_static:la,init:function(a,c,b){c=c===void 0?ha.body:c;b=b===void 0?
H:b;c.innerHTML="";V({o:{B:a,m:b},K:H,H:H,u:0,M:0,N:[],j:H,g:c,h:c,v:J})},node:Y,node_dom:function(a,c,b){return Y(ra(a),c,b)},node_map:function(a,c,b){return Y(S,{B:a,V:c,m:b||H})},now:function(){return y}})})()
