"use strict";/*
 lui.js web framework 2.2.2
 inspired by react and mithril
 l3p3.de 2025
*/
(function(){function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function f(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function k(a){if(!(a instanceof Array)){a=f(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
function ba(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};var l=null,m=!l,u=l,x=0,y=0,z=0,A=!m,B=[],C=[],D={},E={},ca={},da=[l,function(a,b){return a!==b&&a[0]!==b[0]},function(a,b){return a!==b&&(a[0]!==b[0]||a[1]!==b[1])},function(a,b){return a!==b&&(a[0]!==b[0]||a[1]!==b[1]||a[2]!==b[2])}],F=[],fa={},G=l,H=m,I=A,ha=/[A-Z]/g,J=Array,M=Object,N=M.assign,O=M.keys;M.values||(M.values=function(a){var b=[],c;for(c in a)b.push(a[c]);return b});var ia=document,ja=window.performance||Date;function P(a){var b=(a=O(a)).join(",");return ca[b]||(ca[b]=a)}
function Q(a,b,c){if(a===b)return!1;c=f(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,a[d]!==b[d])return!0;return!1}function ka(a,b){return a===b?F:O(a).filter(function(c){return a[c]!==b[c]})}function R(a){return a?a.length<5?da[a.length]:la:G}function la(a,b){if(a===b)return!1;for(var c=0,d=a.length;c<d;++c)if(a[c]!==b[c])return!0;return!1}
function S(a,b){var c=l,d=b,g=c.u+1;u=c.N;x=0;c.v=I;if(c.o.B!==S){var e=G;try{e=(0,c.o.B)(c.o.m||fa)}catch(ua){}var q=c.g;if(e){q&&(a=q,b=G);var n=e.length,h,v=c.j||(c.j=(new J(n)).fill(G));do{var r=v[--n];(h=e[n])&&h!==H?((m=!r)?(v[n]=l=r={o:h,K:h.m&&P(h.m),H:c,u:g,M:n,N:[],j:G,g:G,h:G,v:I},S(a,b),r.g&&a.insertBefore(r.h=r.g,b)):h.m&&Q(r.o.m,h.m,r.K)&&((l=r).o=h,S(a,b)),r.h&&(b=r.h)):r&&(T(r,a),v[n]=G)}while(n>0)}else if(c.j){g=f(c.j);for(e=g.next();!e.done;e=g.next())(e=e.value)&&T(e,a);c.j=G}q||
(c.h=b!==d?b:G)}else{e=c.o.m;q=e.B;var w=e.V;e=e.m;n=w.length;r=H;if(!(U(n,n)+n<=0)){h=ma();v={};var K=[],L;if(L=n>0){L=typeof w[0]==="object";w=f(w);for(var p=w.next();!p.done;p=w.next()){p=p.value;var t=L?p.id:p;v[t]=p;K.push(t)}}if(h.J){r=e&&Q(e,h.T,h.K);w=f(h.P);for(p=w.next();!p.done;p=w.next())p=p.value,p in v||(T(h.J[p],a),delete h.J[p]);h.T=e;h.P=K}else h.J={},h.U=L?P(v[K[0]]):G,h.P=K,h.K=(h.T=e)&&P(e);for(w=c.j=new J(n);n>0;){p=K[--n];t=h.J[p];if(m=!t)h.J[p]=l=t={o:{B:q,m:N({I:v[p]},e)},
K:G,H:c,u:g,M:n,N:[],j:G,g:G,h:G,v:I},S(a,b),t.g&&a.insertBefore(t.h=t.g,b);else{var ea=na(t);ea&&ea.nextSibling!==b&&oa(t,a,b);if(r||L&&Q(v[p],t.o.m.I,h.U))(l=t).o.m=N({I:v[p]},e),S(a,b)}(w[t.M=n]=t).h&&(b=t.h)}c.h=b!==d?b:G}}}
function T(a,b){b&&a.g&&(b.removeChild(a.g),b=G);if(a.j)for(var c=f(a.j),d=c.next();!d.done;d=c.next())(d=d.value)&&T(d,b);b=a.N;for(d=b.length;d>1;)switch((c=b[--d]).A){case 1:c.L&&c.L.apply(c,k(c.l));break;case 2:c.l=F}if(a.v){var g,e;(!(e=B[g=a.u])||(g=e.indexOf(a))<0)&&(!(e=C[g])||(g=e.indexOf(a))<0)||e.splice(g,1)}}function na(a){if(a.g)return a.g;var b;a=(b=a.j)?b.length:0;for(var c,d;a>0;)if((d=b[--a])&&(c=na(d)))return c;return G}
function oa(a,b,c){if(a.g)return b.insertBefore(a.g,c);if(a.h){var d=a.j.length;do a.j[--d]&&(c=oa(a.j[d],b,c));while(d>0)}return c}function V(a){return!a.v&&(a.v=H,B[a.u]?B[a.u].push(a):B[a.u]=[a],A||W())}function ma(a){return(x<u.length?u[x++]:u[x++]={A:0,i:a===void 0?{}:a}).i}function U(a,b){return x<u.length?(b=u[x].i,u[x++].i=a):u[x++]={A:0,i:a},b}function X(a){var b=U(a,G);return b?ka(b,a):O(a)}
function pa(a){var b=l.g;if(a){for(var c=f(X(a)),d=c.next();!d.done;d=c.next()){d=d.value;switch(d.charCodeAt(0)){case 70:b.className=O(a.F).filter(function(g){return a.F[g]}).join(" ");continue;case 82:a.R(b);case 67:case 68:case 83:continue}b[d]=a[d]}if(a.D)for(c=f(X(a.D)),d=c.next();!d.done;d=c.next())d=d.value,b.setAttribute("data-"+d.replace(ha,"-$&").toLowerCase(),a.D[d]);if(a.S)for(c=f(X(a.S)),d=c.next();!d.done;d=c.next())d=d.value,b.style[d]=a.S[d]}return b}
function Y(a,b,c){return{B:a,m:b?c?(b.C=c,b):b:c?{C:c}:G}}
function W(){m=y<=0;y=ja.now();z&&cancelAnimationFrame(z);A=H;z=0;for(var a;(a=B).length;){B=[];a=f(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value){b=f(b);for(var c=b.next();!c.done;c=b.next())if(l=c.value,l.v){if(l.g)S(G,G);else{var d,g=G;c=l.h;for(var e=l,q=l;!(d=(e=e.H).g););do for(var n=q.M,h=(q=q.H).j,v=h.length;++n<v&&h[n]&&!(g=h[n].h););while(!g&&q!==e);q=l;S(d,g);if(q.h!==c)for(;!(q=q.H).g;){c=G;d=f(q.j);for(g=d.next();!(g.done||(g=g.value)&&(c=g.h));g=d.next());if(c===q.h)break;q.h=
c}}m=I}}}A=I;C.length&&(B=C,C=a,qa())}function qa(){return z||(z=requestAnimationFrame(W))}var ra=W;function Z(a){var b=D[a];if(!b){var c=a.indexOf("[");D[a]=b=ia.createElement(c<0?a:a.substr(0,c));if(c>0)for(a=f(a.substring(c+1,a.length-1).split("][")),c=a.next();!c.done;c=a.next()){c=c.value;var d=c.indexOf("=");d>0?b[c.substr(0,d)]=c.substr(d+1):b[c]=H}}return b}function sa(a){var b=E[a];if(!b){var c=Z(a);E[a]=b=function(d){return m&&(l.g=c.cloneNode(H)),pa(d),d&&d.C||G}}return b}var ta=J.prototype;
M.entries||(M.entries=function(a){var b=[],c;for(c in a)b.push([c,a[c]]);return b},ta.fill||(ta.fill=function(a){for(var b=this.length,c=0;c<b;++c)this[c]=a;return this}));define({defer:function(){return A=H,qa()},defer_end:ra,dom_define:function(a,b,c){b=Z(b);c&&(b=b.cloneNode(H),c.D&&(N(b.dataset,c.D),delete c.D),c.S&&(N(b.style,c.S),delete c.S),N(b,c));D["#"+a]=b},hook_assert:function(a){if(!a)throw D;},hook_async:function(a,b,c){var d;if((x<u.length?(d=u[x++],I):d=u[x++]={A:2,G:R(b),l:b||F,i:G})||b&&d.G(d.l,b)&&(d.l=b)){c!==void 0&&(d.i=c);var g=l;a.apply(null,k(d.l)).then(function(e){return d.i!==e&&d.l===b&&(d.i=e,V(g))})}return d.i},hook_dom:function(a,b){return l.g===
G&&(l.g=Z(a).cloneNode(H)),pa(b||G)},hook_effect:function(a,b){if(x>=u.length)u[x]={A:1,G:R(b),l:b=b||F,L:a.apply(null,k(b))||G};else if(b){var c=u[x];c.G(c.l,b)&&(c.L&&c.L.apply(c,k(c.l)),c.L=a.apply(null,k(c.l=b))||G)}++x},hook_memo:function(a,b){return x>=u.length?(u[x++]={A:0,G:R(b),l:b=b||F,i:a.apply(null,k(b))}).i:b&&u[x].G(u[x].l,b)?u[x].i=a.apply(null,k(u[x++].l=b)):u[x++].i},hook_model:function(a){if(x<u.length)return u[x++].i;for(var b=l,c=[(0,a.init)(G),{}],d=f(O(a)),g=d.next(),e={};!g.done;e=
{O:void 0},g=d.next())e.O=g.value,c[1][e.O]=function(q){return function(){var n=a[q.O].apply(null,[c[0]].concat(k(ba.apply(0,arguments))));c[0]!==n&&(c[0]=n,V(b))}}(e);u[x++]={A:0,i:c};return c},hook_prev:U,hook_rerender:function(){var a=l;a.v=H;C[a.u]?C[a.u].push(a):C[a.u]=[a]},hook_state:function(a){if(x<u.length)return u[x++].i;var b=l,c=[a,function(d){c[0]!==d&&(c[0]=d,V(b))},function(){return c[0]}];u[x++]={A:0,i:c};return c},hook_static:ma,init:function(a,b,c){b=b===void 0?ia.body:b;c=c===void 0?
G:c;b.innerHTML="";V({o:{B:a,m:c},K:G,H:G,u:0,M:0,N:[],j:G,g:b,h:b,v:I})},node:Y,node_dom:function(a,b,c){return Y(sa(a),b,c)},node_map:function(a,b,c){return Y(S,{B:a,V:b,m:c||G})},now:function(){return y}})})()
