"use strict";/*
 lui.js web framework 2.5.0
 inspired by react and mithril
 l3p3.de 2026
*/
{var e=null,h=!e,k=e,l=0,u=0,v=0,x=!h,y=[],z=[],A={},B={},E={},F=[],G=[],aa={},H=e,I=h,K=x,L=Array,M=Object,N=M.assign,O=M.keys,P=document,ba=window,ca=ba.performance||Date,da=a=>new Function("a","b",`return a!==b&&(${a.join("||")})`),Q=a=>{var c=(a=O(a)).join(",");return E[c]||(E[c]=da(a.map(b=>`a.${b}!==b.`+b)))},ea=(a,c)=>a===c?G:O(a).filter(b=>a[b]!==c[b]),R=a=>a?F[a.length]||(F[a.length]=da(a.map((c,b)=>`a[${b}]!==b[${b}]`))):H,S=(a,c)=>{var b=e,d=b.u+1,m=c;k=b.N;l=0;b.v=K;if(b.o.G!==S){var f=
H;try{f=b.o.G(b.o.i||aa)}catch(C){if(b.v)return}var n=b.g;if(f){n&&(a=n,m=H);var p=f.length,r,w=b.l||(b.l=(new L(p)).fill(H));do{var g=w[--p];(r=f[p])&&r!==I?((h=!g)?(w[p]=e=g={o:r,M:r.i&&Q(r.i),H:b,u:d,P:p,N:[],l:H,g:H,m:H,v:K,J:K},S(a,m),g.g&&a.insertBefore(g.m=g.g,m)):r.i&&g.M(g.o.i,r.i)&&((e=g).o=r,S(a,m)),g.m&&(m=g.m)):g&&(T(g,a),w[p]=H)}while(p>0)}else if(b.l){n&&(a=n);for(p of b.l)p&&T(p,a);b.l=H}if(n)return}else{r=b.o.i.G;var t=b.o.i.V;f=b.o.i.i;n=t.length;p=I;g=fa();w={};let C=[];var q;if(q=
n>0){q=typeof t[0]==="object";for(var D of t)t=q?D.id:D,w[t]=D,C.push(t)}D=q;if(g.L){if(!(g.O.length|n))return;p=f&&g.M(f,g.T);for(var J of g.O)J in w||(T(g.L[J],a),delete g.L[J]);g.T=f;g.O=C}else{if(n===0)return;g.L={};g.U=D?Q(w[C[0]]):H;g.O=C;g.M=(g.T=f)&&Q(f)}for(J=b.l=new L(n);n>0;){t=C[--n];q=g.L[t];if(h=!q)g.L[t]=e=q={o:{G:r,i:N({I:w[t]},f)},M:H,H:b,u:d,P:0,N:[],l:H,g:H,m:H,v:K,J:K},S(H,H),a.insertBefore(q.g,m);else{if(p||D&&g.U(w[t],q.o.i.I))(e=q).o.i=N({I:w[t]},f),S(H,H);q.g.nextSibling!==
m&&a.insertBefore(q.g,m)}m=(J[n]=q).g}}b.m=m!==c?m:H},T=(a,c)=>{c&&a.g&&(a.g.remove(),c=H);if(c||a.J){if(a.l)for(var b of a.l)b&&T(b,c);if(a.J){c=a.N;let d=c.length;for(;d>1;)switch((b=c[--d]).A){case 1:b.B&&b.B(...b.j);break;case 2:b.j=G}}}if(a.v){let d,m;(!(m=y[d=a.u])||(d=m.indexOf(a))<0)&&(!(m=z[d])||(d=m.indexOf(a))<0)||m.splice(d,1)}},V=a=>!a.v&&(a.v=I,y[a.u]?y[a.u].push(a):y[a.u]=[a],x||U()),W=()=>{for(var a=e;a&&!a.J;)a.J=I,a=a.H},fa=a=>(l<k.length?k[l++]:k[l++]={A:0,h:a===void 0?{}:a}).h,
ha=(a,c)=>(l<k.length?(c=k[l].h,k[l++].h=a):k[l++]={A:0,h:a},c),X=a=>{var c=ha(a,H);return c?ea(c,a):O(a)},ia=a=>{var c=e.g;if(a){for(let b of X(a)){switch(b.charCodeAt(0)){case 70:c.className=O(a.F).filter(d=>a.F[d]).join(" ");continue;case 82:a.R(c);case 67:case 68:case 83:continue}c[b]=a[b]}if(a.D)for(let b of X(a.D))c.dataset[b]=a.D[b];if(a.S)for(let b of X(a.S))c.style[b]=a.S[b]}return c},Y=(a,c,b)=>({G:a,i:c?b?(c.C=b,c):c:b?{C:b}:H}),U=()=>{h=u<=0;u=ca.now();v&&cancelAnimationFrame(v);x=I;v=
0;for(var a;(a=y).length;){y=[];for(let c of a)if(c)for(e of c)if(e.v){if(e.g)S(H,H);else{let b=H,d=e.m,m=e,f=e;for(;!(a=(m=m.H).g););do{let n=f.P,{l:p}=f=f.H,r=p.length;for(;++n<r&&p[n]&&!(b=p[n].m););}while(!b&&f!==m);f=e;S(a,b);if(f.m!==d)for(;!(f=f.H).g;){d=H;for(let n of f.l)if(n&&(d=n.m))break;if(d===f.m)break;f.m=d}}h=K}}x=K;z.length&&(y=z,z=a,ja())},ja=()=>v||(v=requestAnimationFrame(U)),Z=a=>{var c=A[a];if(!c){let b=a.indexOf("[");A[a]=c=P.createElement(b<0?a:a.substr(0,b));if(b>0)for(let d of a.substring(b+
1,a.length-1).split("]["))a=d.indexOf("="),a>0?c[d.substr(0,a)]=d.substr(a+1):c[d]=I}return c},ka=a=>{var c=B[a];if(!c){let b=Z(a);B[a]=c=d=>(h&&(e.g=b.cloneNode(I)),ia(d),d&&d.C||H)}return c};ba.lui={defer:()=>(x=I,ja()),defer_end:U,dom_define:(a,c,b)=>{c=Z(c);b&&(c=c.cloneNode(I),b.D&&(N(c.dataset,b.D),delete b.D),b.S&&(N(c.style,b.S),delete b.S),N(c,b));A["#"+a]=c},hook_assert:a=>{if(!a)throw A;},hook_async:(a,c,b)=>{var d;if((l<k.length?(d=k[l++],K):(W(),d=k[l++]={A:2,K:R(c),j:c||G,h:H}))||c&&d.K(d.j,c)&&(d.j=c)){b!==void 0&&(d.h=b);let m=e;a(...d.j).then(f=>d.h!==f&&d.j===c&&(d.h=f,V(m)))}return d.h},hook_dom:(a,c)=>(e.g===H&&(e.g=Z(a).cloneNode(I)),ia(c||H)),hook_effect:(a,c)=>{if(l>=
k.length)((k[l]={A:1,K:R(c),j:c=c||G,B:H}).B=a(...c)||H)&&W();else if(c){let b=k[l];b.K(b.j,c)&&(b.B&&b.B(...b.j),b.B=H,(b.B=a(...(b.j=c))||H)&&W())}++l},hook_memo:(a,c)=>l>=k.length?(k[l++]={A:0,K:R(c),j:c=c||G,h:a(...c)}).h:c&&k[l].K(k[l].j,c)?k[l].h=a(...(k[l++].j=c)):k[l++].h,hook_model:(a,c)=>{if(l<k.length)return k[l++].h;var b=e,d=[a.init(H,c),{}];for(let m of O(a))d[1][m]=(...f)=>{f=a[m](d[0],...f);if(d[0]!==f&&(d[0]=f,V(b),e===b))throw A;return f};k[l++]={A:0,h:d};return d},hook_prev:ha,
hook_rerender:()=>{var a=e;a.v=I;z[a.u]?z[a.u].push(a):z[a.u]=[a]},hook_state:a=>{if(l<k.length)return k[l++].h;var c=e,b=[a,d=>{if(b[0]!==d&&(b[0]=d,V(c),e===c))throw A;return d},()=>b[0]];k[l++]={A:0,h:b};return b},hook_static:fa,init:(a,c=P.body,b=H)=>{c.innerHTML="";V({o:{G:a,i:b},M:H,H,u:0,P:0,N:[],l:H,g:c,m:c,v:K,J:K})},node:Y,node_dom:(a,c,b)=>Y(ka(a),c,b),node_map:(a,c,b)=>Y(S,{G:a,V:c,i:b||H}),now:()=>u}}
