'use strict';function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function f(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function k(a){if(!(a instanceof Array)){a=f(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
function ba(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};/*
 lui.js web frame work 2.2.0
 inspired by react and mithril
 L3P3.de 2024
*/
(function(){var l=null,m=!l,u=l,x=0,y=0,z=0,A=!m,B=[],C=[],D={},E={},F={},ca=[l,function(a,b){return a!==b&&a[0]!==b[0]},function(a,b){return a!==b&&(a[0]!==b[0]||a[1]!==b[1])},function(a,b){return a!==b&&(a[0]!==b[0]||a[1]!==b[1]||a[2]!==b[2])}],G=[],da={},H=l,I=m,L=A,fa=/[A-Z]/g,M=Array,ha=Object,N=ha.assign,O=ha.keys,ia=document,ja=window.performance||Date;function P(a){var b=(a=O(a)).join(",");return F[b]||(F[b]=a)}
function Q(a,b,c){if(a===b)return!1;c=f(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,a[d]!==b[d])return!0;return!1}function ka(a,b){return a===b?G:O(a).filter(function(c){return a[c]!==b[c]})}function R(a){return a?5>a.length?ca[a.length]:la:H}function la(a,b){if(a===b)return!1;for(var c=0,d=a.length;c<d;++c)if(a[c]!==b[c])return!0;return!1}
function S(a,b){var c=l,d=b,g=c.s+1;u=c.M;x=0;c.u=L;if(c.o.A!==S){var e=H;try{e=(0,c.o.A)(c.o.m||da)}catch(ua){}var q=c.g;if(e){q&&(a=q,b=H);var n=e.length,h,v=c.j||(c.j=(new M(n)).fill(H));do{var r=v[--n];(h=e[n])&&h!==I?((m=!r)?(v[n]=l=r={o:h,J:h.m&&P(h.m),G:c,s:g,L:n,M:[],j:H,g:H,h:H,u:L},S(a,b),r.g&&a.insertBefore(r.h=r.g,b)):h.m&&Q(r.o.m,h.m,r.J)&&((l=r).o=h,S(a,b)),r.h&&(b=r.h)):r&&(T(r,a),v[n]=H)}while(0<n)}else if(c.j){g=f(c.j);for(e=g.next();!e.done;e=g.next())(e=e.value)&&T(e,a);c.j=H}q||
(c.h=b!==d?b:H)}else{e=c.o.m;q=e.A;var w=e.U;e=e.m;n=w.length;r=I;if(!(0>=U(n,n)+n)){h=ma();v={};var J=[],K;if(K=0<n){K="object"===typeof w[0];w=f(w);for(var p=w.next();!p.done;p=w.next()){p=p.value;var t=K?p.id:p;v[t]=p;J.push(t)}}if(h.H){r=e&&Q(e,h.P,h.J);w=f(h.O);for(p=w.next();!p.done;p=w.next())p=p.value,p in v||(T(h.H[p],a),delete h.H[p]);h.P=e;h.O=J}else h.H={},h.T=K?P(v[J[0]]):H,h.O=J,h.J=(h.P=e)&&P(e);for(w=c.j=new M(n);0<n;){p=J[--n];t=h.H[p];if(m=!t)h.H[p]=l=t={o:{A:q,m:N({I:v[p]},e)},
J:H,G:c,s:g,L:n,M:[],j:H,g:H,h:H,u:L},S(a,b),t.g&&a.insertBefore(t.h=t.g,b);else{var ea=na(t);ea&&ea.nextSibling!==b&&oa(t,a,b);if(r||K&&Q(v[p],t.o.m.I,h.T))(l=t).o.m=N({I:v[p]},e),S(a,b)}(w[t.L=n]=t).h&&(b=t.h)}c.h=b!==d?b:H}}}
function T(a,b){b&&a.g&&(b.removeChild(a.g),b=H);if(a.j)for(var c=f(a.j),d=c.next();!d.done;d=c.next())(d=d.value)&&T(d,b);b=a.M;for(d=b.length;1<d;)switch((c=b[--d]).v){case 1:c.K&&c.K.apply(c,k(c.l));break;case 2:c.l=G}if(a.u){var g,e;(!(e=B[g=a.s])||0>(g=e.indexOf(a)))&&(!(e=C[g])||0>(g=e.indexOf(a)))||e.splice(g,1)}}function na(a){if(a.g)return a.g;var b;a=(b=a.j)?b.length:0;for(var c,d;0<a;)if((d=b[--a])&&(c=na(d)))return c;return H}
function oa(a,b,c){if(a.g)return b.insertBefore(a.g,c);if(a.h){var d=a.j.length;do a.j[--d]&&(c=oa(a.j[d],b,c));while(0<d)}return c}function V(a){return!a.u&&(a.u=I,B[a.s]?B[a.s].push(a):B[a.s]=[a],A||W())}function ma(a){return(x<u.length?u[x++]:u[x++]={v:0,i:void 0===a?{}:a}).i}function U(a,b){return x<u.length?(b=u[x].i,u[x++].i=a):u[x++]={v:0,i:a},b}function X(a){var b=U(a,H);return b?ka(b,a):O(a)}
function pa(a){var b=l.g;if(a){for(var c=f(X(a)),d=c.next();!d.done;d=c.next()){d=d.value;switch(d.charCodeAt(0)){case 70:b.className=O(a.F).filter(function(g){return a.F[g]}).join(" ");continue;case 82:a.R(b);case 67:case 68:case 83:continue}b[d]=a[d]}if(a.D)for(c=f(X(a.D)),d=c.next();!d.done;d=c.next())d=d.value,b.setAttribute("data-"+d.replace(fa,"-$&").toLowerCase(),a.D[d]);if(a.S)for(c=f(X(a.S)),d=c.next();!d.done;d=c.next())d=d.value,b.style[d]=a.S[d]}return b}
function Y(a,b,c){return{A:a,m:b?c?(b.C=c,b):b:c?{C:c}:H}}
function W(){m=0>=y;y=ja.now();z&&cancelAnimationFrame(z);A=I;z=0;for(var a;(a=B).length;){B=[];a=f(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value){b=f(b);for(var c=b.next();!c.done;c=b.next())if(l=c.value,l.u){if(l.g)S(H,H);else{var d,g=H;c=l.h;for(var e=l,q=l;!(d=(e=e.G).g););do for(var n=q.L,h=(q=q.G).j,v=h.length;++n<v&&h[n]&&!(g=h[n].h););while(!g&&q!==e);q=l;S(d,g);if(q.h!==c)for(;!(q=q.G).g;){c=H;d=f(q.j);for(g=d.next();!(g.done||(g=g.value)&&(c=g.h));g=d.next());if(c===q.h)break;q.h=
c}}m=L}}}A=L;C.length&&(B=C,C=a,qa())}function qa(){return z||(z=requestAnimationFrame(W))}var ra=W;function Z(a){var b=D[a];if(!b){var c=a.indexOf("[");D[a]=b=ia.createElement(0>c?a:a.substr(0,c));if(0<c)for(a=f(a.substring(c+1,a.length-1).split("][")),c=a.next();!c.done;c=a.next()){c=c.value;var d=c.indexOf("=");0<d?b[c.substr(0,d)]=c.substr(d+1):b[c]=I}}return b}function sa(a){var b=E[a];if(!b){var c=Z(a);E[a]=b=function(d){return m&&(l.g=c.cloneNode(I)),pa(d),d&&d.C||H}}return b}var ta=M.prototype;
ta.fill||(ta.fill=function(a){for(var b=this.length,c=0;c<b;++c)this[c]=a;return this});define({defer:function(){return A=I,qa()},defer_end:ra,dom_define:function(a,b,c){b=Z(b);c&&(b=b.cloneNode(I),c.D&&(N(b.dataset,c.D),delete c.D),c.S&&(N(b.style,c.S),delete c.S),N(b,c));D["#"+a]=b},hook_assert:function(a){if(!a)throw D;},hook_async:function(a,b,c){var d;if((x<u.length?(d=u[x++],L):d=u[x++]={v:2,B:R(b),l:b||G,i:H})||b&&d.B(d.l,b)&&(d.l=b)){void 0!==c&&(d.i=c);var g=l;a.apply(null,k(d.l)).then(function(e){return d.i!==e&&d.l===b&&(d.i=e,V(g))})}return d.i},hook_dom:function(a,b){return l.g===
H&&(l.g=Z(a).cloneNode(I)),pa(b||H)},hook_effect:function(a,b){if(x>=u.length)u[x]={v:1,B:R(b),l:b=b||G,K:a.apply(null,k(b))||H};else if(b){var c=u[x];c.B(c.l,b)&&(c.K&&c.K.apply(c,k(c.l)),c.K=a.apply(null,k(c.l=b))||H)}++x},hook_memo:function(a,b){return x>=u.length?(u[x++]={v:0,B:R(b),l:b=b||G,i:a.apply(null,k(b))}).i:b&&u[x].B(u[x].l,b)?u[x].i=a.apply(null,k(u[x++].l=b)):u[x++].i},hook_model:function(a){if(x<u.length)return u[x++].i;for(var b=l,c=[(0,a.init)(H),{}],d=f(O(a)),g=d.next(),e={};!g.done;e=
{N:void 0},g=d.next())e.N=g.value,c[1][e.N]=function(q){return function(){var n=a[q.N].apply(null,[c[0]].concat(k(ba.apply(0,arguments))));c[0]!==n&&(c[0]=n,V(b))}}(e);u[x++]={v:0,i:c};return c},hook_prev:U,hook_rerender:function(){var a=l;a.u=I;C[a.s]?C[a.s].push(a):C[a.s]=[a]},hook_state:function(a){if(x<u.length)return u[x++].i;var b=l,c=[a,function(d){c[0]!==d&&(c[0]=d,V(b))},function(){return c[0]}];u[x++]={v:0,i:c};return c},hook_static:ma,init:function(a,b,c){b=void 0===b?ia.body:b;c=void 0===
c?H:c;b.innerHTML="";V({o:{A:a,m:c},J:H,G:H,s:0,L:0,M:[],j:H,g:b,h:b,u:L})},node:Y,node_dom:function(a,b,c){return Y(sa(a),b,c)},node_map:function(a,b,c){return Y(S,{A:a,U:b,m:c||H})},now:function(){return y}})})()