"use strict";/*
 lui.js web framework 2.4.0
 inspired by react and mithril
 l3p3.de 2025
*/
{let e=null,k=!e,l=e,m=0,u=0,w=0,x=!k,y=[],z=[];
const A={},B={},E={},F=[],G=[],aa={},H=e,I=k,K=x,L=Array,M=Object,N=M.assign,O=M.keys,P=document,Q=window,ba=Q.performance||Date,ca=a=>new Function("a","b",`return a!==b&&(${a.join("||")})`),R=a=>{const c=(a=O(a)).join(",");return E[c]||(E[c]=ca(a.map(b=>`a.${b}!==b.`+b)))},da=(a,c)=>a===c?G:O(a).filter(b=>a[b]!==c[b]),S=a=>a?F[a.length]||(F[a.length]=ca(a.map((c,b)=>`a[${b}]!==b[${b}]`))):H,T=(a,c)=>{const b=e,d=b.u+1;let h=c;l=b.M;m=0;b.v=K;if(b.o.G!==T){var f=H;try{f=(0,b.o.G)(b.o.i||aa)}catch(C){if(b.v)return}var n=
b.g;if(f){n&&(a=n,h=H);var p=f.length,r,v=b.l||(b.l=(new L(p)).fill(H));do{var g=v[--p];(r=f[p])&&r!==I?((k=!g)?(v[p]=e=g={o:r,L:r.i&&R(r.i),J:b,u:d,O:p,M:[],l:H,g:H,m:H,v:K},T(a,h),g.g&&a.insertBefore(g.m=g.g,h)):r.i&&g.L(g.o.i,r.i)&&((e=g).o=r,T(a,h)),g.m&&(h=g.m)):g&&(U(g,a),v[p]=H)}while(p>0)}else if(b.l){for(p of b.l)p&&U(p,n||a);b.l=H}if(n)return}else{r=b.o.i.G;var t=b.o.i.U;f=b.o.i.i;n=t.length;p=I;g=ea();v={};const C=[];var q;if(q=n>0){q=typeof t[0]==="object";for(var D of t)t=q?D.id:D,v[t]=
D,C.push(t)}D=q;if(g.K){if(!(g.N.length|n))return;p=f&&g.L(f,g.P);for(var J of g.N)J in v||(U(g.K[J],a),delete g.K[J]);g.P=f;g.N=C}else{if(n===0)return;g.K={};g.T=D?R(v[C[0]]):H;g.N=C;g.L=(g.P=f)&&R(f)}for(J=b.l=new L(n);n>0;){t=C[--n];q=g.K[t];if(k=!q)g.K[t]=e=q={o:{G:r,i:N({I:v[t]},f)},L:H,J:b,u:d,O:0,M:[],l:H,g:H,m:H,v:K},T(H,H),a.insertBefore(q.g,h);else{if(p||D&&g.T(v[t],q.o.i.I))(e=q).o.i=N({I:v[t]},f),T(H,H);q.g.nextSibling!==h&&a.insertBefore(q.g,h)}h=(J[n]=q).g}}b.m=h!==c?h:H},U=(a,c)=>{c&&
a.g&&(a.g.remove(),c=H);if(a.l)for(var b of a.l)b&&U(b,c);c=a.M;let d=c.length;for(;d>1;)switch((b=c[--d]).A){case 1:b.B&&b.B(...b.j);break;case 2:b.j=G}if(a.v){let h,f;(!(f=y[h=a.u])||(h=f.indexOf(a))<0)&&(!(f=z[h])||(h=f.indexOf(a))<0)||f.splice(h,1)}},W=a=>!a.v&&(a.v=I,y[a.u]?y[a.u].push(a):y[a.u]=[a],x||V()),ea=a=>(m<l.length?l[m++]:l[m++]={A:0,h:a===void 0?{}:a}).h,fa=(a,c)=>(m<l.length?(c=l[m].h,l[m++].h=a):l[m++]={A:0,h:a},c),X=a=>{const c=fa(a,H);return c?da(c,a):O(a)},ha=a=>{const c=e.g;
if(a){for(const b of X(a)){switch(b.charCodeAt(0)){case 70:c.className=O(a.F).filter(d=>a.F[d]).join(" ");continue;case 82:a.R(c);case 67:case 68:case 83:continue}c[b]=a[b]}if(a.D)for(const b of X(a.D))c.dataset[b]=a.D[b];if(a.S)for(const b of X(a.S))c.style[b]=a.S[b]}return c},Y=(a,c,b)=>({G:a,i:c?b?(c.C=b,c):c:b?{C:b}:H}),V=()=>{k=u<=0;u=ba.now();w&&cancelAnimationFrame(w);x=I;w=0;for(var a;(a=y).length;){y=[];for(const c of a)if(c)for(e of c)if(e.v){if(e.g)T(H,H);else{let b=H,d=e.m,h=e,f=e;for(;!(a=
(h=h.J).g););do{let n=f.O;const {l:p}=f=f.J,r=p.length;for(;++n<r&&p[n]&&!(b=p[n].m););}while(!b&&f!==h);f=e;T(a,b);if(f.m!==d)for(;!(f=f.J).g;){d=H;for(const n of f.l)if(n&&(d=n.m))break;if(d===f.m)break;f.m=d}}k=K}}x=K;z.length&&(y=z,z=a,ia())},ia=()=>w||(w=requestAnimationFrame(V)),Z=a=>{let c=A[a];if(!c){const b=a.indexOf("[");A[a]=c=P.createElement(b<0?a:a.substr(0,b));if(b>0)for(const d of a.substring(b+1,a.length-1).split("]["))a=d.indexOf("="),a>0?c[d.substr(0,a)]=d.substr(a+1):c[d]=I}return c},
ja=a=>{let c=B[a];if(!c){const b=Z(a);B[a]=c=d=>(k&&(e.g=b.cloneNode(I)),ha(d),d&&d.C||H)}return c};Q.lui={defer:()=>(x=I,ia()),defer_end:V,dom_define:(a,c,b)=>{c=Z(c);b&&(c=c.cloneNode(I),b.D&&(N(c.dataset,b.D),delete b.D),b.S&&(N(c.style,b.S),delete b.S),N(c,b));A["#"+a]=c},hook_assert:a=>{if(!a)throw A;},hook_async:(a,c,b)=>{let d;if((m<l.length?(d=l[m++],K):d=l[m++]={A:2,H:S(c),j:c||G,h:H})||c&&d.H(d.j,c)&&(d.j=c)){b!==void 0&&(d.h=b);const h=e;a(...d.j).then(f=>d.h!==f&&d.j===c&&(d.h=f,W(h)))}return d.h},hook_dom:(a,c)=>(e.g===H&&(e.g=Z(a).cloneNode(I)),ha(c||H)),hook_effect:(a,c)=>{if(m>=
l.length)(l[m]={A:1,H:S(c),j:c=c||G,B:H}).B=a(...c)||H;else if(c){const b=l[m];b.H(b.j,c)&&(b.B&&b.B(...b.j),b.B=H,b.B=a(...(b.j=c))||H)}++m},hook_memo:(a,c)=>m>=l.length?(l[m++]={A:0,H:S(c),j:c=c||G,h:a(...c)}).h:c&&l[m].H(l[m].j,c)?l[m].h=a(...(l[m++].j=c)):l[m++].h,hook_model:a=>{if(m<l.length)return l[m++].h;const c=e,b=[(0,a.init)(H),{}];for(const d of O(a))b[1][d]=(...h)=>{h=(0,a[d])(b[0],...h);if(b[0]!==h&&(b[0]=h,W(c),e===c))throw A;return h};l[m++]={A:0,h:b};return b},hook_prev:fa,hook_rerender:()=>
{const a=e;a.v=I;z[a.u]?z[a.u].push(a):z[a.u]=[a]},hook_state:a=>{if(m<l.length)return l[m++].h;const c=e,b=[a,d=>{if(b[0]!==d&&(b[0]=d,W(c),e===c))throw A;return d},()=>b[0]];l[m++]={A:0,h:b};return b},hook_static:ea,init:(a,c=P.body,b=H)=>{c.innerHTML="";W({o:{G:a,i:b},L:H,J:H,u:0,O:0,M:[],l:H,g:c,m:c,v:K})},node:Y,node_dom:(a,c,b)=>Y(ja(a),c,b),node_map:(a,c,b)=>Y(T,{G:a,U:c,i:b||H}),now:()=>u}}
