function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function g(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function h(a){if(!(a instanceof Array)){a=g(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a};/*
 lui.js web frame work 1.1.3
 inspired by react and mithril
 L3P3.de 2021
*/
(function(){var k=null,n=!k,r=k,t=0,v=0,z=0,A=n,B=[],C=[],D={},ba={},ca={},da=[],E=[],F=k,G=n,H=!n,I=Array,K=Object,ea=K.assign||(K.assign=function(a){for(var b=arguments.length,c=0,d,f;++c<b;)if(d=arguments[c])for(f in d)a[f]=d[f];return a}),L=K.keys||(K.keys=function(a){var b=[],c;for(c in a)b.push(c);return b}),fa=setTimeout,ha=clearTimeout,ia=document,M=window,N=Date;function ja(a){return new Function("a","b","return a!==b&&("+a.join("||")+")")}
function O(a){var b=(a=L(a)).join(",");return ca[b]||(ca[b]=ja(a.map(function(c){return"a."+c+"!==b."+c})))}function ka(a,b){return a===b?E:L(a).filter(function(c){return a[c]!==b[c]})}function P(a){return a?da[a.length]||(da[a.length]=ja(a.map(function(b,c){return"a["+c+"]!==b["+c+"]"}))):F}
function Q(a,b){var c=k,d=b,f=c.v+1;r=c.s;t=1;c.B=H;if(c.u.G!==O){var e=F;try{e=c.u.G(c.u.o)}catch(Ba){}var p=c.i;if(e){p&&(a=p,b=F);var m=e.length,l,u=c.m||(c.m=(new I(m)).fill(F));do{var q=u[--m];(l=e[m])&&l!==G?((n=!q)?((u[m]=k=q={u:l,M:l.o&&O(l.o),H:c,v:f,O:m,s:[],m:F,i:F,j:F,B:H}).s[0]={l:0,T:q},Q(a,b),q.i&&a.insertBefore(q.j=q.i,b)):l.o&&q.M(q.u.o,l.o)&&((k=q).u=l,Q(a,b)),q.j&&(b=q.j)):q&&(R(q,a),u[m]=F)}while(0<m)}else if(c.m){f=g(c.m);for(e=f.next();!e.done;e=f.next())(e=e.value)&&R(e,a);
c.m=F}p||(c.j=b!==d?b:F)}else{e=c.u.o;p=e.G;var w=e.L;e=e.o;m=w.length;q=G;if(!(0>=S(m,m)+m)){l=T();u={};var J=[];w=0<m&&la(w,u,J);if(l.J){q=e!==F&&l.M(e,l.ca);for(var U=g(l.ba),x=U.next();!x.done;x=U.next())x=x.value,x in u||(R(l.J[x],a),delete l.J[x]);l.ca=e;l.ba=J}else l.J={},l.V=w?O(u[J[0]]):F,l.ba=J,l.M=(l.ca=e)&&O(e);for(U=c.m=new I(m);0<m;){x=J[--m];var y=l.J[x];if(n=!y)(l.J[x]=k=y={u:{G:p,o:ea({I:u[x]},e)},M:F,H:c,v:f,O:m,s:[],m:F,i:F,j:F,B:H}).s[0]={l:0,T:y},Q(a,b),y.i&&a.insertBefore(y.j=
y.i,b);else if(ma(y,a,b),q||w&&l.V(u[x],y.u.o.I))(k=y).u.o=ea({I:u[x]},e),Q(a,b);(U[y.O=m]=y).j&&(b=y.j)}c.j=b!==d?b:F}}}function R(a,b){b&&a.i&&(b.removeChild(a.i),b=F);if(a.m)for(var c=g(a.m),d=c.next();!d.done;d=c.next())(d=d.value)&&R(d,b);V(a.s);if(a.B){var f,e;(!(e=B[f=a.v])||0>(f=e.indexOf(a)))&&(!(e=C[f])||0>(f=e.indexOf(a)))||e.splice(f,1)}}
function V(a){for(var b,c=a.length;1<c;)switch((b=a[--c]).l){case 1:b.N&&b.N.apply(b,h(b.h));break;case 2:b.h=E;break;case 3:na(b);break;case 4:V(b.s)}}function la(a,b,c){var d,f="object"===typeof a[0];a=g(a);for(d=a.next();!d.done;d=a.next()){d=d.value;var e=f?d.id:d;b[e]=d;c.push(e)}return f}function ma(a,b,c){if(a.i)return b.insertBefore(a.i,c),a.i;if(a.j){var d=a.m.length;do a.m[--d]&&(c=ma(a.m[d],b,c));while(0<d)}return c}
function oa(a){for(;0!==a[0].l;){if(!a[0].U.D)return F;a[0].U.D=H;a=a[0].aa}return a[0].T}function W(a){return(a=oa(a))&&!a.B&&(a.B=G,B[a.v]?B[a.v].push(a):B[a.v]=[a],A||X())}function pa(){var a=oa(r);a&&(a.B=G,C[a.v]?C[a.v].push(a):C[a.v]=[a])}function qa(a,b){if(t>=r.length)r[t]={l:1,A:P(b),h:b=b||E,N:a.apply(null,h(b))||F};else if(b){var c=r[t];c.A(c.h,b)&&(c.N&&c.N.apply(c,h(c.h)),c.N=a.apply(null,h(c.h=b))||F)}++t}
function ra(a){if(t<r.length)return r[t++].g;var b=r,c=[a,function(d){c[0]!==d&&(c[0]=d,W(b))},function(){return c[0]}];r[t++]={l:0,g:c};return c}function T(a){return(t<r.length?r[t++]:r[t++]={l:0,g:void 0===a?{}:a}).g}function sa(a,b){return t>=r.length?(r[t++]={l:0,A:P(b),h:b=b||E,g:a.apply(null,h(b))}).g:b&&r[t].A(r[t].h,b)?r[t].g=a.apply(null,h(r[t++].h=b)):r[t++].g}function S(a,b){return t<r.length?(b=r[t].g,r[t++].g=a):r[t++]={l:0,g:a},b}
function ta(a,b){return a=fa(function(){return b(G)},a),function(){return ha(a)}}function na(a){for(var b=g(a.X),c=b.next();!c.done;c=b.next())V(a.K[c.value])}function ua(a,b,c){return{Z:c.$,ea:a,Y:v,da:n?v:v+b}}function va(a){var b=S(a,F);return b?ka(b,a):L(a)}
function wa(a){var b=k.i;if(a){for(var c=g(va(a)),d=c.next();!d.done;d=c.next())switch(d=d.value,d){case "F":b.className=L(a.F).filter(function(f){return a.F[f]}).join(" ");continue;case "R":a.R(b);case "C":case "S":continue;default:b[d]=a[d]}if(a.S)for(c=g(va(a.S)),d=c.next();!d.done;d=c.next())d=d.value,b.style[d]=a.S[d]}return b}function xa(a,b,c){return{G:a,o:b?c?(b.C=c,b):b:c?{C:c}:F}}
function X(){n=0>=v;v=N.now();A=G;z=0;for(var a;(a=B).length;){B=[];a=g(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value){b=g(b);for(var c=b.next();!c.done;c=b.next())if(k=c.value,k.B){if(k.i)Q(F,F);else{var d,f=F;c=k.j;for(var e=k,p=k;!(d=(e=e.H).i););do for(var m=p.O,l=(p=p.H).m,u=l.length;++m<u&&l[m]&&!(f=l[m].j););while(!f&&p!==e);p=k;Q(d,f);if(p.j!==c)for(;!(p=p.H).i;){c=F;d=g(p.m);for(f=d.next();!(f.done||(f=f.value)&&(c=f.j));f=d.next());if(c===p.j)break;p.j=c}}n=H}}}A=H;C.length&&(B=
C,C=a,ya())}function ya(){return z||(z=requestAnimationFrame(X))}function za(a){var b=D[a];if(!b){var c=a.indexOf("[");D[a]=b=ia.createElement(0>c?a.substr(0):a.substr(0,c));if(0<c)for(a=g(a.substring(c+1,a.length-1).split("][")),c=a.next();!c.done;c=a.next()){c=c.value;var d=c.indexOf("=");0<d?b[c.substr(0,d)]=c.substr(d+1):b[c]=G}}return b}function Aa(a){var b=ba[a];if(!b){var c=za(a);ba[a]=b=function(d){return n&&(k.i=c.cloneNode(G)),wa(d),d&&d.C||F}}return b}var Y=I.prototype,Z=String.prototype;
N.now||(N.now=function(){return(new N).getTime()},Y.map||(Y.map=function(a){for(var b=[],c=this.length,d=0;d<c;++d)b.push(a(this[d],d));return b},Y.filter=function(a){for(var b=[],c=this.length,d=0;d<c;++d)a(this[d],d)&&b.push(this[d]);return b},Y.indexOf=function(a,b){b=b||0;for(var c=this.length;b<c;++b)if(this[b]===a)return b;return-1},Y.fill=function(a){for(var b=this.length,c=0;c<b;++c)this[c]=a;return this},Y.push||(Z.charAt=function(a){return this[a]},Z.substring=function(a,b){for(var c="";a<
b;++a)c+=this[a];return c},Z.substr=function(a){return this.substring(a,this.length)},Z.indexOf=function(a,b){a=a[0];b=b||0;for(var c=this.length;b<c;++b)if(this[b]===a)return b;return-1},Y.push=function(a){this[this.length]=a},Y.join=function(a){for(var b="",c=this.length-1,d=0;d<c;++d)b+=this[d]+a;d<c+1&&(b+=this[d]);return b},Z.split=function(a){for(var b=[],c=this.length,d=a.length,f=0,e;0<=(e=this.indexOf(a,f));f=e+d)b.push(this.substring(f,e));f<c&&b.push(this.substr(f));return b})));
M.requestAnimationFrame||(requestAnimationFrame=M.mozRequestAnimationFrame||M.webkitCancelAnimationFrame&&M.webkitRequestAnimationFrame||function(a){return fa(a,20)},cancelAnimationFrame=M.mozCancelAnimationFrame||M.webkitCancelAnimationFrame||ha);M.lui={defer:function(){return A=G,ya()},defer_end:function(){return cancelAnimationFrame(z),X()},hook_assert:function(a){if(!a)throw D;},hook_async:function(a,b,c){var d;if((t<r.length?(d=r[t++],H):d=r[t++]={l:2,A:P(b),h:b||E,g:F})||b&&d.A(d.h,b)&&(d.h=b)){void 0!==c&&(d.g=c);var f=r;a.apply(null,h(d.h)).then(function(e){return d.g!==e&&d.h===b&&(d.g=e,W(f))})}return d.g},hook_callback:function(a,b){var c=T();c.h=b;return c.fa||(c.fa=function(d){for(var f=[],e=0;e<arguments.length;++e)f[e]=arguments[e];
return a.apply(null,[].concat(h(c.h),h(f)))})},hook_delay:function(a){var b=g(ra(H)),c=b.next().value;b=b.next().value;qa(ta,[a,b]);return c},hook_dom:function(a,b){return n&&(k.i=za(a).cloneNode(G)),wa(b||F)},hook_effect:qa,hook_first:function(){return n},hook_map:function(a,b,c){var d=F,f=G;if(t<r.length)if((d=r[t]).P!==a)na(d),d=F;else if(!d.D||c&&d.A(d.h,c))d.h=c||E,d.D=G;else{if(b===d.L)return++t,d.g;f=H}var e=n,p=r,m=++t,l={},u=[],q=0<b.length&&la(b,l,u);if(d){if(d.g=[],d.L!==b)for(d.L=b,b=
g(d.X),c=b.next();!c.done;c=b.next())c=c.value,c in l||(V(d.K[c]),delete d.K[c])}else r[m-1]=d={l:3,A:P(c),h:c||E,g:[],D:G,P:a,V:q?O(b[0]):F,X:[],K:{},L:b};b=g(u);for(c=b.next();!c.done;c=b.next()){c=c.value;var w=d.K[c];if(n=!w)d.K[c]=w=[{l:1,aa:p,U:d,W:F,g:F}];if(f||n||(q?d.V(l[c],w[0].W):l[c]!==w[0].W)){r=w;t=1;try{w[0].g=a.apply(null,[w[0].W=l[c]].concat(h(d.h)))}catch(J){}}d.g.push(w[0].g)}n=e;r=p;t=m;d.X=u;return d.g},hook_memo:sa,hook_object_changes:va,hook_prev:S,hook_reducer:function(a){if(t<
r.length)return r[t++].g;var b=r,c=[a[0](F),function(d,f){var e=a[d](c[0],f);c[0]!==e&&(c[0]=e,W(b))}];r[t++]={l:0,g:c};return c},hook_reducer_f:function(a,b){if(t<r.length)return r[t++].g;var c=r,d=[b?b():F,function(f){f=a(d[0],f);d[0]!==f&&(d[0]=f,W(c))}];r[t++]={l:0,g:d};return d},hook_rerender:pa,hook_state:ra,hook_static:T,hook_sub:function(a,b){var c=F;if(t<r.length)if((c=r[t]).P!==a)V(c.s),c=F;else if(!c.D||b&&c.A(c.h,b))b&&(c.h=b),c.D=G;else return++t,c.g;var d=n,f=r,e=t;if(n=!c)(r[t]=c={l:4,
A:P(b),h:b||E,g:F,P:a,D:G,s:[]}).s[0]={l:2,aa:r,U:c};r=c.s;t=1;try{c.g=a.apply(null,h(c.h))}catch(p){}n=d;r=f;t=e+1;return c.g},hook_transition:function(a,b){var c=T({$:a}),d=sa(ua,[a,b,c]);return c.$=d.da<=v?d.ea:(pa(),d.Y===v?d.Z:d.Z+(d.ea-d.Z)*(v-d.Y)/(d.da-d.Y))},init:function(a){var b,c=ia.body;c.innerHTML="";(k={u:{G:function(){return wa((b=a())[0]),b[1]},o:F},M:F,H:F,v:0,O:0,s:[],m:F,i:c,j:c,B:G}).s[0]={l:0,T:k};B[0]=[k];X()},node:xa,node_dom:function(a,b,c){return xa(Aa(a),b,c)},node_map:function(a,
b,c){return xa(O,{G:a,L:b,o:c||F})},now:function(){return v}}})()