"use strict";/*
 lui.js web framework 2.4.1
 inspired by react and mithril
 l3p3.de 2025
*/
(function(){function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function e(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function f(a){if(!(a instanceof Array)){a=e(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
function k(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};var l=null,n=!l,x=l,y=0,z=0,A=0,B=!n,C=[],D=[],E={},ba={},ca={},da=[],F=[],ea={},H=l,I=n,J=B,fa=/[A-Z]/g,K=Array,L=Object,N=L.assign,O=L.keys,ha=L.values||(L.values=function(a){var b=[],c;for(c in a)b.push(a[c]);return b}),P=L.freeze||function(a){return a},ia=L.isFrozen||function(a){return a===H||typeof a!=="object"},ja=document,ka=window,la=ka.performance||Date,ma=navigator.userAgent.indexOf("WebKit")<0;P(F);P(ea);
function Q(a){return a===void 0&&R("model state must not contain undefined, missing return?"),ia(a)||(P(a).constructor!==K&&(a.constructor!==L&&R("model state must not contain shit like "+a.constructor.name),a=ha(a)),a.forEach(Q))}function na(a){a=a.i.v;return a===T?"list":a.name_||a.name||"?"}function oa(){var a=[],b=l,c="";for(l&&(a[0]="$"+y);b;)a.unshift(na(b)+c),c=b.i.h&&b.i.h.I!=H?"#"+(typeof b.i.h.I==="object"?b.i.h.I.id:b.i.h.I):":"+b.O,b=b.H;return a.join("/")||"-"}
function pa(){console.log.apply(console,f(k.apply(0,arguments)))}function qa(a){var b=k.apply(1,arguments);pa.apply(null,["lui "+oa()+": "+a].concat(f(b)))}function R(a){throw Error("lui: "+a);}function ra(a){pa("lui "+a+": error in callback");l=H}function U(a,b,c){try{return a.apply(null,f(b))}catch(d){throw ra(c),d;}}function sa(a,b){a===b||a&&b&&JSON.stringify(O(a))===JSON.stringify(O(b))||R("object keys mismatch")}
function V(a,b){x||R("hook called outside of hook context");b&&(b.constructor!==K&&R("deps must be in an array"),b.length===0&&R("deps must not be empty"));a!==H&&y<x.length&&(x[y].G!==a&&R("inconsistent hook order"),x[y].l&&ta(x[y].l,b))}function W(a,b){V(H,H);a!==va(a,a)&&R(b+" changed between renderings")}function ta(a,b){b?a.length!==b.length&&R("deps length changed"):a.length>0&&R("deps presence changed")}function wa(a){return new Function("a","b","return a!==b&&("+a.join("||")+")")}
function xa(a){var b=(a=O(a)).join(",");return ca[b]||(a.length===0&&R("object empty"),a.some(function(c){return(c.includes("-")||"0123456789".includes(c.charAt(0)))&&R("invalid key: "+c)}),ca[b]=wa(a.map(function(c){return"a."+c+"!==b."+c})))}function ya(a,b){return sa(a,b),a===b?F:O(a).filter(function(c){return a[c]!==b[c]})}function za(a){return a?(a.length===0&&R("deps must not be empty"),da[a.length]||(da[a.length]=wa(a.map(function(b,c){return"a["+c+"]!==b["+c+"]"})))):H}
function T(a,b){var c=l,d=c.u+1,p=b;x=c.P;y=0;c.B=J;if(c.i.v!==T){var g=H;try{g=(0,c.i.v)(c.i.h||ea)}catch(ua){if(ua!==E)throw ua;if(c.B)return}var r=c.g;typeof g!=="object"&&R("components need to return child list or null");if(g){r&&(a=r,p=H);var m=g.length,h;typeof m!=="number"&&R("childs must be returned in a list");m===0&&R("returned childs list empty");c.m&&m!==c.m.length&&R("returned childs count changed");var w=c.m||(c.m=(new K(m)).fill(H));do{var t=w[--m];if((h=g[m])&&h!==I){l.u===0&&h.length!=
H&&R("root component signature changed, see https://github.com/L3P3/lui/issues/53");!h.v&&R("invalid node type at "+m);t&&t.i.v!==h.v&&R("node type changed at "+m);if(n=!t)w[m]=l=t={i:h,N:h.h&&xa(h.h),H:c,u:d,O:m,P:[],m:H,g:H,o:H,B:J,J:J},T(a,p),t.g&&a.insertBefore(t.o=t.g,p);else if(sa(t.i.h,h.h),h.h&&t.N(t.i.h,h.h))(l=t).i=h,T(a,p);t.o&&(p=t.o)}else t&&(X(t,a),w[m]=H)}while(m>0)}else if(c.m){r&&(a=r);d=e(c.m);for(g=d.next();!g.done;g=d.next())(g=g.value)&&X(g,a);c.m=H}if(r)return}else{g=c.i.h;r=
g.v;var u=g.X;g=g.h;typeof u==="object"&&u&&u.constructor===K||R("list_data must be an array");typeof g!=="object"&&R("props must be an object");W(r,"item component");W(g&&O(g).join(","),"common props");m=u.length;t=I;h=Y();w={};var S=[],M;if(M=m>0){M=typeof u[0]==="object";var q=Y();q.V||(u[0]!==H&&["object","string","number"].includes(q.V=typeof u[0])||R("item type invalid"),M&&(!["string","number"].includes(q.Y=typeof u[0].id)&&R("item id type invalid"),q.keys=O(u[0]).join(",")));for(var v=e(u),
G=v.next();!G.done;G=v.next())G=G.value,G===H&&R("item is null"),typeof G!==q.V&&R("item type changed"),M&&(typeof G.id!==q.Y&&R("item id type changed"),O(G).join(",")!==q.keys&&R("item keys differ of "+G.id));u=e(u);for(q=u.next();!q.done;q=u.next())q=q.value,v=M?q.id:q,v in w&&R("item key not unique: "+v),w[v]=q,S.push(v)}m||Y();if(h.L){if(!(h.T.length|m))return;t=g&&h.N(g,h.U);u=e(h.T);for(q=u.next();!q.done;q=u.next())q=q.value,q in w||(X(h.L[q],a),delete h.L[q]);h.U=g;h.T=S}else{if(m===0)return;
h.L={};h.W=M?xa(w[S[0]]):H;h.T=S;h.N=(h.U=g)&&xa(g)}for(u=c.m=new K(m);m>0;){q=S[--m];v=h.L[q];if(n=!v)h.L[q]=l=v={i:{v:r,h:N({I:w[q]},g)},N:H,H:c,u:d,O:0,P:[],m:H,g:H,o:H,B:J,J:J},T(H,H),!v.g&&R("node_map item components must have a hook_dom"),a.insertBefore(v.g,p);else{if(t||M&&h.W(w[q],v.i.h.I))(l=v).i.h=N({I:w[q]},g),T(H,H);v.g.nextSibling!==p&&a.insertBefore(v.g,p)}p=(u[m]=v).g}}c.o=p!==b?p:H}
function X(a,b){b&&a.g&&(b.removeChild(a.g),b=H);if(b||a.J){if(a.m)for(var c=e(a.m),d=c.next();!d.done;d=c.next())(d=d.value)&&X(d,b);if(a.J)for(b=a.P,d=b.length;d>1;)switch((c=b[--d]).G){case 3:c.A&&c.A.apply(c,f(c.l));break;case 4:c.l=F}}if(a.B){var p,g;(!(g=C[p=a.u])||(p=g.indexOf(a))<0)&&(!(g=D[p])||(p=g.indexOf(a))<0)||g.splice(p,1)}}function Z(a){return!a.B&&(a.B=I,C[a.u]?C[a.u].push(a):C[a.u]=[a],B||Aa())}function Ba(){for(var a=l;a&&!a.J;)a.J=I,a=a.H}
function Y(a){return V(6,H),(y<x.length?x[y++]:x[y++]={G:6,j:a===void 0?{}:a}).j}function va(a,b){return V(9,H),y<x.length?(b=x[y].j,x[y++].j=a):x[y++]={G:9,j:a},b}function Ca(a){typeof a==="object"&&a||R("object required");var b=va(a,H);return b?ya(b,a):O(a)}
function Da(a){W(!a,"attributes presence");var b=l.g;if(a){for(var c=e(Ca(a)),d=c.next();!d.done;d=c.next()){d=d.value;d.length>1&&d.charAt(0).toLowerCase()!==d.charAt(0)&&R("capital prop: "+d);switch(d.charCodeAt(0)){case 70:typeof a.F==="object"&&a.F||R("invalid css flags");b.className=O(a.F).filter(function(p){return a.F[p]}).join(" ");continue;case 82:typeof a.R!=="function"&&R("invalid ref"),a.R(b);case 67:case 68:case 83:continue}d.charCodeAt(0)<97&&R("invalid prop: "+d);b[d]=a[d]}W(!a.D,"dataset presence");
if(a.D)for(c=e(Ca(a.D)),d=c.next();!d.done;d=c.next())d=d.value,b.setAttribute("data-"+d.replace(fa,"-$&").toLowerCase(),a.D[d]);W(!a.S,"style presence");if(a.S)for(c=e(Ca(a.S)),d=c.next();!d.done;d=c.next())d=d.value,b.style[d]=a.S[d]}return b}function Ea(a,b,c){return typeof a==="string"&&R("component expected, use node_dom instead"),c&&c.constructor!==K&&R("invalid childs type"),P({v:a,h:b?P(c?(b.C=P(c),b):b):c?P({C:P(c)}):H})}
function Aa(){n=z<=0;z=la.now();A&&cancelAnimationFrame(A);B=I;A=0;for(var a,b=0;(a=C).length;){++b>10&&R("rerender loop detected");C=[];a=e(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value){c=e(c);for(var d=c.next();!d.done;d=c.next())if(l=d.value,l.B){if(l.g)T(H,H);else{var p,g=H;d=l.o;for(var r=l,m=l;!(p=(r=r.H).g););do for(var h=m.O,w=(m=m.H).m,t=w.length;++h<t&&w[h]&&!(g=w[h].o););while(!g&&m!==r);m=l;T(p,g);if(m.o!==d)for(;!(m=m.H).g;){d=H;p=e(m.m);for(g=p.next();!(g.done||(g=g.value)&&
(d=g.o));g=p.next());if(d===m.o)break;m.o=d}}n=J}}}B=J;l=x=H;D.length&&(C=D,D=a,Fa())}function Fa(){return A||(A=requestAnimationFrame(Aa))}
function Ga(a){var b=E[a];if(!b){a.startsWith("#")&&R("dom: unknown handle");var c=a.indexOf("[");b=c<0?a:a.substr(0,c);(b.length===0||b!==b.toLowerCase()||b.includes(" ")||b.includes("#")||b.includes("."))&&R("dom: invalid tag");E[a]=b=ja.createElement(b);if(c>0)for(!a.endsWith("]")&&R("dom: ] missing"),a=e(a.substring(c+1,a.length-1).split("][")),c=a.next();!c.done;c=a.next()){c=c.value;!c&&R("dom: empty attribute");(c.includes("[")||c.includes("]"))&&R("dom: attributes screwed up");var d=c.indexOf("=");
c.includes(" ")&&(d<0||c.indexOf(" ")<d)&&R("dom: space in attribute name");var p=c.substr(0,d);d<0?b[c]=I:ma||p!=="style"?b[p]=c.substr(d+1):b.setAttribute(p,c.substr(d+1))}}return b}function Ha(a){a&&typeof a==="string"||R("dom: descriptor string expected");var b=ba[a];if(!b){var c=Ga(a);ba[a]=b=function(d){return n&&(l.g=c.cloneNode(I)),Da(d),d&&d.C||H};b.name_="$"+a}return b}ka.onerror=function(){return l&&qa("error in component"),C=D=[],J};var Ia=K.prototype;
L.entries||(L.entries=function(a){var b=[],c;for(c in a)b.push([c,a[c]]);return b},Ia.fill||(Ia.fill=function(a){for(var b=this.length,c=0;c<b;++c)this[c]=a;return this}));define({defer:function(){return l&&R("defer while rendering"),B=I,Fa()},defer_end:function(){return l&&R("defer_end while rendering"),B||R("nothing was deferred"),Aa()},dom_define:function(a,b,c){E["#"+a]&&R("dom_define: handle exists");b=Ga(b);c&&(c&&(c.C&&R("dom_define cannot have childs"),c.R&&R("dom_define cannot have a ref")),b=b.cloneNode(I),c.D&&(N(b.dataset,c.D),delete c.D),c.S&&(N(b.style,c.S),delete c.S),N(b,c));E["#"+a]=b},hook_assert:function(a){V(H,H);if(!a)throw E;},hook_async:function(a,
b,c){V(4,b);var d,p=oa();if((y<x.length?(d=x[y++],J):(Ba(),d=x[y++]={G:4,K:za(b),l:b||F,j:H}))||b&&d.K(d.l,b)&&(d.l=b)){c!==void 0&&(d.j=c);var g=l;a.apply(null,f(d.l)).then(function(r){return d.j!==r&&d.l===b&&(d.j=r,Z(g))}).catch(function(r){ra(p);throw r;})}return d.j},hook_dom:function(a,b){return V(H,H),l.g?n&&l.H&&R("hook_dom called twice"):n||R("hook_dom skipped before"),b&&(b.C&&R("hook_dom cannot have childs"),b.R&&R("hook_dom cannot have a ref")),l.g===H&&(l.g=Ga(a).cloneNode(I)),Da(b||
H)},hook_effect:function(a,b){V(3,b);if(y>=x.length)((x[y]={G:3,K:za(b),l:b=b||F,A:H}).A=a.apply(null,f(b))||H)&&Ba();else if(b){var c=x[y];c.K(c.l,b)&&(c.A&&c.A.apply(c,f(c.l)),c.A=H,(c.A=a.apply(null,f(c.l=b))||H)&&Ba())}x[y].A&&(x[y].A.then&&R("effect function must be synchronous"),typeof x[y].A!=="function"&&R("effect function may only return unmount function"));++y},hook_memo:function(a,b){return V(8,b),y>=x.length?(x[y++]={G:8,K:za(b),l:b=b||F,j:a.apply(null,f(b))}).j:b&&x[y].K(x[y].l,b)?x[y].j=
a.apply(null,f(x[y++].l=b)):x[y++].j},hook_model:function(a){V(10,H);typeof a==="object"&&a||R("mutations object required");typeof a.init!=="function"&&R("init mutation required for initial value");if(y<x.length)return x[y++].j;var b=l,c=oa(),d=[U(a.init,[H],c+" -> #init"),{}];U(Q,[d[0]],c+" -> #init");for(var p=e(O(a)),g=p.next(),r={};!g.done;r={M:void 0},g=p.next())r.M=g.value,d[1][r.M]=function(m){return function(){var h=U(a[m.M],[d[0]].concat(f(k.apply(0,arguments))),c+" -> #"+m.M);if(d[0]!==
h&&(U(Q,[h],c+" -> #"+m.M),d[0]=h,Z(b),l===b))throw E;return h}}(r);x[y++]={G:10,j:d};return d},hook_prev:va,hook_rerender:function(){V(H,H);var a=l;a.B=I;D[a.u]?D[a.u].push(a):D[a.u]=[a]},hook_state:function(a){V(5,H);if(y<x.length)return x[y++].j;var b=l,c=[a,function(d){if(c[0]!==d&&(c[0]=d,Z(b),l===b))throw E;return d},function(){return c[0]}];x[y++]={G:5,j:c};return c},hook_static:Y,init:function(a,b,c){b=b===void 0?ja.body:b;c=c===void 0?H:c;typeof a!=="function"&&R("no init function specified");
b.innerHTML!=H||R("invalid component_ element");b._lui_used&&R("root element already mounted");b._lui_used=1;b.innerHTML="";b={i:{v:a,h:c},N:H,H:H,u:0,O:0,P:[],m:H,g:b,o:b,B:J,J:J};a.name_="$root";l=x=H;Z(b)},node:Ea,node_dom:function(a,b,c){return Ea(Ha(a),b,c)},node_map:function(a,b,c){return Ea(T,{v:a,X:b,h:c||H})},now:function(){return z}})})()
