'use strict';function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function e(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function f(a){if(!(a instanceof Array)){a=e(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
function l(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};/*
 lui.js web frame work 2.1.1
 inspired by react and mithril
 L3P3.de 2024
*/
(function(){var m=null,n=!m,x=m,y=0,z=0,B=0,C=!n,D=[],E=[],F={},ba={},ca={},da=[],G=[],ea={},H=m,J=n,K=C,fa=/[A-Z]/g,L=Array,M=Object,N=M.assign,O=M.keys,ha=M.freeze||function(a){return a},ia=M.isFrozen||function(a){return a===H||"object"!==typeof a},ja=document,ka=window,la=ka.performance||Date;
function ma(a){return void 0===a&&P("model state must not contain undefined, missing return?"),ia(a)||(ha(a).constructor!==L&&(a.constructor!==M&&P("model state must not contain shit like "+a.constructor.name),a=M.values(a)),a.forEach(ma))}function na(a){a=a.o.u;return a===Q?"list":a.name_||a.name||"?"}function oa(){var a=[],b=m,c=H;for(m&&(a[0]="$"+y);b;)a.unshift(na(b)+(c!==H?":"+c:"")),c=b.L,b=b.B;return a.join("/")||"-"}function pa(){console.log.apply(console,f(l.apply(0,arguments)))}
function qa(a){var b=l.apply(1,arguments);pa.apply(null,["lui "+oa()+": "+a].concat(f(b)))}function P(a){throw Error("lui: "+a);}function sa(a){pa("lui "+a+": error in callback");m=H}function R(a,b,c){try{return a.apply(null,f(b))}catch(d){throw sa(c),d;}}function ta(a,b){a===b||a&&b&&JSON.stringify(O(a))===JSON.stringify(O(b))||P("object keys mismatch")}
function T(a,b){x||P("hook called outside of hook context");b&&(b.constructor!==L&&P("deps must be in an array"),0===b.length&&P("deps must not be empty"));a!==H&&y<x.length&&(x[y].A!==a&&P("inconsistent hook order"),x[y].l&&ua(x[y].l,b))}function U(a,b){T(H,H);a!==V(a,a)&&P(b+" changed between renderings")}function ua(a,b){b?a.length!==b.length&&P("deps length changed"):0<a.length&&P("deps presence changed")}function va(a){return new Function("a","b","return a!==b&&("+a.join("||")+")")}
function Q(a){var b=(a=O(a)).join(",");return ca[b]||(0===a.length&&P("object empty"),a.some(function(c){return(c.includes("-")||"0123456789".includes(c.charAt(0)))&&P("invalid key: "+c)}),ca[b]=va(a.map(function(c){return"a."+c+"!==b."+c})))}function wa(a,b){return ta(a,b),a===b?G:O(a).filter(function(c){return a[c]!==b[c]})}function xa(a){return a?da[a.length]||(0===a.length&&P("deps must not be empty"),da[a.length]=va(a.map(function(b,c){return"a["+c+"]!==b["+c+"]"}))):H}
function W(a,b){var c=m,d=b,q=c.s+1;x=c.N;y=0;c.v=K;if(c.o.u!==Q){var g=H;try{g=(0,c.o.u)(c.o.m||ea)}catch(ra){if(ra!==F)throw ra;}var r=c.g;"object"!==typeof g&&P("components need to return child list or null");if(g){r&&(a=r,b=H);var h=g.length,k;"number"!==typeof h&&P("childs must be returned in a list");0===h&&P("returned childs list empty");c.h&&h!==c.h.length&&P("returned childs count changed");var w=c.h||(c.h=(new L(h)).fill(H));do{var t=w[--h];if((k=g[h])&&k!==J){k.length!=H&&0===h&&0===m.s&&
P("root component signature changed, see https://github.com/L3P3/lui/issues/53");!k.u&&P("invalid node type at "+h);t&&t.o.u!==k.u&&P("node type changed at "+h);if(n=!t)w[h]=m=t={o:k,M:k.m&&Q(k.m),B:c,s:q,L:h,N:[],h:H,g:H,i:H,v:K},W(a,b),t.g&&a.insertBefore(t.i=t.g,b);else if(ta(t.o.m,k.m),k.m&&t.M(t.o.m,k.m))(m=t).o=k,W(a,b);t.i&&(b=t.i)}else t&&(X(t,a),w[h]=H)}while(0<h)}else if(c.h){q=e(c.h);for(g=q.next();!g.done;g=q.next())(g=g.value)&&X(g,a);c.h=H}r||(c.i=b!==d?b:H)}else{g=c.o.m;r=g.u;var v=
g.V;g=g.m;"object"===typeof v&&v&&v.constructor===L||P("list_data must be an array");"object"!==typeof g&&P("props must be an object");U(r,"item component");U(g&&O(g).join(","),"common props");h=v.length;t=J;if(!(0>=V(h,h)+h)){k=Y();w={};var S=[],I;if(I=0<h){I="object"===typeof v[0];var p=Y();p.T||(v[0]!==H&&["object","string","number"].includes(p.T=typeof v[0])||P("item type invalid"),I&&(!["string","number"].includes(p.W=typeof v[0].id)&&P("item id type invalid"),p.keys=O(v[0]).join(",")));for(var u=
e(v),A=u.next();!A.done;A=u.next())A=A.value,A===H&&P("item is null"),typeof A!==p.T&&P("item type changed"),I&&(typeof A.id!==p.W&&P("item id type changed"),O(A).join(",")!==p.keys&&P("item keys differ of "+A.id));v=e(v);for(p=v.next();!p.done;p=v.next())p=p.value,u=I?p.id:p,u in w&&P("item key not unique: "+u),w[u]=p,S.push(u)}h||Y();if(k.J){t=g&&k.M(g,k.P);v=e(k.O);for(p=v.next();!p.done;p=v.next())p=p.value,p in w||(X(k.J[p],a),delete k.J[p]);k.P=g;k.O=S}else k.J={},k.U=I?Q(w[S[0]]):H,k.O=S,k.M=
(k.P=g)&&Q(g);for(v=c.h=new L(h);0<h;){p=S[--h];u=k.J[p];if(n=!u)k.J[p]=m=u={o:{u:r,m:N({I:w[p]},g)},M:H,B:c,s:q,L:h,N:[],h:H,g:H,i:H,v:K},W(a,b),u.g&&a.insertBefore(u.i=u.g,b);else if((A=ya(u))&&A.nextSibling!==b&&za(u,a,b),t||I&&k.U(w[p],u.o.m.I))(m=u).o.m=N({I:w[p]},g),W(a,b);(v[u.L=h]=u).i&&(b=u.i)}c.i=b!==d?b:H}}}
function X(a,b){b&&a.g&&(b.removeChild(a.g),b=H);if(a.h)for(var c=e(a.h),d=c.next();!d.done;d=c.next())(d=d.value)&&X(d,b);b=a.N;for(d=b.length;1<d;)switch((c=b[--d]).A){case 3:c.G&&c.G.apply(c,f(c.l));break;case 4:c.l=G}if(a.v){var q,g;(!(g=D[q=a.s])||0>(q=g.indexOf(a)))&&(!(g=E[q])||0>(q=g.indexOf(a)))||g.splice(q,1)}}function ya(a){if(a.g)return a.g;var b;a=(b=a.h)?b.length:0;for(var c,d;0<a;)if((d=b[--a])&&(c=ya(d)))return c;return H}
function za(a,b,c){if(a.g)return b.insertBefore(a.g,c);if(a.i){var d=a.h.length;do a.h[--d]&&(c=za(a.h[d],b,c));while(0<d)}return c}function Z(a){return!a.v&&(a.v=J,D[a.s]?D[a.s].push(a):D[a.s]=[a],C||Aa())}function Y(a){return T(6,H),(y<x.length?x[y++]:x[y++]={A:6,j:void 0===a?{}:a}).j}function V(a,b){return T(9,H),y<x.length?(b=x[y].j,x[y++].j=a):x[y++]={A:9,j:a},b}function Ba(a){"object"===typeof a&&a||P("object required");var b=V(a,H);return b?wa(b,a):O(a)}
function Ca(a){U(!a,"attributes presence");var b=m.g;if(a){for(var c=e(Ba(a)),d=c.next();!d.done;d=c.next()){d=d.value;1<d.length&&d.charAt(0).toLowerCase()!==d.charAt(0)&&P("capital prop: "+d);switch(d.charCodeAt(0)){case 70:"object"===typeof a.F&&a.F||P("invalid css flags");b.className=O(a.F).filter(function(q){return a.F[q]}).join(" ");continue;case 82:"function"!==typeof a.R&&P("invalid ref"),a.R(b);case 67:case 68:case 83:continue}97>d.charCodeAt(0)&&P("invalid prop: "+d);b[d]=a[d]}U(!a.D,"dataset presence");
if(a.D)for(c=e(Ba(a.D)),d=c.next();!d.done;d=c.next())d=d.value,b.setAttribute("data-"+d.replace(fa,"-$&").toLowerCase(),a.D[d]);U(!a.S,"style presence");if(a.S)for(c=e(Ba(a.S)),d=c.next();!d.done;d=c.next())d=d.value,b.style[d]=a.S[d]}return b}function Da(a,b,c){return"string"===typeof a&&P("component expected, use node_dom instead"),c&&c.constructor!==L&&P("invalid childs type"),{u:a,m:b?c?(b.C=c,b):b:c?{C:c}:H}}
function Aa(){n=0>=z;z=la.now();B&&cancelAnimationFrame(B);C=J;B=0;for(var a,b=0;(a=D).length;){10<++b&&P("rerender loop detected");D=[];a=e(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value){c=e(c);for(var d=c.next();!d.done;d=c.next())if(m=d.value,m.v){if(m.g)W(H,H);else{var q,g=H;d=m.i;for(var r=m,h=m;!(q=(r=r.B).g););do for(var k=h.L,w=(h=h.B).h,t=w.length;++k<t&&w[k]&&!(g=w[k].i););while(!g&&h!==r);h=m;W(q,g);if(h.i!==d)for(;!(h=h.B).g;){d=H;q=e(h.h);for(g=q.next();!(g.done||(g=g.value)&&
(d=g.i));g=q.next());if(d===h.i)break;h.i=d}}n=K}}}C=K;m=x=H;E.length&&(D=E,E=a,Ea())}function Ea(){return B||(B=requestAnimationFrame(Aa))}
function Fa(a){var b=F[a];if(!b){a.startsWith("#")&&P("dom: unknown handle");var c=a.indexOf("[");b=0>c?a:a.substr(0,c);(0===b.length||b!==b.toLowerCase()||b.includes(" ")||b.includes("#")||b.includes("."))&&P("dom: invalid tag");F[a]=b=ja.createElement(b);if(0<c)for(!a.endsWith("]")&&P("dom: ] missing"),a=e(a.substring(c+1,a.length-1).split("][")),c=a.next();!c.done;c=a.next()){c=c.value;!c&&P("dom: empty attribute");(c.includes("[")||c.includes("]"))&&P("dom: attributes screwed up");var d=c.indexOf("=");
c.includes(" ")&&(0>d||c.indexOf(" ")<d)&&P("dom: space in attribute name");0<d?b[c.substr(0,d)]=c.substr(d+1):b[c]=J}}return b}function Ga(a){a&&"string"===typeof a||P("dom: descriptor string expected");var b=ba[a];if(!b){var c=Fa(a);ba[a]=b=function(d){return n&&(m.g=c.cloneNode(J)),Ca(d),d&&d.C||H};b.name_="$"+a}return b}ka.onerror=function(){return m&&qa("error in component"),D=E=[],K};var Ha=L.prototype;Ha.fill||(Ha.fill=function(a){for(var b=this.length,c=0;c<b;++c)this[c]=a;return this});define({defer:function(){return m&&P("defer while rendering"),C=J,Ea()},defer_end:function(){return m&&P("defer_end while rendering"),C||P("nothing was deferred"),Aa()},dom_define:function(a,b,c){F["#"+a]&&P("dom_define: handle exists");b=Fa(b);c&&(c&&(c.C&&P("dom_define cannot have childs"),c.R&&P("dom_define cannot have a ref")),b=b.cloneNode(J),c.D&&(N(b.dataset,c.D),delete c.D),c.S&&(N(b.style,c.S),delete c.S),N(b,c));F["#"+a]=b},hook_assert:function(a){T(H,H);if(!a)throw F;},hook_async:function(a,
b,c){T(4,b);var d,q=oa();if((y<x.length?(d=x[y++],K):d=x[y++]={A:4,H:xa(b),l:b||G,j:H})||b&&d.H(d.l,b)&&(d.l=b)){void 0!==c&&(d.j=c);var g=m;a.apply(null,f(d.l)).then(function(r){return d.j!==r&&d.l===b&&(d.j=r,Z(g))}).catch(function(r){sa(q);throw r;})}return d.j},hook_dom:function(a,b){return T(H,H),m.g?n&&m.B&&P("hook_dom called twice"):n||P("hook_dom skipped before"),b&&(b.C&&P("hook_dom cannot have childs"),b.R&&P("hook_dom cannot have a ref")),m.g===H&&(m.g=Fa(a).cloneNode(J)),Ca(b||H)},hook_effect:function(a,
b){T(3,b);if(y>=x.length)x[y]={A:3,H:xa(b),l:b=b||G,G:a.apply(null,f(b))||H};else if(b){var c=x[y];c.H(c.l,b)&&(c.G&&c.G.apply(c,f(c.l)),c.G=a.apply(null,f(c.l=b))||H)}var d;(null==(d=x[y].G)?0:d.then)&&P("effect function must be synchronous");++y},hook_memo:function(a,b){return T(8,b),y>=x.length?(x[y++]={A:8,H:xa(b),l:b=b||G,j:a.apply(null,f(b))}).j:b&&x[y].H(x[y].l,b)?x[y].j=a.apply(null,f(x[y++].l=b)):x[y++].j},hook_model:function(a){T(10,H);"object"===typeof a&&a||P("mutations object required");
"function"!==typeof a.init&&P("init mutation required for initial value");if(y<x.length)return x[y++].j;var b=m,c=oa(),d=[R(a.init,[H],c+" -> #init"),{}];R(ma,[d[0]],c+" -> #init");for(var q=e(O(a)),g=q.next(),r={};!g.done;r={K:void 0},g=q.next())r.K=g.value,d[1][r.K]=function(h){return function(){var k=R(a[h.K],[d[0]].concat(f(l.apply(0,arguments))),c+" -> #"+h.K);d[0]!==k&&(R(ma,[k],c+" -> #"+h.K),d[0]=k,Z(b))}}(r);x[y++]={A:10,j:d};return d},hook_prev:V,hook_rerender:function(){T(H,H);var a=m;
a.v=J;E[a.s]?E[a.s].push(a):E[a.s]=[a]},hook_state:function(a){T(5,H);if(y<x.length)return x[y++].j;var b=m,c=[a,function(d){c[0]!==d&&(c[0]=d,Z(b))},function(){return c[0]}];x[y++]={A:5,j:c};return c},hook_static:Y,init:function(a,b,c){b=void 0===b?ja.body:b;c=void 0===c?H:c;"function"!==typeof a&&P("no init function specified");b.innerHTML!=H||P("invalid component_ element");b._lui_used&&P("root element already mounted");b._lui_used=1;b.innerHTML="";b={o:{u:a,m:c},M:H,B:H,s:0,L:0,N:[],h:H,g:b,i:b,
v:K};a.name_="$root";m=x=H;Z(b)},node:Da,node_dom:function(a,b,c){return Da(Ga(a),b,c)},node_map:function(a,b,c){return Da(Q,{u:a,V:b,m:c||H})},now:function(){return z}})})()