'use strict';/*
 lui.js web frame work 1.4.0
 inspired by react and mithril
 L3P3.de 2022
*/
{let d=null,f=!d,g=d,h=0,m=0,u=0,y=f,z=[],A=[];
const B={},aa={},ba={},ca=[],C=[],da={},D=d,F=f,G=!f,H=Array,I=Object,J=I.assign,K=I.keys,ea=I.freeze,fa=I.isFrozen,ha=document,M=window,ia=M.performance||Date,O=a=>(void 0===a&&N("model state must not contain undefined, missing return?"),fa(a)||(ea(a).constructor!==H&&(a.constructor!==I&&N("model state must not contain shit like "+a.constructor.name),a=I.values(a)),a.forEach(O))),ja=({s:{v:a}})=>a===P?"list":a.name_||a.name||"?",ka=()=>{const a=[];let b=g,c=D;if(b){for(a.unshift("$"+(h-1));0!==b[0].o;)a.unshift(1===
b[0].o?`hook_map[${"object"===typeof b[0].O?b[0].O.id:b[0].O}]`:"hook_sub"),b=b[0].X;b=b[0].N}for(;b;)a.unshift(ja(b)+(c?":"+c:"")),c=b.L,b=b.H;return a.join("/")||"-"},la=(...a)=>{console.log(...a)},ma=a=>{la("lui "+ka()+": "+a,...[])},N=a=>{throw Error("lui: "+a);},na=a=>{la("lui "+a+": error in callback");d=D},Q=(a,b,c)=>{try{return a(...b)}catch(e){throw na(c),e;}},oa=(a,b)=>{a===b||a&&b&&JSON.stringify(K(a))===JSON.stringify(K(b))||N("object keys mismatch")},T=(a,b,c)=>{g||N("hook called outside of hook context");
c&&(c.constructor!==H&&N("deps must be in an array"),0===c.length&&N("deps must not be empty"));b&&0!==g[0].o&&N("hook called outside of component rendering");a!==D&&h<g.length&&(g[h].o!==a&&N("inconsistent hook order"),g[h].m&&pa(g[h].m,c))},V=(a,b)=>{T(D,G,D);a!==U(a,a)&&N(b+" changed between renderings")},pa=(a,b)=>{b?a.length!==b.length&&N("deps length changed"):0<a.length&&N("deps presence changed")},qa=a=>new Function("a","b",`return a!==b&&(${a.join("||")})`),P=a=>{const b=(a=K(a)).join(",");
return ba[b]||(0===a.length&&N("object empty"),a.some(c=>(c.includes("-")||"0123456789".includes(c.charAt(0)))&&N("invalid key: "+c)),ba[b]=qa(a.map(c=>`a.${c}!==b.`+c)))},ra=(a,b)=>(oa(a,b),a===b?C:K(a).filter(c=>a[c]!==b[c])),sa=a=>a?ca[a.length]||(0===a.length&&N("deps must not be empty"),ca[a.length]=qa(a.map((b,c)=>`a[${c}]!==b[${c}]`))):D,W=(a,b)=>{const c=d,e=b,r=c.u+1;g=c.B;h=1;c.A=G;if(c.s.v!==P){var k=D;try{k=(0,c.s.v)(c.s.l||da)}catch(R){if(R!==B)throw R;}var p=c.g;"object"!==typeof k&&
N("components need to return child list or null");if(k){p&&(a=p,b=D);var q=k.length,l;"number"!==typeof q&&N("childs must be returned in a list");0===q&&N("returned childs list empty");c.h&&q!==c.h.length&&N("returned childs count changed");var v=c.h||(c.h=(new H(q)).fill(D));do{var n=v[--q];if((l=k[q])&&l!==F){n&&n.s.v!==l.v&&N("child component changed at "+q);if(f=!n)(v[q]=d=n={s:l,M:l.l&&P(l.l),H:c,u:r,L:q,B:[],h:D,g:D,i:D,A:G}).B[0]={o:0,N:n},W(a,b),n.g&&a.insertBefore(n.i=n.g,b);else if(oa(n.s.l,
l.l),l.l&&n.M(n.s.l,l.l))(d=n).s=l,W(a,b);n.i&&(b=n.i)}else n&&(X(n,a),v[q]=D)}while(0<q)}else if(c.h){for(q of c.h)q&&X(q,a);c.h=D}p||(c.i=b!==e?b:D)}else{q=c.s.l.v;var x=c.s.l.$;n=c.s.l.l;"object"===typeof x&&x&&x.constructor===H||N("list_data must be an array");"object"!==typeof n&&N("props must be an object");V(q,"item component");V(n&&K(n).join(","),"common props");v=x.length;let R=F;if(!(0>=U(v,v)+v)){l=Y();k={};p=[];var t;if(t=0<v){t="object"===typeof x[0];const E=Y();E.U||(x[0]!==D&&["object",
"string","number"].includes(E.U=typeof x[0])||N("item type invalid"),t&&(!["string","number"].includes(E.aa=typeof x[0].id)&&N("item id type invalid"),E.keys=K(x[0]).join(",")));for(var w of x)w===D&&N("item is null"),typeof w!==E.U&&N("item type changed"),t&&(typeof w.id!==E.aa&&N("item id type changed"),K(w).join(",")!==E.keys&&N("item keys differ of "+w.id));for(var L of x)w=t?L.id:L,w in k&&N("item key not unique: "+w),k[w]=L,p.push(w)}L=t;v||Y();if(l.K){R=n&&l.M(n,l.T);for(var S of l.P)S in k||
(X(l.K[S],a),delete l.K[S]);l.T=n;l.P=p}else l.K={},l.Z=L?P(k[p[0]]):D,l.P=p,l.M=(l.T=n)&&P(n);for(S=c.h=new H(v);0<v;){w=p[--v];t=l.K[w];if(f=!t)(l.K[w]=d=t={s:{v:q,l:J({I:k[w]},n)},M:D,H:c,u:r,L:v,B:[],h:D,g:D,i:D,A:G}).B[0]={o:0,N:t},W(a,b),t.g&&a.insertBefore(t.i=t.g,b);else if((x=ta(t))&&x.nextSibling!==b&&ua(t,a,b),R||L&&l.Z(k[w],t.s.l.I))(d=t).s.l=J({I:k[w]},n),W(a,b);(S[t.L=v]=t).i&&(b=t.i)}c.i=b!==e?b:D}}},X=(a,b)=>{b&&a.g&&(b.removeChild(a.g),b=D);if(a.h)for(var c of a.h)c&&X(c,b);b=a.B;
let e=b.length;for(;1<e;)switch((c=b[--e]).o){case 3:c.G&&c.G(...c.m);break;case 4:c.m=C}if(a.A){let r,k;(!(k=z[r=a.u])||0>(r=k.indexOf(a)))&&(!(k=A[r])||0>(r=k.indexOf(a)))||k.splice(r,1)}},ta=a=>{if(a.g)return a.g;let b;a=(b=a.h)?b.length:0;let c,e;for(;0<a;)if((e=b[--a])&&(c=ta(e)))return c;return D},ua=(a,b,c)=>{if(a.g)return b.insertBefore(a.g,c),a.g;if(a.i){let e=a.h.length;do a.h[--e]&&(c=ua(a.h[e],b,c));while(0<e)}return c},va=a=>{for(;0!==a[0].o;){if(!a[0].Y.V)return D;a[0].Y.V=G;a=a[0].X}return a[0].N},
wa=a=>(a=va(a))&&!a.A&&(a.A=F,z[a.u]?z[a.u].push(a):z[a.u]=[a],y||Z()),Y=a=>(T(6,G,D),(h<g.length?g[h++]:g[h++]={o:6,j:void 0===a?{}:a}).j),U=(a,b)=>(T(9,G,D),h<g.length?(b=g[h].j,g[h++].j=a):g[h++]={o:9,j:a},b),xa=a=>{"object"===typeof a&&a||N("object required");const b=U(a,D);return b?ra(b,a):K(a)},ya=a=>{V(!a,"attributes presence");const b=d.g;if(a){for(const c of xa(a)){1<c.length&&c.charAt(0).toLowerCase()!==c.charAt(0)&&N("capital prop: "+c);switch(c.charCodeAt(0)){case 70:"object"===typeof a.F&&
a.F||N("invalid css flags");b.className=K(a.F).filter(e=>a.F[e]).join(" ");continue;case 82:"function"!==typeof a.R&&N("invalid ref"),a.R(b);case 67:case 68:case 83:continue}97>c.charCodeAt(0)&&N("invalid prop: "+c);b[c]=a[c]}V(!a.D,"dataset presence");if(a.D)for(const c of xa(a.D))b.dataset[c]=a.D[c];V(!a.S,"style presence");if(a.S)for(const c of xa(a.S))b.style[c]=a.S[c]}return b},za=(a,b,c)=>("string"===typeof a&&N("component expected, use node_dom instead"),c&&c.constructor!==H&&N("invalid childs type"),
{v:a,l:b?c?(b.C=c,b):b:c?{C:c}:D}),Z=()=>{f=0>=m;m=ia.now();u&&cancelAnimationFrame(u);y=F;u=0;var a;let b=0;for(;(a=z).length;){10<++b&&N("rerender loop detected");z=[];for(const c of a)if(c)for(d of c)if(d.A){if(d.g)W(D,D);else{let e=D,r=d.i,k=d,p=d;for(;!(a=(k=k.H).g););do{let q=p.L;const {h:l}=p=p.H,v=l.length;for(;++q<v&&l[q]&&!(e=l[q].i););}while(!e&&p!==k);p=d;W(a,e);if(p.i!==r)for(;!(p=p.H).g;){r=D;for(const q of p.h)if(q&&(r=q.i))break;if(r===p.i)break;p.i=r}}f=G}}y=G;d=g=D;A.length&&(z=
A,A=a,Aa())},Aa=()=>u||(u=requestAnimationFrame(Z)),Ba=a=>{var b=B[a];if(!b){a.startsWith("#")&&N("dom: unknown handle");const c=a.indexOf("[");b=0>c?a:a.substring(0,c);(0===b.length||b!==b.toLowerCase()||b.includes(" ")||b.includes("#")||b.includes("."))&&N("dom: invalid tag");B[a]=b=ha.createElement(b);if(0<c){!a.endsWith("]")&&N("dom: ] missing");for(const e of a.substring(c+1,a.length-1).split("]["))!e&&N("dom: empty attribute"),(e.includes("[")||e.includes("]"))&&N("dom: attributes screwed up"),
a=e.indexOf("="),e.includes(" ")&&(0>a||e.indexOf(" ")<a)&&N("dom: space in attribute name"),0<a?b[e.substring(0,a)]=e.substr(a+1):b[e]=F}}return b},Ca=a=>{a&&"string"===typeof a||N("dom: descriptor string expected");let b=aa[a];if(!b){const c=Ba(a);aa[a]=b=e=>(f&&(d.g=c.cloneNode(F)),ya(e),e&&e.C||D);b.name_="$"+a}return b};M.onerror=()=>(d&&ma("error in component"),z=A=[],G);M.lui={defer:()=>(d&&N("defer while rendering"),y=F,Aa()),defer_end:()=>(d&&N("defer_end while rendering"),y||N("nothing was deferred"),Z()),dom_define:(a,b,c)=>{B["#"+a]&&N("dom_define: handle exists");b=Ba(b);c&&(c&&(c.C&&N("dom_define cannot have childs"),c.R&&N("dom_define cannot have a ref")),b=b.cloneNode(F),c.D&&(J(b.dataset,c.D),delete c.D),c.S&&(J(b.style,c.S),delete c.S),J(b,c));B["#"+a]=b},hook_assert:a=>{T(D,G,D);if(!a)throw B;},hook_async:(a,b,c)=>{T(4,G,b);let e;const r=ka();if((h<g.length?
(e=g[h++],G):e=g[h++]={o:4,J:sa(b),m:b||C,j:D})||b&&e.J(e.m,b)&&(e.m=b)){void 0!==c&&(e.j=c);const k=g;a(...e.m).then(p=>e.j!==p&&e.m===b&&(e.j=p,wa(k))).catch(p=>{na(r);throw p;})}return e.j},hook_dom:(a,b)=>(T(D,F,D),d.g?f&&N("hook_dom called twice"):f||N("hook_dom skipped before"),b&&(b.C&&N("hook_dom cannot have childs"),b.R&&N("hook_dom cannot have a ref")),f&&(d.g=Ba(a).cloneNode(F)),ya(b||D)),hook_effect:(a,b)=>{T(3,G,b);if(h>=g.length)g[h]={o:3,J:sa(b),m:b=b||C,G:a(...b)||D};else if(b){const c=
g[h];c.J(c.m,b)&&(c.G&&c.G(...c.m),c.G=a(...(c.m=b))||D)}g[h].G&&g[h].G.then&&N("effect function must be synchronous");++h},hook_memo:(a,b)=>(T(8,G,b),h>=g.length?(g[h++]={o:8,J:sa(b),m:b=b||C,j:a(...b)}).j:b&&g[h].J(g[h].m,b)?g[h].j=a(...(g[h++].m=b)):g[h++].j),hook_model:a=>{T(10,G,D);"object"===typeof a&&a||N("mutations object required");"function"!==typeof a.init&&N("init mutation required for initial value");if(h<g.length)return g[h++].j;const b=g,c=ka(),e=[Q(a.init,[D],c+" -> #init"),{}];Q(O,
[e[0]],c+" -> #init");for(const r of K(a))e[1][r]=(...k)=>{k=Q(a[r],[e[0],...k],c+" -> #"+r);e[0]!==k&&(Q(O,[k],c+" -> #"+r),e[0]=k,wa(b))};g[h++]={o:10,j:e};return e},hook_prev:U,hook_rerender:()=>{T(D,G,D);const a=va(g);a&&(a.A=F,A[a.u]?A[a.u].push(a):A[a.u]=[a])},hook_state:a=>{T(5,G,D);if(h<g.length)return g[h++].j;const b=g,c=[a,e=>{c[0]!==e&&(c[0]=e,wa(b))},()=>c[0]];g[h++]={o:5,j:c};return c},hook_static:Y,init:(a,b=ha.body)=>{"function"!==typeof a&&N("no init function specified");b instanceof
HTMLElement||N("invalid root element");b.W&&N("root element already mounted");b.W=1;let c;b.innerHTML="";const e=()=>((!(c=a())||2!==c.length)&&N("root component must return [props, childs]"),V(!c[0],"attributes presence"),c[0]!==D&&("object"!==typeof c[0]&&N("invalid props type"),oa(U(c[0],c[0]),c[0]),c[0].C&&N("root childs must be in second return value")),ya(c[0]),c[1]);e.name_="$root";(d={s:{v:e,l:D},M:D,H:D,u:0,L:0,B:[],h:D,g:b,i:b,A:F}).B[0]={o:0,N:d};z[0]=[d];d=g=D;Z()},node:za,node_dom:(a,
b,c)=>za(Ca(a),b,c),node_map:(a,b,c)=>za(P,{v:a,$:b,l:c||D}),now:()=>m}}