"use strict";/*
 lui.js web framework 2.4.0
 inspired by react and mithril
 l3p3.de 2025
*/
(function(){function aa(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}function e(a){var c=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(c)return c.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function k(a){if(!(a instanceof Array)){a=e(a);for(var c,b=[];!(c=a.next()).done;)b.push(c.value);a=b}return a}
function ba(){for(var a=Number(this),c=[],b=a;b<arguments.length;b++)c[b-a]=arguments[b];return c};var l=null,m=!l,t=l,x=0,y=0,z=0,A=!m,B=[],C=[],D={},E={},F={},ca=[l,function(a,c){return a!==c&&a[0]!==c[0]},function(a,c){return a!==c&&(a[0]!==c[0]||a[1]!==c[1])},function(a,c){return a!==c&&(a[0]!==c[0]||a[1]!==c[1]||a[2]!==c[2])}],G=[],da={},H=l,I=m,J=A,ea=/[A-Z]/g,K=Array,N=Object,O=N.assign,P=N.keys;N.values||(N.values=function(a){var c=[],b;for(b in a)c.push(a[b]);return c});var fa=document,ha=window.performance||Date,ia=navigator.userAgent.indexOf("WebKit")<0;
function Q(a){var c=(a=P(a)).join(",");return F[c]||(F[c]=a)}function R(a,c,b){if(a===c)return!1;b=e(b);for(var d=b.next();!d.done;d=b.next())if(d=d.value,a[d]!==c[d])return!0;return!1}function ja(a,c){return a===c?G:P(a).filter(function(b){return a[b]!==c[b]})}function S(a){return a?a.length<5?ca[a.length]:ka:H}function ka(a,c){if(a===c)return!1;for(var b=0,d=a.length;b<d;++b)if(a[b]!==c[b])return!0;return!1}
function T(a,c){var b=l,d=b.u+1,g=c;t=b.M;x=0;b.v=J;if(b.o.G!==T){var f=H;try{f=(0,b.o.G)(b.o.j||da)}catch(sa){if(b.v)return}var q=b.g;if(f){q&&(a=q,g=H);var n=f.length,h,u=b.l||(b.l=(new K(n)).fill(H));do{var r=u[--n];(h=f[n])&&h!==I?((m=!r)?(u[n]=l=r={o:h,L:h.j&&Q(h.j),J:b,u:d,P:n,M:[],l:H,g:H,m:H,v:J},T(a,g),r.g&&a.insertBefore(r.m=r.g,g)):h.j&&R(r.o.j,h.j,r.L)&&((l=r).o=h,T(a,g)),r.m&&(g=r.m)):r&&(U(r,a),u[n]=H)}while(n>0)}else if(b.l){d=e(b.l);for(f=d.next();!f.done;f=d.next())(f=f.value)&&U(f,
q||a);b.l=H}if(q)return}else{f=b.o.j;q=f.G;var v=f.V;f=f.j;n=v.length;r=I;h=la();u={};var L=[],M;if(M=n>0){M=typeof v[0]==="object";v=e(v);for(var p=v.next();!p.done;p=v.next()){p=p.value;var w=M?p.id:p;u[w]=p;L.push(w)}}if(h.K){if(!(h.N.length|n))return;r=f&&R(f,h.T,h.L);v=e(h.N);for(p=v.next();!p.done;p=v.next())p=p.value,p in u||(U(h.K[p],a),delete h.K[p]);h.T=f;h.N=L}else{if(n===0)return;h.K={};h.U=M?Q(u[L[0]]):H;h.N=L;h.L=(h.T=f)&&Q(f)}for(v=b.l=new K(n);n>0;){p=L[--n];w=h.K[p];if(m=!w)h.K[p]=
l=w={o:{G:q,j:O({I:u[p]},f)},L:H,J:b,u:d,P:0,M:[],l:H,g:H,m:H,v:J},T(H,H),a.insertBefore(w.g,g);else{if(r||M&&R(u[p],w.o.j.I,h.U))(l=w).o.j=O({I:u[p]},f),T(H,H);w.g.nextSibling!==g&&a.insertBefore(w.g,g)}g=(v[n]=w).g}}b.m=g!==c?g:H}
function U(a,c){c&&a.g&&(c.removeChild(a.g),c=H);if(a.l)for(var b=e(a.l),d=b.next();!d.done;d=b.next())(d=d.value)&&U(d,c);c=a.M;for(d=c.length;d>1;)switch((b=c[--d]).A){case 1:b.B&&b.B.apply(b,k(b.i));break;case 2:b.i=G}if(a.v){var g,f;(!(f=B[g=a.u])||(g=f.indexOf(a))<0)&&(!(f=C[g])||(g=f.indexOf(a))<0)||f.splice(g,1)}}function V(a){return!a.v&&(a.v=I,B[a.u]?B[a.u].push(a):B[a.u]=[a],A||W())}function la(a){return(x<t.length?t[x++]:t[x++]={A:0,h:a===void 0?{}:a}).h}
function ma(a,c){return x<t.length?(c=t[x].h,t[x++].h=a):t[x++]={A:0,h:a},c}function X(a){var c=ma(a,H);return c?ja(c,a):P(a)}
function na(a){var c=l.g;if(a){for(var b=e(X(a)),d=b.next();!d.done;d=b.next()){d=d.value;switch(d.charCodeAt(0)){case 70:c.className=P(a.F).filter(function(g){return a.F[g]}).join(" ");continue;case 82:a.R(c);case 67:case 68:case 83:continue}c[d]=a[d]}if(a.D)for(b=e(X(a.D)),d=b.next();!d.done;d=b.next())d=d.value,c.setAttribute("data-"+d.replace(ea,"-$&").toLowerCase(),a.D[d]);if(a.S)for(b=e(X(a.S)),d=b.next();!d.done;d=b.next())d=d.value,c.style[d]=a.S[d]}return c}
function Y(a,c,b){return{G:a,j:c?b?(c.C=b,c):c:b?{C:b}:H}}
function W(){m=y<=0;y=ha.now();z&&cancelAnimationFrame(z);A=I;z=0;for(var a;(a=B).length;){B=[];a=e(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value){c=e(c);for(var b=c.next();!b.done;b=c.next())if(l=b.value,l.v){if(l.g)T(H,H);else{var d,g=H;b=l.m;for(var f=l,q=l;!(d=(f=f.J).g););do for(var n=q.P,h=(q=q.J).l,u=h.length;++n<u&&h[n]&&!(g=h[n].m););while(!g&&q!==f);q=l;T(d,g);if(q.m!==b)for(;!(q=q.J).g;){b=H;d=e(q.l);for(g=d.next();!(g.done||(g=g.value)&&(b=g.m));g=d.next());if(b===q.m)break;q.m=
b}}m=J}}}A=J;C.length&&(B=C,C=a,oa())}function oa(){return z||(z=requestAnimationFrame(W))}var pa=W;function Z(a){var c=D[a];if(!c){var b=a.indexOf("[");D[a]=c=fa.createElement(b<0?a:a.substr(0,b));if(b>0)for(a=e(a.substring(b+1,a.length-1).split("][")),b=a.next();!b.done;b=a.next()){b=b.value;var d=b.indexOf("="),g=b.substr(0,d);d<0?c[b]=I:ia||g!=="style"?c[g]=b.substr(d+1):c.setAttribute(g,b.substr(d+1))}}return c}
function qa(a){var c=E[a];if(!c){var b=Z(a);E[a]=c=function(d){return m&&(l.g=b.cloneNode(I)),na(d),d&&d.C||H}}return c}var ra=K.prototype;N.entries||(N.entries=function(a){var c=[],b;for(b in a)c.push([b,a[b]]);return c},ra.fill||(ra.fill=function(a){for(var c=this.length,b=0;b<c;++b)this[b]=a;return this}));define({defer:function(){return A=I,oa()},defer_end:pa,dom_define:function(a,c,b){c=Z(c);b&&(c=c.cloneNode(I),b.D&&(O(c.dataset,b.D),delete b.D),b.S&&(O(c.style,b.S),delete b.S),O(c,b));D["#"+a]=c},hook_assert:function(a){if(!a)throw D;},hook_async:function(a,c,b){var d;if((x<t.length?(d=t[x++],J):d=t[x++]={A:2,H:S(c),i:c||G,h:H})||c&&d.H(d.i,c)&&(d.i=c)){b!==void 0&&(d.h=b);var g=l;a.apply(null,k(d.i)).then(function(f){return d.h!==f&&d.i===c&&(d.h=f,V(g))})}return d.h},hook_dom:function(a,c){return l.g===
H&&(l.g=Z(a).cloneNode(I)),na(c||H)},hook_effect:function(a,c){if(x>=t.length)(t[x]={A:1,H:S(c),i:c=c||G,B:H}).B=a.apply(null,k(c))||H;else if(c){var b=t[x];b.H(b.i,c)&&(b.B&&b.B.apply(b,k(b.i)),b.B=H,b.B=a.apply(null,k(b.i=c))||H)}++x},hook_memo:function(a,c){return x>=t.length?(t[x++]={A:0,H:S(c),i:c=c||G,h:a.apply(null,k(c))}).h:c&&t[x].H(t[x].i,c)?t[x].h=a.apply(null,k(t[x++].i=c)):t[x++].h},hook_model:function(a){if(x<t.length)return t[x++].h;for(var c=l,b=[(0,a.init)(H),{}],d=e(P(a)),g=d.next(),
f={};!g.done;f={O:void 0},g=d.next())f.O=g.value,b[1][f.O]=function(q){return function(){var n=a[q.O].apply(null,[b[0]].concat(k(ba.apply(0,arguments))));if(b[0]!==n&&(b[0]=n,V(c),l===c))throw D;return n}}(f);t[x++]={A:0,h:b};return b},hook_prev:ma,hook_rerender:function(){var a=l;a.v=I;C[a.u]?C[a.u].push(a):C[a.u]=[a]},hook_state:function(a){if(x<t.length)return t[x++].h;var c=l,b=[a,function(d){if(b[0]!==d&&(b[0]=d,V(c),l===c))throw D;return d},function(){return b[0]}];t[x++]={A:0,h:b};return b},
hook_static:la,init:function(a,c,b){c=c===void 0?fa.body:c;b=b===void 0?H:b;c.innerHTML="";V({o:{G:a,j:b},L:H,J:H,u:0,P:0,M:[],l:H,g:c,m:c,v:J})},node:Y,node_dom:function(a,c,b){return Y(qa(a),c,b)},node_map:function(a,c,b){return Y(T,{G:a,V:c,j:b||H})},now:function(){return y}})})()
