'use strict';function aa(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}function f(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):{next:aa(a)}}function g(a){if(!(a instanceof Array)){a=f(a);for(var c,b=[];!(c=a.next()).done;)b.push(c.value);a=b}return a};/*
 lui.js web frame work 1.1.0
 inspired by react and mithril
 L3P3.de 2021
*/
(function(){var k=null,l=!k,q=k,r=0,u=0,v=0,w=l,y=[],C=[],D={},ba={},ca={},da=[],E=[],F=k,G=l,H=!l,I=Array,ea=Object,fa=ea.assign,J=ea.keys,ha=document,ia=window,ka=ia.performance||Date;
function la(a,c){for(var b=[],d=1;d<arguments.length;++d)b[d-1]=arguments[d];d=console.log;var e=d.apply,p=console;b=g(b);var h=[],m=q,t=F;if(m){for(h.unshift("$"+(r-1));0!==m[0].i;)h.unshift(1===m[0].i?"hook_map["+("object"===typeof m[0].K?m[0].K.id:m[0].K)+"]":"hook_sub"),m=m[0].V;m=m[0].T}for(;m;){var n=m.s.A;h.unshift((n===K?"list":n.name_||n.name||"?")+(t?":"+t:""));t=m.L;m=m.J}e.call(d,p,["lui "+(h.join("/")||"-")+": "+a].concat(b))}function L(a){throw Error("lui: "+a);}
function M(a,c){a===c||a&&c&&JSON.stringify(J(a))===JSON.stringify(J(c))||L("object keys mismatch")}function N(a,c,b){q||L("hook called outside of hook context");b&&(b.constructor!==I&&L("deps must be in an array"),0===b.length&&L("deps must not be empty"));c&&0!==q[0].i&&L("hook called outside of component rendering");a!==F&&r<q.length&&(q[r].i!==a&&L("inconsistent hook order"),q[r].h&&ma(q[r].h,b))}function O(a,c){N(F,H,F);a!==P(a,a)&&L(c+" changed between renderings")}
function ma(a,c){c?a.length!==c.length&&L("deps length changed"):0<a.length&&L("deps presence changed")}function na(a){return new Function("a","b","return a!==b&&("+a.join("||")+")")}function K(a){var c=(a=J(a)).join(",");return ca[c]||(0===a.length&&L("object empty"),a.some(function(b){return(b.includes("-")||"0123456789".includes(b.charAt(0)))&&L("invalid key: "+b)}),ca[c]=na(a.map(function(b){return"a."+b+"!==b."+b})))}
function oa(a,c){return M(a,c),a===c?E:J(a).filter(function(b){return a[b]!==c[b]})}function Q(a){return a?da[a.length]||(0===a.length&&L("deps must not be empty"),da[a.length]=na(a.map(function(c,b){return"a["+b+"]!==b["+b+"]"}))):F}
function R(a,c){var b=k,d=c;q=b.u;r=1;b.D=H;if(b.s.A!==K){var e=F;try{e=b.s.A(b.s.o)}catch(ja){if(ja!==D)throw ja;}var p=b.j;"object"!==typeof e&&L("components need to return child list or null");if(e){p&&(a=p,c=F);var h=e.length,m;"number"!==typeof h&&L("childs must be returned in a list");0===h&&L("returned childs list empty");b.l&&h!==b.l.length&&L("returned childs count changed");var t=b.l||(b.l=(new I(h)).fill(F));do{var n=t[--h];if((m=e[h])&&m!==G){n&&n.s.A!==m.A&&L("child component changed at "+
h);if(l=!n)(t[h]=k=n={s:m,P:m.o&&K(m.o),J:b,v:b.v+1,L:h,u:[],l:F,j:F,m:F,D:H}).u[0]={i:0,T:n},R(a,c),n.j&&a.insertBefore(n.m=n.j,c);else if(M(n.s.o,m.o),m.o&&n.P(n.s.o,m.o))(k=n).s=m,R(a,c);n.m&&(c=n.m)}else n&&(S(n,a),t[h]=F)}while(0<h)}else if(b.l){e=f(b.l);for(h=e.next();!h.done;h=e.next())(h=h.value)&&S(h,a);b.l=F}p||(b.m=c!==d?c:F)}else{e=b.s.o;p=e.A;var z=e.O;e=e.o;"object"===typeof z&&z&&z.constructor===I||L("list_data must be an array");"object"!==typeof e&&L("props must be an object");O(p,
"item component");O(e&&J(e).join(","),"common props");h=z.length;if(!(0>=P(h,h)+h)){n=T();m={};t=[];z=0<h&&pa(z,m,t);h||T();if(n.M){n.ca=e!==F&&n.P(e,n.da);for(var A=f(n.ba),x=A.next();!x.done;x=A.next())x=x.value,x in m||(S(n.M[x],a),delete n.M[x]);n.da=e;n.ba=t}else n.M={},n.X=z?K(m[t[0]]):F,n.ba=t,n.P=(n.da=e)&&K(e),n.ca=G;for(A=b.l=new I(h);0<h;){x=t[--h];var B=n.M[x];if(l=!B)(n.M[x]=k=B={s:{A:p,o:fa({I:m[x]},e)},P:F,J:b,v:b.v+1,L:h,u:[],l:F,j:F,m:F,D:H}).u[0]={i:0,T:B},R(a,c),B.j&&a.insertBefore(B.m=
B.j,c);else if(B.L!==h&&(qa(B,a,c),B.L=h),n.ca||z&&n.X(m[x],B.s.o.I))(k=B).s.o=fa({I:m[x]},e),R(a,c);(A[h]=B).m&&(c=B.m)}b.m=c!==d?c:F}}}function S(a,c){c&&a.j&&(c.removeChild(a.j),c=F);if(a.l)for(var b=f(a.l),d=b.next();!d.done;d=b.next())(d=d.value)&&S(d,c);U(a.u);if(a.D){var e,p;(!(p=y[e=a.v])||0>(e=p.indexOf(a)))&&(!(p=C[e])||0>(e=p.indexOf(a)))||p.splice(e,1)}}
function U(a){for(var c,b=a.length;1<b;)switch((c=a[--b]).i){case 3:c.H&&c.H.apply(c,g(c.h));break;case 4:c.h=E;break;case 7:ra(c);break;case 12:U(c.u)}}
function pa(a,c,b){var d="object"===typeof a[0],e=T();e.fa||(a[0]!==F&&["object","string","number"].includes(e.fa=typeof a[0])||L("item type invalid"),d&&(!["string","number"].includes(e.ia=typeof a[0].id)&&L("item id type invalid"),e.keys=J(a[0]).join(",")));for(var p=f(a),h=p.next();!h.done;h=p.next())h=h.value,h===F&&L("item is null"),typeof h!==e.fa&&L("item type changed"),d&&(typeof h.id!==e.ia&&L("item id type changed"),J(h).join(",")!==e.keys&&L("item keys differ of "+h.id));a=f(a);for(h=a.next();!h.done;h=
a.next())e=h.value,p=d?e.id:e,p in c&&L("item key not unique: "+p),c[p]=e,b.push(p);return d}function qa(a,c,b){if(a.j)return c.insertBefore(a.j,b),a.j;if(a.m){var d=a.l.length;do a.l[--d]&&(b=qa(a.l[d],c,b));while(0<d)}return b}function sa(a){for(;0!==a[0].i;){if(!a[0].W.G)return F;a[0].W.G=H;a=a[0].V}return a[0].T}function V(a){return(a=sa(a))&&!a.D&&(a.D=G,y[a.v]?y[a.v].push(a):y[a.v]=[a],w||W())}function ta(){N(F,H,F);var a=sa(q);a&&(a.D=G,C[a.v]?C[a.v].push(a):C[a.v]=[a])}
function ua(a,c){N(3,H,c);if(r>=q.length)q[r]={i:3,B:Q(c),h:c=c||E,H:a.apply(null,g(c))||F};else if(c){var b=q[r];b.B(b.h,c)&&(b.H&&b.H.apply(b,g(b.h)),b.H=a.apply(null,g(b.h=c))||F)}q[r].H&&q[r].H.then&&L("effect function must be synchronous");++r}function va(a){N(5,H,F);if(r<q.length)return q[r++].g;var c=q,b=[a,function(d){b[0]!==d&&(b[0]=d,V(c))},function(){return b[0]}];q[r++]={i:5,g:b};return b}function T(a){return N(6,H,F),(r<q.length?q[r++]:q[r++]={i:6,g:void 0===a?{}:a}).g}
function wa(a,c){return N(8,H,c),r>=q.length?(q[r++]={i:8,B:Q(c),h:c=c||E,g:a.apply(null,g(c))}).g:c&&q[r].B(q[r].h,c)?q[r].g=a.apply(null,g(q[r++].h=c)):q[r++].g}function P(a,c){return N(9,H,F),r<q.length?(c=q[r].g,q[r++].g=a):q[r++]={i:9,g:a},c}function xa(a,c){return a=setTimeout(function(){return c(G)},a),function(){return clearTimeout(a)}}function ra(a){for(var c=f(a.Y),b=c.next();!b.done;b=c.next())U(a.N[b.value])}function ya(a,c,b){return{$:b.aa,ga:a,Z:u,ea:l?u:u+c}}
function X(a){"object"===typeof a&&a||L("object required");var c=P(a,F);return c?oa(c,a):J(a)}
function Y(a){O(!a,"attributes presence");var c=k.j;if(a){for(var b=f(X(a)),d=b.next();!d.done;d=b.next())switch(d=d.value,1<d.length&&d.charAt(0).toLowerCase()!==d.charAt(0)&&L("capital prop: "+d),d.charCodeAt(0)){case 70:"object"===typeof a.F&&a.F||L("invalid css flags");c.className=J(a.F).filter(function(e){return a.F[e]}).join(" ");continue;case 82:"function"!==typeof a.R&&L("invalid ref"),a.R(c);case 67:case 83:continue;default:97>d.charCodeAt(0)&&L("invalid prop: "+d),c[d]=a[d]}O(!a.S,"style presence");
if(a.S)for(b=f(X(a.S)),d=b.next();!d.done;d=b.next())d=d.value,c.style[d]=a.S[d]}return c}function Z(a,c,b){return"string"===typeof a&&L("component expected, use node_dom instead"),b&&b.constructor!==I&&L("invalid childs type"),{A:a,o:c?b?(c.C=b,c):c:b?{C:b}:F}}
function W(){l=0>=u;u=ka.now();w=G;v=0;for(var a,c=0;(a=y).length;){10<++c&&L("rerender loop detected");y=[];a=f(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value){b=f(b);for(var d=b.next();!d.done;d=b.next())if(k=d.value,k.D){if(k.j)R(F,F);else{var e,p=F;d=k.m;for(var h=k,m=k;!(e=(h=h.J).j););do for(var t=m.L,n=(m=m.J).l,z=n.length;++t<z&&n[t]&&!(p=n[t].m););while(!p&&m!==h);m=k;R(e,p);if(m.m!==d)for(;!(m=m.J).j;){d=F;e=f(m.l);for(p=e.next();!(p.done||(p=p.value)&&(d=p.m));p=e.next());if(d===
m.m)break;m.m=d}}l=H}}}w=H;k=q=F;C.length&&(y=C,C=a,za())}function za(){return v||(v=requestAnimationFrame(W))}
function Aa(a){var c=D[a];if(!c){var b=a.indexOf("[");c=0>b?a.substr(0):a.substr(0,b);(0===c.length||c!==c.toLowerCase()||c.includes(" ")||c.includes("#")||c.includes("."))&&L("dom: invalid tag");D[a]=c=ha.createElement(c);if(0<b)for(!a.endsWith("]")&&L("dom: ] missing"),a=f(a.substring(b+1,a.length-1).split("][")),b=a.next();!b.done;b=a.next()){b=b.value;!b&&L("dom: empty attribute");(b.includes("[")||b.includes("]"))&&L("dom: attributes screwed up");var d=b.indexOf("=");b.includes(" ")&&(0>d||b.indexOf(" ")<
d)&&L("dom: space in attribute name");0<d?c[b.substr(0,d)]=b.substr(d+1):c[b]=G}}return c}function Ba(a){var c=ba[a];if(!c){var b=Aa(a);ba[a]=c=function(d){return l&&(k.j=b.cloneNode(G)),Y(d),d&&d.C||F};c.name_="$"+a}return c}ia.onerror=function(){return k&&la("error"),y=C=[]};define({defer:function(){return k&&L("defer while rendering"),w=G,za()},defer_end:function(){return k&&L("defer_end while rendering"),w||L("nothing was deferred"),cancelAnimationFrame(v),W()},hook_assert:function(a){N(F,H,F);if(!a)throw D;},hook_async:function(a,c,b){N(4,H,c);var d;if((r<q.length?(d=q[r++],H):d=q[r++]={i:4,B:Q(c),h:c||E,g:F})||c&&d.B(d.h,c)&&(d.h=c)){void 0!==b&&(d.g=b);var e=q;a.apply(null,g(d.h)).then(function(p){return d.g!==p&&d.h===c&&(d.g=p,V(e))})}return d.g},hook_callback:function(a,
c){var b=T();b.h&&ma(b.h,c);b.h=c;return b.ha||(b.ha=function(d){for(var e=[],p=0;p<arguments.length;++p)e[p]=arguments[p];return a.apply(null,[].concat(g(b.h),g(e)))})},hook_delay:function(a){var c=f(va(H)),b=c.next().value;c=c.next().value;ua(xa,[a,c]);return b},hook_dom:function(a,c){return N(F,G,F),k.j?l&&L("hook_dom called twice"):l||L("hook_dom skipped before"),c&&(c.C&&L("hook_dom cannot have childs"),c.R&&L("hook_dom cannot have a ref")),l&&(k.j=Aa(a).cloneNode(G)),Y(c||F)},hook_effect:ua,
hook_first:function(){return N(F,H,F),l},hook_map:function(a,c,b){N(7,H,b);var d=F,e=G;if(r<q.length)if((d=q[r]).U!==a)ra(d),d=F;else if(!d.G||b&&d.B(d.h,b))d.h=b||E,d.G=G;else{if(c===d.O)return++r,d.g;e=H}var p=l,h=q,m=++r,t={},n=[],z=0<c.length&&pa(c,t,n);0===c.length&&T();if(d){if(d.g=[],d.O!==c)for(d.O=c,c=f(d.Y),b=c.next();!b.done;b=c.next())b=b.value,b in t||(U(d.N[b]),delete d.N[b])}else q[m-1]=d={i:7,B:Q(b),h:b||E,g:[],G:G,U:a,X:z?K(c[0]):F,Y:[],N:{},O:c};c=f(n);for(b=c.next();!b.done;b=c.next()){b=
b.value;var A=d.N[b];if(l=!A)d.N[b]=A=[{i:1,V:h,W:d,K:F,g:F}];if(e||l||(z?d.X(t[b],A[0].K):t[b]!==A[0].K)){q=A;r=1;try{A[0].g=a.apply(null,[A[0].K=t[b]].concat(g(d.h)))}catch(x){if(x!==D)throw x;}q=h}d.g.push(A[0].g)}l=p;q=h;r=m;d.Y=n;return d.g},hook_memo:wa,hook_object_changes:X,hook_prev:P,hook_reducer:function(a){N(10,H,F);a&&a.constructor!==I&&L("actions array required");"function"===typeof a&&L("array required, use hook_reducer_f instead");if(r<q.length)return q[r++].g;var c=q,b=[a[0](F),function(d,
e){d=a[d](b[0],e);b[0]!==d&&(b[0]=d,V(c))}];q[r++]={i:10,g:b};return b},hook_reducer_f:function(a,c){N(11,H,F);"function"!==typeof a&&L("reducer function required");c&&"function"!==typeof c&&L("initializer must be a function");if(r<q.length)return q[r++].g;var b=q,d=[c?c():F,function(e){e=a(d[0],e);d[0]!==e&&(d[0]=e,V(b))}];q[r++]={i:11,g:d};return d},hook_rerender:ta,hook_state:va,hook_static:T,hook_sub:function(a,c){N(12,H,c);var b=F;if(r<q.length)if((b=q[r]).U!==a)U(b.u),b=F;else if(!b.G||c&&b.B(b.h,
c))c&&(b.h=c),b.G=G;else return++r,b.g;var d=l,e=q,p=r;if(l=!b)(q[r]=b={i:12,B:Q(c),h:c||E,g:F,U:a,G:G,u:[]}).u[0]={i:2,V:q,W:b};q=b.u;r=1;try{b.g=a.apply(null,g(b.h))}catch(h){if(h!==D)throw h;}l=d;q=e;r=p+1;return b.g},hook_transition:function(a,c){var b=T({aa:a});a=wa(ya,[a,c,b]);return b.aa=a.ea<=u?a.ga:(ta(),a.Z===u?a.$:a.$+(a.ga-a.$)*(u-a.Z)/(a.ea-a.Z))},init:function(a,c){function b(){return(!(d=a())||2!==d.length)&&L("root component must return [props, childs]"),O(!d[0],"attributes presence"),
d[0]!==F&&("object"!==typeof d[0]&&L("invalid props type"),M(P(d[0],d[0]),d[0]),d[0].C&&L("root childs must be in second return value")),Y(d[0]),d[1]}(k||y.length||C.length)&&L("init called more than once");"function"!==typeof a&&L("init function requires root component");c||L("root element must be specified");var d;c.innerHTML="";b.name_="$root";(k={s:{A:b,o:F},P:F,J:F,v:0,L:0,u:[],l:F,j:c,m:c,D:G}).u[0]={i:0,T:k};y[0]=[k];k=q=F;W()},node:Z,node_dom:function(a,c,b){return Z(Ba(a),c,b)},node_map:function(a,
c,b){return Z(K,{A:a,O:c,o:b||F})},now:function(){return u}})})()