"use strict";/*
 lui.js web framework 2.2.2
 inspired by react and mithril
 l3p3.de 2025
*/
(function(){function ba(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function e(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:ba(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function f(a){if(!(a instanceof Array)){a=e(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
function h(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};var k=null,q=!k,t=k,u=0,w=0,x=0,z=!q,A=[],D=[],E={},ca={},da={},ea=[],F=[],fa={},G=k,H=q,I=z,ha=/[A-Z]/g,J=Array,K=Object,M=K.assign,N=K.keys,ia=K.values||(K.values=function(a){var b=[],c;for(c in a)b.push(a[c]);return b}),ja=K.freeze||function(a){return a},ka=K.isFrozen||function(a){return a===G||typeof a!=="object"},la=document,ma=window,na=ma.performance||Date;
function oa(a){return a===void 0&&O("model state must not contain undefined, missing return?"),ka(a)||(ja(a).constructor!==J&&(a.constructor!==K&&O("model state must not contain shit like "+a.constructor.name),a=ia(a)),a.forEach(oa))}function pa(a){a=a.u.B;return a===P?"list":a.name_||a.name||"?"}
function Q(){var a=[],b=t,c=G;if(t){for(a[0]="$"+(u-1);b[0].j!==0;)a.unshift(b[0].j===1?"hook_map["+(typeof b[0].L==="object"?b[0].L.id:b[0].L)+"]":"hook_sub"),b=b[0].Y;b=b[0].W}for(;b;)a.unshift(pa(b)+(c!==G?":"+c:"")),c=b.U,b=b.K;return a.join("/")||"-"}function qa(){console.log.apply(console,f(h.apply(0,arguments)))}function ra(a){var b=h.apply(1,arguments);qa.apply(null,["lui "+Q()+": "+a].concat(f(b)))}function O(a){throw Error("lui: "+a);}
function ta(a){qa("lui "+a+": error in callback");k=G}function R(a,b,c){try{return a.apply(null,f(b))}catch(d){throw ta(c),d;}}function ua(a,b){a===b||a&&b&&JSON.stringify(N(a))===JSON.stringify(N(b))||O("object keys mismatch")}
function S(a,b,c){t||O("hook called outside of hook context");c&&(c.constructor!==J&&O("deps must be in an array"),c.length===0&&O("deps must not be empty"));b&&t[0].j!==0&&O("hook called outside of component rendering");a!==G&&u<t.length&&(t[u].j!==a&&O("inconsistent hook order"),t[u].h&&wa(t[u].h,c))}function T(a,b){S(G,I,G);a!==U(a,a)&&O(b+" changed between renderings")}function wa(a,b){b?a.length!==b.length&&O("deps length changed"):a.length>0&&O("deps presence changed")}
function xa(a){return new Function("a","b","return a!==b&&("+a.join("||")+")")}function V(a){var b=(a=N(a)).join(",");return da[b]||(a.length===0&&O("object empty"),a.some(function(c){return(c.includes("-")||"0123456789".includes(c.charAt(0)))&&O("invalid key: "+c)}),da[b]=xa(a.map(function(c){return"a."+c+"!==b."+c})))}function ya(a,b){return ua(a,b),a===b?F:N(a).filter(function(c){return a[c]!==b[c]})}
function W(a){return a?(a.length===0&&O("deps must not be empty"),ea[a.length]||(ea[a.length]=xa(a.map(function(b,c){return"a["+c+"]!==b["+c+"]"})))):G}
function P(a,b){var c=k,d=b,l=c.A+1;t=c.v;u=1;c.H=I;if(c.u.B!==P){var g=G;try{g=(0,c.u.B)(c.u.o||fa)}catch(sa){if(sa!==E)throw sa;}var p=c.i;typeof g!=="object"&&O("components need to return child list or null");if(g){p&&(a=p,b=G);var n=g.length,m;typeof n!=="number"&&O("childs must be returned in a list");n===0&&O("returned childs list empty");c.l&&n!==c.l.length&&O("returned childs count changed");var v=c.l||(c.l=(new J(n)).fill(G));do{var r=v[--n];if((m=g[n])&&m!==H){k.A===0&&m.length!=G&&O("root component signature changed, see https://github.com/L3P3/lui/issues/53");
!m.B&&O("invalid node type at "+n);r&&r.u.B!==m.B&&O("node type changed at "+n);if(q=!r)v[n]=k=r={u:m,V:m.o&&V(m.o),K:c,A:l,U:n,v:[],l:G,i:G,m:G,H:I},k.v[0]={j:0,W:r},P(a,b),r.i&&a.insertBefore(r.m=r.i,b);else if(ua(r.u.o,m.o),m.o&&r.V(r.u.o,m.o))(k=r).u=m,P(a,b);r.m&&(b=r.m)}else r&&(X(r,a),v[n]=G)}while(n>0)}else if(c.l){l=e(c.l);for(g=l.next();!g.done;g=l.next())(g=g.value)&&X(g,a);c.l=G}p||(c.m=b!==d?b:G)}else{g=c.u.o;p=g.B;var y=g.T;g=g.o;typeof y==="object"&&y&&y.constructor===J||O("list_data must be an array");
typeof g!=="object"&&O("props must be an object");T(p,"item component");T(g&&N(g).join(","),"common props");n=y.length;r=H;if(!(U(n,n)+n<=0)){m=Y();v={};var L=[];y=n>0&&za(y,v,L);n||Y();if(m.N){r=g&&m.V(g,m.fa);for(var aa=e(m.ea),B=aa.next();!B.done;B=aa.next())B=B.value,B in v||(X(m.N[B],a),delete m.N[B]);m.fa=g;m.ea=L}else m.N={},m.$=y?V(v[L[0]]):G,m.ea=L,m.V=(m.fa=g)&&V(g);for(aa=c.l=new J(n);n>0;){B=L[--n];var C=m.N[B];if(q=!C)m.N[B]=k=C={u:{B:p,o:M({I:v[B]},g)},V:G,K:c,A:l,U:n,v:[],l:G,i:G,m:G,
H:I},k.v[0]={j:0,W:C},P(a,b),C.i&&a.insertBefore(C.m=C.i,b);else{var va=Aa(C);va&&va.nextSibling!==b&&Ba(C,a,b);if(r||y&&m.$(v[B],C.u.o.I))(k=C).u.o=M({I:v[B]},g),P(a,b)}(aa[C.U=n]=C).m&&(b=C.m)}c.m=b!==d?b:G}}}function X(a,b){b&&a.i&&(b.removeChild(a.i),b=G);if(a.l)for(var c=e(a.l),d=c.next();!d.done;d=c.next())(d=d.value)&&X(d,b);Z(a.v);if(a.H){var l,g;(!(g=A[l=a.A])||(l=g.indexOf(a))<0)&&(!(g=D[l])||(l=g.indexOf(a))<0)||g.splice(l,1)}}
function Z(a){for(var b,c=a.length;c>1;)switch((b=a[--c]).j){case 3:b.M&&b.M.apply(b,f(b.h));break;case 4:b.h=F;break;case 7:Ca(b);break;case 11:Z(b.v)}}
function za(a,b,c){var d=typeof a[0]==="object",l=Y();l.ha||(a[0]!==G&&["object","string","number"].includes(l.ha=typeof a[0])||O("item type invalid"),d&&(!["string","number"].includes(l.ka=typeof a[0].id)&&O("item id type invalid"),l.keys=N(a[0]).join(",")));for(var g=e(a),p=g.next();!p.done;p=g.next())p=p.value,p===G&&O("item is null"),typeof p!==l.ha&&O("item type changed"),d&&(typeof p.id!==l.ka&&O("item id type changed"),N(p).join(",")!==l.keys&&O("item keys differ of "+p.id));a=e(a);for(l=a.next();!l.done;l=
a.next())l=l.value,g=d?l.id:l,g in b&&O("item key not unique: "+g),b[g]=l,c.push(g);return d}function Aa(a){if(a.i)return a.i;var b;a=(b=a.l)?b.length:0;for(var c,d;a>0;)if((d=b[--a])&&(c=Aa(d)))return c;return G}function Ba(a,b,c){if(a.i)return b.insertBefore(a.i,c);if(a.m){var d=a.l.length;do a.l[--d]&&(c=Ba(a.l[d],b,c));while(d>0)}return c}function Da(a){for(;a[0].j!==0;){if(!a[0].Z.J)return G;a[0].Z.J=I;a=a[0].Y}return a[0].W}function Ea(a){return(a=Da(a))&&Fa(a)}
function Fa(a){return!a.H&&(a.H=H,A[a.A]?A[a.A].push(a):A[a.A]=[a],z||Ga())}function Ha(){S(G,I,G);var a=Da(t);a&&(a.H=H,D[a.A]?D[a.A].push(a):D[a.A]=[a])}function Ia(a,b){S(3,I,b);if(u>=t.length)t[u]={j:3,G:W(b),h:b=b||F,M:a.apply(null,f(b))||G};else if(b){var c=t[u];c.G(c.h,b)&&(c.M&&c.M.apply(c,f(c.h)),c.M=a.apply(null,f(c.h=b))||G)}var d;((d=t[u].M)==null?0:d.then)&&O("effect function must be synchronous");++u}
function Ja(a){S(5,I,G);if(u<t.length)return t[u++].g;var b=t,c=[a,function(d){c[0]!==d&&(c[0]=d,Ea(b))},function(){return c[0]}];t[u++]={j:5,g:c};return c}function Y(a){return S(6,I,G),(u<t.length?t[u++]:t[u++]={j:6,g:a===void 0?{}:a}).g}function Ka(a,b){return S(8,I,b),u>=t.length?(t[u++]={j:8,G:W(b),h:b=b||F,g:a.apply(null,f(b))}).g:b&&t[u].G(t[u].h,b)?t[u].g=a.apply(null,f(t[u++].h=b)):t[u++].g}function U(a,b){return S(9,I,G),u<t.length?(b=t[u].g,t[u++].g=a):t[u++]={j:9,g:a},b}
function La(a,b){return a=setTimeout(function(){return b(H)},a),function(){return clearTimeout(a)}}function Ca(a){for(var b=e(a.aa),c=b.next();!c.done;c=b.next())Z(a.O[c.value])}function Ma(a,b,c){return{ca:c.da,ia:a,ba:w,ga:q?w:w+b}}function Na(a){typeof a==="object"&&a||O("object required");var b=U(a,G);return b?ya(b,a):N(a)}
function Oa(a){T(!a,"attributes presence");var b=k.i;if(a){for(var c=e(Na(a)),d=c.next();!d.done;d=c.next()){d=d.value;d.length>1&&d.charAt(0).toLowerCase()!==d.charAt(0)&&O("capital prop: "+d);switch(d.charCodeAt(0)){case 70:typeof a.F==="object"&&a.F||O("invalid css flags");b.className=N(a.F).filter(function(l){return a.F[l]}).join(" ");continue;case 82:typeof a.R!=="function"&&O("invalid ref"),a.R(b);case 67:case 68:case 83:continue}d.charCodeAt(0)<97&&O("invalid prop: "+d);b[d]=a[d]}T(!a.D,"dataset presence");
if(a.D)for(c=e(Na(a.D)),d=c.next();!d.done;d=c.next())d=d.value,b.setAttribute("data-"+d.replace(ha,"-$&").toLowerCase(),a.D[d]);T(!a.S,"style presence");if(a.S)for(c=e(Na(a.S)),d=c.next();!d.done;d=c.next())d=d.value,b.style[d]=a.S[d]}return b}function Pa(a,b,c){return typeof a==="string"&&O("component expected, use node_dom instead"),c&&c.constructor!==J&&O("invalid childs type"),{B:a,o:b?c?(b.C=c,b):b:c?{C:c}:G}}
function Ga(){q=w<=0;w=na.now();x&&cancelAnimationFrame(x);z=H;x=0;for(var a,b=0;(a=A).length;){++b>10&&O("rerender loop detected");A=[];a=e(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value){c=e(c);for(var d=c.next();!d.done;d=c.next())if(k=d.value,k.H){if(k.i)P(G,G);else{var l,g=G;d=k.m;for(var p=k,n=k;!(l=(p=p.K).i););do for(var m=n.U,v=(n=n.K).l,r=v.length;++m<r&&v[m]&&!(g=v[m].m););while(!g&&n!==p);n=k;P(l,g);if(n.m!==d)for(;!(n=n.K).i;){d=G;l=e(n.l);for(g=l.next();!(g.done||(g=g.value)&&
(d=g.m));g=l.next());if(d===n.m)break;n.m=d}}q=I}}}z=I;k=t=G;D.length&&(A=D,D=a,Qa())}function Qa(){return x||(x=requestAnimationFrame(Ga))}
function Ra(a){var b=E[a];if(!b){a.startsWith("#")&&O("dom: unknown handle");var c=a.indexOf("[");b=c<0?a:a.substr(0,c);(b.length===0||b!==b.toLowerCase()||b.includes(" ")||b.includes("#")||b.includes("."))&&O("dom: invalid tag");E[a]=b=la.createElement(b);if(c>0)for(!a.endsWith("]")&&O("dom: ] missing"),a=e(a.substring(c+1,a.length-1).split("][")),c=a.next();!c.done;c=a.next()){c=c.value;!c&&O("dom: empty attribute");(c.includes("[")||c.includes("]"))&&O("dom: attributes screwed up");var d=c.indexOf("=");
c.includes(" ")&&(d<0||c.indexOf(" ")<d)&&O("dom: space in attribute name");d>0?b[c.substr(0,d)]=c.substr(d+1):b[c]=H}}return b}function Sa(a){a&&typeof a==="string"||O("dom: descriptor string expected");var b=ca[a];if(!b){var c=Ra(a);ca[a]=b=function(d){return q&&(k.i=c.cloneNode(H)),Oa(d),d&&d.C||G};b.name_="$"+a}return b}ma.onerror=function(){return k&&ra("error in component"),A=D=[],I};var Ta=J.prototype;
K.entries||(K.entries=function(a){var b=[],c;for(c in a)b.push([c,a[c]]);return b},Ta.fill||(Ta.fill=function(a){for(var b=this.length,c=0;c<b;++c)this[c]=a;return this}));define({defer:function(){return k&&O("defer while rendering"),z=H,Qa()},defer_end:function(){return k&&O("defer_end while rendering"),z||O("nothing was deferred"),Ga()},dom_define:function(a,b,c){E["#"+a]&&O("dom_define: handle exists");b=Ra(b);c&&(c&&(c.C&&O("dom_define cannot have childs"),c.R&&O("dom_define cannot have a ref")),b=b.cloneNode(H),c.D&&(M(b.dataset,c.D),delete c.D),c.S&&(M(b.style,c.S),delete c.S),M(b,c));E["#"+a]=b},hook_assert:function(a){S(G,I,G);if(!a)throw E;},hook_async:function(a,
b,c){S(4,I,b);var d,l=Q();if((u<t.length?(d=t[u++],I):d=t[u++]={j:4,G:W(b),h:b||F,g:G})||b&&d.G(d.h,b)&&(d.h=b)){c!==void 0&&(d.g=c);var g=t;a.apply(null,f(d.h)).then(function(p){return d.g!==p&&d.h===b&&(d.g=p,Ea(g))}).catch(function(p){ta(l);throw p;})}return d.g},hook_callback:function(a,b){var c=u>=t.length?Q():"";(b==null?0:b.length)||O("deps required, use hook_static instead");var d=Y();d.h&&wa(d.h,b);d.h=b;return d.ja||(d.ja=function(){var l=h.apply(0,arguments);return R(a,[].concat(f(d.h),
f(l)),c)})},hook_delay:function(a){var b=e(Ja(I)),c=b.next().value;b=b.next().value;Ia(La,[a,b]);return c},hook_dom:function(a,b){return S(G,H,G),k.i?q&&k.K&&O("hook_dom called twice"):q||O("hook_dom skipped before"),b&&(b.C&&O("hook_dom cannot have childs"),b.R&&O("hook_dom cannot have a ref")),k.i===G&&(k.i=Ra(a).cloneNode(H)),Oa(b||G)},hook_effect:Ia,hook_map:function(a,b,c){S(7,I,c);var d=G,l=H;if(u<t.length)if((d=t[u]).X!==a)Ca(d),d=G;else if(!d.J||c&&d.G(d.h,c))d.h=c||F,d.J=H;else{if(b===d.T)return++u,
d.g;l=I}var g=q,p=t,n=++u,m={},v=[],r=b.length>0&&za(b,m,v);b.length===0&&Y();if(d){if(d.g=[],d.T!==b)for(d.T=b,b=e(d.aa),c=b.next();!c.done;c=b.next())c=c.value,c in m||(Z(d.O[c]),delete d.O[c])}else t[n-1]=d={j:7,G:W(c),h:c||F,g:[],J:H,X:a,$:r?V(b[0]):G,aa:[],O:{},T:b};b=e(v);for(c=b.next();!c.done;c=b.next()){c=c.value;var y=d.O[c];if(q=!y)d.O[c]=y=[{j:1,Y:p,Z:d,L:G,g:G}];if(l||q||(r?d.$(m[c],y[0].L):m[c]!==y[0].L)){t=y;u=1;try{y[0].g=a.apply(null,[y[0].L=m[c]].concat(f(d.h)))}catch(L){if(L!==
E)throw L;}t=p}d.g.push(y[0].g)}q=g;t=p;u=n;d.aa=v;return d.g},hook_memo:Ka,hook_model:function(a){S(10,I,G);typeof a==="object"&&a||O("mutations object required");typeof a.init!=="function"&&O("init mutation required for initial value");if(u<t.length)return t[u++].g;var b=t,c=Q(),d=[R(a.init,[G],c+" -> #init"),{}];R(oa,[d[0]],c+" -> #init");for(var l=e(N(a)),g=l.next(),p={};!g.done;p={P:void 0},g=l.next())p.P=g.value,d[1][p.P]=function(n){return function(){var m=R(a[n.P],[d[0]].concat(f(h.apply(0,
arguments))),c+" -> #"+n.P);d[0]!==m&&(R(oa,[m],c+" -> #"+n.P),d[0]=m,Ea(b))}}(p);t[u++]={j:10,g:d};return d},hook_object_changes:Na,hook_prev:U,hook_rerender:Ha,hook_state:Ja,hook_static:Y,hook_sub:function(a,b){S(11,I,b);var c=G;if(u<t.length)if((c=t[u]).X!==a)Z(c.v),c=G;else if(!c.J||b&&c.G(c.h,b))b&&(c.h=b),c.J=H;else return++u,c.g;var d=q,l=t,g=u;if(q=!c)(t[u]=c={j:11,G:W(b),h:b||F,g:G,X:a,J:H,v:[]}).v[0]={j:2,Y:t,Z:c};t=c.v;u=1;try{c.g=a.apply(null,f(c.h))}catch(p){if(p!==E)throw p;}q=d;t=l;
u=g+1;return c.g},hook_transition:function(a,b){var c=Y({da:a});a=Ka(Ma,[a,b,c]);return c.da=a.ga<=w?a.ia:(Ha(),a.ba===w?a.ca:a.ca+(a.ia-a.ca)*(w-a.ba)/(a.ga-a.ba))},init:function(a,b,c){b=b===void 0?la.body:b;c=c===void 0?G:c;typeof a!=="function"&&O("no init function specified");b.innerHTML!=G||O("invalid component_ element");b._lui_used&&O("root element already mounted");b._lui_used=1;b.innerHTML="";b={u:{B:a,o:c},V:G,K:G,A:0,U:0,v:[],l:G,i:b,m:b,H:I};b.v[0]={j:0,W:b};a.name_="$root";k=t=G;Fa(b)},
node:Pa,node_dom:function(a,b,c){return Pa(Sa(a),b,c)},node_map:function(a,b,c){return Pa(P,{B:a,T:b,o:c||G})},now:function(){return w}})})()
