"use strict";/*
 lui.js web framework 2.2.2
 inspired by react and mithril
 l3p3.de 2025
*/
(function(){function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function g(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function h(a){if(!(a instanceof Array)){a=g(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
function ba(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};var k=null,p=!k,r=k,t=0,v=0,w=0,A=!p,B=[],C=[],D,E,F={},ca={},da={},ea=[],G=[],fa={},H=k,I=p,K=A,ha=/[A-Z]/g,ia=Array,L=Object,M=L.assign||(L.assign=function(a){for(var b=arguments,c=b.length,d=0,f,e;++d<c;)if(f=b[d])for(e in f)a[e]=f[e];return a}),N=L.keys||(L.keys=function(a){var b=[],c;for(c in a)b.push(c);return b});L.values||(L.values=function(a){var b=[],c;for(c in a)b.push(a[c]);return b});var ja=setTimeout,ka=clearTimeout,la=document,O=window,P=Date;
function ma(a){return new Function("a","b","return a!==b&&("+a.join("||")+")")}function Q(a){var b=(a=N(a)).join(",");return da[b]||(da[b]=ma(a.map(function(c){return"a."+c+"!==b."+c})))}function na(a,b){return a===b?G:N(a).filter(function(c){return a[c]!==b[c]})}function R(a){return a?ea[a.length]||(ea[a.length]=ma(a.map(function(b,c){return"a["+c+"]!==b["+c+"]"}))):H}
function S(a,b){var c=k,d=b,f=c.A+1;r=c.u;t=1;c.G=K;if(c.v.J!==S){var e=H;try{e=(0,c.v.J)(c.v.o||fa)}catch(Ka){}var l=c.i;if(e){l&&(a=l,b=H);var n=e.length,m,u=c.l||(c.l=(new ia(n)).fill(H));do{var q=u[--n];(m=e[n])&&m!==I?((p=!q)?(u[n]=k=q={v:m,O:m.o&&Q(m.o),K:c,A:f,T:n,u:[],l:H,i:H,j:H,G:K},k.u[0]={m:0,V:q},S(a,b),q.i&&a.insertBefore(q.j=q.i,b)):m.o&&q.O(q.v.o,m.o)&&((k=q).v=m,S(a,b)),q.j&&(b=q.j)):q&&(T(q,a),u[n]=H)}while(n>0)}else if(c.l){f=g(c.l);for(e=f.next();!e.done;e=f.next())(e=e.value)&&
T(e,a);c.l=H}l||(c.j=b!==d?b:H)}else{e=c.v.o;l=e.J;var x=e.N;e=e.o;n=x.length;q=I;if(!(oa(n,n)+n<=0)){m=U();u={};var J=[];x=n>0&&pa(x,u,J);if(m.L){q=e&&m.O(e,m.fa);for(var X=g(m.ea),y=X.next();!y.done;y=X.next())y=y.value,u[y]===void 0&&(T(m.L[y],a),delete m.L[y]);m.fa=e;m.ea=J}else m.L={},m.X=x?Q(u[J[0]]):H,m.ea=J,m.O=(m.fa=e)&&Q(e);for(X=c.l=new ia(n);n>0;){y=J[--n];var z=m.L[y];if(p=!z)m.L[y]=k=z={v:{J:l,o:M({I:u[y]},e)},O:H,K:c,A:f,T:n,u:[],l:H,i:H,j:H,G:K},k.u[0]={m:0,V:z},S(a,b),z.i&&a.insertBefore(z.j=
z.i,b);else{var ra=qa(z);ra&&ra.nextSibling!==b&&sa(z,a,b);if(q||x&&m.X(u[y],z.v.o.I))(k=z).v.o=M({I:u[y]},e),S(a,b)}(X[z.T=n]=z).j&&(b=z.j)}c.j=b!==d?b:H}}}function T(a,b){b&&a.i&&(b.removeChild(a.i),b=H);if(a.l)for(var c=g(a.l),d=c.next();!d.done;d=c.next())(d=d.value)&&T(d,b);V(a.u);if(a.G){var f,e;(!(e=B[f=a.A])||(f=e.indexOf(a))<0)&&(!(e=C[f])||(f=e.indexOf(a))<0)||e.splice(f,1)}}
function V(a){for(var b,c=a.length;c>1;)switch((b=a[--c]).m){case 1:b.P&&b.P.apply(b,h(b.h));break;case 2:b.h=G;break;case 3:ta(b);break;case 4:V(b.u)}}function pa(a,b,c){var d=typeof a[0]==="object";a=g(a);for(var f=a.next();!f.done;f=a.next()){f=f.value;var e=d?f.id:f;b[e]=f;c.push(e)}return d}function qa(a){if(a.i)return a.i;var b;a=(b=a.l)?b.length:0;for(var c,d;a>0;)if((d=b[--a])&&(c=qa(d)))return c;return H}
function sa(a,b,c){if(a.i)return b.insertBefore(a.i,c);if(a.j){var d=a.l.length;do a.l[--d]&&(c=sa(a.l[d],b,c));while(d>0)}return c}function ua(a){for(;a[0].m!==0;){if(!a[0].W.H)return H;a[0].W.H=K;a=a[0].da}return a[0].V}function va(a){return(a=ua(a))&&wa(a)}function wa(a){return!a.G&&(a.G=I,B[a.A]?B[a.A].push(a):B[a.A]=[a],A||xa())}function ya(){var a=ua(r);a&&(a.G=I,C[a.A]?C[a.A].push(a):C[a.A]=[a])}
function za(a,b){if(t>=r.length)r[t]={m:1,B:R(b),h:b=b||G,P:a.apply(null,h(b))||H};else if(b){var c=r[t];c.B(c.h,b)&&(c.P&&c.P.apply(c,h(c.h)),c.P=a.apply(null,h(c.h=b))||H)}++t}function Aa(a){if(t<r.length)return r[t++].g;var b=r,c=[a,function(d){c[0]!==d&&(c[0]=d,va(b))},function(){return c[0]}];r[t++]={m:0,g:c};return c}function U(a){return(t<r.length?r[t++]:r[t++]={m:0,g:a===void 0?{}:a}).g}
function Ba(a,b){return t>=r.length?(r[t++]={m:0,B:R(b),h:b=b||G,g:a.apply(null,h(b))}).g:b&&r[t].B(r[t].h,b)?r[t].g=a.apply(null,h(r[t++].h=b)):r[t++].g}function oa(a,b){return t<r.length?(b=r[t].g,r[t++].g=a):r[t++]={m:0,g:a},b}function Ca(a,b){return a=ja(function(){return b(I)},a),function(){return ka(a)}}function ta(a){for(var b=g(a.Z),c=b.next();!c.done;c=b.next())V(a.M[c.value])}function Da(a,b,c){return{ba:c.ca,ha:a,aa:v,ga:p?v:v+b}}function W(a){var b=oa(a,H);return b?na(b,a):N(a)}
function Ea(a){var b=k.i;if(a){for(var c=g(W(a)),d=c.next();!d.done;d=c.next()){d=d.value;switch(d){case "F":b.className=N(a.F).filter(function(f){return a.F[f]}).join(" ");continue;case "R":a.R(b);case "C":case "D":case "S":continue}b[d]=a[d]}if(a.D)for(c=g(W(a.D)),d=c.next();!d.done;d=c.next())d=d.value,b.setAttribute("data-"+d.replace(ha,"-$&").toLowerCase(),a.D[d]);if(a.S)for(c=g(W(a.S)),d=c.next();!d.done;d=c.next())d=d.value,b.style[d]=a.S[d]}return b}
function Fa(a,b,c){return{J:a,o:b?c?(b.C=c,b):b:c?{C:c}:H}}
function xa(){p=v<=0;v=P.now();w&&E(w);A=I;w=0;for(var a;(a=B).length;){B=[];a=g(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value){b=g(b);for(var c=b.next();!c.done;c=b.next())if(k=c.value,k.G){if(k.i)S(H,H);else{var d,f=H;c=k.j;for(var e=k,l=k;!(d=(e=e.K).i););do for(var n=l.T,m=(l=l.K).l,u=m.length;++n<u&&m[n]&&!(f=m[n].j););while(!f&&l!==e);l=k;S(d,f);if(l.j!==c)for(;!(l=l.K).i;){c=H;d=g(l.l);for(f=d.next();!(f.done||(f=f.value)&&(c=f.j));f=d.next());if(c===l.j)break;l.j=c}}p=K}}}A=K;C.length&&
(B=C,C=a,Ga())}function Ga(){return w||(w=D(xa))}var Ha=xa;function Ia(a){var b=F[a];if(!b){var c=a.indexOf("[");F[a]=b=la.createElement(c<0?a:a.substring(0,c));if(c>0)for(a=g(a.substring(c+1,a.length-1).split("][")),c=a.next();!c.done;c=a.next()){c=c.value;var d=c.indexOf("=");d>0?b[c.substring(0,d)]=c.substr(d+1):b[c]=I}}return b}function Ja(a){var b=ca[a];if(!b){var c=Ia(a);ca[a]=b=function(d){return p&&(k.i=c.cloneNode(I)),Ea(d),d&&d.C||H}}return b}var Y=ia.prototype,Z=String.prototype;D=O.requestAnimationFrame;
E=O.cancelAnimationFrame;
L.entries||(L.entries=function(a){var b=[],c;for(c in a)b.push([c,a[c]]);return b},Y.fill||(Y.fill=function(a){for(var b=this.length,c=0;c<b;++c)this[c]=a;return this},E||(D=(E=O.mozCancelAnimationFrame||O.webkitCancelAnimationFrame)?O.mozRequestAnimationFrame||O.webkitRequestAnimationFrame:(E=ka,function(a){return ja(a,20)}),P.now||(P.now=function(){return(new P).getTime()},Y.map||(Y.filter=function(a){for(var b=[],c=this.length,d=-1,f=0;f<c;++f)a(this[f],f)&&(b[++d]=this[f]);return b},Y.find=function(a){a=
this.findIndex(a);if(a>=0)return this[a]},Y.findIndex=Y.forEach=function(a){for(var b=this.length,c=0;c<b;++c)if(a(this[c],c))return c;return-1},Y.includes=Z.includes=function(a){return this.indexOf(a)>=0},Y.indexOf=function(a,b){b=b||0;for(var c=this.length;b<c;++b)if(this[b]===a)return b;return-1},Y.map=function(a){for(var b=[],c=this.length,d=0;d<c;++d)b[d]=a(this[d],d);return b},Y.some=function(a){return this.findIndex(a)>=0},Y.push||(Y.push=function(a){this[this.length]=a},Function.prototype.apply=
function(a,b){a==H?(O._=this,a=O):L.prototype._=this;switch(b?b.length:0){case 0:return a._();case 1:return a._(b[0]);case 2:return a._(b[0],b[1]);case 3:return a._(b[0],b[1],b[2]);case 4:return a._(b[0],b[1],b[2],b[3]);case 5:return a._(b[0],b[1],b[2],b[3],b[4]);default:return a._(b[0],b[1],b[2],b[3],b[4],b[5])}},Y.join||(Y.concat=function(){for(var a=arguments,b=this,c=[],d=a.length,f=b.length,e=0,l=0,n=-1;l<f;++l)c[++n]=b[l];for(;e<d;++e)for(f=(l=0,b=a[e]).length;l<f;++l)c[++n]=b[l];return c},
Y.join=function(a){for(var b="",c=this.length-1,d=0;d<c;++d)b+=this[d]+a;d<c+1&&(b+=this[d]);return b},Z.charAt=function(a){return this[a]},Z.indexOf=function(a,b){a=a[0];b=b||0;for(var c=this.length;b<c;++b)if(this[b]===a)return b;return-1},Z.split=function(a){for(var b=[],c=this.length,d=a.length,f=-1,e=0,l;(l=this.indexOf(a,e))>=0;e=l+d)b[++f]=this.substring(e,l);e<c&&(b[++f]=this.substr(e));return b},Z.substr=function(a){return this.substring(a,this.length)},Z.substring=function(a,b){for(var c=
"";a<b;++a)c+=this[a];return c})))))));O.lui={defer:function(){return A=I,Ga()},defer_end:Ha,dom_define:function(a,b,c){b=Ia(b);c&&(b=b.cloneNode(I),c.D&&(M(b.dataset,c.D),delete c.D),c.S&&(M(b.style,c.S),delete c.S),M(b,c));F["#"+a]=b},hook_assert:function(a){if(!a)throw F;},hook_async:function(a,b,c){var d;if((t<r.length?(d=r[t++],K):d=r[t++]={m:2,B:R(b),h:b||G,g:H})||b&&d.B(d.h,b)&&(d.h=b)){c!==void 0&&(d.g=c);var f=r;a.apply(null,h(d.h)).then(function(e){return d.g!==e&&d.h===b&&(d.g=e,va(f))})}return d.g},hook_callback:function(a,
b){var c=U();c.h=b;return c.ia||(c.ia=function(){var d=ba.apply(0,arguments);return a.apply(null,[].concat(h(c.h),h(d)))})},hook_delay:function(a){var b=g(Aa(K)),c=b.next().value;b=b.next().value;za(Ca,[a,b]);return c},hook_dom:function(a,b){return k.i===H&&(k.i=Ia(a).cloneNode(I)),Ea(b||H)},hook_effect:za,hook_map:function(a,b,c){var d=H,f=I;if(t<r.length)if((d=r[t]).U!==a)ta(d),d=H;else if(!d.H||c&&d.B(d.h,c))d.h=c||G,d.H=I;else{if(b===d.N)return++t,d.g;f=K}var e=p,l=r,n=++t,m={},u=[],q=b.length>
0&&pa(b,m,u);if(d){if(d.g=[],d.N!==b)for(d.N=b,b=g(d.Z),c=b.next();!c.done;c=b.next())c=c.value,m[c]===void 0&&(V(d.M[c]),delete d.M[c])}else r[n-1]=d={m:3,B:R(c),h:c||G,g:[],H:I,U:a,X:q?Q(b[0]):H,Z:[],M:{},N:b};b=g(u);for(c=b.next();!c.done;c=b.next()){c=c.value;var x=d.M[c];if(p=!x)d.M[c]=x=[{m:1,da:l,W:d,Y:H,g:H}];if(f||p||(q?d.X(m[c],x[0].Y):m[c]!==x[0].Y)){r=x;t=1;try{x[0].g=a.apply(null,[x[0].Y=m[c]].concat(h(d.h)))}catch(J){}}d.g.push(x[0].g)}p=e;r=l;t=n;d.Z=u;return d.g},hook_memo:Ba,hook_model:function(a){if(t<
r.length)return r[t++].g;for(var b=r,c=[(0,a.init)(H),{}],d=g(N(a)),f=d.next(),e={};!f.done;e={$:void 0},f=d.next())e.$=f.value,c[1][e.$]=function(l){return function(){var n=a[l.$].apply(null,[c[0]].concat(h(ba.apply(0,arguments))));c[0]!==n&&(c[0]=n,va(b))}}(e);r[t++]={m:0,g:c};return c},hook_object_changes:W,hook_prev:oa,hook_rerender:ya,hook_state:Aa,hook_static:U,hook_sub:function(a,b){var c=H;if(t<r.length)if((c=r[t]).U!==a)V(c.u),c=H;else if(!c.H||b&&c.B(c.h,b))b&&(c.h=b),c.H=I;else return++t,
c.g;var d=p,f=r,e=t;if(p=!c)(r[t]=c={m:4,B:R(b),h:b||G,g:H,U:a,H:I,u:[]}).u[0]={m:2,da:r,W:c};r=c.u;t=1;try{c.g=a.apply(null,h(c.h))}catch(l){}p=d;r=f;t=e+1;return c.g},hook_transition:function(a,b){var c=U({ca:a}),d=Ba(Da,[a,b,c]);return c.ca=d.ga<=v?d.ha:(ya(),d.aa===v?d.ba:d.ba+(d.ha-d.ba)*(v-d.aa)/(d.ga-d.aa))},init:function(a,b,c){b=b===void 0?la.body:b;c=c===void 0?H:c;b.innerHTML="";a={v:{J:a,o:c},O:H,K:H,A:0,T:0,u:[],l:H,i:b,j:b,G:K};a.u[0]={m:0,V:a};wa(a)},node:Fa,node_dom:function(a,b,c){return Fa(Ja(a),
b,c)},node_map:function(a,b,c){return Fa(S,{J:a,N:b,o:c||H})},now:function(){return v}}})()
