"use strict";/*
 lui.js web framework 2.4.1
 inspired by react and mithril
 l3p3.de 2025
*/
(function(){function aa(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}function f(a){var c=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(c)return c.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function h(a){if(!(a instanceof Array)){a=f(a);for(var c,b=[];!(c=a.next()).done;)b.push(c.value);a=b}return a}
function ba(){for(var a=Number(this),c=[],b=a;b<arguments.length;b++)c[b-a]=arguments[b];return c};var k=null,p=!k,r=k,t=0,v=0,x=0,z=!p,A=[],C=[],D={},ca={},da={},ea=[],E=[],fa={},F=k,H=p,I=z,ha=/[A-Z]/g,J=Array,K=Object,L=K.assign,M=K.keys;K.values||(K.values=function(a){var c=[],b;for(b in a)c.push(a[b]);return c});var ia=document,ja=window.performance||Date,ka=navigator.userAgent.indexOf("WebKit")<0;function la(a){return new Function("a","b","return a!==b&&("+a.join("||")+")")}function N(a){var c=(a=M(a)).join(",");return da[c]||(da[c]=la(a.map(function(b){return"a."+b+"!==b."+b})))}
function ma(a,c){return a===c?E:M(a).filter(function(b){return a[b]!==c[b]})}function O(a){return a?ea[a.length]||(ea[a.length]=la(a.map(function(c,b){return"a["+b+"]!==b["+b+"]"}))):F}
function P(a,c){var b=k,d=b.B+1,e=c;r=b.u;t=1;b.v=I;if(b.A.K!==P){var g=F;try{g=(0,b.A.K)(b.A.l||fa)}catch(Da){if(b.v)return}var m=b.i;if(g){m&&(a=m,e=F);var n=g.length,l,u=b.m||(b.m=(new J(n)).fill(F));do{var q=u[--n];(l=g[n])&&l!==H?((p=!q)?(u[n]=k=q={A:l,T:l.l&&N(l.l),L:b,B:d,ba:n,u:[],m:F,i:F,o:F,v:I,M:I},k.u[0]={j:0,V:q},P(a,e),q.i&&a.insertBefore(q.o=q.i,e)):l.l&&q.T(q.A.l,l.l)&&((k=q).A=l,P(a,e)),q.o&&(e=q.o)):q&&(Q(q,a),u[n]=F)}while(n>0)}else if(b.m){m&&(a=m);d=f(b.m);for(g=d.next();!g.done;g=
d.next())(g=g.value)&&Q(g,a);b.m=F}if(m)return}else{g=b.A.l;m=g.K;var w=g.P;g=g.l;n=w.length;q=H;l=R();u={};var G=[];w=n>0&&na(w,u,G);if(l.N){if(!(l.$.length|n))return;q=g&&l.T(g,l.ga);for(var S=f(l.$),y=S.next();!y.done;y=S.next())y=y.value,y in u||(Q(l.N[y],a),delete l.N[y]);l.ga=g;l.$=G}else{if(n===0)return;l.N={};l.X=w?N(u[G[0]]):F;l.$=G;l.T=(l.ga=g)&&N(g)}for(S=b.m=new J(n);n>0;){y=G[--n];var B=l.N[y];if(p=!B)l.N[y]=k=B={A:{K:m,l:L({I:u[y]},g)},T:F,L:b,B:d,ba:0,u:[],m:F,i:F,o:F,v:I,M:I},k.u[0]=
{j:0,V:B},P(F,F),a.insertBefore(B.i,e);else{if(q||w&&l.X(u[y],B.A.l.I))(k=B).A.l=L({I:u[y]},g),P(F,F);B.i.nextSibling!==e&&a.insertBefore(B.i,e)}e=(S[n]=B).i}}b.o=e!==c?e:F}function Q(a,c){c&&a.i&&(c.removeChild(a.i),c=F);if(c||a.M){if(a.m)for(var b=f(a.m),d=b.next();!d.done;d=b.next())(d=d.value)&&Q(d,c);a.M&&T(a.u)}if(a.v){var e,g;(!(g=A[e=a.B])||(e=g.indexOf(a))<0)&&(!(g=C[e])||(e=g.indexOf(a))<0)||g.splice(e,1)}}
function T(a){for(var c,b=a.length;b>1;)switch((c=a[--b]).j){case 1:c.J&&c.J.apply(c,h(c.h));break;case 2:c.h=E;break;case 3:oa(c);break;case 4:T(c.u)}}function na(a,c,b){var d=typeof a[0]==="object";a=f(a);for(var e=a.next();!e.done;e=a.next()){e=e.value;var g=d?e.id:e;c[g]=e;b.push(g)}return d}function pa(a){for(;a[0].j!==0;){if(!a[0].W.H)return F;a[0].W.H=I;a=a[0].fa}return a[0].V}function U(a){return(a=pa(a))&&qa(a)}function qa(a){return!a.v&&(a.v=H,A[a.B]?A[a.B].push(a):A[a.B]=[a],z||V())}
function W(){for(var a=k;a&&!a.M;)a.M=H,a=a.L}function ra(){var a=pa(r);a&&(a.v=H,C[a.B]?C[a.B].push(a):C[a.B]=[a])}function sa(a,c){if(t>=r.length)((r[t]={j:1,G:O(c),h:c=c||E,J:F}).J=a.apply(null,h(c))||F)&&W();else if(c){var b=r[t];b.G(b.h,c)&&(b.J&&b.J.apply(b,h(b.h)),b.J=F,(b.J=a.apply(null,h(b.h=c))||F)&&W())}++t}function ta(a){if(t<r.length)return r[t++].g;var c=r,b=[a,function(d){if(b[0]!==d&&(b[0]=d,U(c),r===c))throw D;return d},function(){return b[0]}];r[t++]={j:0,g:b};return b}
function R(a){return(t<r.length?r[t++]:r[t++]={j:0,g:a===void 0?{}:a}).g}function ua(a,c){return t>=r.length?(r[t++]={j:0,G:O(c),h:c=c||E,g:a.apply(null,h(c))}).g:c&&r[t].G(r[t].h,c)?r[t].g=a.apply(null,h(r[t++].h=c)):r[t++].g}function va(a,c){return t<r.length?(c=r[t].g,r[t++].g=a):r[t++]={j:0,g:a},c}function wa(a,c){return a=setTimeout(function(){return c(H)},a),function(){return clearTimeout(a)}}function oa(a){for(var c=f(a.Z),b=c.next();!b.done;b=c.next())T(a.O[b.value])}
function xa(a,c,b){return{da:b.ea,ia:a,ca:v,ha:p?v:v+c}}function X(a){var c=va(a,F);return c?ma(c,a):M(a)}
function ya(a){var c=k.i;if(a){for(var b=f(X(a)),d=b.next();!d.done;d=b.next()){d=d.value;switch(d.charCodeAt(0)){case 70:c.className=M(a.F).filter(function(e){return a.F[e]}).join(" ");continue;case 82:a.R(c);case 67:case 68:case 83:continue}c[d]=a[d]}if(a.D)for(b=f(X(a.D)),d=b.next();!d.done;d=b.next())d=d.value,c.setAttribute("data-"+d.replace(ha,"-$&").toLowerCase(),a.D[d]);if(a.S)for(b=f(X(a.S)),d=b.next();!d.done;d=b.next())d=d.value,c.style[d]=a.S[d]}return c}
function Y(a,c,b){return{K:a,l:c?b?(c.C=b,c):c:b?{C:b}:F}}
function V(){p=v<=0;v=ja.now();x&&cancelAnimationFrame(x);z=H;x=0;for(var a;(a=A).length;){A=[];a=f(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value){c=f(c);for(var b=c.next();!b.done;b=c.next())if(k=b.value,k.v){if(k.i)P(F,F);else{var d,e=F;b=k.o;for(var g=k,m=k;!(d=(g=g.L).i););do for(var n=m.ba,l=(m=m.L).m,u=l.length;++n<u&&l[n]&&!(e=l[n].o););while(!e&&m!==g);m=k;P(d,e);if(m.o!==b)for(;!(m=m.L).i;){b=F;d=f(m.m);for(e=d.next();!(e.done||(e=e.value)&&(b=e.o));e=d.next());if(b===m.o)break;m.o=
b}}p=I}}}z=I;C.length&&(A=C,C=a,za())}function za(){return x||(x=requestAnimationFrame(V))}var Aa=V;function Z(a){var c=D[a];if(!c){var b=a.indexOf("[");D[a]=c=ia.createElement(b<0?a:a.substr(0,b));if(b>0)for(a=f(a.substring(b+1,a.length-1).split("][")),b=a.next();!b.done;b=a.next()){b=b.value;var d=b.indexOf("="),e=b.substr(0,d);d<0?c[b]=H:ka||e!=="style"?c[e]=b.substr(d+1):c.setAttribute(e,b.substr(d+1))}}return c}
function Ba(a){var c=ca[a];if(!c){var b=Z(a);ca[a]=c=function(d){return p&&(k.i=b.cloneNode(H)),ya(d),d&&d.C||F}}return c}var Ca=J.prototype;K.entries||(K.entries=function(a){var c=[],b;for(b in a)c.push([b,a[b]]);return c},Ca.fill||(Ca.fill=function(a){for(var c=this.length,b=0;b<c;++b)this[b]=a;return this}));define({defer:function(){return z=H,za()},defer_end:Aa,dom_define:function(a,c,b){c=Z(c);b&&(c=c.cloneNode(H),b.D&&(L(c.dataset,b.D),delete b.D),b.S&&(L(c.style,b.S),delete b.S),L(c,b));D["#"+a]=c},hook_assert:function(a){if(!a)throw D;},hook_async:function(a,c,b){var d;if((t<r.length?(d=r[t++],I):(W(),d=r[t++]={j:2,G:O(c),h:c||E,g:F}))||c&&d.G(d.h,c)&&(d.h=c)){b!==void 0&&(d.g=b);var e=r;a.apply(null,h(d.h)).then(function(g){return d.g!==g&&d.h===c&&(d.g=g,U(e))})}return d.g},hook_callback:function(a,
c){var b=R();b.h=c;return b.ja||(b.ja=function(){var d=ba.apply(0,arguments);return a.apply(null,[].concat(h(b.h),h(d)))})},hook_delay:function(a){var c=f(ta(I)),b=c.next().value;c=c.next().value;sa(wa,[a,c]);return b},hook_dom:function(a,c){return k.i===F&&(k.i=Z(a).cloneNode(H)),ya(c||F)},hook_effect:sa,hook_map:function(a,c,b){var d=F,e=H;if(t<r.length)if((d=r[t]).U!==a)oa(d),d=F;else if(!d.H||b&&d.G(d.h,b))d.h=b||E,d.H=H;else{if(c===d.P)return++t,d.g;e=I}var g=p,m=r,n=++t,l={},u=[],q=c.length>
0&&na(c,l,u);if(d){if(d.g=[],d.P!==c)for(d.P=c,c=f(d.Z),b=c.next();!b.done;b=c.next())b=b.value,b in l||(T(d.O[b]),delete d.O[b])}else r[n-1]=d={j:3,G:O(b),h:b||E,g:[],H:H,U:a,X:q?N(c[0]):F,Z:[],O:{},P:c};c=f(u);for(b=c.next();!b.done;b=c.next()){b=b.value;var w=d.O[b];if(p=!w)d.O[b]=w=[{j:1,fa:m,W:d,Y:F,g:F}];if(e||p||(q?d.X(l[b],w[0].Y):l[b]!==w[0].Y)){r=w;t=1;try{w[0].g=a.apply(null,[w[0].Y=l[b]].concat(h(d.h)))}catch(G){if(k.v)throw G;}}d.g.push(w[0].g)}p=g;r=m;t=n;d.Z=u;return d.g},hook_memo:ua,
hook_model:function(a){if(t<r.length)return r[t++].g;for(var c=r,b=[(0,a.init)(F),{}],d=f(M(a)),e=d.next(),g={};!e.done;g={aa:void 0},e=d.next())g.aa=e.value,b[1][g.aa]=function(m){return function(){var n=a[m.aa].apply(null,[b[0]].concat(h(ba.apply(0,arguments))));if(b[0]!==n&&(b[0]=n,U(c),r===c))throw D;return n}}(g);r[t++]={j:0,g:b};return b},hook_object_changes:X,hook_prev:va,hook_rerender:ra,hook_state:ta,hook_static:R,hook_sub:function(a,c){var b=F;if(t<r.length)if((b=r[t]).U!==a)T(b.u),b=F;
else if(!b.H||c&&b.G(b.h,c))c&&(b.h=c),b.H=H;else return++t,b.g;var d=p,e=r,g=t;if(p=!b)(r[t]=b={j:4,G:O(c),h:c||E,g:F,U:a,H:H,u:[]}).u[0]={j:2,fa:r,W:b};r=b.u;t=1;try{b.g=a.apply(null,h(b.h))}catch(m){if(k.v)throw m;}p=d;r=e;t=g+1;return b.g},hook_transition:function(a,c){var b=R({ea:a});a=ua(xa,[a,c,b]);return b.ea=a.ha<=v?a.ia:(ra(),a.ca===v?a.da:a.da+(a.ia-a.da)*(v-a.ca)/(a.ha-a.ca))},init:function(a,c,b){c=c===void 0?ia.body:c;b=b===void 0?F:b;c.innerHTML="";a={A:{K:a,l:b},T:F,L:F,B:0,ba:0,u:[],
m:F,i:c,o:c,v:I,M:I};a.u[0]={j:0,V:a};qa(a)},node:Y,node_dom:function(a,c,b){return Y(Ba(a),c,b)},node_map:function(a,c,b){return Y(P,{K:a,P:c,l:b||F})},now:function(){return v}})})()
