"use strict";/*
 lui.js web framework 2.2.1
 inspired by react and mithril
 l3p3.de 2025
*/
(function(){function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function f(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function g(a){if(!(a instanceof Array)){a=f(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
function ba(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};var k=null,p=!k,r=k,t=0,v=0,z=0,A=!p,B=[],C=[],D={},ca={},da={},ea=[k,function(a,b){return a!==b&&a[0]!==b[0]},function(a,b){return a!==b&&(a[0]!==b[0]||a[1]!==b[1])},function(a,b){return a!==b&&(a[0]!==b[0]||a[1]!==b[1]||a[2]!==b[2])}],E=[],fa={},F=k,H=p,I=A,ha=/[A-Z]/g,J=Array,ja=Object,K=ja.assign,L=ja.keys,ka=document,la=window.performance||Date;function M(a){var b=(a=L(a)).join(",");return da[b]||(da[b]=a)}
function N(a,b,c){if(a===b)return!1;c=f(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,a[d]!==b[d])return!0;return!1}function ma(a,b){return a===b?E:L(a).filter(function(c){return a[c]!==b[c]})}function O(a){return a?a.length<5?ea[a.length]:na:F}function na(a,b){if(a===b)return!1;for(var c=0,d=a.length;c<d;++c)if(a[c]!==b[c])return!0;return!1}
function P(a,b){var c=k,d=b,h=c.A+1;r=c.u;t=1;c.G=I;if(c.v.J!==P){var e=F;try{e=(0,c.v.J)(c.v.o||fa)}catch(Fa){}var n=c.i;if(e){n&&(a=n,b=F);var m=e.length,l,u=c.l||(c.l=(new J(m)).fill(F));do{var q=u[--m];(l=e[m])&&l!==H?((p=!q)?(u[m]=k=q={v:l,O:l.o&&M(l.o),K:c,A:h,T:m,u:[],l:F,i:F,j:F,G:I},k.u[0]={m:0,V:q},P(a,b),q.i&&a.insertBefore(q.j=q.i,b)):l.o&&N(q.v.o,l.o,q.O)&&((k=q).v=l,P(a,b)),q.j&&(b=q.j)):q&&(Q(q,a),u[m]=F)}while(m>0)}else if(c.l){h=f(c.l);for(e=h.next();!e.done;e=h.next())(e=e.value)&&
Q(e,a);c.l=F}n||(c.j=b!==d?b:F)}else{e=c.v.o;n=e.J;var w=e.N;e=e.o;m=w.length;q=H;if(!(R(m,m)+m<=0)){l=T();u={};var G=[];w=m>0&&oa(w,u,G);if(l.L){q=e&&N(e,l.fa,l.O);for(var S=f(l.ea),x=S.next();!x.done;x=S.next())x=x.value,x in u||(Q(l.L[x],a),delete l.L[x]);l.fa=e;l.ea=G}else l.L={},l.X=w?M(u[G[0]]):F,l.ea=G,l.O=(l.fa=e)&&M(e);for(S=c.l=new J(m);m>0;){x=G[--m];var y=l.L[x];if(p=!y)l.L[x]=k=y={v:{J:n,o:K({I:u[x]},e)},O:F,K:c,A:h,T:m,u:[],l:F,i:F,j:F,G:I},k.u[0]={m:0,V:y},P(a,b),y.i&&a.insertBefore(y.j=
y.i,b);else{var ia=pa(y);ia&&ia.nextSibling!==b&&qa(y,a,b);if(q||w&&N(u[x],y.v.o.I,l.X))(k=y).v.o=K({I:u[x]},e),P(a,b)}(S[y.T=m]=y).j&&(b=y.j)}c.j=b!==d?b:F}}}function Q(a,b){b&&a.i&&(b.removeChild(a.i),b=F);if(a.l)for(var c=f(a.l),d=c.next();!d.done;d=c.next())(d=d.value)&&Q(d,b);U(a.u);if(a.G){var h,e;(!(e=B[h=a.A])||(h=e.indexOf(a))<0)&&(!(e=C[h])||(h=e.indexOf(a))<0)||e.splice(h,1)}}
function U(a){for(var b,c=a.length;c>1;)switch((b=a[--c]).m){case 1:b.P&&b.P.apply(b,g(b.h));break;case 2:b.h=E;break;case 3:ra(b);break;case 4:U(b.u)}}function oa(a,b,c){var d=typeof a[0]==="object";a=f(a);for(var h=a.next();!h.done;h=a.next()){h=h.value;var e=d?h.id:h;b[e]=h;c.push(e)}return d}function pa(a){if(a.i)return a.i;var b;a=(b=a.l)?b.length:0;for(var c,d;a>0;)if((d=b[--a])&&(c=pa(d)))return c;return F}
function qa(a,b,c){if(a.i)return b.insertBefore(a.i,c);if(a.j){var d=a.l.length;do a.l[--d]&&(c=qa(a.l[d],b,c));while(d>0)}return c}function sa(a){for(;a[0].m!==0;){if(!a[0].W.H)return F;a[0].W.H=I;a=a[0].da}return a[0].V}function V(a){return(a=sa(a))&&ta(a)}function ta(a){return!a.G&&(a.G=H,B[a.A]?B[a.A].push(a):B[a.A]=[a],A||W())}function ua(){var a=sa(r);a&&(a.G=H,C[a.A]?C[a.A].push(a):C[a.A]=[a])}
function va(a,b){if(t>=r.length)r[t]={m:1,B:O(b),h:b=b||E,P:a.apply(null,g(b))||F};else if(b){var c=r[t];c.B(c.h,b)&&(c.P&&c.P.apply(c,g(c.h)),c.P=a.apply(null,g(c.h=b))||F)}++t}function wa(a){if(t<r.length)return r[t++].g;var b=r,c=[a,function(d){c[0]!==d&&(c[0]=d,V(b))},function(){return c[0]}];r[t++]={m:0,g:c};return c}function T(a){return(t<r.length?r[t++]:r[t++]={m:0,g:a===void 0?{}:a}).g}
function xa(a,b){return t>=r.length?(r[t++]={m:0,B:O(b),h:b=b||E,g:a.apply(null,g(b))}).g:b&&r[t].B(r[t].h,b)?r[t].g=a.apply(null,g(r[t++].h=b)):r[t++].g}function R(a,b){return t<r.length?(b=r[t].g,r[t++].g=a):r[t++]={m:0,g:a},b}function ya(a,b){return a=setTimeout(function(){return b(H)},a),function(){return clearTimeout(a)}}function ra(a){for(var b=f(a.Z),c=b.next();!c.done;c=b.next())U(a.M[c.value])}function za(a,b,c){return{ba:c.ca,ha:a,aa:v,ga:p?v:v+b}}
function X(a){var b=R(a,F);return b?ma(b,a):L(a)}
function Aa(a){var b=k.i;if(a){for(var c=f(X(a)),d=c.next();!d.done;d=c.next()){d=d.value;switch(d.charCodeAt(0)){case 70:b.className=L(a.F).filter(function(h){return a.F[h]}).join(" ");continue;case 82:a.R(b);case 67:case 68:case 83:continue}b[d]=a[d]}if(a.D)for(c=f(X(a.D)),d=c.next();!d.done;d=c.next())d=d.value,b.setAttribute("data-"+d.replace(ha,"-$&").toLowerCase(),a.D[d]);if(a.S)for(c=f(X(a.S)),d=c.next();!d.done;d=c.next())d=d.value,b.style[d]=a.S[d]}return b}
function Y(a,b,c){return{J:a,o:b?c?(b.C=c,b):b:c?{C:c}:F}}
function W(){p=v<=0;v=la.now();z&&cancelAnimationFrame(z);A=H;z=0;for(var a;(a=B).length;){B=[];a=f(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value){b=f(b);for(var c=b.next();!c.done;c=b.next())if(k=c.value,k.G){if(k.i)P(F,F);else{var d,h=F;c=k.j;for(var e=k,n=k;!(d=(e=e.K).i););do for(var m=n.T,l=(n=n.K).l,u=l.length;++m<u&&l[m]&&!(h=l[m].j););while(!h&&n!==e);n=k;P(d,h);if(n.j!==c)for(;!(n=n.K).i;){c=F;d=f(n.l);for(h=d.next();!(h.done||(h=h.value)&&(c=h.j));h=d.next());if(c===n.j)break;n.j=
c}}p=I}}}A=I;C.length&&(B=C,C=a,Ba())}function Ba(){return z||(z=requestAnimationFrame(W))}var Ca=W;function Z(a){var b=D[a];if(!b){var c=a.indexOf("[");D[a]=b=ka.createElement(c<0?a:a.substr(0,c));if(c>0)for(a=f(a.substring(c+1,a.length-1).split("][")),c=a.next();!c.done;c=a.next()){c=c.value;var d=c.indexOf("=");d>0?b[c.substr(0,d)]=c.substr(d+1):b[c]=H}}return b}function Da(a){var b=ca[a];if(!b){var c=Z(a);ca[a]=b=function(d){return p&&(k.i=c.cloneNode(H)),Aa(d),d&&d.C||F}}return b}var Ea=J.prototype;
Ea.fill||(Ea.fill=function(a){for(var b=this.length,c=0;c<b;++c)this[c]=a;return this});define({defer:function(){return A=H,Ba()},defer_end:Ca,dom_define:function(a,b,c){b=Z(b);c&&(b=b.cloneNode(H),c.D&&(K(b.dataset,c.D),delete c.D),c.S&&(K(b.style,c.S),delete c.S),K(b,c));D["#"+a]=b},hook_assert:function(a){if(!a)throw D;},hook_async:function(a,b,c){var d;if((t<r.length?(d=r[t++],I):d=r[t++]={m:2,B:O(b),h:b||E,g:F})||b&&d.B(d.h,b)&&(d.h=b)){c!==void 0&&(d.g=c);var h=r;a.apply(null,g(d.h)).then(function(e){return d.g!==e&&d.h===b&&(d.g=e,V(h))})}return d.g},hook_callback:function(a,
b){var c=T();c.h=b;return c.ia||(c.ia=function(){var d=ba.apply(0,arguments);return a.apply(null,[].concat(g(c.h),g(d)))})},hook_delay:function(a){var b=f(wa(I)),c=b.next().value;b=b.next().value;va(ya,[a,b]);return c},hook_dom:function(a,b){return k.i===F&&(k.i=Z(a).cloneNode(H)),Aa(b||F)},hook_effect:va,hook_map:function(a,b,c){var d=F,h=H;if(t<r.length)if((d=r[t]).U!==a)ra(d),d=F;else if(!d.H||c&&d.B(d.h,c))d.h=c||E,d.H=H;else{if(b===d.N)return++t,d.g;h=I}var e=p,n=r,m=++t,l={},u=[],q=b.length>
0&&oa(b,l,u);if(d){if(d.g=[],d.N!==b)for(d.N=b,b=f(d.Z),c=b.next();!c.done;c=b.next())c=c.value,c in l||(U(d.M[c]),delete d.M[c])}else r[m-1]=d={m:3,B:O(c),h:c||E,g:[],H:H,U:a,X:q?M(b[0]):F,Z:[],M:{},N:b};b=f(u);for(c=b.next();!c.done;c=b.next()){c=c.value;var w=d.M[c];if(p=!w)d.M[c]=w=[{m:1,da:n,W:d,Y:F,g:F}];if(h||p||(q?N(l[c],w[0].Y,d.X):l[c]!==w[0].Y)){r=w;t=1;try{w[0].g=a.apply(null,[w[0].Y=l[c]].concat(g(d.h)))}catch(G){}}d.g.push(w[0].g)}p=e;r=n;t=m;d.Z=u;return d.g},hook_memo:xa,hook_model:function(a){if(t<
r.length)return r[t++].g;for(var b=r,c=[(0,a.init)(F),{}],d=f(L(a)),h=d.next(),e={};!h.done;e={$:void 0},h=d.next())e.$=h.value,c[1][e.$]=function(n){return function(){var m=a[n.$].apply(null,[c[0]].concat(g(ba.apply(0,arguments))));c[0]!==m&&(c[0]=m,V(b))}}(e);r[t++]={m:0,g:c};return c},hook_object_changes:X,hook_prev:R,hook_rerender:ua,hook_state:wa,hook_static:T,hook_sub:function(a,b){var c=F;if(t<r.length)if((c=r[t]).U!==a)U(c.u),c=F;else if(!c.H||b&&c.B(c.h,b))b&&(c.h=b),c.H=H;else return++t,
c.g;var d=p,h=r,e=t;if(p=!c)(r[t]=c={m:4,B:O(b),h:b||E,g:F,U:a,H:H,u:[]}).u[0]={m:2,da:r,W:c};r=c.u;t=1;try{c.g=a.apply(null,g(c.h))}catch(n){}p=d;r=h;t=e+1;return c.g},hook_transition:function(a,b){var c=T({ca:a});a=xa(za,[a,b,c]);return c.ca=a.ga<=v?a.ha:(ua(),a.aa===v?a.ba:a.ba+(a.ha-a.ba)*(v-a.aa)/(a.ga-a.aa))},init:function(a,b,c){b=b===void 0?ka.body:b;c=c===void 0?F:c;b.innerHTML="";a={v:{J:a,o:c},O:F,K:F,A:0,T:0,u:[],l:F,i:b,j:b,G:I};a.u[0]={m:0,V:a};ta(a)},node:Y,node_dom:function(a,b,c){return Y(Da(a),
b,c)},node_map:function(a,b,c){return Y(P,{J:a,N:b,o:c||F})},now:function(){return v}})})()
