'use strict';/*
 lui.js web frame work 2.1.1
 inspired by react and mithril
 L3P3.de 2024
*/
{let e=null,f=!e,g=e,h=0,n=0,t=0,w=!f,x=[],y=[];
const A={},aa={},ba={},ca=[],B=[],da={},C=e,D=f,E=w,F=Array,H=Object,I=H.assign,J=H.keys,ea=H.freeze,fa=H.isFrozen,ha=document,K=window,ia=K.performance||Date,ja=a=>(void 0===a&&L("model state must not contain undefined, missing return?"),fa(a)||(ea(a).constructor!==F&&(a.constructor!==H&&L("model state must not contain shit like "+a.constructor.name),a=H.values(a)),a.forEach(ja))),ka=({s:{A:a}})=>a===M?"list":a.name_||a.name||"?",N=()=>{const a=[];let b=g,c=C;if(g){for(a[0]="$"+(h-1);0!==b[0].j;)a.unshift(1===
b[0].j?`hook_map[${"object"===typeof b[0].K?b[0].K.id:b[0].K}]`:"hook_sub"),b=b[0].W;b=b[0].U}for(;b;)a.unshift(ka(b)+(c!==C?":"+c:"")),c=b.P,b=b.J;return a.join("/")||"-"},la=(...a)=>{console.log(...a)},ma=a=>{la("lui "+N()+": "+a)},L=a=>{throw Error("lui: "+a);},na=a=>{la("lui "+a+": error in callback");e=C},O=(a,b,c)=>{try{return a(...b)}catch(d){throw na(c),d;}},oa=(a,b)=>{a===b||a&&b&&JSON.stringify(J(a))===JSON.stringify(J(b))||L("object keys mismatch")},P=(a,b,c)=>{g||L("hook called outside of hook context");
c&&(c.constructor!==F&&L("deps must be in an array"),0===c.length&&L("deps must not be empty"));b&&0!==g[0].j&&L("hook called outside of component rendering");a!==C&&h<g.length&&(g[h].j!==a&&L("inconsistent hook order"),g[h].h&&pa(g[h].h,c))},R=(a,b)=>{P(C,E,C);a!==Q(a,a)&&L(b+" changed between renderings")},pa=(a,b)=>{b?a.length!==b.length&&L("deps length changed"):0<a.length&&L("deps presence changed")},qa=a=>new Function("a","b",`return a!==b&&(${a.join("||")})`),M=a=>{const b=(a=J(a)).join(",");
return ba[b]||(0===a.length&&L("object empty"),a.some(c=>(c.includes("-")||"0123456789".includes(c.charAt(0)))&&L("invalid key: "+c)),ba[b]=qa(a.map(c=>`a.${c}!==b.`+c)))},sa=(a,b)=>(oa(a,b),a===b?B:J(a).filter(c=>a[c]!==b[c])),U=a=>a?ca[a.length]||(0===a.length&&L("deps must not be empty"),ca[a.length]=qa(a.map((b,c)=>`a[${c}]!==b[${c}]`))):C,V=(a,b)=>{const c=e,d=b,p=c.v+1;g=c.u;h=1;c.G=E;if(c.s.A!==M){var l=C;try{l=(0,c.s.A)(c.s.o||da)}catch(S){if(S!==A)throw S;}var m=c.i;"object"!==typeof l&&
L("components need to return child list or null");if(l){m&&(a=m,b=C);var r=l.length,k;"number"!==typeof r&&L("childs must be returned in a list");0===r&&L("returned childs list empty");c.l&&r!==c.l.length&&L("returned childs count changed");var u=c.l||(c.l=(new F(r)).fill(C));do{var q=u[--r];if((k=l[r])&&k!==D){k.length!=C&&0===r&&0===e.v&&L("root component signature changed, see https://github.com/L3P3/lui/issues/53");!k.A&&L("invalid node type at "+r);q&&q.s.A!==k.A&&L("node type changed at "+r);
if(f=!q)u[r]=e=q={s:k,T:k.o&&M(k.o),J:c,v:p,P:r,u:[],l:C,i:C,m:C,G:E},e.u[0]={j:0,U:q},V(a,b),q.i&&a.insertBefore(q.m=q.i,b);else if(oa(q.s.o,k.o),k.o&&q.T(q.s.o,k.o))(e=q).s=k,V(a,b);q.m&&(b=q.m)}else q&&(W(q,a),u[r]=C)}while(0<r)}else if(c.l){for(r of c.l)r&&W(r,a);c.l=C}m||(c.m=b!==d?b:C)}else{r=c.s.o.A;var v=c.s.o.O;q=c.s.o.o;"object"===typeof v&&v&&v.constructor===F||L("list_data must be an array");"object"!==typeof q&&L("props must be an object");R(r,"item component");R(q&&J(q).join(","),"common props");
u=v.length;let S=D;if(!(0>=Q(u,u)+u)){k=X();l={};m=[];v=0<u&&ta(v,l,m);u||X();if(k.M){S=q&&k.T(q,k.da);for(var G of k.ca)G in l||(W(k.M[G],a),delete k.M[G]);k.da=q;k.ca=m}else k.M={},k.Y=v?M(l[m[0]]):C,k.ca=m,k.T=(k.da=q)&&M(q);for(G=c.l=new F(u);0<u;){const T=m[--u];let z=k.M[T];if(f=!z)k.M[T]=e=z={s:{A:r,o:I({I:l[T]},q)},T:C,J:c,v:p,P:u,u:[],l:C,i:C,m:C,G:E},e.u[0]={j:0,U:z},V(a,b),z.i&&a.insertBefore(z.m=z.i,b);else{const ra=ua(z);ra&&ra.nextSibling!==b&&va(z,a,b);if(S||v&&k.Y(l[T],z.s.o.I))(e=
z).s.o=I({I:l[T]},q),V(a,b)}(G[z.P=u]=z).m&&(b=z.m)}c.m=b!==d?b:C}}},W=(a,b)=>{b&&a.i&&(a.i.remove(),b=C);if(a.l)for(const c of a.l)c&&W(c,b);Y(a.u);if(a.G){let c,d;(!(d=x[c=a.v])||0>(c=d.indexOf(a)))&&(!(d=y[c])||0>(c=d.indexOf(a)))||d.splice(c,1)}},Y=a=>{let b,c=a.length;for(;1<c;)switch((b=a[--c]).j){case 3:b.L&&b.L(...b.h);break;case 4:b.h=B;break;case 7:wa(b);break;case 11:Y(b.u)}},ta=(a,b,c)=>{const d="object"===typeof a[0],p=X();p.fa||(a[0]!==C&&["object","string","number"].includes(p.fa=typeof a[0])||
L("item type invalid"),d&&(!["string","number"].includes(p.ia=typeof a[0].id)&&L("item id type invalid"),p.keys=J(a[0]).join(",")));for(const l of a)l===C&&L("item is null"),typeof l!==p.fa&&L("item type changed"),d&&(typeof l.id!==p.ia&&L("item id type changed"),J(l).join(",")!==p.keys&&L("item keys differ of "+l.id));for(const l of a)a=d?l.id:l,a in b&&L("item key not unique: "+a),b[a]=l,c.push(a);return d},ua=a=>{if(a.i)return a.i;let b;a=(b=a.l)?b.length:0;let c,d;for(;0<a;)if((d=b[--a])&&(c=
ua(d)))return c;return C},va=(a,b,c)=>{if(a.i)return b.insertBefore(a.i,c);if(a.m){let d=a.l.length;do a.l[--d]&&(c=va(a.l[d],b,c));while(0<d)}return c},xa=a=>{for(;0!==a[0].j;){if(!a[0].X.H)return C;a[0].X.H=E;a=a[0].W}return a[0].U},za=a=>(a=xa(a))&&ya(a),ya=a=>!a.G&&(a.G=D,x[a.v]?x[a.v].push(a):x[a.v]=[a],w||Aa()),Ba=()=>{P(C,E,C);const a=xa(g);a&&(a.G=D,y[a.v]?y[a.v].push(a):y[a.v]=[a])},Ca=(a,b)=>{P(3,E,b);if(h>=g.length)g[h]={j:3,B:U(b),h:b=b||B,L:a(...b)||C};else if(b){const c=g[h];c.B(c.h,
b)&&(c.L&&c.L(...c.h),c.L=a(...(c.h=b))||C)}g[h].L?.then&&L("effect function must be synchronous");++h},Da=a=>{P(5,E,C);if(h<g.length)return g[h++].g;const b=g,c=[a,d=>{c[0]!==d&&(c[0]=d,za(b))},()=>c[0]];g[h++]={j:5,g:c};return c},X=a=>(P(6,E,C),(h<g.length?g[h++]:g[h++]={j:6,g:void 0===a?{}:a}).g),Ea=(a,b)=>(P(8,E,b),h>=g.length?(g[h++]={j:8,B:U(b),h:b=b||B,g:a(...b)}).g:b&&g[h].B(g[h].h,b)?g[h].g=a(...(g[h++].h=b)):g[h++].g),Q=(a,b)=>(P(9,E,C),h<g.length?(b=g[h].g,g[h++].g=a):g[h++]={j:9,g:a},
b),Fa=(a,b)=>(a=setTimeout(()=>b(D),a),()=>clearTimeout(a)),wa=a=>{for(const b of a.Z)Y(a.N[b])},Ga=(a,b,c)=>({aa:c.ba,ga:a,$:n,ea:f?n:n+b}),Z=a=>{"object"===typeof a&&a||L("object required");const b=Q(a,C);return b?sa(b,a):J(a)},Ha=a=>{R(!a,"attributes presence");const b=e.i;if(a){for(const c of Z(a)){1<c.length&&c.charAt(0).toLowerCase()!==c.charAt(0)&&L("capital prop: "+c);switch(c.charCodeAt(0)){case 70:"object"===typeof a.F&&a.F||L("invalid css flags");b.className=J(a.F).filter(d=>a.F[d]).join(" ");
continue;case 82:"function"!==typeof a.R&&L("invalid ref"),a.R(b);case 67:case 68:case 83:continue}97>c.charCodeAt(0)&&L("invalid prop: "+c);b[c]=a[c]}R(!a.D,"dataset presence");if(a.D)for(const c of Z(a.D))b.dataset[c]=a.D[c];R(!a.S,"style presence");if(a.S)for(const c of Z(a.S))b.style[c]=a.S[c]}return b},Ia=(a,b,c)=>("string"===typeof a&&L("component expected, use node_dom instead"),c&&c.constructor!==F&&L("invalid childs type"),{A:a,o:b?c?(b.C=c,b):b:c?{C:c}:C}),Aa=()=>{f=0>=n;n=ia.now();t&&cancelAnimationFrame(t);
w=D;t=0;var a;let b=0;for(;(a=x).length;){10<++b&&L("rerender loop detected");x=[];for(const c of a)if(c)for(e of c)if(e.G){if(e.i)V(C,C);else{let d=C,p=e.m,l=e,m=e;for(;!(a=(l=l.J).i););do{let r=m.P;const {l:k}=m=m.J,u=k.length;for(;++r<u&&k[r]&&!(d=k[r].m););}while(!d&&m!==l);m=e;V(a,d);if(m.m!==p)for(;!(m=m.J).i;){p=C;for(const r of m.l)if(r&&(p=r.m))break;if(p===m.m)break;m.m=p}}f=E}}w=E;e=g=C;y.length&&(x=y,y=a,Ja())},Ja=()=>t||(t=requestAnimationFrame(Aa)),Ka=a=>{var b=A[a];if(!b){a.startsWith("#")&&
L("dom: unknown handle");const c=a.indexOf("[");b=0>c?a:a.substr(0,c);(0===b.length||b!==b.toLowerCase()||b.includes(" ")||b.includes("#")||b.includes("."))&&L("dom: invalid tag");A[a]=b=ha.createElement(b);if(0<c){!a.endsWith("]")&&L("dom: ] missing");for(const d of a.substring(c+1,a.length-1).split("]["))!d&&L("dom: empty attribute"),(d.includes("[")||d.includes("]"))&&L("dom: attributes screwed up"),a=d.indexOf("="),d.includes(" ")&&(0>a||d.indexOf(" ")<a)&&L("dom: space in attribute name"),0<
a?b[d.substr(0,a)]=d.substr(a+1):b[d]=D}}return b},La=a=>{a&&"string"===typeof a||L("dom: descriptor string expected");let b=aa[a];if(!b){const c=Ka(a);aa[a]=b=d=>(f&&(e.i=c.cloneNode(D)),Ha(d),d&&d.C||C);b.name_="$"+a}return b};K.onerror=()=>(e&&ma("error in component"),x=y=[],E);K.lui={defer:()=>(e&&L("defer while rendering"),w=D,Ja()),defer_end:()=>(e&&L("defer_end while rendering"),w||L("nothing was deferred"),Aa()),dom_define:(a,b,c)=>{A["#"+a]&&L("dom_define: handle exists");b=Ka(b);c&&(c&&(c.C&&L("dom_define cannot have childs"),c.R&&L("dom_define cannot have a ref")),b=b.cloneNode(D),c.D&&(I(b.dataset,c.D),delete c.D),c.S&&(I(b.style,c.S),delete c.S),I(b,c));A["#"+a]=b},hook_assert:a=>{P(C,E,C);if(!a)throw A;},hook_async:(a,b,c)=>{P(4,E,b);let d;const p=N();if((h<g.length?
(d=g[h++],E):d=g[h++]={j:4,B:U(b),h:b||B,g:C})||b&&d.B(d.h,b)&&(d.h=b)){void 0!==c&&(d.g=c);const l=g;a(...d.h).then(m=>d.g!==m&&d.h===b&&(d.g=m,za(l))).catch(m=>{na(p);throw m;})}return d.g},hook_callback:(a,b)=>{const c=h>=g.length?N():"";!b?.length&&L("deps required, use hook_static instead");const d=X();d.h&&pa(d.h,b);d.h=b;return d.ha||(d.ha=(...p)=>O(a,[...d.h,...p],c))},hook_delay:a=>{const [b,c]=Da(E);Ca(Fa,[a,c]);return b},hook_dom:(a,b)=>(P(C,D,C),e.i?f&&e.J&&L("hook_dom called twice"):
f||L("hook_dom skipped before"),b&&(b.C&&L("hook_dom cannot have childs"),b.R&&L("hook_dom cannot have a ref")),e.i===C&&(e.i=Ka(a).cloneNode(D)),Ha(b||C)),hook_effect:Ca,hook_map:(a,b,c)=>{P(7,E,c);let d=C,p=D;if(h<g.length)if((d=g[h]).V!==a)wa(d),d=C;else if(!d.H||c&&d.B(d.h,c))d.h=c||B,d.H=D;else{if(b===d.O)return++h,d.g;p=E}const l=f,m=g,r=++h,k={},u=[],q=0<b.length&&ta(b,k,u);0===b.length&&X();if(d){if(d.g=[],d.O!==b){d.O=b;for(const v of d.Z)v in k||(Y(d.N[v]),delete d.N[v])}}else g[r-1]=d=
{j:7,B:U(c),h:c||B,g:[],H:D,V:a,Y:q?M(b[0]):C,Z:[],N:{},O:b};for(const v of u){b=d.N[v];if(f=!b)d.N[v]=b=[{j:1,W:m,X:d,K:C,g:C}];if(p||f||(q?d.Y(k[v],b[0].K):k[v]!==b[0].K)){g=b;h=1;try{b[0].g=a(b[0].K=k[v],...d.h)}catch(G){if(G!==A)throw G;}g=m}d.g.push(b[0].g)}f=l;g=m;h=r;d.Z=u;return d.g},hook_memo:Ea,hook_model:a=>{P(10,E,C);"object"===typeof a&&a||L("mutations object required");"function"!==typeof a.init&&L("init mutation required for initial value");if(h<g.length)return g[h++].g;const b=g,c=
N(),d=[O(a.init,[C],c+" -> #init"),{}];O(ja,[d[0]],c+" -> #init");for(const p of J(a))d[1][p]=(...l)=>{l=O(a[p],[d[0],...l],c+" -> #"+p);d[0]!==l&&(O(ja,[l],c+" -> #"+p),d[0]=l,za(b))};g[h++]={j:10,g:d};return d},hook_object_changes:Z,hook_prev:Q,hook_rerender:Ba,hook_state:Da,hook_static:X,hook_sub:(a,b)=>{P(11,E,b);let c=C;if(h<g.length)if((c=g[h]).V!==a)Y(c.u),c=C;else if(!c.H||b&&c.B(c.h,b))b&&(c.h=b),c.H=D;else return++h,c.g;const d=f,p=g,l=h;if(f=!c)(g[h]=c={j:11,B:U(b),h:b||B,g:C,V:a,H:D,u:[]}).u[0]=
{j:2,W:g,X:c};g=c.u;h=1;try{c.g=a(...c.h)}catch(m){if(m!==A)throw m;}f=d;g=p;h=l+1;return c.g},hook_transition:(a,b)=>{const c=X({ba:a});a=Ea(Ga,[a,b,c]);return c.ba=a.ea<=n?a.ga:(Ba(),a.$===n?a.aa:a.aa+(a.ga-a.aa)*(n-a.$)/(a.ea-a.$))},init:(a,b=ha.body,c=C)=>{"function"!==typeof a&&L("no init function specified");b.innerHTML!=C||L("invalid component_ element");b._lui_used&&L("root element already mounted");b._lui_used=1;b.innerHTML="";b={s:{A:a,o:c},T:C,J:C,v:0,P:0,u:[],l:C,i:b,m:b,G:E};b.u[0]={j:0,
U:b};a.name_="$root";e=g=C;ya(b)},node:Ia,node_dom:(a,b,c)=>Ia(La(a),b,c),node_map:(a,b,c)=>Ia(M,{A:a,O:b,o:c||C}),now:()=>n}}