"use strict";/*
 lui.js web framework 2.2.1
 inspired by react and mithril
 l3p3.de 2025
*/
(function(){function aa(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}function f(a){var c=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(c)return c.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function g(a){if(!(a instanceof Array)){a=f(a);for(var c,b=[];!(c=a.next()).done;)b.push(c.value);a=b}return a}
function k(){for(var a=Number(this),c=[],b=a;b<arguments.length;b++)c[b-a]=arguments[b];return c};var p=null,r=!p,t=p,v=0,z=0,A=0,B=!r,C=[],D=[],E={},ba={},ca={},da=[],F=[],ea={},H=p,I=r,J=B,fa=/[A-Z]/g,K=Array,ha=Object,L=ha.assign,M=ha.keys,ia=document,ka=window.performance||Date;function la(a){return new Function("a","b","return a!==b&&("+a.join("||")+")")}function N(a){var c=(a=M(a)).join(",");return ca[c]||(ca[c]=la(a.map(function(b){return"a."+b+"!==b."+b})))}function ma(a,c){return a===c?F:M(a).filter(function(b){return a[b]!==c[b]})}
function O(a){return a?da[a.length]||(da[a.length]=la(a.map(function(c,b){return"a["+b+"]!==b["+b+"]"}))):H}
function P(a,c){var b=p,d=c,h=b.A+1;t=b.u;v=1;b.G=J;if(b.v.J!==P){var e=H;try{e=(0,b.v.J)(b.v.o||ea)}catch(Ea){}var n=b.i;if(e){n&&(a=n,c=H);var m=e.length,l,u=b.l||(b.l=(new K(m)).fill(H));do{var q=u[--m];(l=e[m])&&l!==I?((r=!q)?(u[m]=p=q={v:l,O:l.o&&N(l.o),K:b,A:h,T:m,u:[],l:H,i:H,j:H,G:J},p.u[0]={m:0,V:q},P(a,c),q.i&&a.insertBefore(q.j=q.i,c)):l.o&&q.O(q.v.o,l.o)&&((p=q).v=l,P(a,c)),q.j&&(c=q.j)):q&&(Q(q,a),u[m]=H)}while(m>0)}else if(b.l){h=f(b.l);for(e=h.next();!e.done;e=h.next())(e=e.value)&&
Q(e,a);b.l=H}n||(b.j=c!==d?c:H)}else{e=b.v.o;n=e.J;var w=e.N;e=e.o;m=w.length;q=I;if(!(S(m,m)+m<=0)){l=T();u={};var G=[];w=m>0&&na(w,u,G);if(l.L){q=e&&l.O(e,l.fa);for(var R=f(l.ea),x=R.next();!x.done;x=R.next())x=x.value,x in u||(Q(l.L[x],a),delete l.L[x]);l.fa=e;l.ea=G}else l.L={},l.X=w?N(u[G[0]]):H,l.ea=G,l.O=(l.fa=e)&&N(e);for(R=b.l=new K(m);m>0;){x=G[--m];var y=l.L[x];if(r=!y)l.L[x]=p=y={v:{J:n,o:L({I:u[x]},e)},O:H,K:b,A:h,T:m,u:[],l:H,i:H,j:H,G:J},p.u[0]={m:0,V:y},P(a,c),y.i&&a.insertBefore(y.j=
y.i,c);else{var ja=oa(y);ja&&ja.nextSibling!==c&&pa(y,a,c);if(q||w&&l.X(u[x],y.v.o.I))(p=y).v.o=L({I:u[x]},e),P(a,c)}(R[y.T=m]=y).j&&(c=y.j)}b.j=c!==d?c:H}}}function Q(a,c){c&&a.i&&(c.removeChild(a.i),c=H);if(a.l)for(var b=f(a.l),d=b.next();!d.done;d=b.next())(d=d.value)&&Q(d,c);U(a.u);if(a.G){var h,e;(!(e=C[h=a.A])||(h=e.indexOf(a))<0)&&(!(e=D[h])||(h=e.indexOf(a))<0)||e.splice(h,1)}}
function U(a){for(var c,b=a.length;b>1;)switch((c=a[--b]).m){case 1:c.P&&c.P.apply(c,g(c.h));break;case 2:c.h=F;break;case 3:qa(c);break;case 4:U(c.u)}}function na(a,c,b){var d=typeof a[0]==="object";a=f(a);for(var h=a.next();!h.done;h=a.next()){h=h.value;var e=d?h.id:h;c[e]=h;b.push(e)}return d}function oa(a){if(a.i)return a.i;var c;a=(c=a.l)?c.length:0;for(var b,d;a>0;)if((d=c[--a])&&(b=oa(d)))return b;return H}
function pa(a,c,b){if(a.i)return c.insertBefore(a.i,b);if(a.j){var d=a.l.length;do a.l[--d]&&(b=pa(a.l[d],c,b));while(d>0)}return b}function ra(a){for(;a[0].m!==0;){if(!a[0].W.H)return H;a[0].W.H=J;a=a[0].da}return a[0].V}function V(a){return(a=ra(a))&&sa(a)}function sa(a){return!a.G&&(a.G=I,C[a.A]?C[a.A].push(a):C[a.A]=[a],B||W())}function ta(){var a=ra(t);a&&(a.G=I,D[a.A]?D[a.A].push(a):D[a.A]=[a])}
function ua(a,c){if(v>=t.length)t[v]={m:1,B:O(c),h:c=c||F,P:a.apply(null,g(c))||H};else if(c){var b=t[v];b.B(b.h,c)&&(b.P&&b.P.apply(b,g(b.h)),b.P=a.apply(null,g(b.h=c))||H)}++v}function va(a){if(v<t.length)return t[v++].g;var c=t,b=[a,function(d){b[0]!==d&&(b[0]=d,V(c))},function(){return b[0]}];t[v++]={m:0,g:b};return b}function T(a){return(v<t.length?t[v++]:t[v++]={m:0,g:a===void 0?{}:a}).g}
function wa(a,c){return v>=t.length?(t[v++]={m:0,B:O(c),h:c=c||F,g:a.apply(null,g(c))}).g:c&&t[v].B(t[v].h,c)?t[v].g=a.apply(null,g(t[v++].h=c)):t[v++].g}function S(a,c){return v<t.length?(c=t[v].g,t[v++].g=a):t[v++]={m:0,g:a},c}function xa(a,c){return a=setTimeout(function(){return c(I)},a),function(){return clearTimeout(a)}}function qa(a){for(var c=f(a.Z),b=c.next();!b.done;b=c.next())U(a.M[b.value])}function ya(a,c,b){return{ba:b.ca,ha:a,aa:z,ga:r?z:z+c}}
function X(a){var c=S(a,H);return c?ma(c,a):M(a)}
function za(a){var c=p.i;if(a){for(var b=f(X(a)),d=b.next();!d.done;d=b.next()){d=d.value;switch(d.charCodeAt(0)){case 70:c.className=M(a.F).filter(function(h){return a.F[h]}).join(" ");continue;case 82:a.R(c);case 67:case 68:case 83:continue}c[d]=a[d]}if(a.D)for(b=f(X(a.D)),d=b.next();!d.done;d=b.next())d=d.value,c.setAttribute("data-"+d.replace(fa,"-$&").toLowerCase(),a.D[d]);if(a.S)for(b=f(X(a.S)),d=b.next();!d.done;d=b.next())d=d.value,c.style[d]=a.S[d]}return c}
function Y(a,c,b){return{J:a,o:c?b?(c.C=b,c):c:b?{C:b}:H}}
function W(){r=z<=0;z=ka.now();A&&cancelAnimationFrame(A);B=I;A=0;for(var a;(a=C).length;){C=[];a=f(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value){c=f(c);for(var b=c.next();!b.done;b=c.next())if(p=b.value,p.G){if(p.i)P(H,H);else{var d,h=H;b=p.j;for(var e=p,n=p;!(d=(e=e.K).i););do for(var m=n.T,l=(n=n.K).l,u=l.length;++m<u&&l[m]&&!(h=l[m].j););while(!h&&n!==e);n=p;P(d,h);if(n.j!==b)for(;!(n=n.K).i;){b=H;d=f(n.l);for(h=d.next();!(h.done||(h=h.value)&&(b=h.j));h=d.next());if(b===n.j)break;n.j=
b}}r=J}}}B=J;D.length&&(C=D,D=a,Aa())}function Aa(){return A||(A=requestAnimationFrame(W))}var Ba=W;function Z(a){var c=E[a];if(!c){var b=a.indexOf("[");E[a]=c=ia.createElement(b<0?a:a.substr(0,b));if(b>0)for(a=f(a.substring(b+1,a.length-1).split("][")),b=a.next();!b.done;b=a.next()){b=b.value;var d=b.indexOf("=");d>0?c[b.substr(0,d)]=b.substr(d+1):c[b]=I}}return c}function Ca(a){var c=ba[a];if(!c){var b=Z(a);ba[a]=c=function(d){return r&&(p.i=b.cloneNode(I)),za(d),d&&d.C||H}}return c}var Da=K.prototype;
Da.fill||(Da.fill=function(a){for(var c=this.length,b=0;b<c;++b)this[b]=a;return this});define({defer:function(){return B=I,Aa()},defer_end:Ba,dom_define:function(a,c,b){c=Z(c);b&&(c=c.cloneNode(I),b.D&&(L(c.dataset,b.D),delete b.D),b.S&&(L(c.style,b.S),delete b.S),L(c,b));E["#"+a]=c},hook_assert:function(a){if(!a)throw E;},hook_async:function(a,c,b){var d;if((v<t.length?(d=t[v++],J):d=t[v++]={m:2,B:O(c),h:c||F,g:H})||c&&d.B(d.h,c)&&(d.h=c)){b!==void 0&&(d.g=b);var h=t;a.apply(null,g(d.h)).then(function(e){return d.g!==e&&d.h===c&&(d.g=e,V(h))})}return d.g},hook_callback:function(a,
c){var b=T();b.h=c;return b.ia||(b.ia=function(){var d=k.apply(0,arguments);return a.apply(null,[].concat(g(b.h),g(d)))})},hook_delay:function(a){var c=f(va(J)),b=c.next().value;c=c.next().value;ua(xa,[a,c]);return b},hook_dom:function(a,c){return p.i===H&&(p.i=Z(a).cloneNode(I)),za(c||H)},hook_effect:ua,hook_map:function(a,c,b){var d=H,h=I;if(v<t.length)if((d=t[v]).U!==a)qa(d),d=H;else if(!d.H||b&&d.B(d.h,b))d.h=b||F,d.H=I;else{if(c===d.N)return++v,d.g;h=J}var e=r,n=t,m=++v,l={},u=[],q=c.length>
0&&na(c,l,u);if(d){if(d.g=[],d.N!==c)for(d.N=c,c=f(d.Z),b=c.next();!b.done;b=c.next())b=b.value,b in l||(U(d.M[b]),delete d.M[b])}else t[m-1]=d={m:3,B:O(b),h:b||F,g:[],H:I,U:a,X:q?N(c[0]):H,Z:[],M:{},N:c};c=f(u);for(b=c.next();!b.done;b=c.next()){b=b.value;var w=d.M[b];if(r=!w)d.M[b]=w=[{m:1,da:n,W:d,Y:H,g:H}];if(h||r||(q?d.X(l[b],w[0].Y):l[b]!==w[0].Y)){t=w;v=1;try{w[0].g=a.apply(null,[w[0].Y=l[b]].concat(g(d.h)))}catch(G){}}d.g.push(w[0].g)}r=e;t=n;v=m;d.Z=u;return d.g},hook_memo:wa,hook_model:function(a){if(v<
t.length)return t[v++].g;for(var c=t,b=[(0,a.init)(H),{}],d=f(M(a)),h=d.next(),e={};!h.done;e={$:void 0},h=d.next())e.$=h.value,b[1][e.$]=function(n){return function(){var m=a[n.$].apply(null,[b[0]].concat(g(k.apply(0,arguments))));b[0]!==m&&(b[0]=m,V(c))}}(e);t[v++]={m:0,g:b};return b},hook_object_changes:X,hook_prev:S,hook_rerender:ta,hook_state:va,hook_static:T,hook_sub:function(a,c){var b=H;if(v<t.length)if((b=t[v]).U!==a)U(b.u),b=H;else if(!b.H||c&&b.B(b.h,c))c&&(b.h=c),b.H=I;else return++v,
b.g;var d=r,h=t,e=v;if(r=!b)(t[v]=b={m:4,B:O(c),h:c||F,g:H,U:a,H:I,u:[]}).u[0]={m:2,da:t,W:b};t=b.u;v=1;try{b.g=a.apply(null,g(b.h))}catch(n){}r=d;t=h;v=e+1;return b.g},hook_transition:function(a,c){var b=T({ca:a});a=wa(ya,[a,c,b]);return b.ca=a.ga<=z?a.ha:(ta(),a.aa===z?a.ba:a.ba+(a.ha-a.ba)*(z-a.aa)/(a.ga-a.aa))},init:function(a,c,b){c=c===void 0?ia.body:c;b=b===void 0?H:b;c.innerHTML="";a={v:{J:a,o:b},O:H,K:H,A:0,T:0,u:[],l:H,i:c,j:c,G:J};a.u[0]={m:0,V:a};sa(a)},node:Y,node_dom:function(a,c,b){return Y(Ca(a),
c,b)},node_map:function(a,c,b){return Y(P,{J:a,N:c,o:b||H})},now:function(){return z}})})()
