"use strict";/*
 lui.js web framework 2.5.1
 inspired by react and mithril
 l3p3.de 2026
*/
{let e=null,f=!e,g=e,n=0,r=0,t=0,w=!f,x=[],z=[];
const A={},B={},C={},E=[],G=[],aa={},H=e,I=f,J=w,K=Array,ba=Object,M=ba.assign,N=ba.keys,ca=document,da=window,ea=da.performance||Date,fa=a=>new Function("a","b",`return a!==b&&(${a.join("||")})`),O=a=>{const c=(a=N(a)).join(",");return C[c]||(C[c]=fa(a.map(b=>`a.${b}!==b.`+b)))},ha=(a,c)=>a===c?G:N(a).filter(b=>a[b]!==c[b]),P=a=>a?E[a.length]||(E[a.length]=fa(a.map((c,b)=>`a[${b}]!==b[${b}]`))):H,Q=(a,c)=>{const b=e,d=b.B+1;let l=c;g=b.v;n=1;b.A=J;if(b.u.K!==Q){var h=H;try{h=b.u.K(b.u.l||aa)}catch(F){if(b.A)return}var m=
b.i;if(h){m&&(a=m,l=H);var p=h.length,q,v=b.m||(b.m=(new K(p)).fill(H));do{var k=v[--p];(q=h[p])&&q!==I?((f=!k)?(v[p]=e=k={u:q,T:q.l&&O(q.l),L:b,B:d,aa:p,v:[],m:H,i:H,o:H,A:J,M:J},e.v[0]={j:0,V:k},Q(a,l),k.i&&a.insertBefore(k.o=k.i,l)):q.l&&k.T(k.u.l,q.l)&&((e=k).u=q,Q(a,l)),k.o&&(l=k.o)):k&&(R(k,a),v[p]=H)}while(p>0)}else if(b.m){m&&(a=m);for(p of b.m)p&&R(p,a);b.m=H}if(m)return}else{q=b.u.l.K;var u=b.u.l.P;h=b.u.l.l;m=u.length;p=I;k=S();v={};const F=[];u=m>0&&ia(u,v,F);if(k.N){if(!(k.$.length|m))return;
p=h&&k.T(h,k.fa);for(var D of k.$)D in v||(R(k.N[D],a),delete k.N[D]);k.fa=h;k.$=F}else{if(m===0)return;k.N={};k.X=u?O(v[F[0]]):H;k.$=F;k.T=(k.fa=h)&&O(h)}for(D=b.m=new K(m);m>0;){const L=F[--m];let y=k.N[L];if(f=!y)k.N[L]=e=y={u:{K:q,l:M({I:v[L]},h)},T:H,L:b,B:d,aa:0,v:[],m:H,i:H,o:H,A:J,M:J},e.v[0]={j:0,V:y},Q(H,H),a.insertBefore(y.i,l);else{if(p||u&&k.X(v[L],y.u.l.I))(e=y).u.l=M({I:v[L]},h),Q(H,H);y.i.nextSibling!==l&&a.insertBefore(y.i,l)}l=(D[m]=y).i}}b.o=l!==c?l:H},R=(a,c)=>{c&&a.i&&(a.i.remove(),
c=H);if(c||a.M){if(a.m)for(const b of a.m)b&&R(b,c);a.M&&T(a.v)}if(a.A){let b,d;(!(d=x[b=a.B])||(b=d.indexOf(a))<0)&&(!(d=z[b])||(b=d.indexOf(a))<0)||d.splice(b,1)}},T=a=>{let c,b=a.length;for(;b>1;)switch((c=a[--b]).j){case 1:c.J&&c.J(...c.h);break;case 2:c.h=G;break;case 3:ja(c);break;case 4:T(c.v)}},ia=(a,c,b)=>{const d=typeof a[0]==="object";for(const l of a)a=d?l.id:l,c[a]=l,b.push(a);return d},ka=a=>{for(;a[0].j!==0;){if(!a[0].W.H)return H;a[0].W.H=J;a=a[0].ea}return a[0].V},U=a=>(a=ka(a))&&
la(a),la=a=>!a.A&&(a.A=I,x[a.B]?x[a.B].push(a):x[a.B]=[a],w||V()),W=()=>{let a=e;for(;a&&!a.M;)a.M=I,a=a.L},ma=()=>{const a=ka(g);a&&(a.A=I,z[a.B]?z[a.B].push(a):z[a.B]=[a])},na=(a,c)=>{if(n>=g.length)((g[n]={j:1,G:P(c),h:c=c||G,J:H}).J=a(...c)||H)&&W();else if(c){const b=g[n];b.G(b.h,c)&&(b.J&&b.J(...b.h),b.J=H,(b.J=a(...(b.h=c))||H)&&W())}++n},oa=a=>{if(n<g.length)return g[n++].g;const c=g,b=[a,d=>{if(b[0]!==d&&(b[0]=d,U(c),g===c))throw A;return d},()=>b[0]];g[n++]={j:0,g:b};return b},S=a=>(n<g.length?
g[n++]:g[n++]={j:0,g:a===void 0?{}:a}).g,pa=(a,c)=>n>=g.length?(g[n++]={j:0,G:P(c),h:c=c||G,g:a(...c)}).g:c&&g[n].G(g[n].h,c)?g[n].g=a(...(g[n++].h=c)):g[n++].g,qa=(a,c)=>(n<g.length?(c=g[n].g,g[n++].g=a):g[n++]={j:0,g:a},c),ra=(a,c)=>(a=setTimeout(()=>c(I),a),()=>clearTimeout(a)),ja=a=>{for(const c of a.Z)T(a.O[c])},sa=(a,c,b)=>({ca:b.da,ha:a,ba:r,ga:f?r:r+c}),X=a=>{const c=qa(a,H);return c?ha(c,a):N(a)},ta=a=>{const c=e.i;if(a){for(const b of X(a)){switch(b.charCodeAt(0)){case 70:c.className=N(a.F).filter(d=>
a.F[d]).join(" ");continue;case 82:a.R(c);case 67:case 68:case 83:continue}c[b]=a[b]}if(a.D)for(const b of X(a.D))c.dataset[b]=a.D[b];if(a.S)for(const b of X(a.S))c.style[b]=a.S[b]}return c},Y=(a,c,b)=>({K:a,l:c?b?(c.C=b,c):c:b?{C:b}:H}),V=()=>{f=r<=0;r=ea.now();t&&cancelAnimationFrame(t);w=I;t=0;for(var a;(a=x).length;){x=[];for(const c of a)if(c)for(e of c)if(e.A){if(e.i)Q(H,H);else{let b=H,d=e.o,l=e,h=e;for(;!(a=(l=l.L).i););do{let m=h.aa;const {m:p}=h=h.L,q=p.length;for(;++m<q&&p[m]&&!(b=p[m].o););
}while(!b&&h!==l);h=e;Q(a,b);if(h.o!==d)for(;!(h=h.L).i;){d=H;for(const m of h.m)if(m&&(d=m.o))break;if(d===h.o)break;h.o=d}}f=J}}w=J;z.length&&(x=z,z=a,ua())},ua=()=>t||(t=requestAnimationFrame(V)),Z=a=>{let c=A[a];if(!c){const b=a.indexOf("[");A[a]=c=ca.createElement(b<0?a:a.substr(0,b));if(b>0)for(const d of a.substring(b+1,a.length-1).split("]["))a=d.indexOf("="),a>0?c[d.substr(0,a)]=d.substr(a+1):c[d]=I}return c},va=a=>{let c=B[a];if(!c){const b=Z(a);B[a]=c=d=>(f&&(e.i=b.cloneNode(I)),ta(d),
d&&d.C||H)}return c};da.lui={defer:()=>(w=I,ua()),defer_end:V,dom_define:(a,c,b)=>{c=Z(c);b&&(c=c.cloneNode(I),b.D&&(M(c.dataset,b.D),delete b.D),b.S&&(M(c.style,b.S),delete b.S),M(c,b));A["#"+a]=c},hook_assert:a=>{if(!a)throw A;},hook_async:(a,c,b)=>{let d;if((n<g.length?(d=g[n++],J):(W(),d=g[n++]={j:2,G:P(c),h:c||G,g:H}))||c&&d.G(d.h,c)&&(d.h=c)){b!==void 0&&(d.g=b);const l=g;a(...d.h).then(h=>d.g!==h&&d.h===c&&(d.g=h,U(l)))}return d.g},hook_callback:(a,c)=>{const b=S();b.h=c;return b.ia||(b.ia=(...d)=>a(...b.h,...d))},
hook_delay:a=>{const [c,b]=oa(J);na(ra,[a,b]);return c},hook_dom:(a,c)=>(e.i===H&&(e.i=Z(a).cloneNode(I)),ta(c||H)),hook_effect:na,hook_map:(a,c,b)=>{let d=H,l=I;if(n<g.length)if((d=g[n]).U!==a)ja(d),d=H;else if(!d.H||b&&d.G(d.h,b))d.h=b||G,d.H=I;else{if(c===d.P)return++n,d.g;l=J}const h=f,m=g,p=++n,q={},v=[],k=c.length>0&&ia(c,q,v);if(d){if(d.g=[],d.P!==c){d.P=c;for(const u of d.Z)u in q||(T(d.O[u]),delete d.O[u])}}else g[p-1]=d={j:3,G:P(b),h:b||G,g:[],H:I,U:a,X:k?O(c[0]):H,Z:[],O:{},P:c};for(const u of v){c=
d.O[u];if(f=!c)d.O[u]=c=[{j:1,ea:m,W:d,Y:H,g:H}];if(l||f||(k?d.X(q[u],c[0].Y):q[u]!==c[0].Y)){g=c;n=1;try{c[0].g=a(c[0].Y=q[u],...d.h)}catch(D){if(e.A)throw D;}}d.g.push(c[0].g)}f=h;g=m;n=p;d.Z=v;return d.g},hook_memo:pa,hook_model:(a,c)=>{if(n<g.length)return g[n++].g;const b=g,d=[a.init(H,c),{}];for(const l of N(a))d[1][l]=(...h)=>{h=a[l](d[0],...h);if(d[0]!==h&&(d[0]=h,U(b),g===b))throw A;return h};g[n++]={j:0,g:d};return d},hook_object_changes:X,hook_prev:qa,hook_rerender:ma,hook_state:oa,hook_static:S,
hook_sub:(a,c)=>{let b=H;if(n<g.length)if((b=g[n]).U!==a)T(b.v),b=H;else if(!b.H||c&&b.G(b.h,c))c&&(b.h=c),b.H=I;else return++n,b.g;const d=f,l=g,h=n;if(f=!b)(g[n]=b={j:4,G:P(c),h:c||G,g:H,U:a,H:I,v:[]}).v[0]={j:2,ea:g,W:b};g=b.v;n=1;try{b.g=a(...b.h)}catch(m){if(e.A)throw m;}f=d;g=l;n=h+1;return b.g},hook_transition:(a,c)=>{const b=S({da:a});a=pa(sa,[a,c,b]);return b.da=a.ga<=r?a.ha:(ma(),a.ba===r?a.ca:a.ca+(a.ha-a.ca)*(r-a.ba)/(a.ga-a.ba))},init:(a,c=ca.body,b=H)=>{c.innerHTML="";a={u:{K:a,l:b},
T:H,L:H,B:0,aa:0,v:[],m:H,i:c,o:c,A:J,M:J};a.v[0]={j:0,V:a};la(a)},node:Y,node_dom:(a,c,b)=>Y(va(a),c,b),node_map:(a,c,b)=>Y(Q,{K:a,P:c,l:b||H}),now:()=>r}}
