"use strict";/*
 lui.js web framework 2.4.1
 inspired by react and mithril
 l3p3.de 2025
*/
(function(){function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function g(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function h(a){if(!(a instanceof Array)){a=g(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
function ba(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};var k=null,p=!k,r=k,t=0,v=0,w=0,y=!p,A=[],B=[],C,D,F={},ca={},da={},ea=[],G=[],fa={},H=k,I=p,K=y,ha=/[A-Z]/g,ia=Array,L=Object,M=L.assign||(L.assign=function(a){for(var b=arguments,c=b.length,d=0,e,f;++d<c;)if(e=b[d])for(f in e)a[f]=e[f];return a}),N=L.keys||(L.keys=function(a){var b=[],c;for(c in a)b.push(c);return b});L.values||(L.values=function(a){var b=[],c;for(c in a)b.push(a[c]);return b});
var ja=setTimeout,ka=clearTimeout,la=document,O=window,P=Date,ma=navigator.userAgent.indexOf("WebKit")<0;function na(a){return new Function("a","b","return a!==b&&("+a.join("||")+")")}function Q(a){var b=(a=N(a)).join(",");return da[b]||(da[b]=na(a.map(function(c){return"a."+c+"!==b."+c})))}function oa(a,b){return a===b?G:N(a).filter(function(c){return a[c]!==b[c]})}function R(a){return a?ea[a.length]||(ea[a.length]=na(a.map(function(b,c){return"a["+c+"]!==b["+c+"]"}))):H}
function S(a,b){var c=k,d=c.B+1,e=b;r=c.u;t=1;c.v=K;if(c.A.K!==S){var f=H;try{f=(0,c.A.K)(c.A.l||fa)}catch(Ja){if(c.v)return}var l=c.i;if(f){l&&(a=l,e=H);var n=f.length,m,u=c.m||(c.m=(new ia(n)).fill(H));do{var q=u[--n];(m=f[n])&&m!==I?((p=!q)?(u[n]=k=q={A:m,T:m.l&&Q(m.l),L:c,B:d,ba:n,u:[],m:H,i:H,o:H,v:K,M:K},k.u[0]={j:0,V:q},S(a,e),q.i&&a.insertBefore(q.o=q.i,e)):m.l&&q.T(q.A.l,m.l)&&((k=q).A=m,S(a,e)),q.o&&(e=q.o)):q&&(T(q,a),u[n]=H)}while(n>0)}else if(c.m){l&&(a=l);d=g(c.m);for(f=d.next();!f.done;f=
d.next())(f=f.value)&&T(f,a);c.m=H}if(l)return}else{f=c.A.l;l=f.K;var x=f.P;f=f.l;n=x.length;q=I;m=U();u={};var J=[];x=n>0&&pa(x,u,J);if(m.N){if(!(m.$.length|n))return;q=f&&m.T(f,m.ga);for(var X=g(m.$),z=X.next();!z.done;z=X.next())z=z.value,u[z]==H&&(T(m.N[z],a),delete m.N[z]);m.ga=f;m.$=J}else{if(n===0)return;m.N={};m.X=x?Q(u[J[0]]):H;m.$=J;m.T=(m.ga=f)&&Q(f)}for(X=c.m=new ia(n);n>0;){z=J[--n];var E=m.N[z];if(p=!E)m.N[z]=k=E={A:{K:l,l:M({I:u[z]},f)},T:H,L:c,B:d,ba:0,u:[],m:H,i:H,o:H,v:K,M:K},k.u[0]=
{j:0,V:E},S(H,H),a.insertBefore(E.i,e);else{if(q||x&&m.X(u[z],E.A.l.I))(k=E).A.l=M({I:u[z]},f),S(H,H);E.i.nextSibling!==e&&a.insertBefore(E.i,e)}e=(X[n]=E).i}}c.o=e!==b?e:H}function T(a,b){b&&a.i&&(b.removeChild(a.i),b=H);if(b||a.M){if(a.m)for(var c=g(a.m),d=c.next();!d.done;d=c.next())(d=d.value)&&T(d,b);a.M&&V(a.u)}if(a.v){var e,f;(!(f=A[e=a.B])||(e=f.indexOf(a))<0)&&(!(f=B[e])||(e=f.indexOf(a))<0)||f.splice(e,1)}}
function V(a){for(var b,c=a.length;c>1;)switch((b=a[--c]).j){case 1:b.J&&b.J.apply(b,h(b.h));break;case 2:b.h=G;break;case 3:qa(b);break;case 4:V(b.u)}}function pa(a,b,c){var d=typeof a[0]==="object";a=g(a);for(var e=a.next();!e.done;e=a.next()){e=e.value;var f=d?e.id:e;b[f]=e;c.push(f)}return d}function ra(a){for(;a[0].j!==0;){if(!a[0].W.H)return H;a[0].W.H=K;a=a[0].fa}return a[0].V}function sa(a){return(a=ra(a))&&ta(a)}
function ta(a){return!a.v&&(a.v=I,A[a.B]?A[a.B].push(a):A[a.B]=[a],y||ua())}function va(){for(var a=k;a&&!a.M;)a.M=I,a=a.L}function wa(){var a=ra(r);a&&(a.v=I,B[a.B]?B[a.B].push(a):B[a.B]=[a])}function xa(a,b){if(t>=r.length)((r[t]={j:1,G:R(b),h:b=b||G,J:H}).J=a.apply(null,h(b))||H)&&va();else if(b){var c=r[t];c.G(c.h,b)&&(c.J&&c.J.apply(c,h(c.h)),c.J=H,(c.J=a.apply(null,h(c.h=b))||H)&&va())}++t}
function ya(a){if(t<r.length)return r[t++].g;var b=r,c=[a,function(d){if(c[0]!==d&&(c[0]=d,sa(b),r===b))throw F;return d},function(){return c[0]}];r[t++]={j:0,g:c};return c}function U(a){return(t<r.length?r[t++]:r[t++]={j:0,g:a===void 0?{}:a}).g}function za(a,b){return t>=r.length?(r[t++]={j:0,G:R(b),h:b=b||G,g:a.apply(null,h(b))}).g:b&&r[t].G(r[t].h,b)?r[t].g=a.apply(null,h(r[t++].h=b)):r[t++].g}function Aa(a,b){return t<r.length?(b=r[t].g,r[t++].g=a):r[t++]={j:0,g:a},b}
function Ba(a,b){return a=ja(function(){return b(I)},a),function(){return ka(a)}}function qa(a){for(var b=g(a.Z),c=b.next();!c.done;c=b.next())V(a.O[c.value])}function Ca(a,b,c){return{da:c.ea,ia:a,ca:v,ha:p?v:v+b}}function W(a){var b=Aa(a,H);return b?oa(b,a):N(a)}
function Da(a){var b=k.i;if(a){for(var c=g(W(a)),d=c.next();!d.done;d=c.next()){d=d.value;switch(d){case "F":b.className=N(a.F).filter(function(e){return a.F[e]}).join(" ");continue;case "R":a.R(b);case "C":case "D":case "S":continue}b[d]=a[d]}if(a.D)for(c=g(W(a.D)),d=c.next();!d.done;d=c.next())d=d.value,b.setAttribute("data-"+d.replace(ha,"-$&").toLowerCase(),a.D[d]);if(a.S)for(c=g(W(a.S)),d=c.next();!d.done;d=c.next())d=d.value,b.style[d]=a.S[d]}return b}
function Ea(a,b,c){return{K:a,l:b?c?(b.C=c,b):b:c?{C:c}:H}}
function ua(){p=v<=0;v=P.now();w&&D(w);y=I;w=0;for(var a;(a=A).length;){A=[];a=g(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value){b=g(b);for(var c=b.next();!c.done;c=b.next())if(k=c.value,k.v){if(k.i)S(H,H);else{var d,e=H;c=k.o;for(var f=k,l=k;!(d=(f=f.L).i););do for(var n=l.ba,m=(l=l.L).m,u=m.length;++n<u&&m[n]&&!(e=m[n].o););while(!e&&l!==f);l=k;S(d,e);if(l.o!==c)for(;!(l=l.L).i;){c=H;d=g(l.m);for(e=d.next();!(e.done||(e=e.value)&&(c=e.o));e=d.next());if(c===l.o)break;l.o=c}}p=K}}}y=K;B.length&&
(A=B,B=a,Fa())}function Fa(){return w||(w=C(ua))}var Ga=ua;function Ha(a){var b=F[a];if(!b){var c=a.indexOf("[");F[a]=b=la.createElement(c<0?a:a.substring(0,c));if(c>0)for(a=g(a.substring(c+1,a.length-1).split("][")),c=a.next();!c.done;c=a.next()){c=c.value;var d=c.indexOf("="),e=c.substring(0,d);d<0?b[c]=I:ma||e!=="style"?b[e]=c.substr(d+1):b.setAttribute(e,c.substr(d+1))}}return b}
function Ia(a){var b=ca[a];if(!b){var c=Ha(a);ca[a]=b=function(d){return p&&(k.i=c.cloneNode(I)),Da(d),d&&d.C||H}}return b}var Y=ia.prototype,Z=String.prototype;C=O.requestAnimationFrame;D=O.cancelAnimationFrame;
L.entries||(L.entries=function(a){var b=[],c;for(c in a)b.push([c,a[c]]);return b},Y.fill||(Y.fill=function(a){for(var b=this.length,c=0;c<b;++c)this[c]=a;return this},D||(C=(D=O.mozCancelAnimationFrame||O.webkitCancelAnimationFrame)?O.mozRequestAnimationFrame||O.webkitRequestAnimationFrame:(D=ka,function(a){return ja(a,20)}),P.now||(P.now=function(){return(new P).getTime()},Y.map||(Y.filter=function(a){for(var b=[],c=this.length,d=-1,e=0;e<c;++e)a(this[e],e)&&(b[++d]=this[e]);return b},Y.find=function(a){a=
this.findIndex(a);if(a>=0)return this[a]},Y.findIndex=Y.forEach=function(a){for(var b=this.length,c=0;c<b;++c)if(a(this[c],c))return c;return-1},Y.includes=Z.includes=function(a){return this.indexOf(a)>=0},Y.indexOf=function(a,b){b=b||0;for(var c=this.length;b<c;++b)if(this[b]===a)return b;return-1},Y.map=function(a){for(var b=[],c=this.length,d=0;d<c;++d)b[d]=a(this[d],d);return b},Y.some=function(a){return this.findIndex(a)>=0},Y.push||(Y.push=function(a){this[this.length]=a},Function.prototype.apply=
function(a,b){a==H?(O._=this,a=O):L.prototype._=this;switch(b?b.length:0){case 0:return a._();case 1:return a._(b[0]);case 2:return a._(b[0],b[1]);case 3:return a._(b[0],b[1],b[2]);case 4:return a._(b[0],b[1],b[2],b[3]);case 5:return a._(b[0],b[1],b[2],b[3],b[4]);default:return a._(b[0],b[1],b[2],b[3],b[4],b[5])}},Y.join||(Y.concat=function(){for(var a=arguments,b=this,c=[],d=a.length,e=b.length,f=0,l=0,n=-1;l<e;++l)c[++n]=b[l];for(;f<d;++f)for(e=(l=0,b=a[f]).length;l<e;++l)c[++n]=b[l];return c},
Y.join=function(a){for(var b="",c=this.length-1,d=0;d<c;++d)b+=this[d]+a;d<c+1&&(b+=this[d]);return b},Z.charAt=function(a){return this[a]},Z.indexOf=function(a,b){a=a[0];b=b||0;for(var c=this.length;b<c;++b)if(this[b]===a)return b;return-1},Z.split=function(a){for(var b=[],c=this.length,d=a.length,e=-1,f=0,l;(l=this.indexOf(a,f))>=0;f=l+d)b[++e]=this.substring(f,l);f<c&&(b[++e]=this.substr(f));return b},Z.substr=function(a){return this.substring(a,this.length)},Z.substring=function(a,b){for(var c=
"";a<b;++a)c+=this[a];return c})))))));O.lui={defer:function(){return y=I,Fa()},defer_end:Ga,dom_define:function(a,b,c){b=Ha(b);c&&(b=b.cloneNode(I),c.D&&(M(b.dataset,c.D),delete c.D),c.S&&(M(b.style,c.S),delete c.S),M(b,c));F["#"+a]=b},hook_assert:function(a){if(!a)throw F;},hook_async:function(a,b,c){var d;if((t<r.length?(d=r[t++],K):(va(),d=r[t++]={j:2,G:R(b),h:b||G,g:H}))||b&&d.G(d.h,b)&&(d.h=b)){c!==void 0&&(d.g=c);var e=r;a.apply(null,h(d.h)).then(function(f){return d.g!==f&&d.h===b&&(d.g=f,sa(e))})}return d.g},hook_callback:function(a,
b){var c=U();c.h=b;return c.ja||(c.ja=function(){var d=ba.apply(0,arguments);return a.apply(null,[].concat(h(c.h),h(d)))})},hook_delay:function(a){var b=g(ya(K)),c=b.next().value;b=b.next().value;xa(Ba,[a,b]);return c},hook_dom:function(a,b){return k.i===H&&(k.i=Ha(a).cloneNode(I)),Da(b||H)},hook_effect:xa,hook_map:function(a,b,c){var d=H,e=I;if(t<r.length)if((d=r[t]).U!==a)qa(d),d=H;else if(!d.H||c&&d.G(d.h,c))d.h=c||G,d.H=I;else{if(b===d.P)return++t,d.g;e=K}var f=p,l=r,n=++t,m={},u=[],q=b.length>
0&&pa(b,m,u);if(d){if(d.g=[],d.P!==b)for(d.P=b,b=g(d.Z),c=b.next();!c.done;c=b.next())c=c.value,m[c]===void 0&&(V(d.O[c]),delete d.O[c])}else r[n-1]=d={j:3,G:R(c),h:c||G,g:[],H:I,U:a,X:q?Q(b[0]):H,Z:[],O:{},P:b};b=g(u);for(c=b.next();!c.done;c=b.next()){c=c.value;var x=d.O[c];if(p=!x)d.O[c]=x=[{j:1,fa:l,W:d,Y:H,g:H}];if(e||p||(q?d.X(m[c],x[0].Y):m[c]!==x[0].Y)){r=x;t=1;try{x[0].g=a.apply(null,[x[0].Y=m[c]].concat(h(d.h)))}catch(J){if(k.v)throw J;}}d.g.push(x[0].g)}p=f;r=l;t=n;d.Z=u;return d.g},hook_memo:za,
hook_model:function(a){if(t<r.length)return r[t++].g;for(var b=r,c=[(0,a.init)(H),{}],d=g(N(a)),e=d.next(),f={};!e.done;f={aa:void 0},e=d.next())f.aa=e.value,c[1][f.aa]=function(l){return function(){var n=a[l.aa].apply(null,[c[0]].concat(h(ba.apply(0,arguments))));if(c[0]!==n&&(c[0]=n,sa(b),r===b))throw F;return n}}(f);r[t++]={j:0,g:c};return c},hook_object_changes:W,hook_prev:Aa,hook_rerender:wa,hook_state:ya,hook_static:U,hook_sub:function(a,b){var c=H;if(t<r.length)if((c=r[t]).U!==a)V(c.u),c=H;
else if(!c.H||b&&c.G(c.h,b))b&&(c.h=b),c.H=I;else return++t,c.g;var d=p,e=r,f=t;if(p=!c)(r[t]=c={j:4,G:R(b),h:b||G,g:H,U:a,H:I,u:[]}).u[0]={j:2,fa:r,W:c};r=c.u;t=1;try{c.g=a.apply(null,h(c.h))}catch(l){if(k.v)throw l;}p=d;r=e;t=f+1;return c.g},hook_transition:function(a,b){var c=U({ea:a}),d=za(Ca,[a,b,c]);return c.ea=d.ha<=v?d.ia:(wa(),d.ca===v?d.da:d.da+(d.ia-d.da)*(v-d.ca)/(d.ha-d.ca))},init:function(a,b,c){b=b===void 0?la.body:b;c=c===void 0?H:c;b.innerHTML="";a={A:{K:a,l:c},T:H,L:H,B:0,ba:0,u:[],
m:H,i:b,o:b,v:K,M:K};a.u[0]={j:0,V:a};ta(a)},node:Ea,node_dom:function(a,b,c){return Ea(Ia(a),b,c)},node_map:function(a,b,c){return Ea(S,{K:a,P:b,l:c||H})},now:function(){return v}}})()
