"use strict";/*
 lui.js web framework 2.2.3
 inspired by react and mithril
 l3p3.de 2025
*/
{let e=null,f=!e,g=e,m=0,t=0,u=0,x=!f,y=[],z=[];
const A={},B={},C={},aa=[e,(a,b)=>a!==b&&a[0]!==b[0],(a,b)=>a!==b&&(a[0]!==b[0]||a[1]!==b[1]),(a,b)=>a!==b&&(a[0]!==b[0]||a[1]!==b[1]||a[2]!==b[2])],E=[],ba={},F=e,G=f,H=x,I=Array,ca=Object,K=ca.assign,L=ca.keys,da=document,ea=window,ha=ea.performance||Date,M=a=>{const b=(a=L(a)).join(",");return C[b]||(C[b]=a)},N=(a,b,c)=>{if(a===b)return!1;for(const d of c)if(a[d]!==b[d])return!0;return!1},ia=(a,b)=>a===b?E:L(a).filter(c=>a[c]!==b[c]),O=a=>a?a.length<5?aa[a.length]:ja:F,ja=(a,b)=>{if(a===b)return!1;
for(let c=0,d=a.length;c<d;++c)if(a[c]!==b[c])return!0;return!1},P=(a,b)=>{const c=e,d=b,n=c.A+1;g=c.v;m=1;c.G=H;if(c.u.J!==P){var k=F;try{k=(0,c.u.J)(c.u.o||ba)}catch(R){}var p=c.i;if(k){p&&(a=p,b=F);var q=k.length,h,r=c.l||(c.l=(new I(q)).fill(F));do{var l=r[--q];(h=k[q])&&h!==G?((f=!l)?(r[q]=e=l={u:h,O:h.o&&M(h.o),K:c,A:n,T:q,v:[],l:F,i:F,j:F,G:H},e.v[0]={m:0,V:l},P(a,b),l.i&&a.insertBefore(l.j=l.i,b)):h.o&&N(l.u.o,h.o,l.O)&&((e=l).u=h,P(a,b)),l.j&&(b=l.j)):l&&(Q(l,a),r[q]=F)}while(q>0)}else if(c.l){for(q of c.l)q&&
Q(q,a);c.l=F}p||(c.j=b!==d?b:F)}else{q=c.u.o.J;var v=c.u.o.N;l=c.u.o.o;r=v.length;let R=G;if(!(S(r,r)+r<=0)){h=T();k={};p=[];v=r>0&&ka(v,k,p);if(h.L){R=l&&N(l,h.ea,h.O);for(var D of h.da)D in k||(Q(h.L[D],a),delete h.L[D]);h.ea=l;h.da=p}else h.L={},h.X=v?M(k[p[0]]):F,h.da=p,h.O=(h.ea=l)&&M(l);for(D=c.l=new I(r);r>0;){const J=p[--r];let w=h.L[J];if(f=!w)h.L[J]=e=w={u:{J:q,o:K({I:k[J]},l)},O:F,K:c,A:n,T:r,v:[],l:F,i:F,j:F,G:H},e.v[0]={m:0,V:w},P(a,b),w.i&&a.insertBefore(w.j=w.i,b);else{const fa=la(w);
fa&&fa.nextSibling!==b&&ma(w,a,b);if(R||v&&N(k[J],w.u.o.I,h.X))(e=w).u.o=K({I:k[J]},l),P(a,b)}(D[w.T=r]=w).j&&(b=w.j)}c.j=b!==d?b:F}}},Q=(a,b)=>{b&&a.i&&(a.i.remove(),b=F);if(a.l)for(const c of a.l)c&&Q(c,b);U(a.v);if(a.G){let c,d;(!(d=y[c=a.A])||(c=d.indexOf(a))<0)&&(!(d=z[c])||(c=d.indexOf(a))<0)||d.splice(c,1)}},U=a=>{let b,c=a.length;for(;c>1;)switch((b=a[--c]).m){case 1:b.P&&b.P(...b.h);break;case 2:b.h=E;break;case 3:na(b);break;case 4:U(b.v)}},ka=(a,b,c)=>{const d=typeof a[0]==="object";for(const n of a)a=
d?n.id:n,b[a]=n,c.push(a);return d},la=a=>{if(a.i)return a.i;let b;a=(b=a.l)?b.length:0;let c,d;for(;a>0;)if((d=b[--a])&&(c=la(d)))return c;return F},ma=(a,b,c)=>{if(a.i)return b.insertBefore(a.i,c);if(a.j){let d=a.l.length;do a.l[--d]&&(c=ma(a.l[d],b,c));while(d>0)}return c},oa=a=>{for(;a[0].m!==0;){if(!a[0].W.H)return F;a[0].W.H=H;a=a[0].ca}return a[0].V},V=a=>(a=oa(a))&&pa(a),pa=a=>!a.G&&(a.G=G,y[a.A]?y[a.A].push(a):y[a.A]=[a],x||W()),qa=()=>{const a=oa(g);a&&(a.G=G,z[a.A]?z[a.A].push(a):z[a.A]=
[a])},ra=(a,b)=>{if(m>=g.length)g[m]={m:1,B:O(b),h:b=b||E,P:a(...b)||F};else if(b){const c=g[m];c.B(c.h,b)&&(c.P&&c.P(...c.h),c.P=a(...(c.h=b))||F)}++m},sa=a=>{if(m<g.length)return g[m++].g;const b=g,c=[a,d=>{c[0]!==d&&(c[0]=d,V(b))},()=>c[0]];g[m++]={m:0,g:c};return c},T=a=>(m<g.length?g[m++]:g[m++]={m:0,g:a===void 0?{}:a}).g,ta=(a,b)=>m>=g.length?(g[m++]={m:0,B:O(b),h:b=b||E,g:a(...b)}).g:b&&g[m].B(g[m].h,b)?g[m].g=a(...(g[m++].h=b)):g[m++].g,S=(a,b)=>(m<g.length?(b=g[m].g,g[m++].g=a):g[m++]={m:0,
g:a},b),ua=(a,b)=>(a=setTimeout(()=>b(G),a),()=>clearTimeout(a)),na=a=>{for(const b of a.Z)U(a.M[b])},va=(a,b,c)=>({aa:c.ba,ga:a,$:t,fa:f?t:t+b}),X=a=>{const b=S(a,F);return b?ia(b,a):L(a)},wa=a=>{const b=e.i;if(a){for(const c of X(a)){switch(c.charCodeAt(0)){case 70:b.className=L(a.F).filter(d=>a.F[d]).join(" ");continue;case 82:a.R(b);case 67:case 68:case 83:continue}b[c]=a[c]}if(a.D)for(const c of X(a.D))b.dataset[c]=a.D[c];if(a.S)for(const c of X(a.S))b.style[c]=a.S[c]}return b},Y=(a,b,c)=>({J:a,
o:b?c?(b.C=c,b):b:c?{C:c}:F}),W=()=>{f=t<=0;t=ha.now();u&&cancelAnimationFrame(u);x=G;u=0;for(var a;(a=y).length;){y=[];for(const b of a)if(b)for(e of b)if(e.G){if(e.i)P(F,F);else{let c=F,d=e.j,n=e,k=e;for(;!(a=(n=n.K).i););do{let p=k.T;const {l:q}=k=k.K,h=q.length;for(;++p<h&&q[p]&&!(c=q[p].j););}while(!c&&k!==n);k=e;P(a,c);if(k.j!==d)for(;!(k=k.K).i;){d=F;for(const p of k.l)if(p&&(d=p.j))break;if(d===k.j)break;k.j=d}}f=H}}x=H;z.length&&(y=z,z=a,xa())},xa=()=>u||(u=requestAnimationFrame(W)),Z=a=>
{let b=A[a];if(!b){const c=a.indexOf("[");A[a]=b=da.createElement(c<0?a:a.substr(0,c));if(c>0)for(const d of a.substring(c+1,a.length-1).split("]["))a=d.indexOf("="),a>0?b[d.substr(0,a)]=d.substr(a+1):b[d]=G}return b},ya=a=>{let b=B[a];if(!b){const c=Z(a);B[a]=b=d=>(f&&(e.i=c.cloneNode(G)),wa(d),d&&d.C||F)}return b};ea.lui={defer:()=>(x=G,xa()),defer_end:W,dom_define:(a,b,c)=>{b=Z(b);c&&(b=b.cloneNode(G),c.D&&(K(b.dataset,c.D),delete c.D),c.S&&(K(b.style,c.S),delete c.S),K(b,c));A["#"+a]=b},hook_assert:a=>{if(!a)throw A;},hook_async:(a,b,c)=>{let d;if((m<g.length?(d=g[m++],H):d=g[m++]={m:2,B:O(b),h:b||E,g:F})||b&&d.B(d.h,b)&&(d.h=b)){c!==void 0&&(d.g=c);const n=g;a(...d.h).then(k=>d.g!==k&&d.h===b&&(d.g=k,V(n)))}return d.g},hook_callback:(a,b)=>{const c=T();c.h=b;return c.ha||(c.ha=(...d)=>a(...c.h,...d))},hook_delay:a=>
{const [b,c]=sa(H);ra(ua,[a,c]);return b},hook_dom:(a,b)=>(e.i===F&&(e.i=Z(a).cloneNode(G)),wa(b||F)),hook_effect:ra,hook_map:(a,b,c)=>{let d=F,n=G;if(m<g.length)if((d=g[m]).U!==a)na(d),d=F;else if(!d.H||c&&d.B(d.h,c))d.h=c||E,d.H=G;else{if(b===d.N)return++m,d.g;n=H}const k=f,p=g,q=++m,h={},r=[],l=b.length>0&&ka(b,h,r);if(d){if(d.g=[],d.N!==b){d.N=b;for(const v of d.Z)v in h||(U(d.M[v]),delete d.M[v])}}else g[q-1]=d={m:3,B:O(c),h:c||E,g:[],H:G,U:a,X:l?M(b[0]):F,Z:[],M:{},N:b};for(const v of r){b=
d.M[v];if(f=!b)d.M[v]=b=[{m:1,ca:p,W:d,Y:F,g:F}];if(n||f||(l?N(h[v],b[0].Y,d.X):h[v]!==b[0].Y)){g=b;m=1;try{b[0].g=a(b[0].Y=h[v],...d.h)}catch(D){}}d.g.push(b[0].g)}f=k;g=p;m=q;d.Z=r;return d.g},hook_memo:ta,hook_model:a=>{if(m<g.length)return g[m++].g;const b=g,c=[(0,a.init)(F),{}];for(const d of L(a))c[1][d]=(...n)=>{n=(0,a[d])(c[0],...n);c[0]!==n&&(c[0]=n,V(b))};g[m++]={m:0,g:c};return c},hook_object_changes:X,hook_prev:S,hook_rerender:qa,hook_state:sa,hook_static:T,hook_sub:(a,b)=>{let c=F;if(m<
g.length)if((c=g[m]).U!==a)U(c.v),c=F;else if(!c.H||b&&c.B(c.h,b))b&&(c.h=b),c.H=G;else return++m,c.g;const d=f,n=g,k=m;if(f=!c)(g[m]=c={m:4,B:O(b),h:b||E,g:F,U:a,H:G,v:[]}).v[0]={m:2,ca:g,W:c};g=c.v;m=1;try{c.g=a(...c.h)}catch(p){}f=d;g=n;m=k+1;return c.g},hook_transition:(a,b)=>{const c=T({ba:a});a=ta(va,[a,b,c]);return c.ba=a.fa<=t?a.ga:(qa(),a.$===t?a.aa:a.aa+(a.ga-a.aa)*(t-a.$)/(a.fa-a.$))},init:(a,b=da.body,c=F)=>{b.innerHTML="";a={u:{J:a,o:c},O:F,K:F,A:0,T:0,v:[],l:F,i:b,j:b,G:H};a.v[0]={m:0,
V:a};pa(a)},node:Y,node_dom:(a,b,c)=>Y(ya(a),b,c),node_map:(a,b,c)=>Y(P,{J:a,N:b,o:c||F}),now:()=>t}}
