'use strict';function aa(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}function f(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):{next:aa(a)}}function g(a){if(!(a instanceof Array)){a=f(a);for(var c,b=[];!(c=a.next()).done;)b.push(c.value);a=b}return a}function h(){for(var a=Number(this),c=[],b=a;b<arguments.length;b++)c[b-a]=arguments[b];return c};/*
 lui.js web frame work 1.3.6
 inspired by react and mithril
 L3P3.de 2022
*/
(function(){var p=null,r=!p,t=p,u=0,z=0,A=0,B=r,C=[],D=[],E={},F={},ba={},ca=[],G=[],da={},I=p,J=r,K=!r,ea=/[A-Z]/g,L=Array,fa=Object,ha=fa.assign,M=fa.keys,ja=document,ka=window.performance||Date;function la(a){return new Function("a","b","return a!==b&&("+a.join("||")+")")}function N(a){var c=(a=M(a)).join(",");return ba[c]||(ba[c]=la(a.map(function(b){return"a."+b+"!==b."+b})))}function ma(a,c){return a===c?G:M(a).filter(function(b){return a[b]!==c[b]})}
function O(a){return a?ca[a.length]||(ca[a.length]=la(a.map(function(c,b){return"a["+b+"]!==b["+b+"]"}))):I}
function Q(a,c){var b=p,d=c,k=b.v+1;t=b.s;u=1;b.B=K;if(b.u.H!==N){var e=I;try{e=(0,b.u.H)(b.u.o||da)}catch(Da){}var n=b.i;if(e){n&&(a=n,c=I);var m=e.length,l,v=b.l||(b.l=(new L(m)).fill(I));do{var q=v[--m];(l=e[m])&&l!==J?((r=!q)?((v[m]=p=q={u:l,N:l.o&&N(l.o),J:b,v:k,T:m,s:[],l:I,i:I,j:I,B:K}).s[0]={m:0,V:q},Q(a,c),q.i&&a.insertBefore(q.j=q.i,c)):l.o&&q.N(q.u.o,l.o)&&((p=q).u=l,Q(a,c)),q.j&&(c=q.j)):q&&(R(q,a),v[m]=I)}while(0<m)}else if(b.l){k=f(b.l);for(e=k.next();!e.done;e=k.next())(e=e.value)&&
R(e,a);b.l=I}n||(b.j=c!==d?c:I)}else{e=b.u.o;n=e.H;var w=e.M;e=e.o;m=w.length;q=J;if(!(0>=S(m,m)+m)){l=T();v={};var H=[];w=0<m&&na(w,v,H);if(l.K){q=e&&l.N(e,l.ea);for(var P=f(l.da),x=P.next();!x.done;x=P.next())x=x.value,x in v||(R(l.K[x],a),delete l.K[x]);l.ea=e;l.da=H}else l.K={},l.X=w?N(v[H[0]]):I,l.da=H,l.N=(l.ea=e)&&N(e);for(P=b.l=new L(m);0<m;){x=H[--m];var y=l.K[x];if(r=!y)(l.K[x]=p=y={u:{H:n,o:ha({I:v[x]},e)},N:I,J:b,v:k,T:m,s:[],l:I,i:I,j:I,B:K}).s[0]={m:0,V:y},Q(a,c),y.i&&a.insertBefore(y.j=
y.i,c);else{var ia=oa(y);ia&&ia.nextSibling!==c&&pa(y,a,c);if(q||w&&l.X(v[x],y.u.o.I))(p=y).u.o=ha({I:v[x]},e),Q(a,c)}(P[y.T=m]=y).j&&(c=y.j)}b.j=c!==d?c:I}}}function R(a,c){c&&a.i&&(c.removeChild(a.i),c=I);if(a.l)for(var b=f(a.l),d=b.next();!d.done;d=b.next())(d=d.value)&&R(d,c);U(a.s);if(a.B){var k,e;(!(e=C[k=a.v])||0>(k=e.indexOf(a)))&&(!(e=D[k])||0>(k=e.indexOf(a)))||e.splice(k,1)}}
function U(a){for(var c,b=a.length;1<b;)switch((c=a[--b]).m){case 1:c.O&&c.O.apply(c,g(c.h));break;case 2:c.h=G;break;case 3:qa(c);break;case 4:U(c.s)}}function na(a,c,b){var d,k="object"===typeof a[0];a=f(a);for(d=a.next();!d.done;d=a.next()){d=d.value;var e=k?d.id:d;c[e]=d;b.push(e)}return k}function oa(a){if(a.i)return a.i;var c;a=(c=a.l)?c.length:0;for(var b,d;0<a;)if((d=c[--a])&&(b=oa(d)))return b;return I}
function pa(a,c,b){if(a.i)return c.insertBefore(a.i,b),a.i;if(a.j){var d=a.l.length;do a.l[--d]&&(b=pa(a.l[d],c,b));while(0<d)}return b}function ra(a){for(;0!==a[0].m;){if(!a[0].W.G)return I;a[0].W.G=K;a=a[0].ca}return a[0].V}function V(a){return(a=ra(a))&&!a.B&&(a.B=J,C[a.v]?C[a.v].push(a):C[a.v]=[a],B||W())}function sa(){var a=ra(t);a&&(a.B=J,D[a.v]?D[a.v].push(a):D[a.v]=[a])}
function ta(a,c){if(u>=t.length)t[u]={m:1,A:O(c),h:c=c||G,O:a.apply(null,g(c))||I};else if(c){var b=t[u];b.A(b.h,c)&&(b.O&&b.O.apply(b,g(b.h)),b.O=a.apply(null,g(b.h=c))||I)}++u}function ua(a){if(u<t.length)return t[u++].g;var c=t,b=[a,function(d){b[0]!==d&&(b[0]=d,V(c))},function(){return b[0]}];t[u++]={m:0,g:b};return b}function T(a){return(u<t.length?t[u++]:t[u++]={m:0,g:void 0===a?{}:a}).g}
function va(a,c){return u>=t.length?(t[u++]={m:0,A:O(c),h:c=c||G,g:a.apply(null,g(c))}).g:c&&t[u].A(t[u].h,c)?t[u].g=a.apply(null,g(t[u++].h=c)):t[u++].g}function S(a,c){return u<t.length?(c=t[u].g,t[u++].g=a):t[u++]={m:0,g:a},c}function wa(a,c){return a=setTimeout(function(){return c(J)},a),function(){return clearTimeout(a)}}function qa(a){for(var c=f(a.Z),b=c.next();!b.done;b=c.next())U(a.L[b.value])}function xa(a,c,b){return{aa:b.ba,ga:a,$:z,fa:r?z:z+c}}
function X(a){var c=S(a,I);return c?ma(c,a):M(a)}
function Y(a){var c=p.i;if(a){for(var b=f(X(a)),d=b.next();!d.done;d=b.next()){d=d.value;switch(d.charCodeAt(0)){case 70:c.className=M(a.F).filter(function(k){return a.F[k]}).join(" ");continue;case 82:a.R(c);case 67:case 68:case 83:continue}c[d]=a[d]}if(a.D)for(b=f(X(a.D)),d=b.next();!d.done;d=b.next())d=d.value,c.setAttribute("data-"+d.replace(ea,"-$&").toLowerCase(),a.D[d]);if(a.S)for(b=f(X(a.S)),d=b.next();!d.done;d=b.next())d=d.value,c.style[d]=a.S[d]}return c}
function Z(a,c,b){return{H:a,o:c?b?(c.C=b,c):c:b?{C:b}:I}}
function W(){r=0>=z;z=ka.now();A&&cancelAnimationFrame(A);B=J;A=0;for(var a;(a=C).length;){C=[];a=f(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value){c=f(c);for(var b=c.next();!b.done;b=c.next())if(p=b.value,p.B){if(p.i)Q(I,I);else{var d,k=I;b=p.j;for(var e=p,n=p;!(d=(e=e.J).i););do for(var m=n.T,l=(n=n.J).l,v=l.length;++m<v&&l[m]&&!(k=l[m].j););while(!k&&n!==e);n=p;Q(d,k);if(n.j!==b)for(;!(n=n.J).i;){b=I;d=f(n.l);for(k=d.next();!(k.done||(k=k.value)&&(b=k.j));k=d.next());if(b===n.j)break;n.j=
b}}r=K}}}B=K;D.length&&(C=D,D=a,ya())}function ya(){return A||(A=requestAnimationFrame(W))}var za=W;function Aa(a){var c=E[a];if(!c){var b=a.indexOf("[");E[a]=c=ja.createElement(0>b?a:a.substring(0,b));if(0<b)for(a=f(a.substring(b+1,a.length-1).split("][")),b=a.next();!b.done;b=a.next()){b=b.value;var d=b.indexOf("=");0<d?c[b.substring(0,d)]=b.substr(d+1):c[b]=J}}return c}function Ba(a){var c=F[a];if(!c){var b=Aa(a);F[a]=c=function(d){return r&&(p.i=b.cloneNode(J)),Y(d),d&&d.C||I}}return c}
var Ca=L.prototype;Ca.fill||(Ca.fill=function(a){for(var c=this.length,b=0;b<c;++b)this[b]=a;return this});define({defer:function(){return B=J,ya()},defer_end:za,hook_assert:function(a){if(!a)throw E;},hook_async:function(a,c,b){var d;if((u<t.length?(d=t[u++],K):d=t[u++]={m:2,A:O(c),h:c||G,g:I})||c&&d.A(d.h,c)&&(d.h=c)){void 0!==b&&(d.g=b);var k=t;a.apply(null,g(d.h)).then(function(e){return d.g!==e&&d.h===c&&(d.g=e,V(k))})}return d.g},hook_callback:function(a,c){var b=T();b.h=c;return b.ha||(b.ha=function(){var d=h.apply(0,arguments);return a.apply(null,[].concat(g(b.h),g(d)))})},hook_delay:function(a){var c=
f(ua(K)),b=c.next().value;c=c.next().value;ta(wa,[a,c]);return b},hook_dom:function(a,c){return r&&(p.i=Aa(a).cloneNode(J)),Y(c||I)},hook_effect:ta,hook_map:function(a,c,b){var d=I,k=J;if(u<t.length)if((d=t[u]).U!==a)qa(d),d=I;else if(!d.G||b&&d.A(d.h,b))d.h=b||G,d.G=J;else{if(c===d.M)return++u,d.g;k=K}var e=r,n=t,m=++u,l={},v=[],q=0<c.length&&na(c,l,v);if(d){if(d.g=[],d.M!==c)for(d.M=c,c=f(d.Z),b=c.next();!b.done;b=c.next())b=b.value,b in l||(U(d.L[b]),delete d.L[b])}else t[m-1]=d={m:3,A:O(b),h:b||
G,g:[],G:J,U:a,X:q?N(c[0]):I,Z:[],L:{},M:c};c=f(v);for(b=c.next();!b.done;b=c.next()){b=b.value;var w=d.L[b];if(r=!w)d.L[b]=w=[{m:1,ca:n,W:d,Y:I,g:I}];if(k||r||(q?d.X(l[b],w[0].Y):l[b]!==w[0].Y)){t=w;u=1;try{w[0].g=a.apply(null,[w[0].Y=l[b]].concat(g(d.h)))}catch(H){}}d.g.push(w[0].g)}r=e;t=n;u=m;d.Z=v;return d.g},hook_memo:va,hook_model:function(a){if(u<t.length)return t[u++].g;for(var c=t,b=[(0,a.init)(I),{}],d={},k=f(M(a)),e=k.next();!e.done;d={P:d.P},e=k.next())d.P=e.value,b[1][d.P]=function(n){return function(){var m=
a[n.P].apply(null,[b[0]].concat(g(h.apply(0,arguments))));b[0]!==m&&(b[0]=m,V(c))}}(d);t[u++]={m:0,g:b};return b},hook_object_changes:X,hook_prev:S,hook_rerender:sa,hook_state:ua,hook_static:T,hook_sub:function(a,c){var b=I;if(u<t.length)if((b=t[u]).U!==a)U(b.s),b=I;else if(!b.G||c&&b.A(b.h,c))c&&(b.h=c),b.G=J;else return++u,b.g;var d=r,k=t,e=u;if(r=!b)(t[u]=b={m:4,A:O(c),h:c||G,g:I,U:a,G:J,s:[]}).s[0]={m:2,ca:t,W:b};t=b.s;u=1;try{b.g=a.apply(null,g(b.h))}catch(n){}r=d;t=k;u=e+1;return b.g},hook_transition:function(a,
c){var b=T({ba:a});a=va(xa,[a,c,b]);return b.ba=a.fa<=z?a.ga:(sa(),a.$===z?a.aa:a.aa+(a.ga-a.aa)*(z-a.$)/(a.fa-a.$))},init:function(a,c){var b;c.innerHTML="";(p={u:{H:function(){return Y((b=a())[0]),b[1]},o:I},N:I,J:I,v:0,T:0,s:[],l:I,i:c,j:c,B:J}).s[0]={m:0,V:p};C[0]=[p];W()},node:Z,node_dom:function(a,c,b){return Z(Ba(a),c,b)},node_map:function(a,c,b){return Z(N,{H:a,M:c,o:b||I})},now:function(){return z}})})()