'use strict';function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function e(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function g(a){if(!(a instanceof Array)){a=e(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function ba(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};/*
 lui.js web frame work 1.3.5
 inspired by react and mithril
 L3P3.de 2022
*/
(function(){var h=null,k=!h,q=h,t=0,u=0,v=0,w=k,z=[],A=[],D={},ca={},da={},ea=[],E=[],fa={},F=h,G=k,H=!k,ha=/[A-Z]/g,J=Array,K=Object,ia=K.assign,L=K.keys,ja=K.freeze||function(a){return a},ka=K.isFrozen||function(a){return null===a||"object"!==typeof a},la=document,ma=window,na=ma.performance||Date;
function oa(a){return void 0===a&&M("model state must not contain undefined, missing return?"),ka(a)||(ja(a).constructor!==J&&(a.constructor!==K&&M("model state must not contain shit like "+a.constructor.name),a=K.values(a)),a.forEach(oa))}function pa(a){a=a.s.A;return a===N?"list":a.name_||a.name||"?"}
function O(){var a=[],b=q,c=F;if(b){for(a.unshift("$"+(t-1));0!==b[0].j;)a.unshift(1===b[0].j?"hook_map["+("object"===typeof b[0].M?b[0].M.id:b[0].M)+"]":"hook_sub"),b=b[0].X;b=b[0].V}for(;b;)a.unshift(pa(b)+(c?":"+c:"")),c=b.T,b=b.L;return a.join("/")||"-"}function qa(){console.log.apply(console,g(ba.apply(0,arguments)))}function sa(a){var b=ba.apply(1,arguments);qa.apply(null,["lui "+O()+": "+a].concat(g(b)))}function M(a){throw Error("lui: "+a);}
function ta(a){qa("lui "+a+": error in callback");h=F}function P(a,b,c){try{return a.apply(null,g(b))}catch(d){throw ta(c),d;}}function va(a,b){a===b||a&&b&&JSON.stringify(L(a))===JSON.stringify(L(b))||M("object keys mismatch")}
function Q(a,b,c){q||M("hook called outside of hook context");c&&(c.constructor!==J&&M("deps must be in an array"),0===c.length&&M("deps must not be empty"));b&&0!==q[0].j&&M("hook called outside of component rendering");a!==F&&t<q.length&&(q[t].j!==a&&M("inconsistent hook order"),q[t].h&&wa(q[t].h,c))}function R(a,b){Q(F,H,F);a!==S(a,a)&&M(b+" changed between renderings")}function wa(a,b){b?a.length!==b.length&&M("deps length changed"):0<a.length&&M("deps presence changed")}
function xa(a){return new Function("a","b","return a!==b&&("+a.join("||")+")")}function N(a){var b=(a=L(a)).join(",");return da[b]||(0===a.length&&M("object empty"),a.some(function(c){return(c.includes("-")||"0123456789".includes(c.charAt(0)))&&M("invalid key: "+c)}),da[b]=xa(a.map(function(c){return"a."+c+"!==b."+c})))}function ya(a,b){return va(a,b),a===b?E:L(a).filter(function(c){return a[c]!==b[c]})}
function T(a){return a?ea[a.length]||(0===a.length&&M("deps must not be empty"),ea[a.length]=xa(a.map(function(b,c){return"a["+c+"]!==b["+c+"]"}))):F}
function U(a,b){var c=h,d=b,l=c.v+1;q=c.u;t=1;c.G=H;if(c.s.A!==N){var f=F;try{f=(0,c.s.A)(c.s.o||fa)}catch(ra){if(ra!==D)throw ra;}var p=c.i;"object"!==typeof f&&M("components need to return child list or null");if(f){p&&(a=p,b=F);var n=f.length,m;"number"!==typeof n&&M("childs must be returned in a list");0===n&&M("returned childs list empty");c.l&&n!==c.l.length&&M("returned childs count changed");var x=c.l||(c.l=(new J(n)).fill(F));do{var r=x[--n];if((m=f[n])&&m!==G){r&&r.s.A!==m.A&&M("child component changed at "+
n);if(k=!r)(x[n]=h=r={s:m,U:m.o&&N(m.o),L:c,v:l,T:n,u:[],l:F,i:F,m:F,G:H}).u[0]={j:0,V:r},U(a,b),r.i&&a.insertBefore(r.m=r.i,b);else if(va(r.s.o,m.o),m.o&&r.U(r.s.o,m.o))(h=r).s=m,U(a,b);r.m&&(b=r.m)}else r&&(V(r,a),x[n]=F)}while(0<n)}else if(c.l){l=e(c.l);for(f=l.next();!f.done;f=l.next())(f=f.value)&&V(f,a);c.l=F}p||(c.m=b!==d?b:F)}else{f=c.s.o;p=f.A;var y=f.P;f=f.o;"object"===typeof y&&y&&y.constructor===J||M("list_data must be an array");"object"!==typeof f&&M("props must be an object");R(p,"item component");
R(f&&L(f).join(","),"common props");n=y.length;r=G;if(!(0>=S(n,n)+n)){m=W();x={};var I=[];y=0<n&&za(y,x,I);n||W();if(m.N){r=f&&m.U(f,m.ea);for(var Y=e(m.da),B=Y.next();!B.done;B=Y.next())B=B.value,B in x||(V(m.N[B],a),delete m.N[B]);m.ea=f;m.da=I}else m.N={},m.Z=y?N(x[I[0]]):F,m.da=I,m.U=(m.ea=f)&&N(f);for(Y=c.l=new J(n);0<n;){B=I[--n];var C=m.N[B];if(k=!C)(m.N[B]=h=C={s:{A:p,o:ia({I:x[B]},f)},U:F,L:c,v:l,T:n,u:[],l:F,i:F,m:F,G:H}).u[0]={j:0,V:C},U(a,b),C.i&&a.insertBefore(C.m=C.i,b);else{var ua=
Aa(C);ua&&ua.nextSibling!==b&&Ba(C,a,b);if(r||y&&m.Z(x[B],C.s.o.I))(h=C).s.o=ia({I:x[B]},f),U(a,b)}(Y[C.T=n]=C).m&&(b=C.m)}c.m=b!==d?b:F}}}function V(a,b){b&&a.i&&(b.removeChild(a.i),b=F);if(a.l)for(var c=e(a.l),d=c.next();!d.done;d=c.next())(d=d.value)&&V(d,b);X(a.u);if(a.G){var l,f;(!(f=z[l=a.v])||0>(l=f.indexOf(a)))&&(!(f=A[l])||0>(l=f.indexOf(a)))||f.splice(l,1)}}
function X(a){for(var b,c=a.length;1<c;)switch((b=a[--c]).j){case 3:b.J&&b.J.apply(b,g(b.h));break;case 4:b.h=E;break;case 7:Ca(b);break;case 11:X(b.u)}}
function za(a,b,c){var d="object"===typeof a[0],l=W();l.ga||(a[0]!==F&&["object","string","number"].includes(l.ga=typeof a[0])||M("item type invalid"),d&&(!["string","number"].includes(l.ja=typeof a[0].id)&&M("item id type invalid"),l.keys=L(a[0]).join(",")));for(var f=e(a),p=f.next();!p.done;p=f.next())p=p.value,p===F&&M("item is null"),typeof p!==l.ga&&M("item type changed"),d&&(typeof p.id!==l.ja&&M("item id type changed"),L(p).join(",")!==l.keys&&M("item keys differ of "+p.id));a=e(a);for(p=a.next();!p.done;p=
a.next())l=p.value,f=d?l.id:l,f in b&&M("item key not unique: "+f),b[f]=l,c.push(f);return d}function Aa(a){if(a.i)return a.i;var b;a=(b=a.l)?b.length:0;for(var c,d;0<a;)if((d=b[--a])&&(c=Aa(d)))return c;return F}function Ba(a,b,c){if(a.i)return b.insertBefore(a.i,c),a.i;if(a.m){var d=a.l.length;do a.l[--d]&&(c=Ba(a.l[d],b,c));while(0<d)}return c}function Da(a){for(;0!==a[0].j;){if(!a[0].Y.H)return F;a[0].Y.H=H;a=a[0].X}return a[0].V}
function Ea(a){return(a=Da(a))&&!a.G&&(a.G=G,z[a.v]?z[a.v].push(a):z[a.v]=[a],w||Z())}function Fa(){Q(F,H,F);var a=Da(q);a&&(a.G=G,A[a.v]?A[a.v].push(a):A[a.v]=[a])}function Ga(a,b){Q(3,H,b);if(t>=q.length)q[t]={j:3,B:T(b),h:b=b||E,J:a.apply(null,g(b))||F};else if(b){var c=q[t];c.B(c.h,b)&&(c.J&&c.J.apply(c,g(c.h)),c.J=a.apply(null,g(c.h=b))||F)}q[t].J&&q[t].J.then&&M("effect function must be synchronous");++t}
function Ha(a){Q(5,H,F);if(t<q.length)return q[t++].g;var b=q,c=[a,function(d){c[0]!==d&&(c[0]=d,Ea(b))},function(){return c[0]}];q[t++]={j:5,g:c};return c}function W(a){return Q(6,H,F),(t<q.length?q[t++]:q[t++]={j:6,g:void 0===a?{}:a}).g}function Ia(a,b){return Q(8,H,b),t>=q.length?(q[t++]={j:8,B:T(b),h:b=b||E,g:a.apply(null,g(b))}).g:b&&q[t].B(q[t].h,b)?q[t].g=a.apply(null,g(q[t++].h=b)):q[t++].g}function S(a,b){return Q(9,H,F),t<q.length?(b=q[t].g,q[t++].g=a):q[t++]={j:9,g:a},b}
function Ja(a,b){return a=setTimeout(function(){return b(G)},a),function(){return clearTimeout(a)}}function Ca(a){for(var b=e(a.$),c=b.next();!c.done;c=b.next())X(a.O[c.value])}function Ka(a,b,c){return{ba:c.ca,ha:a,aa:u,fa:k?u:u+b}}function La(a){"object"===typeof a&&a||M("object required");var b=S(a,F);return b?ya(b,a):L(a)}
function Ma(a){R(!a,"attributes presence");var b=h.i;if(a){for(var c=e(La(a)),d=c.next();!d.done;d=c.next()){d=d.value;1<d.length&&d.charAt(0).toLowerCase()!==d.charAt(0)&&M("capital prop: "+d);switch(d.charCodeAt(0)){case 70:"object"===typeof a.F&&a.F||M("invalid css flags");b.className=L(a.F).filter(function(l){return a.F[l]}).join(" ");continue;case 82:"function"!==typeof a.R&&M("invalid ref"),a.R(b);case 67:case 68:case 83:continue}97>d.charCodeAt(0)&&M("invalid prop: "+d);b[d]=a[d]}R(!a.D,"dataset presence");
if(a.D)for(c=e(La(a.D)),d=c.next();!d.done;d=c.next())d=d.value,b.setAttribute("data-"+d.replace(ha,"-$&").toLowerCase(),a.D[d]);R(!a.S,"style presence");if(a.S)for(c=e(La(a.S)),d=c.next();!d.done;d=c.next())d=d.value,b.style[d]=a.S[d]}return b}function Na(a,b,c){return"string"===typeof a&&M("component expected, use node_dom instead"),c&&c.constructor!==J&&M("invalid childs type"),{A:a,o:b?c?(b.C=c,b):b:c?{C:c}:F}}
function Z(){k=0>=u;u=na.now();v&&cancelAnimationFrame(v);w=G;v=0;for(var a,b=0;(a=z).length;){10<++b&&M("rerender loop detected");z=[];a=e(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value){c=e(c);for(var d=c.next();!d.done;d=c.next())if(h=d.value,h.G){if(h.i)U(F,F);else{var l,f=F;d=h.m;for(var p=h,n=h;!(l=(p=p.L).i););do for(var m=n.T,x=(n=n.L).l,r=x.length;++m<r&&x[m]&&!(f=x[m].m););while(!f&&n!==p);n=h;U(l,f);if(n.m!==d)for(;!(n=n.L).i;){d=F;l=e(n.l);for(f=l.next();!(f.done||(f=f.value)&&
(d=f.m));f=l.next());if(d===n.m)break;n.m=d}}k=H}}}w=H;h=q=F;A.length&&(z=A,A=a,Oa())}function Oa(){return v||(v=requestAnimationFrame(Z))}
function Pa(a){var b=D[a];if(!b){var c=a.indexOf("[");b=0>c?a:a.substring(0,c);(0===b.length||b!==b.toLowerCase()||b.includes(" ")||b.includes("#")||b.includes("."))&&M("dom: invalid tag");D[a]=b=la.createElement(b);if(0<c)for(!a.endsWith("]")&&M("dom: ] missing"),a=e(a.substring(c+1,a.length-1).split("][")),c=a.next();!c.done;c=a.next()){c=c.value;!c&&M("dom: empty attribute");(c.includes("[")||c.includes("]"))&&M("dom: attributes screwed up");var d=c.indexOf("=");c.includes(" ")&&(0>d||c.indexOf(" ")<
d)&&M("dom: space in attribute name");0<d?b[c.substring(0,d)]=c.substr(d+1):b[c]=G}}return b}function Qa(a){var b=ca[a];if(!b){var c=Pa(a);ca[a]=b=function(d){return k&&(h.i=c.cloneNode(G)),Ma(d),d&&d.C||F};b.name_="$"+a}return b}ma.onerror=function(){return h&&sa("error in component"),z=A=[],H};var Ra=J.prototype;Ra.fill||(Ra.fill=function(a){for(var b=this.length,c=0;c<b;++c)this[c]=a;return this});define({defer:function(){return h&&M("defer while rendering"),w=G,Oa()},defer_end:function(){return h&&M("defer_end while rendering"),w||M("nothing was deferred"),Z()},hook_assert:function(a){Q(F,H,F);if(!a)throw D;},hook_async:function(a,b,c){Q(4,H,b);var d,l=O();if((t<q.length?(d=q[t++],H):d=q[t++]={j:4,B:T(b),h:b||E,g:F})||b&&d.B(d.h,b)&&(d.h=b)){void 0!==c&&(d.g=c);var f=q;a.apply(null,g(d.h)).then(function(p){return d.g!==p&&d.h===b&&(d.g=p,Ea(f))}).catch(function(p){ta(l);throw p;})}return d.g},
hook_callback:function(a,b){var c=t>=q.length?O():"";b&&b.length||M("deps required, use hook_static instead");var d=W();d.h&&wa(d.h,b);d.h=b;return d.ia||(d.ia=function(){var l=ba.apply(0,arguments);return P(a,[].concat(g(d.h),g(l)),c)})},hook_delay:function(a){var b=e(Ha(H)),c=b.next().value;b=b.next().value;Ga(Ja,[a,b]);return c},hook_dom:function(a,b){return Q(F,G,F),h.i?k&&M("hook_dom called twice"):k||M("hook_dom skipped before"),b&&(b.C&&M("hook_dom cannot have childs"),b.R&&M("hook_dom cannot have a ref")),
k&&(h.i=Pa(a).cloneNode(G)),Ma(b||F)},hook_effect:Ga,hook_map:function(a,b,c){Q(7,H,c);var d=F,l=G;if(t<q.length)if((d=q[t]).W!==a)Ca(d),d=F;else if(!d.H||c&&d.B(d.h,c))d.h=c||E,d.H=G;else{if(b===d.P)return++t,d.g;l=H}var f=k,p=q,n=++t,m={},x=[],r=0<b.length&&za(b,m,x);0===b.length&&W();if(d){if(d.g=[],d.P!==b)for(d.P=b,b=e(d.$),c=b.next();!c.done;c=b.next())c=c.value,c in m||(X(d.O[c]),delete d.O[c])}else q[n-1]=d={j:7,B:T(c),h:c||E,g:[],H:G,W:a,Z:r?N(b[0]):F,$:[],O:{},P:b};b=e(x);for(c=b.next();!c.done;c=
b.next()){c=c.value;var y=d.O[c];if(k=!y)d.O[c]=y=[{j:1,X:p,Y:d,M:F,g:F}];if(l||k||(r?d.Z(m[c],y[0].M):m[c]!==y[0].M)){q=y;t=1;try{y[0].g=a.apply(null,[y[0].M=m[c]].concat(g(d.h)))}catch(I){if(I!==D)throw I;}q=p}d.g.push(y[0].g)}k=f;q=p;t=n;d.$=x;return d.g},hook_memo:Ia,hook_model:function(a){Q(10,H,F);"object"===typeof a&&a||M("mutations object required");"function"!==typeof a.init&&M("init mutation required for initial value");if(t<q.length)return q[t++].g;var b=q,c=O(),d=[P(a.init,[F],c+" -> #init"),
{}];P(oa,[d[0]],c+" -> #init");for(var l={},f=e(L(a)),p=f.next();!p.done;l={K:l.K},p=f.next())l.K=p.value,d[1][l.K]=function(n){return function(m){m=P(a[n.K],[d[0],m],c+" -> #"+n.K);d[0]!==m&&(P(oa,[m],c+" -> #"+n.K),d[0]=m,Ea(b))}}(l);q[t++]={j:10,g:d};return d},hook_object_changes:La,hook_prev:S,hook_rerender:Fa,hook_state:Ha,hook_static:W,hook_sub:function(a,b){Q(11,H,b);var c=F;if(t<q.length)if((c=q[t]).W!==a)X(c.u),c=F;else if(!c.H||b&&c.B(c.h,b))b&&(c.h=b),c.H=G;else return++t,c.g;var d=k,l=
q,f=t;if(k=!c)(q[t]=c={j:11,B:T(b),h:b||E,g:F,W:a,H:G,u:[]}).u[0]={j:2,X:q,Y:c};q=c.u;t=1;try{c.g=a.apply(null,g(c.h))}catch(p){if(p!==D)throw p;}k=d;q=l;t=f+1;return c.g},hook_transition:function(a,b){var c=W({ca:a});a=Ia(Ka,[a,b,c]);return c.ca=a.fa<=u?a.ha:(Fa(),a.aa===u?a.ba:a.ba+(a.ha-a.ba)*(u-a.aa)/(a.fa-a.aa))},init:function(a,b){function c(){return(!(d=a())||2!==d.length)&&M("root component must return [props, childs]"),R(!d[0],"attributes presence"),d[0]!==F&&("object"!==typeof d[0]&&M("invalid props type"),
va(S(d[0],d[0]),d[0]),d[0].C&&M("root childs must be in second return value")),Ma(d[0]),d[1]}b||M("no root element specified");b.lui&&M("root element already mounted");b.lui=G;"function"!==typeof a&&M("no init function specified");var d;b.innerHTML="";c.name_="$root";(h={s:{A:c,o:F},U:F,L:F,v:0,T:0,u:[],l:F,i:b,m:b,G:G}).u[0]={j:0,V:h};z[0]=[h];h=q=F;Z()},node:Na,node_dom:function(a,b,c){return Na(Qa(a),b,c)},node_map:function(a,b,c){return Na(N,{A:a,P:b,o:c||F})},now:function(){return u}})})()