"use strict";/*
 lui.js web framework 2.3.0
 inspired by react and mithril
 l3p3.de 2025
*/
(function(){function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function g(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function h(a){if(!(a instanceof Array)){a=g(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
function ba(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};var k=null,p=!k,r=k,t=0,v=0,z=0,A=!p,B=[],C=[],D={},ca={},da={},ea=[k,function(a,b){return a!==b&&a[0]!==b[0]},function(a,b){return a!==b&&(a[0]!==b[0]||a[1]!==b[1])},function(a,b){return a!==b&&(a[0]!==b[0]||a[1]!==b[1]||a[2]!==b[2])}],E=[],fa={},F=k,G=p,I=A,ha=/[A-Z]/g,J=Array,K=Object,L=K.assign,M=K.keys;K.values||(K.values=function(a){var b=[],c;for(c in a)b.push(a[c]);return b});var ja=document,ka=window.performance||Date,la=navigator.userAgent.indexOf("WebKit")<0;
function N(a){var b=(a=M(a)).join(",");return da[b]||(da[b]=a)}function O(a,b,c){if(a===b)return!1;c=g(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,a[d]!==b[d])return!0;return!1}function ma(a,b){return a===b?E:M(a).filter(function(c){return a[c]!==b[c]})}function P(a){return a?a.length<5?ea[a.length]:na:F}function na(a,b){if(a===b)return!1;for(var c=0,d=a.length;c<d;++c)if(a[c]!==b[c])return!0;return!1}
function Q(a,b){var c=k,d=b,f=c.A+1;r=c.u;t=1;c.G=I;if(c.v.J!==Q){var e=F;try{e=(0,c.v.J)(c.v.o||fa)}catch(Ga){}var n=c.i;if(e){n&&(a=n,b=F);var m=e.length,l,u=c.l||(c.l=(new J(m)).fill(F));do{var q=u[--m];(l=e[m])&&l!==G?((p=!q)?(u[m]=k=q={v:l,O:l.o&&N(l.o),K:c,A:f,T:m,u:[],l:F,i:F,j:F,G:I},k.u[0]={m:0,V:q},Q(a,b),q.i&&a.insertBefore(q.j=q.i,b)):l.o&&O(q.v.o,l.o,q.O)&&((k=q).v=l,Q(a,b)),q.j&&(b=q.j)):q&&(R(q,a),u[m]=F)}while(m>0)}else if(c.l){f=g(c.l);for(e=f.next();!e.done;e=f.next())(e=e.value)&&
R(e,a);c.l=F}n||(c.j=b!==d?b:F)}else{e=c.v.o;n=e.J;var w=e.N;e=e.o;m=w.length;q=G;if(!(S(m,m)+m<=0)){l=U();u={};var H=[];w=m>0&&oa(w,u,H);if(l.L){q=e&&O(e,l.fa,l.O);for(var T=g(l.ea),x=T.next();!x.done;x=T.next())x=x.value,x in u||(R(l.L[x],a),delete l.L[x]);l.fa=e;l.ea=H}else l.L={},l.X=w?N(u[H[0]]):F,l.ea=H,l.O=(l.fa=e)&&N(e);for(T=c.l=new J(m);m>0;){x=H[--m];var y=l.L[x];if(p=!y)l.L[x]=k=y={v:{J:n,o:L({I:u[x]},e)},O:F,K:c,A:f,T:m,u:[],l:F,i:F,j:F,G:I},k.u[0]={m:0,V:y},Q(a,b),y.i&&a.insertBefore(y.j=
y.i,b);else{var ia=pa(y);ia&&ia.nextSibling!==b&&qa(y,a,b);if(q||w&&O(u[x],y.v.o.I,l.X))(k=y).v.o=L({I:u[x]},e),Q(a,b)}(T[y.T=m]=y).j&&(b=y.j)}c.j=b!==d?b:F}}}function R(a,b){b&&a.i&&(b.removeChild(a.i),b=F);if(a.l)for(var c=g(a.l),d=c.next();!d.done;d=c.next())(d=d.value)&&R(d,b);V(a.u);if(a.G){var f,e;(!(e=B[f=a.A])||(f=e.indexOf(a))<0)&&(!(e=C[f])||(f=e.indexOf(a))<0)||e.splice(f,1)}}
function V(a){for(var b,c=a.length;c>1;)switch((b=a[--c]).m){case 1:b.P&&b.P.apply(b,h(b.h));break;case 2:b.h=E;break;case 3:ra(b);break;case 4:V(b.u)}}function oa(a,b,c){var d=typeof a[0]==="object";a=g(a);for(var f=a.next();!f.done;f=a.next()){f=f.value;var e=d?f.id:f;b[e]=f;c.push(e)}return d}function pa(a){if(a.i)return a.i;var b;a=(b=a.l)?b.length:0;for(var c,d;a>0;)if((d=b[--a])&&(c=pa(d)))return c;return F}
function qa(a,b,c){if(a.i)return b.insertBefore(a.i,c);if(a.j){var d=a.l.length;do a.l[--d]&&(c=qa(a.l[d],b,c));while(d>0)}return c}function sa(a){for(;a[0].m!==0;){if(!a[0].W.H)return F;a[0].W.H=I;a=a[0].da}return a[0].V}function W(a){return(a=sa(a))&&ta(a)}function ta(a){return!a.G&&(a.G=G,B[a.A]?B[a.A].push(a):B[a.A]=[a],A||X())}function ua(){var a=sa(r);a&&(a.G=G,C[a.A]?C[a.A].push(a):C[a.A]=[a])}
function va(a,b){if(t>=r.length)r[t]={m:1,B:P(b),h:b=b||E,P:a.apply(null,h(b))||F};else if(b){var c=r[t];c.B(c.h,b)&&(c.P&&c.P.apply(c,h(c.h)),c.P=a.apply(null,h(c.h=b))||F)}++t}function wa(a){if(t<r.length)return r[t++].g;var b=r,c=[a,function(d){c[0]!==d&&(c[0]=d,W(b));return d},function(){return c[0]}];r[t++]={m:0,g:c};return c}function U(a){return(t<r.length?r[t++]:r[t++]={m:0,g:a===void 0?{}:a}).g}
function xa(a,b){return t>=r.length?(r[t++]={m:0,B:P(b),h:b=b||E,g:a.apply(null,h(b))}).g:b&&r[t].B(r[t].h,b)?r[t].g=a.apply(null,h(r[t++].h=b)):r[t++].g}function S(a,b){return t<r.length?(b=r[t].g,r[t++].g=a):r[t++]={m:0,g:a},b}function ya(a,b){return a=setTimeout(function(){return b(G)},a),function(){return clearTimeout(a)}}function ra(a){for(var b=g(a.Z),c=b.next();!c.done;c=b.next())V(a.M[c.value])}function za(a,b,c){return{ba:c.ca,ha:a,aa:v,ga:p?v:v+b}}
function Y(a){var b=S(a,F);return b?ma(b,a):M(a)}
function Aa(a){var b=k.i;if(a){for(var c=g(Y(a)),d=c.next();!d.done;d=c.next()){d=d.value;switch(d.charCodeAt(0)){case 70:b.className=M(a.F).filter(function(f){return a.F[f]}).join(" ");continue;case 82:a.R(b);case 67:case 68:case 83:continue}b[d]=a[d]}if(a.D)for(c=g(Y(a.D)),d=c.next();!d.done;d=c.next())d=d.value,b.setAttribute("data-"+d.replace(ha,"-$&").toLowerCase(),a.D[d]);if(a.S)for(c=g(Y(a.S)),d=c.next();!d.done;d=c.next())d=d.value,b.style[d]=a.S[d]}return b}
function Z(a,b,c){return{J:a,o:b?c?(b.C=c,b):b:c?{C:c}:F}}
function X(){p=v<=0;v=ka.now();z&&cancelAnimationFrame(z);A=G;z=0;for(var a;(a=B).length;){B=[];a=g(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value){b=g(b);for(var c=b.next();!c.done;c=b.next())if(k=c.value,k.G){if(k.i)Q(F,F);else{var d,f=F;c=k.j;for(var e=k,n=k;!(d=(e=e.K).i););do for(var m=n.T,l=(n=n.K).l,u=l.length;++m<u&&l[m]&&!(f=l[m].j););while(!f&&n!==e);n=k;Q(d,f);if(n.j!==c)for(;!(n=n.K).i;){c=F;d=g(n.l);for(f=d.next();!(f.done||(f=f.value)&&(c=f.j));f=d.next());if(c===n.j)break;n.j=
c}}p=I}}}A=I;C.length&&(B=C,C=a,Ba())}function Ba(){return z||(z=requestAnimationFrame(X))}var Ca=X;function Da(a){var b=D[a];if(!b){var c=a.indexOf("[");D[a]=b=ja.createElement(c<0?a:a.substr(0,c));if(c>0)for(a=g(a.substring(c+1,a.length-1).split("][")),c=a.next();!c.done;c=a.next()){c=c.value;var d=c.indexOf("="),f=c.substr(0,d);d<0?b[c]=G:la||f!=="style"?b[f]=c.substr(d+1):b.setAttribute(f,c.substr(d+1))}}return b}
function Ea(a){var b=ca[a];if(!b){var c=Da(a);ca[a]=b=function(d){return p&&(k.i=c.cloneNode(G)),Aa(d),d&&d.C||F}}return b}var Fa=J.prototype;K.entries||(K.entries=function(a){var b=[],c;for(c in a)b.push([c,a[c]]);return b},Fa.fill||(Fa.fill=function(a){for(var b=this.length,c=0;c<b;++c)this[c]=a;return this}));define({defer:function(){return A=G,Ba()},defer_end:Ca,dom_define:function(a,b,c){b=Da(b);c&&(b=b.cloneNode(G),c.D&&(L(b.dataset,c.D),delete c.D),c.S&&(L(b.style,c.S),delete c.S),L(b,c));D["#"+a]=b},hook_assert:function(a){if(!a)throw D;},hook_async:function(a,b,c){var d;if((t<r.length?(d=r[t++],I):d=r[t++]={m:2,B:P(b),h:b||E,g:F})||b&&d.B(d.h,b)&&(d.h=b)){c!==void 0&&(d.g=c);var f=r;a.apply(null,h(d.h)).then(function(e){return d.g!==e&&d.h===b&&(d.g=e,W(f))})}return d.g},hook_callback:function(a,
b){var c=U();c.h=b;return c.ia||(c.ia=function(){var d=ba.apply(0,arguments);return a.apply(null,[].concat(h(c.h),h(d)))})},hook_delay:function(a){var b=g(wa(I)),c=b.next().value;b=b.next().value;va(ya,[a,b]);return c},hook_dom:function(a,b){return k.i===F&&(k.i=Da(a).cloneNode(G)),Aa(b||F)},hook_effect:va,hook_map:function(a,b,c){var d=F,f=G;if(t<r.length)if((d=r[t]).U!==a)ra(d),d=F;else if(!d.H||c&&d.B(d.h,c))d.h=c||E,d.H=G;else{if(b===d.N)return++t,d.g;f=I}var e=p,n=r,m=++t,l={},u=[],q=b.length>
0&&oa(b,l,u);if(d){if(d.g=[],d.N!==b)for(d.N=b,b=g(d.Z),c=b.next();!c.done;c=b.next())c=c.value,c in l||(V(d.M[c]),delete d.M[c])}else r[m-1]=d={m:3,B:P(c),h:c||E,g:[],H:G,U:a,X:q?N(b[0]):F,Z:[],M:{},N:b};b=g(u);for(c=b.next();!c.done;c=b.next()){c=c.value;var w=d.M[c];if(p=!w)d.M[c]=w=[{m:1,da:n,W:d,Y:F,g:F}];if(f||p||(q?O(l[c],w[0].Y,d.X):l[c]!==w[0].Y)){r=w;t=1;try{w[0].g=a.apply(null,[w[0].Y=l[c]].concat(h(d.h)))}catch(H){}}d.g.push(w[0].g)}p=e;r=n;t=m;d.Z=u;return d.g},hook_memo:xa,hook_model:function(a){if(t<
r.length)return r[t++].g;for(var b=r,c=[(0,a.init)(F),{}],d=g(M(a)),f=d.next(),e={};!f.done;e={$:void 0},f=d.next())e.$=f.value,c[1][e.$]=function(n){return function(){var m=a[n.$].apply(null,[c[0]].concat(h(ba.apply(0,arguments))));c[0]!==m&&(c[0]=m,W(b));return m}}(e);r[t++]={m:0,g:c};return c},hook_object_changes:Y,hook_prev:S,hook_rerender:ua,hook_state:wa,hook_static:U,hook_sub:function(a,b){var c=F;if(t<r.length)if((c=r[t]).U!==a)V(c.u),c=F;else if(!c.H||b&&c.B(c.h,b))b&&(c.h=b),c.H=G;else return++t,
c.g;var d=p,f=r,e=t;if(p=!c)(r[t]=c={m:4,B:P(b),h:b||E,g:F,U:a,H:G,u:[]}).u[0]={m:2,da:r,W:c};r=c.u;t=1;try{c.g=a.apply(null,h(c.h))}catch(n){}p=d;r=f;t=e+1;return c.g},hook_transition:function(a,b){var c=U({ca:a});a=xa(za,[a,b,c]);return c.ca=a.ga<=v?a.ha:(ua(),a.aa===v?a.ba:a.ba+(a.ha-a.ba)*(v-a.aa)/(a.ga-a.aa))},init:function(a,b,c){b=b===void 0?ja.body:b;c=c===void 0?F:c;b.innerHTML="";a={v:{J:a,o:c},O:F,K:F,A:0,T:0,u:[],l:F,i:b,j:b,G:I};a.u[0]={m:0,V:a};ta(a)},node:Z,node_dom:function(a,b,c){return Z(Ea(a),
b,c)},node_map:function(a,b,c){return Z(Q,{J:a,N:b,o:c||F})},now:function(){return v}})})()
