"use strict";/*
 lui.js web framework 2.4.0
 inspired by react and mithril
 l3p3.de 2025
*/
{let e=null,f=!e,g=e,m=0,r=0,t=0,w=!f,x=[],z=[];
const A={},B={},C={},aa=[e,(a,b)=>a!==b&&a[0]!==b[0],(a,b)=>a!==b&&(a[0]!==b[0]||a[1]!==b[1]),(a,b)=>a!==b&&(a[0]!==b[0]||a[1]!==b[1]||a[2]!==b[2])],E=[],ba={},G=e,H=f,I=w,J=Array,K=Object,M=K.assign,N=K.keys,ca=document,da=window,ea=da.performance||Date,O=a=>{const b=(a=N(a)).join(",");return C[b]||(C[b]=a)},P=(a,b,c)=>{if(a===b)return!1;for(const d of c)if(a[d]!==b[d])return!0;return!1},fa=(a,b)=>a===b?E:N(a).filter(c=>a[c]!==b[c]),Q=a=>a?a.length<5?aa[a.length]:ha:G,ha=(a,b)=>{if(a===b)return!1;
for(let c=0,d=a.length;c<d;++c)if(a[c]!==b[c])return!0;return!1},R=(a,b)=>{const c=e,d=c.B+1;let k=b;g=c.v;m=1;c.A=I;if(c.u.K!==R){var l=G;try{l=(0,c.u.K)(c.u.l||ba)}catch(F){if(c.A)return}var n=c.i;if(l){n&&(a=n,k=G);var p=l.length,q,v=c.m||(c.m=(new J(p)).fill(G));do{var h=v[--p];(q=l[p])&&q!==H?((f=!h)?(v[p]=e=h={u:q,P:q.l&&O(q.l),L:c,B:d,$:p,v:[],m:G,i:G,o:G,A:I},e.v[0]={j:0,U:h},R(a,k),h.i&&a.insertBefore(h.o=h.i,k)):q.l&&P(h.u.l,q.l,h.P)&&((e=h).u=q,R(a,k)),h.o&&(k=h.o)):h&&(S(h,a),v[p]=G)}while(p>
0)}else if(c.m){for(p of c.m)p&&S(p,n||a);c.m=G}if(n)return}else{q=c.u.l.K;var u=c.u.l.O;l=c.u.l.l;n=u.length;p=H;h=T();v={};const F=[];u=n>0&&ia(u,v,F);if(h.M){if(!(h.Z.length|n))return;p=l&&P(l,h.ea,h.P);for(var D of h.Z)D in v||(S(h.M[D],a),delete h.M[D]);h.ea=l;h.Z=F}else{if(n===0)return;h.M={};h.W=u?O(v[F[0]]):G;h.Z=F;h.P=(h.ea=l)&&O(l)}for(D=c.m=new J(n);n>0;){const L=F[--n];let y=h.M[L];if(f=!y)h.M[L]=e=y={u:{K:q,l:M({I:v[L]},l)},P:G,L:c,B:d,$:0,v:[],m:G,i:G,o:G,A:I},e.v[0]={j:0,U:y},R(G,G),
a.insertBefore(y.i,k);else{if(p||u&&P(v[L],y.u.l.I,h.W))(e=y).u.l=M({I:v[L]},l),R(G,G);y.i.nextSibling!==k&&a.insertBefore(y.i,k)}k=(D[n]=y).i}}c.o=k!==b?k:G},S=(a,b)=>{b&&a.i&&(a.i.remove(),b=G);if(a.m)for(const c of a.m)c&&S(c,b);U(a.v);if(a.A){let c,d;(!(d=x[c=a.B])||(c=d.indexOf(a))<0)&&(!(d=z[c])||(c=d.indexOf(a))<0)||d.splice(c,1)}},U=a=>{let b,c=a.length;for(;c>1;)switch((b=a[--c]).j){case 1:b.J&&b.J(...b.h);break;case 2:b.h=E;break;case 3:ja(b);break;case 4:U(b.v)}},ia=(a,b,c)=>{const d=typeof a[0]===
"object";for(const k of a)a=d?k.id:k,b[a]=k,c.push(a);return d},ka=a=>{for(;a[0].j!==0;){if(!a[0].V.H)return G;a[0].V.H=I;a=a[0].da}return a[0].U},V=a=>(a=ka(a))&&la(a),la=a=>!a.A&&(a.A=H,x[a.B]?x[a.B].push(a):x[a.B]=[a],w||W()),ma=()=>{const a=ka(g);a&&(a.A=H,z[a.B]?z[a.B].push(a):z[a.B]=[a])},na=(a,b)=>{if(m>=g.length)(g[m]={j:1,G:Q(b),h:b=b||E,J:G}).J=a(...b)||G;else if(b){const c=g[m];c.G(c.h,b)&&(c.J&&c.J(...c.h),c.J=G,c.J=a(...(c.h=b))||G)}++m},oa=a=>{if(m<g.length)return g[m++].g;const b=g,
c=[a,d=>{if(c[0]!==d&&(c[0]=d,V(b),g===b))throw A;return d},()=>c[0]];g[m++]={j:0,g:c};return c},T=a=>(m<g.length?g[m++]:g[m++]={j:0,g:a===void 0?{}:a}).g,pa=(a,b)=>m>=g.length?(g[m++]={j:0,G:Q(b),h:b=b||E,g:a(...b)}).g:b&&g[m].G(g[m].h,b)?g[m].g=a(...(g[m++].h=b)):g[m++].g,qa=(a,b)=>(m<g.length?(b=g[m].g,g[m++].g=a):g[m++]={j:0,g:a},b),ra=(a,b)=>(a=setTimeout(()=>b(H),a),()=>clearTimeout(a)),ja=a=>{for(const b of a.Y)U(a.N[b])},sa=(a,b,c)=>({ba:c.ca,ga:a,aa:r,fa:f?r:r+b}),X=a=>{const b=qa(a,G);return b?
fa(b,a):N(a)},ta=a=>{const b=e.i;if(a){for(const c of X(a)){switch(c.charCodeAt(0)){case 70:b.className=N(a.F).filter(d=>a.F[d]).join(" ");continue;case 82:a.R(b);case 67:case 68:case 83:continue}b[c]=a[c]}if(a.D)for(const c of X(a.D))b.dataset[c]=a.D[c];if(a.S)for(const c of X(a.S))b.style[c]=a.S[c]}return b},Y=(a,b,c)=>({K:a,l:b?c?(b.C=c,b):b:c?{C:c}:G}),W=()=>{f=r<=0;r=ea.now();t&&cancelAnimationFrame(t);w=H;t=0;for(var a;(a=x).length;){x=[];for(const b of a)if(b)for(e of b)if(e.A){if(e.i)R(G,
G);else{let c=G,d=e.o,k=e,l=e;for(;!(a=(k=k.L).i););do{let n=l.$;const {m:p}=l=l.L,q=p.length;for(;++n<q&&p[n]&&!(c=p[n].o););}while(!c&&l!==k);l=e;R(a,c);if(l.o!==d)for(;!(l=l.L).i;){d=G;for(const n of l.m)if(n&&(d=n.o))break;if(d===l.o)break;l.o=d}}f=I}}w=I;z.length&&(x=z,z=a,ua())},ua=()=>t||(t=requestAnimationFrame(W)),Z=a=>{let b=A[a];if(!b){const c=a.indexOf("[");A[a]=b=ca.createElement(c<0?a:a.substr(0,c));if(c>0)for(const d of a.substring(c+1,a.length-1).split("]["))a=d.indexOf("="),a>0?b[d.substr(0,
a)]=d.substr(a+1):b[d]=H}return b},va=a=>{let b=B[a];if(!b){const c=Z(a);B[a]=b=d=>(f&&(e.i=c.cloneNode(H)),ta(d),d&&d.C||G)}return b};da.lui={defer:()=>(w=H,ua()),defer_end:W,dom_define:(a,b,c)=>{b=Z(b);c&&(b=b.cloneNode(H),c.D&&(M(b.dataset,c.D),delete c.D),c.S&&(M(b.style,c.S),delete c.S),M(b,c));A["#"+a]=b},hook_assert:a=>{if(!a)throw A;},hook_async:(a,b,c)=>{let d;if((m<g.length?(d=g[m++],I):d=g[m++]={j:2,G:Q(b),h:b||E,g:G})||b&&d.G(d.h,b)&&(d.h=b)){c!==void 0&&(d.g=c);const k=g;a(...d.h).then(l=>d.g!==l&&d.h===b&&(d.g=l,V(k)))}return d.g},hook_callback:(a,b)=>{const c=T();c.h=b;return c.ha||(c.ha=(...d)=>a(...c.h,...d))},hook_delay:a=>
{const [b,c]=oa(I);na(ra,[a,c]);return b},hook_dom:(a,b)=>(e.i===G&&(e.i=Z(a).cloneNode(H)),ta(b||G)),hook_effect:na,hook_map:(a,b,c)=>{let d=G,k=H;if(m<g.length)if((d=g[m]).T!==a)ja(d),d=G;else if(!d.H||c&&d.G(d.h,c))d.h=c||E,d.H=H;else{if(b===d.O)return++m,d.g;k=I}const l=f,n=g,p=++m,q={},v=[],h=b.length>0&&ia(b,q,v);if(d){if(d.g=[],d.O!==b){d.O=b;for(const u of d.Y)u in q||(U(d.N[u]),delete d.N[u])}}else g[p-1]=d={j:3,G:Q(c),h:c||E,g:[],H,T:a,W:h?O(b[0]):G,Y:[],N:{},O:b};for(const u of v){b=d.N[u];
if(f=!b)d.N[u]=b=[{j:1,da:n,V:d,X:G,g:G}];if(k||f||(h?P(q[u],b[0].X,d.W):q[u]!==b[0].X)){g=b;m=1;try{b[0].g=a(b[0].X=q[u],...d.h)}catch(D){if(e.A)throw D;}}d.g.push(b[0].g)}f=l;g=n;m=p;d.Y=v;return d.g},hook_memo:pa,hook_model:a=>{if(m<g.length)return g[m++].g;const b=g,c=[(0,a.init)(G),{}];for(const d of N(a))c[1][d]=(...k)=>{k=(0,a[d])(c[0],...k);if(c[0]!==k&&(c[0]=k,V(b),g===b))throw A;return k};g[m++]={j:0,g:c};return c},hook_object_changes:X,hook_prev:qa,hook_rerender:ma,hook_state:oa,hook_static:T,
hook_sub:(a,b)=>{let c=G;if(m<g.length)if((c=g[m]).T!==a)U(c.v),c=G;else if(!c.H||b&&c.G(c.h,b))b&&(c.h=b),c.H=H;else return++m,c.g;const d=f,k=g,l=m;if(f=!c)(g[m]=c={j:4,G:Q(b),h:b||E,g:G,T:a,H,v:[]}).v[0]={j:2,da:g,V:c};g=c.v;m=1;try{c.g=a(...c.h)}catch(n){if(e.A)throw n;}f=d;g=k;m=l+1;return c.g},hook_transition:(a,b)=>{const c=T({ca:a});a=pa(sa,[a,b,c]);return c.ca=a.fa<=r?a.ga:(ma(),a.aa===r?a.ba:a.ba+(a.ga-a.ba)*(r-a.aa)/(a.fa-a.aa))},init:(a,b=ca.body,c=G)=>{b.innerHTML="";a={u:{K:a,l:c},P:G,
L:G,B:0,$:0,v:[],m:G,i:b,o:b,A:I};a.v[0]={j:0,U:a};la(a)},node:Y,node_dom:(a,b,c)=>Y(va(a),b,c),node_map:(a,b,c)=>Y(R,{K:a,O:b,l:c||G}),now:()=>r}}
