"use strict";/*
 lui.js web framework 2.4.1
 inspired by react and mithril
 l3p3.de 2025
*/
{let e=null,f=!e,g=e,m=0,r=0,t=0,w=!f,x=[],z=[];
const A={},B={},C={},aa=[e,(a,b)=>a!==b&&a[0]!==b[0],(a,b)=>a!==b&&(a[0]!==b[0]||a[1]!==b[1]),(a,b)=>a!==b&&(a[0]!==b[0]||a[1]!==b[1]||a[2]!==b[2])],E=[],ba={},G=e,H=f,I=w,J=Array,ca=Object,K=ca.assign,M=ca.keys,da=document,ea=window,fa=ea.performance||Date,N=a=>{const b=(a=M(a)).join(",");return C[b]||(C[b]=a)},O=(a,b,c)=>{if(a===b)return!1;for(const d of c)if(a[d]!==b[d])return!0;return!1},ha=(a,b)=>a===b?E:M(a).filter(c=>a[c]!==b[c]),P=a=>a?a.length<5?aa[a.length]:ia:G,ia=(a,b)=>{if(a===b)return!1;
for(let c=0,d=a.length;c<d;++c)if(a[c]!==b[c])return!0;return!1},Q=(a,b)=>{const c=e,d=c.B+1;let k=b;g=c.v;m=1;c.A=I;if(c.u.K!==Q){var l=G;try{l=(0,c.u.K)(c.u.l||ba)}catch(F){if(c.A)return}var n=c.i;if(l){n&&(a=n,k=G);var p=l.length,q,v=c.m||(c.m=(new J(p)).fill(G));do{var h=v[--p];(q=l[p])&&q!==H?((f=!h)?(v[p]=e=h={u:q,T:q.l&&N(q.l),L:c,B:d,aa:p,v:[],m:G,i:G,o:G,A:I,M:I},e.v[0]={j:0,V:h},Q(a,k),h.i&&a.insertBefore(h.o=h.i,k)):q.l&&O(h.u.l,q.l,h.T)&&((e=h).u=q,Q(a,k)),h.o&&(k=h.o)):h&&(R(h,a),v[p]=
G)}while(p>0)}else if(c.m){n&&(a=n);for(p of c.m)p&&R(p,a);c.m=G}if(n)return}else{q=c.u.l.K;var u=c.u.l.P;l=c.u.l.l;n=u.length;p=H;h=S();v={};const F=[];u=n>0&&ja(u,v,F);if(h.N){if(!(h.$.length|n))return;p=l&&O(l,h.fa,h.T);for(var D of h.$)D in v||(R(h.N[D],a),delete h.N[D]);h.fa=l;h.$=F}else{if(n===0)return;h.N={};h.X=u?N(v[F[0]]):G;h.$=F;h.T=(h.fa=l)&&N(l)}for(D=c.m=new J(n);n>0;){const L=F[--n];let y=h.N[L];if(f=!y)h.N[L]=e=y={u:{K:q,l:K({I:v[L]},l)},T:G,L:c,B:d,aa:0,v:[],m:G,i:G,o:G,A:I,M:I},
e.v[0]={j:0,V:y},Q(G,G),a.insertBefore(y.i,k);else{if(p||u&&O(v[L],y.u.l.I,h.X))(e=y).u.l=K({I:v[L]},l),Q(G,G);y.i.nextSibling!==k&&a.insertBefore(y.i,k)}k=(D[n]=y).i}}c.o=k!==b?k:G},R=(a,b)=>{b&&a.i&&(a.i.remove(),b=G);if(b||a.M){if(a.m)for(const c of a.m)c&&R(c,b);a.M&&T(a.v)}if(a.A){let c,d;(!(d=x[c=a.B])||(c=d.indexOf(a))<0)&&(!(d=z[c])||(c=d.indexOf(a))<0)||d.splice(c,1)}},T=a=>{let b,c=a.length;for(;c>1;)switch((b=a[--c]).j){case 1:b.J&&b.J(...b.h);break;case 2:b.h=E;break;case 3:ka(b);break;
case 4:T(b.v)}},ja=(a,b,c)=>{const d=typeof a[0]==="object";for(const k of a)a=d?k.id:k,b[a]=k,c.push(a);return d},la=a=>{for(;a[0].j!==0;){if(!a[0].W.H)return G;a[0].W.H=I;a=a[0].ea}return a[0].V},U=a=>(a=la(a))&&ma(a),ma=a=>!a.A&&(a.A=H,x[a.B]?x[a.B].push(a):x[a.B]=[a],w||V()),W=()=>{let a=e;for(;a&&!a.M;)a.M=H,a=a.L},na=()=>{const a=la(g);a&&(a.A=H,z[a.B]?z[a.B].push(a):z[a.B]=[a])},oa=(a,b)=>{if(m>=g.length)((g[m]={j:1,G:P(b),h:b=b||E,J:G}).J=a(...b)||G)&&W();else if(b){const c=g[m];c.G(c.h,b)&&
(c.J&&c.J(...c.h),c.J=G,(c.J=a(...(c.h=b))||G)&&W())}++m},pa=a=>{if(m<g.length)return g[m++].g;const b=g,c=[a,d=>{if(c[0]!==d&&(c[0]=d,U(b),g===b))throw A;return d},()=>c[0]];g[m++]={j:0,g:c};return c},S=a=>(m<g.length?g[m++]:g[m++]={j:0,g:a===void 0?{}:a}).g,qa=(a,b)=>m>=g.length?(g[m++]={j:0,G:P(b),h:b=b||E,g:a(...b)}).g:b&&g[m].G(g[m].h,b)?g[m].g=a(...(g[m++].h=b)):g[m++].g,ra=(a,b)=>(m<g.length?(b=g[m].g,g[m++].g=a):g[m++]={j:0,g:a},b),sa=(a,b)=>(a=setTimeout(()=>b(H),a),()=>clearTimeout(a)),
ka=a=>{for(const b of a.Z)T(a.O[b])},ta=(a,b,c)=>({ca:c.da,ha:a,ba:r,ga:f?r:r+b}),X=a=>{const b=ra(a,G);return b?ha(b,a):M(a)},ua=a=>{const b=e.i;if(a){for(const c of X(a)){switch(c.charCodeAt(0)){case 70:b.className=M(a.F).filter(d=>a.F[d]).join(" ");continue;case 82:a.R(b);case 67:case 68:case 83:continue}b[c]=a[c]}if(a.D)for(const c of X(a.D))b.dataset[c]=a.D[c];if(a.S)for(const c of X(a.S))b.style[c]=a.S[c]}return b},Y=(a,b,c)=>({K:a,l:b?c?(b.C=c,b):b:c?{C:c}:G}),V=()=>{f=r<=0;r=fa.now();t&&cancelAnimationFrame(t);
w=H;t=0;for(var a;(a=x).length;){x=[];for(const b of a)if(b)for(e of b)if(e.A){if(e.i)Q(G,G);else{let c=G,d=e.o,k=e,l=e;for(;!(a=(k=k.L).i););do{let n=l.aa;const {m:p}=l=l.L,q=p.length;for(;++n<q&&p[n]&&!(c=p[n].o););}while(!c&&l!==k);l=e;Q(a,c);if(l.o!==d)for(;!(l=l.L).i;){d=G;for(const n of l.m)if(n&&(d=n.o))break;if(d===l.o)break;l.o=d}}f=I}}w=I;z.length&&(x=z,z=a,va())},va=()=>t||(t=requestAnimationFrame(V)),Z=a=>{let b=A[a];if(!b){const c=a.indexOf("[");A[a]=b=da.createElement(c<0?a:a.substr(0,
c));if(c>0)for(const d of a.substring(c+1,a.length-1).split("]["))a=d.indexOf("="),a>0?b[d.substr(0,a)]=d.substr(a+1):b[d]=H}return b},wa=a=>{let b=B[a];if(!b){const c=Z(a);B[a]=b=d=>(f&&(e.i=c.cloneNode(H)),ua(d),d&&d.C||G)}return b};ea.lui={defer:()=>(w=H,va()),defer_end:V,dom_define:(a,b,c)=>{b=Z(b);c&&(b=b.cloneNode(H),c.D&&(K(b.dataset,c.D),delete c.D),c.S&&(K(b.style,c.S),delete c.S),K(b,c));A["#"+a]=b},hook_assert:a=>{if(!a)throw A;},hook_async:(a,b,c)=>{let d;if((m<g.length?(d=g[m++],I):(W(),d=g[m++]={j:2,G:P(b),h:b||E,g:G}))||b&&d.G(d.h,b)&&(d.h=b)){c!==void 0&&(d.g=c);const k=g;a(...d.h).then(l=>d.g!==l&&d.h===b&&(d.g=l,U(k)))}return d.g},hook_callback:(a,b)=>{const c=S();c.h=b;return c.ia||(c.ia=(...d)=>a(...c.h,...d))},
hook_delay:a=>{const [b,c]=pa(I);oa(sa,[a,c]);return b},hook_dom:(a,b)=>(e.i===G&&(e.i=Z(a).cloneNode(H)),ua(b||G)),hook_effect:oa,hook_map:(a,b,c)=>{let d=G,k=H;if(m<g.length)if((d=g[m]).U!==a)ka(d),d=G;else if(!d.H||c&&d.G(d.h,c))d.h=c||E,d.H=H;else{if(b===d.P)return++m,d.g;k=I}const l=f,n=g,p=++m,q={},v=[],h=b.length>0&&ja(b,q,v);if(d){if(d.g=[],d.P!==b){d.P=b;for(const u of d.Z)u in q||(T(d.O[u]),delete d.O[u])}}else g[p-1]=d={j:3,G:P(c),h:c||E,g:[],H,U:a,X:h?N(b[0]):G,Z:[],O:{},P:b};for(const u of v){b=
d.O[u];if(f=!b)d.O[u]=b=[{j:1,ea:n,W:d,Y:G,g:G}];if(k||f||(h?O(q[u],b[0].Y,d.X):q[u]!==b[0].Y)){g=b;m=1;try{b[0].g=a(b[0].Y=q[u],...d.h)}catch(D){if(e.A)throw D;}}d.g.push(b[0].g)}f=l;g=n;m=p;d.Z=v;return d.g},hook_memo:qa,hook_model:a=>{if(m<g.length)return g[m++].g;const b=g,c=[(0,a.init)(G),{}];for(const d of M(a))c[1][d]=(...k)=>{k=(0,a[d])(c[0],...k);if(c[0]!==k&&(c[0]=k,U(b),g===b))throw A;return k};g[m++]={j:0,g:c};return c},hook_object_changes:X,hook_prev:ra,hook_rerender:na,hook_state:pa,
hook_static:S,hook_sub:(a,b)=>{let c=G;if(m<g.length)if((c=g[m]).U!==a)T(c.v),c=G;else if(!c.H||b&&c.G(c.h,b))b&&(c.h=b),c.H=H;else return++m,c.g;const d=f,k=g,l=m;if(f=!c)(g[m]=c={j:4,G:P(b),h:b||E,g:G,U:a,H,v:[]}).v[0]={j:2,ea:g,W:c};g=c.v;m=1;try{c.g=a(...c.h)}catch(n){if(e.A)throw n;}f=d;g=k;m=l+1;return c.g},hook_transition:(a,b)=>{const c=S({da:a});a=qa(ta,[a,b,c]);return c.da=a.ga<=r?a.ha:(na(),a.ba===r?a.ca:a.ca+(a.ha-a.ca)*(r-a.ba)/(a.ga-a.ba))},init:(a,b=da.body,c=G)=>{b.innerHTML="";a=
{u:{K:a,l:c},T:G,L:G,B:0,aa:0,v:[],m:G,i:b,o:b,A:I,M:I};a.v[0]={j:0,V:a};ma(a)},node:Y,node_dom:(a,b,c)=>Y(wa(a),b,c),node_map:(a,b,c)=>Y(Q,{K:a,P:b,l:c||G}),now:()=>r}}
