# Builds prod and dev builds
name: Build lui

on:
  push:
    branches-ignore:
      - dist
    paths:
      - 'package.json'
  pull_request:
    branches-ignore:
      - dist
    paths:
      - 'package.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build lui
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install closure-compiler
        run: |
          sudo npm i -g google-closure-compiler
      - name: Build lui
        run: |
          git fetch origin dist
          npm run-script build
      - name: Commit artifacts and purge cache
        if: github.ref == 'refs/heads/master'
        run: |
          export LUIVERSION=$(echo "console.log(require('./package.json').version)" | node)
          export LUIVERSION_MAJOR=$(echo "console.log(require('./package.json').version.split('.')[0])" | node)
          mv dist /tmp/lui-dist
          git checkout dist
          mv /tmp/lui-dist/* ./
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff-index --quiet HEAD || git commit -m "v$LUIVERSION"
          git push
          git tag -f "v$LUIVERSION"
          git push -f --tags
          for i in *.js; do curl -s "https://purge.jsdelivr.net/gh/L3P3/lui@$LUIVERSION_MAJOR/$i" > /dev/null; done
