# Builds prod and dev builds
name: Build lui

on:
  push:
    branches-ignore:
      - dist
    paths:
      - 'package.json'
  pull_request:
    branches-ignore:
      - dist
    paths:
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build lui
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setting up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install closure-compiler
        run: |
          sudo npm i -g google-closure-compiler
      - name: Build lui
        run: npm run-script build
      - name: Commit artifacts and purge cache
        if: github.ref == 'refs/heads/master'
        run: |
          export LUIVERSION=$(echo "console.log(require('./package.json').version)" | node)
          export LUIVERSION_MINOR=$(echo "d=require('./package.json').version.split('.');d.pop();d.push('x');console.log(d.join('.'))" | node)
          mv dist /tmp/lui-dist
          git tag -f "v$LUIVERSION"
          git push -f --tags
          git fetch
          git checkout dist
          mv /tmp/lui-dist/* ./
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "v$LUIVERSION"
          git push
          git tag -f "v$LUIVERSION_MINOR"
          git push -f --tags
          for i in *.js; do curl -s "https://purge.jsdelivr.net/gh/L3P3/lui@dist/$i" > /dev/null; done
          for i in *.js; do curl -s "https://purge.jsdelivr.net/gh/L3P3/lui@v$LUIVERSION_MINOR/$i" > /dev/null; done
