# Builds prod and dev builds
name: Build lui

on: [push, pull_request]
# TODO: only if version in package.json changed

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build lui
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setting up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install closure-compiler
        run: |
          sudo npm i -g google-closure-compiler
      - name: Build lui
        run: npm run-script build
      - name: Commit artifacts
        if: github.ref == 'refs/heads/master'
        run: |
          export LUIVERSION=$(echo "console.log(require('./package.json').version)" | node)
          mv dist /tmp/lui-dist
          git fetch
          git checkout dist
          mv /tmp/lui-dist/* ./
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "v$LUIVERSION"
          git push
