# Run tests with bun
name: Test lui

on:
  push:
    branches-ignore:
      - dist
    paths:
      - 'test/**'
      - 'src/**'
  pull_request:
    branches-ignore:
      - dist
    paths:
      - 'test/**'
      - 'src/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@main
      
      - name: Install dependencies
        run: |
          mv package.json _ackage.json
          bun install --no-save jsdom
          mv _ackage.json package.json
      
      - name: Run tests
        run: bun test
